### ISSUE TITLE
Bug: プロフィール画像の削除後、ユーザー管理画面でデフォルト画像が表示されない

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1007]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.4.8-RC (f2c137d)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 74.0.3729.169|

How to reproduce? (再現手順)
---------------------------

1. ユーザー設定でプロフィール画像をアップロード
1. プロフィール画像を削除
1. ユーザー管理画面で当該ユーザーの行を確認

What happens? (症状)
---------------------

- デフォルトのプロフィール画像が表示されない
![User management   GroupWiKi](https://user-images.githubusercontent.com/3660715/58927742-c8772980-878a-11e9-91a8-412a31738e24.png)

What is the expected result? (期待される動作)
-------------------------------------------

- デフォルトのプロフィール画像が表示される

**Comment by shinoka7** [comment]
@shield-9 ご報告ありがとうございます。再現確認しました。
画像の削除をしてもサーバー側でユーザーのデータ下では削除されてないみたいですね。

**Comment by yuki-takei** [comment]
fixed by #1018
