### ISSUE TITLE
Improvement: Allow some more HTML tags

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1010]
Some safe HTML tags, such as `small` or `caption`, are not whitelisted by default.

Refs:
- https://ja.wikipedia.org/wiki/Help:%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8BHTML#%E4%BD%BF%E7%94%A8%E3%81%A7%E3%81%8D%E3%82%8BHTML
- https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L41

**Comment by yuki-takei** [comment]
Merged.
Please wait a moment until the next release.
