### ISSUE TITLE
Bug: Production build is broken

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1027]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.5.0-RC (7b5d741)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 74.0.3729.169|

How to reproduce? (再現手順)
---------------------------

0. `npm run server:prod`
1. Login to GROWI

What happens? (症状)
---------------------

- Page content was not loaded.
- Not able to switch to edit tab.

![](https://user-images.githubusercontent.com/3660715/59098869-8867a080-895c-11e9-88f9-4366ed158fac.png)

JS Console:
![](https://user-images.githubusercontent.com/3660715/59099054-0f1c7d80-895d-11e9-86f8-70cec6bda5f5.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Page content is displayed.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report. I have confirmed it was reproduced. I'll fix it soon.
