### ISSUE TITLE
Bug: Couldn't update page after cancellation

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1030]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.5.0-RC (d3a7702aaf542bc3f0deb259a2cfe0d414f83e97)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 75.0.3770.80|

How to reproduce? (再現手順)
---------------------------

1. Open existing page
1. Switch to edit tab
1. Modify content
1. Click "Update"
1. Asked "Do you want to leave this page?" by browser and choose "Stay"
1. Click "Update" again

What happens? (症状)
---------------------

- Nothing happens to editor.
- Got error in JS console: 
```
Uncaught (in promise) Error: Posted param "revisionId" is outdated.
    at commons.a4a23a2e699c062ab33f.chunk.js:1
```

What is the expected result? (期待される動作)
-------------------------------------------

- Page updated successfully.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report. I have confirmed it was reproduced. I'll fix this soon.
