### ISSUE TITLE
Improvement: Upload attachments from CodiMD

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1034]
現状、CodiMDからファイルをアップロードすると、CodiMDの管理するストレージ(つまり、GROWIの管理外)に対してアップロードされてしまいます。
CodiMD側のファイルアップロード機能では、GROWIのユーザのみにファイルを閲覧させることが難しいため、CodiMDの画面からGROWIのattachmentが作成できると便利です。

(https://github.com/weseek/growi-docker-compose/issues/28 の話もあるようなので、改変版CodiMDをメンテするより、共同編集機能を搭載する方が現実的なのかもしれませんが。)

**Comment by yuki-takei** [comment]
@shield-9 ご意見ありがとうございます。

5月末の社内の GROWI 開発チームで行った会議で、同時編集に関しては built-in editor での実装を目指すことを決めました。

その頃の議事録は Slack にしか残っていなかったので、とりあえず dev wiki に結論だけ起こしました。

[devwiki: /Web会議室/同時編集機能付きエディタ考](https://dev.growi.org/5cfe2858c736ef004312fa08)

HackMD(CodiMD)との連携機能を強化していく方向は一旦プライオリティを落とす感じになりましたので、こちらの issue は close とさせていただきます。悪しからず。
