### ISSUE TITLE
Bug: PATHに日本語を含むと正しく表示されない

### ISSUE THREAD

**Issue by norikroos** [weseek/growi#1038]
Environment
----------------------------

### Host

| item     | version |
| ---      | --- |
|OS        |windows server 2012|
|GROWI 	|3.4.7-RC|
|node.js 	|8.16.0|
|npm 	|6.4.1|
|yarn |	1.15.2|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   | Firefox 60.6.1esr(32bit)|

How to reproduce? (再現手順)
---------------------------

1. PATHに日本語文字を含むページに移動
1. 検索ボックス左部プルダウンで「この階層配下の子ページのみ」を選択
1. 検索ワードを入力して「Enter」押下

What happens? (症状)
---------------------

- 検索時の`prefix`がURLエンコードされ、正しい検索結果が表示されない

```
 No page found with "テスト prefix:/%E3%83%86%E3%82%B9%E3%83%88" under "undefined"
```

What is the expected result? (期待される動作)
-------------------------------------------

- PATHに日本語を含んでいても「この階層配下の子ページのみ」検索ができる
```
 Found 2 pages with "テスト prefix:/テスト"
```

Note
----

**Comment by shinoka7** [comment]
@norikroos ご報告ありがとうございます。
uriがdecodeされてないみたいですね。それはdecodeすれば直ると思うのですが、おそらく`No page found` は別の原因ですね。

**Comment by yuki-takei** [comment]
fixed by #1041
