### ISSUE TITLE
Bug: JS error at Full Text Search management

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1047]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.5.0-RC (703215f9b1ddc727486e2036bb03edfbf52581dc)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 75.0.3770.80|

How to reproduce? (再現手順)
---------------------------

1. Open Full Text Search management

What happens? (症状)
---------------------

- In JS console, TypeError happened.
![スクリーンショット 2019-06-13 19 11 50](https://user-images.githubusercontent.com/3660715/59424665-5e582780-8e0f-11e9-8357-ab77ba8a0f13.png)

What is the expected result? (期待される動作)
-------------------------------------------

- No error

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report. I have confirmed it was reproduced. I'll fix this soon.
