### ISSUE TITLE
IE11で開くとページがブランクになる

### ISSUE THREAD

**Issue by nc23user** [weseek/growi#1058]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|GROWI     |3.4.7|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Internet Explorer 11.829.17134.0|

How to reproduce? (再現手順)
---------------------------

1. TOPページや作成したページを表示

What happens? (症状)
---------------------

- IEで開くと「View」「編集」「Comment」領域に何も表示されず、記事の編集が出来ない。
-  GROWIのデモサイト上ではIEでも問題なく表示されており、デモサイト上のJS(vendor*.js/plugin*.js/app*.js/commons*.js/legacy*.js)をローカルにコピーすると
正常に表示されるようになる。

What is the expected result? (期待される動作)
-------------------------------------------

- 社内の規定ブラウザであるため、IEでも正常に表示できるようにしたい。
（IEが動作対象外であることは認識しております。)

Note
----

- 
-

**Comment by hinananoha** [comment]
上記issue、私の環境でも確認されました。その後の（個人的な）検証で確認されている追加情報を追記します。

- ver.3.4.3以降のすべてのバージョンで確認されました。ver.3.4.2まではIE11でも正常に表示されました。
- 現在はデモサイトも正常に表示されません。

**Comment by yuki-takei** [comment]
IE11 を今後サポート対象とすることはないのでクローズします。
