### ISSUE TITLE
全文検索が動作しない

### ISSUE THREAD

**Issue by kunitake** [weseek/growi#1067]
Environment
------------

### Host

| item     | version |
| ---      | --- |
| OS                            | CentOS 7.6.1810 |
| GROWI                         | v3.4.7          |
| node.js                       | v10.16.0        |
| npm                           | 6.9.0           |
| yarn                              |      1.16.0           |
| Elasticsearch                 | 6.8.0           |
| Mongodb                       | 3.6.13          |
| Using Docker                  | No              |
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS and Windows10|
|browser   |Google Chrome 75.0.3770.100|

How to reproduce? (再現手順)
---------------------------
CROWI -> GROWI 3.1.3-RC ->  GROWI 3.5.0-RC -> GROWI v3.4.7 

GROWI 3.1.3-RC から GROWI v3.5.0-RC に上げる際には別サーバに移行。
移行後、全文検索が動かなくなったため、v3.4.7に下げてみたが改善せず。

Index Build はどのフェーズでも動作しました。

What happens? (症状)
---------------------

## 検索窓に入力

検索したいワードを入力している最中に、検索窓が消える。

## 検索したいワードを入力してリターンキーまで押せた場合

logを見る限り、

- /_search?q=TCP
- /_api/search?q=TCP
- /_api/revisions.get?page_id=XXXXX x 複数行

がアクセスログとして記録されている。が、Growi のヘッダ、フッタ以外は真っ白なページに。

Chrome のディベロッパーツールを見ると

```
25 commons.6b81d5ccff15c63b1ce3.chunk.js:28 TypeError: Cannot read property 'username' of undefined
    at t.value (app.95735e0b3cd897317005.bundle.js:1)
    at Pi (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Ai (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Li (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Gs (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Ys (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Pa (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Ta (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at ja (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
    at Xs (commons.6b81d5ccff15c63b1ce3.chunk.js:28)
fs @ commons.6b81d5ccff15c63b1ce3.chunk.js:28
```

とエラーを吐いている。検索できていたときには表示されていなかったエラー

# 直接アクセス

https://growi.example.co.jp/_search?q=TCP

なにも表示されず

# APIアクセス

https://growi.example.co.jp/_api/search?q=TCP

JSONで検索結果が帰ってくる。

What is the expected result? (期待される動作)
-------------------------------------------
検索結果のリンクが表示される。

Note
----
- 類似issue https://github.com/weseek/growi/issues/842

問題解決するのに必要なログがあれば教えてください。報告したいと思います。

**Comment by yuki-takei** [comment]
@kunitake 今回 v3.5.0-RC はかなり大胆にいろいろ変更してるので、データが壊れて戻らない等も有り得そうです。

ご報告いただいているエラーの発生箇所を知りたいので、production mode ではなく development mode で起動した時のエラーを貼っていただけると助かります。 `yarn build:dev` してから `yarn server:dev` です。

**Comment by icchy** [comment]
こちら同様の現象で悩まされていましたが、crowiから移行したときのスキーマ不整合によるものでした。
`db.pages` 内の `lastUpdateUser` がGROWIでは必須になっており、UI側でnull参照により落ちているようです。
とりあえず応急処置として `lastUpdateUser` に `creator` と同じObjectIdを書き込むとエラーは出なくなりました。

**Comment by yuki-takei** [comment]
@icchy おお、有力情報ありがとうございます。
Crowi からの移行ユーザーが躓かないように、これを期に migration 書こうと思います。

**Comment by kunitake** [comment]
@icchy さんが言われた通りでした。

> db.pages.find ( {lastUpdateUser:{$exists:false} } )

で多数のページがありました。MongoDBには不慣れなので、乱暴ではありますが、ひとまず自分の ObjectID を埋めることにしました。

>  db.pages.update(  {lastUpdateUser:{$exists:false} }, { $set: {"lastUpdateUser" : ObjectId("db.usersで調べた私のObjectId") }}, { multi: true });

で lastUpdateUserを追加したところ、検索が動作するようになりました。ありがとうございました！
