### ISSUE TITLE
Bug: Inviting New Users from admin user management page denies access to page on invitation reload

### ISSUE THREAD

**Issue by shinoka7** [weseek/growi#1072]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Windows 10 |
|GROWI     |3.5.0-RC|
|node.js   |10.16.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |GoogleChrome 75.0.3770.100|

How to reproduce? (再現手順)
---------------------------

1. Go to /admin/users
1. Invite a new user with the `Invite New Users`
1. Page will reload after invitation is sent.

What happens? (症状)
---------------------

- Page becomes inaccessible after reload
![bug_inviteUser](https://user-images.githubusercontent.com/42939055/60075075-727d1c80-975f-11e9-955f-a889cc34e9d0.PNG)

- Nothing appears in log

What is the expected result? (期待される動作)
-------------------------------------------

- Page is accessible after reload from sending invitation

Note
----

- If reloaded (F5) again, it escapes the situation
- Might be something to consider after React-ifying the admin pages

**Comment by miya** [comment]
Thanks for the report!!
GROWI has been React-ized and this bug has been fixed
