### ISSUE TITLE
Bug: ユーザ一覧の最終ログイン日時がUTCで表示される

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#1085]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 4.9.110
|GROWI     |3.4.7|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose](growi-docker-compose)|yes|

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 |
|browser   |Google Chrome 75.0.3770.100|

How to reproduce? (再現手順)
---------------------------

1. 管理者権限のあるユーザになる
1. 「管理」→「ユーザ管理」を開く

What happens? (症状)
---------------------

-  ユーザー一覧の最終ログインの列に表示される時刻がUTCになっている。
※ログアウト→再ログインで更新すると確認できるかと思います。

What is the expected result? (期待される動作)
-------------------------------------------

- システムのタイムゾーンの時刻で表示される。 

Note
----
- Crowiの頃からこの挙動だったように思います。
- 記事ページ右上に表示される時間はシステムのタイムゾーンになっています。
- 何かしらの意図や制限がある等であれば、運用上の実害はないので、私としてはそのままでも問題ありません。

**Comment by yuki-takei** [comment]
@hide-o-mvd ご報告ありがとうございます。
先ほど対応したコードをマージしました。次のリリースまで今しばらくお待ちください。
