### ISSUE TITLE
Bug: Edgeで画像アップロード後に文字入力ができなくなる

### ISSUE THREAD

**Issue by gaku-h** [weseek/growi#1087]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |windows server2012R2|
|GROWI     |3.3.6|
|node.js   |8.11.4|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10 1803|
|browser   |Edge　42.27234.1.0|

How to reproduce? (再現手順)
---------------------------

1. process 1
新規で記事作成→何か文字入力→作成ボタン
1. process 2
編集→画像アップロード→文字入力受け付けない

What happens? (症状)
---------------------
画像アップロード後に文字入力ができなくなる
IE、Chromeでは出来た
画像アップロード→更新→編集→文字入力ｈ可能
　※demoでも同じ症状でした。

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------
画像アップロード直後に文字入力ができる

Note
----

- 
-

**Comment by yuki-takei** [comment]
@gaku-h ご報告ありがとうございます。

まず前提として、開発チームとして動作確認対象のブラウザは Chrome と Firefox に絞っています。Edge は今後も手厚くサポートしていくかどうか微妙な部分ではあるので、そこだけご了承ください。

ご報告いただいたバージョン、v3.3.6 はかなり昔のバージョンなので、こちらでは v3.5.2-RC と Edge 44.17763.1.0 で再現確認を行いました。

問題は2つあるようです。

## 編集ができない
まず編集画面そのものが動かないケース。症状としてはコンソールに

```
0: Object doesn't support property or method 'scroll'
ScrollSyncHelper.js (221,6)
```

と表示されました。こちらは Edge で scroll メソッドが動かないことが原因のようです。

https://stackoverflow.com/questions/51517324/scrollto-method-doesnt-work-in-edge

対策としては、上記ページにあるように `scrollTo` property に値を代入する方法を採用することにしました。

## 画像アップロード後に文字入力できない

こちらは、編集できない問題解決後に再現確認しました。
エディタ最下部のボタンからファイルを選択してアップロードを行った後は編集可能でしたので、ドラッグ&ドロップ処理に何らかの原因がありそうです。

原因が判明したら修正を行いますが、取り扱いの優先度は低くなると思います。
よろしくお願いいたします。

**Comment by yuki-takei** [comment]
Edge は Chromium 版になると挙動がまた変わるはずですが、少なくとも旧 Edge はサポート外としますので、こちらはクローズします。
