### ISSUE TITLE
アップロードされたプロフィール画像のリサイズ

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1108]
現状、プロフィール画像として非常に大きなサイズの画像(例えば2048x2048)をアップロードすると、そのままのサイズで保存されます。

しかし、GROWIではそれほど大きくプロフィール画像を表示することはないので、ストレージの使用量と転送量 (S3-GROWI間とGROWI-ブラウザ間) を節約するために、「128x128より大きかったら、縮小する」といったロジックがあると良さそうです。

**Comment by yuki-takei** [comment]
React Component で見繕ってみましたがこの辺でしょうか。

https://github.com/roadmanfong/react-cropper
https://github.com/DominicTobias/react-image-crop

**Comment by shield-9** [comment]
リサイズだけでなく、クロップも同時に実現するってことですかね？
それであれば、正方形ではない画像がアップロードされたとき、アイコンが極端に引き伸ばされて表示される現象も解消できて良さそうですね。

(Reactは全然書けないので、完全に個人的なUIの好みとしては下の方が良さそうに見えました)

**Comment by yuki-takei** [comment]
マージされました。v3.7.3 リリースをお待ちください。
