### ISSUE TITLE
Cannot duplicate a page when it restricted by a user group permission

### ISSUE THREAD

**Issue by kainosuke** [weseek/growi#1109]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Linux|
|GROWI     |3.4.7|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windwos10|
|browser   |Firefox 67|

How to reproduce? (再現手順)
---------------------------

1. Create a page with a user group restriction.
1. Click `Duplicate` button on the created page.
1. Modify `New page name` as you like.
1. Click `Duplicate page` button

What happens? (症状)
---------------------

- Notthing happen.

What is the expected result? (期待される動作)
-------------------------------------------

- The page should be duplicated.

Note
----

- a client browser POST `/_api/pages.duplicate` when I clicked  `Duplicate page` button. But a server do not response.
  - When I use growi with a reverse proxy (nginx), it responded 504 status

**Comment by yuki-takei** [comment]
I have confirmed that this problem reproduces.
