### ISSUE TITLE
Bug: 検索結果内のページタイトルがクリックしづらい

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1112]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Alpine Linux 3.9|
|GROWI     |3.5.1|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Google Chrome 75.0.3770.100|

How to reproduce? (再現手順)
---------------------------

1. Enter keywords to search box, and hit enter
1. Click an anchor link from search results summary (left side)
1. Click page title (in right side)

[Demonstration Movie](https://gist.github.com/shield-9/ba90981211caee1a1c4bf4a37ffd9939/raw/cf57a26d153da2acf36d6175377eebca5335dc7b/%25E7%2594%25BB%25E9%259D%25A2%25E5%258F%258E%25E9%258C%25B2%25202019-07-10%252012.04.35.mov)

What happens? (症状)
---------------------

- It is extremely hard to click page title.

What is the expected result? (期待される動作)
-------------------------------------------

- It must be easier to click.

**Comment by yuki-takei** [comment]
@shield-9 動画確認しました。v3.5.x でそもそも検索結果ページが壊れているような気もするので、それも併せて改修を入れます。少々お待ちください。
