### ISSUE TITLE
Bug: 右側の Table of Contents が消えてしまう

### ISSUE THREAD

**Issue by kometchtech** [weseek/growi#1128]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu 18.04|
|GROWI     |3.5.3|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 1903 x64|
|browser   |Firefox 68.0.1, Chrome 75.0.3770.142|

How to reproduce? (再現手順)
---------------------------

1. process 1
見出し付きのページを一度下へスクロールすると、右のサイドバーの表示が消えてしまう。

What happens? (症状)
---------------------

- symptom 1
見出し付きのページを一度下へスクロールすると、右のサイドバーの表示が消えてしまう。

![growi](https://user-images.githubusercontent.com/5137077/61535747-fcbe5500-aa6d-11e9-9df6-7624d2c9b834.gif)

What is the expected result? (期待される動作)
-------------------------------------------
右サイドバーの表示がスクロールに追従する？

Note
----

- 
-

**Comment by yuki-takei** [comment]
@kometchtech ご報告ありがとうございます。こちらは度々観測はされていましたが、ページリロードすると戻るので対応が延び延びになっていました。いずれ React component 化することにより解消されるとは思いますが、優先度は低い状態です。気長に待っていただければと思います。

**Comment by kometchtech** [comment]
将来の対応ということで気長に待たせていただきますー
