### ISSUE TITLE
バッチ実行によるインデックス作成

### ISSUE THREAD

**Issue by opst-sekine** [weseek/growi#1131]
現在、pythonによるバッチ実行で定期的にインデックスを作成することを検討しています。利用するユーザーが今後増えることが予想されているため、自動化したいと考えています。

UI上から実行する場合は、管理画面の全文検索管理メニュー内の「Build Now」を実行することで
実行できると思いますが、スクリプトで実行するために必要なパラメータをお聞きしたいです。

よろしくお願いいたします。

**Comment by yuki-takei** [comment]
@opst-sekine 
ご希望の処理ですが、現時点の最新版では、外から REST API として呼ばれることを想定した作りになっていないです。

https://github.com/weseek/growi/blob/deed0cf2b9b5b4d81157c5562a32a4e6b4751f8d/src/server/routes/index.js#L102

GROWI(Crowi) はユーザー毎に access token を発行する機能がありますが、たとえば
```
app.get('/_api/users.list'          , accessTokenParser , loginRequired(false) , user.api.list);
```
のように accessTokenParser を頭に置いた routes 定義にした版をリリースする必要があります。

**Comment by opst-sekine** [comment]
ご回答いただきありがとうございます。

そうですか、運用面でカバーができないか検討してみます。

**Comment by yuki-takei** [comment]
@opst-sekine 
因みにどういった利用シーンで定期的なインデックス化をしようと考えているのかって教えていただけないでしょうか？
GROWIはページの作成/更新/削除時にESインデックスも触っているので、定期実行が必要なシチュエーションがちょっと想像つかず…

**Comment by opst-sekine** [comment]
すいません、自分も上司に言われただけで詳しい利用シーンを聞いたわけではないのでわかりません。

おそらくボタンを押した段階で存在するページにインデックスが作成されるだけで、
それ以後に作成されたページにはインデックスがない状態という事を考えたものと思われます。

自分の認識もそのようなものだったのですが、一度インデックスの作成をすると、
以後新規ページにもインデックスが作成される仕様でしたでしょうか
（ドキュメントとしてどこかに記載されていたら自分の確認が不十分でした）

**Comment by yuki-takei** [comment]
なるほど。そしたらそもそもそういった定期実行の運用は必要ないですね。

> 自分の認識もそのようなものだったのですが、一度インデックスの作成をすると、
> 以後新規ページにもインデックスが作成される仕様でしたでしょうか
> （ドキュメントとしてどこかに記載されていたら自分の確認が不十分でした）

上記認識の通りで、特にドキュメント化はしていないです。

**Comment by opst-sekine** [comment]
ご回答ありがとうございます。

上司に確認したところ、利用シーンの認識は自分の認識と相違ないことがわかりました。
ご回答頂いた内容をエビデンスとして、バッチ化する必要がないとの結論に持っていきたいと思います。

この度はご対応いただき、ありがとうございました。
