### ISSUE TITLE
Bug: global notificationのメール通知がされない

### ISSUE THREAD

**Issue by ham-katsu** [weseek/growi#1143]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.6|
|GROWI     |3.5.5|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac 10.14|
|browser   |chrome 75.0|

How to reproduce? (再現手順)
---------------------------

1. 通知設定 -> Global notificationの設定で

  - トリガパスを``` /* ```に設定
  - 通知先に受取可能なメールアドレスを設定
  - トリガイベントをすべて選択

2.  任意のページにコメント(/Sandbox)

What happens? (症状)
---------------------

- メールが送られない
- 次のエラーが吐かれる

```
app_1            | [2019-07-31T06:45:34.026Z]  INFO: express/65 on 5923509acbda: ::ffff:10.3.207.31 <-- POST /_api/comments.add HTTP/1.1 200 273 http://hoge.com/Sandbox Chrome 75.0 Mac OS X 10.14.4 13.31631 ms (req_id=1fcc7dd8-b30c-4d48-b319-bdfc0a123f62)
app_1            | [2019-07-31T06:45:34.030Z] ERROR: growi/65 on 5923509acbda:
app_1            |   Uncaught Exception:  { [Error: ENOENT: no such file or directory, open '/locales/en-US/notifications/comment.txt']
app_1            |     errno: -2,
app_1            |     code: 'ENOENT',
app_1            |     syscall: 'open',
app_1            |     path: '/locales/en-US/notifications/comment.txt' }
app_1            | [2019-07-31T06:45:34.056Z]  INFO: express/65 on 5923509acbda: ::ffff:10.3.207.31 <-- GET /_api/comments.get?page_id=5d22ff43b78fcf004c027859 HTTP/1.1 200 1217 http://hoge.com/Sandbox Chrome 75.0 Mac OS X 10.14.4 9.942784 ms (req_id=ba2a1343-bf19-473a-aa2e-ec2fa2e004c5)

```

What is the expected result? (期待される動作)
-------------------------------------------

- なんらかの通知が送られる

Note
----

- アプリ設定 -> メールの設定 でSMTPの設定を更新したときのメールは届く

**Comment by yuki-takei** [comment]
@ham-katsu ご報告ありがとうございます。再現を確認しました。
修正してリリースしますので今しばらくお待ちください。

**Comment by miwa442** [comment]
最新バージョン（v3.5.22）で同様の現象が起きます。
エラー内容は以下の通りです。
```
[2019-11-26T01:01:36.184Z]  INFO: express/92 on 8d028d0a7469: ::ffff:172.27.0.1 <-- POST /_api/pages.create HTTP/1.1 200 1339 http://XXX/Support/%E3%83%86%E3%82%B9%E3%83%885 Chrome 78.0 Windows 10.0.0 192.8973 ms (req_id=8f09f762-9cc6-4559-946b-b0c75b73063f)
[2019-11-26T01:01:36.202Z] ERROR: growi/92 on 8d028d0a7469:
  Uncaught Exception:  { [Error: ENOENT: no such file or directory, open '/opt/growi/resource/locales/undefined/notifications/pageCreate.txt']
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path:
     '/opt/growi/resource/locales/undefined/notifications/pageCreate.txt' }
[2019-11-26T01:01:37.916Z]  INFO: express/92 on 8d028d0a7469: ::ffff:172.27.0.1 <-- GET /Support/%E3%83%86%E3%82%B9%E3%83%885 HTTP/1.1 200 55201 
```
ご確認のほどよろしくお願いいたします。

**Comment by yuki-takei** [comment]
修正完了しました。
v3.5.23, v3.6.0 リリースをお待ちください。
