### ISSUE TITLE
Feature: Dark Mode using preferes-color-scheme

### ISSUE THREAD

**Issue by tats-u** [weseek/growi#1144]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.5.3|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |FireFox 68 / Chrome 76|

Description
------------

Firefox (67～)・Chrome (76～)・Safari (12.1～) は、Webページ側のCSSで指定したダークモード用のデザインを、OSなどの設定に応じて表示することができます。([対応状況](https://caniuse.com/#search=prefers-color-scheme)) iOS Safariも、9月頃に対応予定で、AndroidのChromeの対応も予断を許さない状況です。大勢の使用者がいるChromeが対応したこのタイミングで本issueを立てます。

ダークテーマをCSSで指定する場合、`@media (prefers-color-scheme: dark) { ... }` 構文を使用します。 ([詳細](https://developer.mozilla.org/ja/docs/Web/CSS/@media/prefers-color-scheme))

ダークテーマを作成する場合、ブラウザのアドオン、Dark Reader ([公式](https://darkreader.org/) / [FireFox](https://addons.mozilla.org/ja/firefox/addon/darkreader/) / [Chrome](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=ja) / [紹介記事(Gigazine)](https://gigazine.net/news/20181205-dark-reader/) / [紹介記事 (Qiita)](https://qiita.com/kai_kou/items/8b33e599668926d80e7e)) で自動生成したものを開発者ツールでチェックすると、工数が削減できると思います。

**Comment by yuki-takei** [comment]
@tats-u 問題提起ありがとうございます。これは悩ましい…

## 元々の GROWI テーマの目的
まず前提として、GROWI のテーマというのは管理画面から変更可能で、エディタ部分以外は全てのユーザーに同じ見た目を提供するという目的で作られました。弊社は複数の GROWI を扱っているので、それぞれぱっと見でどの Wiki かを判別できるように、という意図もあります。

## GROWI テーマの現状の実装
css をテーマ別に用意して、テーマ変更時に読み込み対象をファイルごと切り替える方式を採っています。テーマには「ライト系テーマ」と「ダーク系テーマ」があり、それぞれベースの CSS を用意した上で、各テーマは色を変更するなどしています。

## 懸念点
ユーザー毎 light/dark の選択に対応するには、それぞれのテーマで、「ライト系」「ダーク系」の両方のベース CSS に合わせた変数群を用意する必要があります。

- 「default-dark」テーマのライトモードみたいなのができることになるけど…どうしたらいいんだろ
- 「ライトモードのみ」「ダークモードのみ」のテーマができるのもやむなしと割り切って、両対応のテーマを徐々に増やしていく？
- 実装上、[_apply-colors-dark.scss](https://github.com/weseek/growi/blob/4ae7acd014f345a1806ef5d25fc10942d44a76a2/src/client/styles/agile-admin/inverse/colors/_apply-colors-dark.scss) のようなものをどう扱うかを再考しなければ…


## まとめ
ただ、モチベーションは理解できて、「ユーザーに選択権を与える」という改修は GROWI の哲学的にも向かいたい方向ではあります。とりあえず継続協議ということで。

**Comment by tats-u** [comment]
> 「default-dark」テーマのライトモードみたいなのができることになるけど…どうしたらいいんだろ
`default-dark`は`default`のダーク版とみなすにはアクセント色が違いすぎる(赤↔青)と思います。
むしろ`blue-night`の方が`default`のダーク版に近いと思います。
`default-dark`は名前変更し、後方互換としてエイリアスとして残すのがいいのではないかというのが個人的な意見です。

> 「ライトモードのみ」「ダークモードのみ」のテーマができるのもやむなしと割り切って、両対応のテーマを徐々に増やしていく？
`antarctic`などはパット見両対応が難しそうなので、まずは`default`のダーク化だけからでも始めると良いと思います。
> 実装上、_apply-colors-dark.scss のようなものをどう扱うかを再考しなければ…
`@media(prefer-...: dark / light) { ... }`の中に放り込む手もある(SCSSが対応しているかどうかは不明)のですが、適用したとしてそれがマッチするかどうかは別問題ですし難しい問題です。

**Comment by you-at4** [comment]
個人的にはダークテーマは好きなのですが、
社内向けとして使っている場合にはユーザー毎に見かけを変えたくないという場合もあると思います。
なので、管理者設定で「ユーザー毎のテーマを反映しない」みたいな設定があると嬉しいかもしれないですね。

**Comment by yuki-takei** [comment]
@tats-u @you-at4 
大変長らくお待たせしました。v4 リリースでユーザーによるライトモード/ダークモードの変更が可能になりました。現状では default テーマおよび mono-blue テーマのみ両モード対応となっています。お試しいただけると幸いです。

本 Issue はクローズいたします。
