### ISSUE TITLE
Bug: Edgeにて検索ができない

### ISSUE THREAD

**Issue by norikroos** [weseek/growi#1152]
Environment
----------------------------

### Host

| item     | version |
| ---      | --- |
|OS        |windows server 2012|
|GROWI 	|3.5.5-RC|
|node.js 	|8.16.0|
|npm 	|6.4.1|
|yarn |	1.15.2|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   | Microsoft Edge 41.16299.1004.0|

How to reproduce? (再現手順)
---------------------------

1. 検索ボックスに検索キーワードを入力
1. 「Enter」押下 or 検索マークをクリック

What happens? (症状)
---------------------

- 検索が実行されない

コンソールには以下のエラーが表示される
`SCRIPT5007: Unable to get property 'append' of undefined or null reference`

What is the expected result? (期待される動作)
-------------------------------------------

- 検索画面へ遷移して検索結果が表示される

Note
----
Edgeは動作確認対象外と認識しておりますが、可能な範囲でご対応いただけると助かります。

**Comment by yuki-takei** [comment]
Edge は Chromium 版になると挙動がまた変わるはずですが、少なくとも旧 Edge はサポート外としますので、こちらはクローズします。
