### ISSUE TITLE
Bug: 「特定グループのみ」のページで「Edit Table」の「Done」を押すとエラーが表示され、編集できません。

### ISSUE THREAD

**Issue by yamatomo717** [weseek/growi#1156]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.5.3|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*Demoサイトで再現します。

### Client

| item     | version |
| ---      | --- |
|OS        |Mac/Windows|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. ページをグループ限定公開に設定する
1. テーブルエディットのモーダルウィンドウを開く
1. Doneを押すとエラーが表示され編集できないことを確認

What happens? (症状)
---------------------

- 「特定グループのみ」のページで「Edit Table」の「Done」を押すとエラーが表示され、編集できません。

What is the expected result? (期待される動作)
-------------------------------------------

- 「特定グループのみ」のページで「Edit Table」の「Done」を押してもエラーが表示されない

Note
----

- 修正済みのためプルリク送ります。

**Comment by yuki-takei** [comment]
@yamatomo717 
ご報告ありがとうございます。
再現とPRでの修正完了を確認しました。助かります。

次バージョンリリースまで少々お待ちください。
