### ISSUE TITLE
Bug: the same user can be added to the same group multiple times

### ISSUE THREAD

**Issue by mizozobu** [weseek/growi#1170]
Environment
------------
demo.growi.org

How to reproduce? (再現手順)
---------------------------

1. create a new user group
1. add a user to the group
1. add the same user to the same group by username

What happens? (症状)
---------------------

- the same user can be added to the group twice

What is the expected result? (期待される動作)
-------------------------------------------

- the same user cannot be added to the group twice

**Comment by itizawa** [comment]
https://github.com/weseek/growi/pull/1448
で解消していたので close

**Comment by itizawa** [comment]
https://github.com/weseek/growi/pull/1448
で解消していたので close
