### ISSUE TITLE
Bug: ユーザ管理画面にて最終ログイン日時が表示されない

### ISSUE THREAD

**Issue by hifukumo** [weseek/growi#1174]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |RHEL7.5|
|GROWI     |3.5.9|
|node.js   |10.16.3|
|npm       |6.9.0|
|Using Docker|yes ※nocdn版を使用|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 75.0.3770.100|

How to reproduce? (再現手順)
---------------------------

1. docker-composeにてgrowiを起動する。
1. ユーザを作成し、作成したユーザにてログインを行う。
1. 管理ユーザでログイン後、管理メニューのユーザ管理画面を表示する。

What happens? (症状)
---------------------

- ログインしたはずのユーザの最終ログイン日時が表示されていない。

What is the expected result? (期待される動作)
-------------------------------------------

- ユーザの最終ログイン日時が表示されていること。

**Comment by yuki-takei** [comment]
@hifukumo ご報告ありがとうございます。再現確認しました。
次のバージョンで修正される予定です。

**Comment by yuki-takei** [comment]
fixed by #1175
