### ISSUE TITLE
Bug: Markdown Helpのmodal上の/Sandboxへのリンクが動作していない

### ISSUE THREAD

**Issue by yutasa** [weseek/growi#1199]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.2 |
|GROWI     | 3.5.9 |
|node.js   | 8.16.0 |
|npm       | 6.4.1 |
|Using Docker| no |
|Using growi-docker-compose | no |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.13.6 |
|browser   | chrome77.0.3865.75, safari, firefox69.0 |

How to reproduce? (再現手順)
---------------------------

1. 何のページでもいいので編集画面に入る。
1. 何かしら入力する。
1. エディタ右下の "?Markdown"をクリック
1. "Sandboxを開く"をクリック

What happens? (症状)
---------------------

- リンクが機能していない

What is the expected result? (期待される動作)
-------------------------------------------

- 別タブで`/Sandbox` ページが開く 

Note
----

- https://demo.growi.org/ でも同様の現象を確認。

**Comment by yuki-takei** [comment]
@yutasa ご報告ありがとうございます。確かに最新版でも同様の挙動であることを確認しました。
修正して次のバージョンに反映させますので今しばらくお待ちください。
