### ISSUE TITLE
Bug: Full Text Search doesn't work (全文検索ができない)

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#1224]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 18.04.3 LTS |
|GROWI     |3.5.15|
|node.js   |10.16.3|
|npm       |6.9.0|
|Using Docker| no|

#### plugins
| plugin | version |
| ---------------- | ------ | 
|growi-plugin-lsx | 3.0.3 |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.6 |
|browser   | Chrome 77.0.3865.90 |

How to reproduce? (再現手順)
---------------------------
全文検索欄に適当な文字列を入れる

What happens? (症状)
---------------------
どの文字列を入力しても
No page found with "hogehoge"
のようにHITしない

What is the expected result? (期待される動作)
-------------------------------------------
入力文字列を含むページが列挙される

Note
----
- growi.cloudでも同様の現象が起きています。

**Comment by yuki-takei** [comment]
@hanapage ご報告ありがとうございます。以下手順で再現確認しました。

1. v3.5.9 で起動
1. Build Index
1. 検索 -> 成功
1. v3.5.12 以上にアップグレード
1. 検索 -> 成功
1. Build Index
1. 検索 -> **失敗**

おそらく
* Improvement: Use Elasticsearch Alias
による本体側デグレだと推測。原因判明次第修正してリリースします。
