### ISSUE TITLE
PlantUMLでイメージが描画されない

### ISSUE THREAD

**Issue by ma-chisuke** [weseek/growi#1248]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |debian|
|GROWI     |3.5.16|
|node.js   |10.16.3|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac|
|browser   |google chrome|

How to reproduce? (再現手順)
---------------------------

1. PlantUMLの記法を用いて記事を書く。

What happens? (症状)
---------------------

- UMLが描画されない。

-------------------------------------------
自前でPlantUMLは用意しておりません。
v3.5.12からplantuml.comへのアクセスがhttpsになったようですが、こちらにアクセスするとログイン画面に飛ばされるようで、イメージが描画されないようです。

https://plantuml.com/plantuml

**Comment by yuki-takei** [comment]
@ma-chisuke ご報告ありがとうございます。こちら既知のバグで、master ブランチでは改修済みです。v3.5.17 リリースをお待ちください。
