### ISSUE TITLE
Index Buildでエラーが発生しました　というエラーが出る

### ISSUE THREAD

**Issue by usernamehogehoge** [weseek/growi#1271]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux release 2 (Karoo)|
|GROWI     |3.5.16|
|node.js   | 10.16.3 |
|npm       | 6.9.0 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac 10.15|
|browser   |chrome バージョン: 77.0.3865.90（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. 管理ページへ行く
1. 全文検索管理ページに行く
1. Build Nowボタンを押す

What happens? (症状)
---------------------

- エラーが発生しました　というエラーが出る
<img src="http://or2.mobi/data/img/250462.png">

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------

- build 完了

Note
----

**Comment by usernamehogehoge** [comment]
自前のサーバーで動かしています。必要なデータが有ればお気軽にお知らせください。
こちら
https://github.com/weseek/growi-docker-compose
のUpgrading app container　の手順通り3.4系からアップグレードしたらこのような形になりました

**Comment by shield-9** [comment]
3.4.xから3.5.16にアップグレードされる際、直接アップグレードするのではなく、3.5.12~3.5.15を挟んでいたた場合には #1224 の影響を受けている場合があります。
Elasticsearch上のデータ(IndexとAliasを含む)を一度すべて消すことで、解消するようです。

当てはまらない、もしくは解消しないようであれば、アプリケーション(Node.js)側のログを確認してみてください。
