### ISSUE TITLE
Strange pager in User Management page

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1293]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.6|
|GROWI     |3.5.17|
|node.js   |10.16.3|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 19H1|
|browser   |Chrome 77.0.3865.120|

How to reproduce? (再現手順)
---------------------------

1. Login with admin user.
1. Open "User Management".

What happens? (症状)
---------------------

Pager is not rendered correctly.
![User Management - GroupWiki](https://user-images.githubusercontent.com/3660715/67366045-b5d08600-f5ad-11e9-958f-2608d344604d.png)

What is the expected result? (期待される動作)
-------------------------------------------

![User Management - GroupWiki (1)](https://user-images.githubusercontent.com/3660715/67366051-b832e000-f5ad-11e9-8264-c532e676b66d.png)

Note
----

- 
-

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report.
Please wait until v3.5.18 is released.
