### ISSUE TITLE
growiにアクセスしてもページコンテンツと検索バーが20秒くらい表示されない

### ISSUE THREAD

**Issue by usernamehogehoge** [weseek/growi#1303]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux release 2 (Karoo) メモリ　2GB|
|GROWI     | 3.5.16 |
|node.js   |10.16.3|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client
| item     | version |
| ---      | --- |
|OS        |Mac 10.15|
|browser   |google chrome バージョン: 77.0.3865.120（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. growiのどのURLでもいいのでアクセスする

What happens? (症状)
---------------------
- ページコンテンツが20秒くらい表示されない
- 検索バーが20秒くらい表示されず重たい

What is the expected result? (期待される動作)
-------------------------------------------

- ページアクセス後すぐにページコンテンツと検索バーが表示される

自前のサーバーで動かしています。必要なデータが有ればお気軽にお知らせください。
こちら https://github.com/weseek/growi-docker-compose
のUpgrading app container　の手順通り3.4系からアップグレードしたらこのようなエラーがでました

**Comment by usernamehogehoge** [comment]
<img src="https://f.uploader.xzy.pw/eu-prd/upload/20191027161838_5949624a55.png">

**Comment by shield-9** [comment]
アプリケーション側とブラウザ側の両方のコンソールやログを確認して、エラーなどが出ていなければ、ChromeであればDevToolsなどを使って、具体的にどのリソースの取得に時間がかかっているのか、その時間の内訳はどうなっているのかを確認するのが一番早そうですね。

特定できたら、アプリケーションがそのコンテンツを応答するまでの処理 (静的 or 動的、DBにどういうリクエストをしているのかなど) を確認することで、大体の原因は掴めるかと。

**Comment by usernamehogehoge** [comment]
ありがとうございます。調べてみます。

**Comment by usernamehogehoge** [comment]
遅いときの　コンソールのネットワークタブの時間を計測できましたので共有しておきます。
<img src="https://f.uploader.xzy.pw/eu-prd/upload/20191028232651_3678427479.PNG">
