### ISSUE TITLE
インポート・エクスポートすると、configs コレクションが重複する

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1330]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Mac 10.14.6|
|GROWI     |3.5.17|
|node.js   |10.16.0|
|npm       |6.12.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac 10.14.6|
|browser   |google chrome バージョン: 77.0.3865.120|

How to reproduce? (再現手順)
---------------------------

1. v3.5.17でエクスポート機能を使って `configs`を含む全てのコレクションをダウンロードする
1. v3.5.17でデータベースを空にしてインポート機能を使ってファイルをインポートする。その際 `configs` を含む全てのコレクションをアップロードする

What happens? (症状)
---------------------

- `configs` コレクションが重複して作られる。
- 管理画面で `config` を変更しても意図した状況に変更できない

What is the expected result? (期待される動作)
-------------------------------------------

- `configs` コレクションが重複して作られない。
-  インポート後意図した通りに `configs` を設定できるようにする。

**Comment by yuki-takei** [comment]
## v3.5.17 まで
* 機能的に、コレクションを選んで insert することしかできない
* configs も ns, key でユニーク制約があればこの症状は起こらないのだが、あいにくスキーマが重複を許している

## v3.5.18 以降
以下により、この issue の症状は起こらない

* インポート時に各コレクション別に insert, upsert, flush and insert を選べるようになっている
* configs は flush and insert 操作のみに制限されている
* users は insert と upsert 操作のみ可能に制限されている
