### ISSUE TITLE
Bug: Can't login when all login providers are disabled

### ISSUE THREAD

**Issue by skomma** [weseek/growi#1390]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.5.22|

How to reproduce? (再現手順)
---------------------------

1. Prepare GROWI instance
1. Setup first user
1. Go to `Admin page > Security Settings`
1. Set OFF in `Authentication Mechanism Settings > ID/Pass`
1. Logout from GROWI

What happens? (症状)
---------------------

- No one can login GROWI.
    - Username/Password fields are not shown on login page.

What is the expected result? (期待される動作)
-------------------------------------------

- Show error when all login providers are disabled.
- Should not be able to save settings.

**Comment by TM82** [comment]
同じ症状が出ています。
ID/PassをOFFにしてからログアウトすると、ログインページに入力フィールドが表示されず、誰もログインできなくなりました。

**Comment by yuki-takei** [comment]
@TM82 現在 Admin page > Security Settings ページの React 化改修を行っています。完了次第こちらの issue も解決しますので今しばらくお待ちください。

**Comment by itizawa** [comment]
@TM82 
Security Settings ページの React 化改修が完了し master にマージされました。
https://github.com/weseek/growi/pull/1571 

次のバージョンで Issue も解決しますので close とさせていただきます。
v3.6.10 のリリースをお待ちください。
