### ISSUE TITLE
添付ファイルも検索対象に含める方法もしくはヒントについて教えてください

### ISSUE THREAD

**Issue by noffin** [weseek/growi#1395]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI     |3.6.0-RC|
|node.js   |10.17.0|
|npm       |6.11.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

What is the expected result? (期待される動作)
-------------------------------------------

Growiに付与されている検索機能は、作成したページのみが対象だと思われますが、添付ファイルの全文検索を追加する予定はありますか？
また、どのあたりを確認すれば全文検索機能を追加できる可能性があるのでしょうか？

例：下記に関連するソース
* ファイル追加/削除時にElasticSearchに添付ファイルを食わせる/インデックス削除
* 検索実行時にファイルと関連ページを表示させる

Note
----
ファイルは基本的にS3に保存しています

**Comment by yuki-takei** [comment]
> Growiに付与されている検索機能は、作成したページのみが対象だと思われますが、添付ファイルの全文検索を追加する予定はありますか？

WESEEK での開発チーム内では今のところ予定はありません。

## 実現可能性について
添付ファイルといってもいろんなファイルがあるので、とりあえずテキストファイルのみに絞るという解であれば実用可能なレベルで実装はできるかもしれません。

検索に必要なインデックス情報を作っているのはこのファイルです。
https://github.com/weseek/growi/blob/master/src/server/service/search-delegator/elasticsearch.js

検索実行時の処理も上記ファイルに書かれています。

**Comment by noffin** [comment]
ご回答どうもありがとうございます。添付ファイル検索機能予定がないこと承知しました。検索機能のファイルの連絡もありがとうございます。今後余裕があるときに確認いたします。
（その際何か分からないことがありましたら新Issueを立てますので）この件はCloseさせて頂きます。
