### ISSUE TITLE
Bug: Pagination is not working for trash list

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1402]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.3|
|GROWI     |3.5.17 and 3.6.0.-RC|
|node.js   |10.17.0|
|npm       |6.11.3|
|Using Docker|yes (Kubernetes) |
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 1909 18363.476|
|browser   |Chrome 78.0.3904.108|

How to reproduce? (再現手順)
---------------------------

1. Create a lot of new pages (more than 50) and delete them
1. Open `/trash`
1. Click "Next"

What happens? (症状)
---------------------

- `/trash/?offset=51` is redirected to `/trash`

What is the expected result? (期待される動作)
-------------------------------------------

- The link should be `/trash?offset=51` (no trailing slash)

**Comment by yuki-takei** [comment]
Fixed in dev/3.5.x branch.
Please wait v3.5.23 is released.
