### ISSUE TITLE
Feature: アイコン画像の変更について

### ISSUE THREAD

**Issue by sho621** [weseek/growi#1414]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI     |3.5.17|
|node.js   |8.16.2|
|npm       |6.4.1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

What is the expected result? (期待される動作)
-------------------------------------------
500～600人規模でGrowi使用させて頂いております。
社内に浸透してきた中で、画面ヘッダー左上のアイコンを社内独自のアイコンに変更したいというお話が出てきているのですが、今後こちらが変更される予定はありますでしょうか。

**Comment by shield-9** [comment]
うちだと、ログイン画面など何箇所かのソースに独自のパッチを当ててからデプロイするようにしています。
ほぼ自動化してしまったので、あまり気にしていませんでしたが、標準で可能であれば需要はありそうですね。

**Comment by yuki-takei** [comment]
@sho621 実装検討しますが先になると思います…

**Comment by sho621** [comment]
@shield-9 @yuki-takei お返事有難うございます。ご検討感謝します。
気長にお待ちしております。

**Comment by hiroki-koike** [comment]
当社でも同様の話が出ており、アイコン画像の変更に四苦八苦している初心者です。
GROWI 5.0.4, Docker, growi-docker-compose,GitBash を使用しています。

1,git clone https://github.com/weseek/growi.git growi

2,git clone https://github.com/weseek/growi-docker-compose.git growi-docker-compose 

3,growiフォルダ内のfavicon.png 絡みの画像を差し替えてcommit（形式・画素数は同一のまま）

4,3をgit push https://github.com/hiroki-koike/growi-icon（プライベートリポジトリとして）

5,growi-docker-composeフォルダ内のDockerfileを編集

- ARG version=5
+ ARG version=latest
- FROM weseek/growi:${version}
+ FROM hiroki-koike/growi-icon:${version}
- LABEL maintainer Yuki Takei <yuki@weseek.co.jp>
+ LABEL maintainer hiroki-koike <koike@example.co.jp>

6,docker compose up

6 で詰まりました。

#3 [internal] load metadata for docker.io/hiroki-koike/growi-icon:latest
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/hiroki-koike/growi-icon:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

上記がエラーメッセージです。access denied -> authorization failed あたりで「認証に失敗している」というのは
グーグル先生が教えてくれたのですが、これはGithubとGitbashに認証連携を持たせないとダメということでしょうか？

こちらに書くべきか迷いましたが、どなたか、何かヒントをいただけると幸いです。
よろしくお願い申し上げます。

**Comment by shield-9** [comment]
Dockerfileを書き換えた意図って何かありますか？手元でdocker-compose upするだけなら、通常は書き換えなくていいものです。
ビルドしたイメージを一般公開するのであれば、maintainer情報は書き換えたほうがベターですが。

**Comment by hiroki-koike** [comment]
@shield-9 お返事ありがとうございます。Dockerfileを書き換えた理由は、未編集のDockerfileでコンテナを作成した際に、
既存のgrowi/weseekのgrowiが立ち上がってしまったからでした。（favicon.png 絡みが初期画像のまま）
Dockerfileの FROM weseek/growi~ を書き換えることで「参照先が自分のリポジトリに変わらないかなー」という感じです。

**Comment by shield-9** [comment]
あー、なるほど。Dockerの使い方の話になってしまうので、GROWI SlackのhelpチャンネルやDockerのコミュニティで聞いていただいたほうがレス付きやすそうです。

ご参考までに、FROMは元にするDockerイメージを指定するための命令なので、gitのコミットが~という話は今回は基本的に気にする必要はないはずです。

**Comment by hiroki-koike** [comment]
@shield-9 ご丁寧にありがとうございました。
>GROWI SlackのhelpチャンネルやDockerのコミュニティで聞いていただいたほうがレス付きやすそうです。
とのことなので、色々試した上で今後はそちらにお邪魔しようと思います。

**Comment by yuki-takei** [comment]
@sho621 @shield-9 @hiroki-koike 
こちらでの報告が大変遅くなりましたが [v5.1.0](https://github.com/weseek/growi/releases/tag/v5.1.0) で実装されました。
