### ISSUE TITLE
Bug: Cannot Import GROWI Archive from Mac OS client

### ISSUE THREAD

**Issue by utsushiiro** [weseek/growi#1423]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS Mojave 10.14.6|
|GROWI     |3.6.0-RC|
|node.js   |10.17.0|
|npm       |6.11.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Mojave 10.14.6|
|Chrome  |78.0.3904.108|
|Firefox| 70.0.1 |

How to reproduce?
---------------------------

1. Access /admin/importer
1. Click choose file button
1. Cannot select `GROWI-XXXXXX.growi.zip` generated by export archive data feature

**Comment by yuki-takei** [comment]
Thank you.
Use the version >= v3.5.25 or >= v3.6.1.
