### ISSUE TITLE
Improvement: テーブル編集ダイアログをEscapeキーで閉じないようにしたい

### ISSUE THREAD

**Issue by fmy** [weseek/growi#1452]
テーブルを編集する際のダイアログですが、Escapeキーを押すと確認なしで閉じるので、時間をかけて編集したものが消えてしまうことがあります。

- Escapeでは閉じないようにする
- 編集されていると閉じる場合確認ダイアログを出す

などの動作になると嬉しいです。

<img width="377" alt="スクリーンショット 2019-12-09 23 10 24" src="https://user-images.githubusercontent.com/856469/70442171-1a519100-1ad9-11ea-9964-5da416db24c7.png">

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |heroku|
|GROWI     |3.5.5|
|node.js   | 10.16.1 |
|npm       | 6.10.2 |
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | macOS |
|browser   |chrome 78|

How to reproduce? (再現手順)
---------------------------

1. テーブルを作成
1. 編集する
1. Escapeキーを押す
1. 確認なしで閉じる

**Comment by yuki-takei** [comment]
> Escapeでは閉じないようにする
こちらで対応します。v3.5.25 リリースをお待ちください。
