### ISSUE TITLE
exportしてimport した時、custom CSS、Markdown settings の custom whitelist の内容が import先に反映されない

### ISSUE THREAD

**Issue by TsuyoshiSuzukief** [weseek/growi#1454]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.5.20|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------
1. GROWI App  A で 管理画面からデータアーカイブを選択し、、エクスポートデータを作成する。

1. GROWI App B で、エクスポートした zip ファイルを インポートする
    ```bash
    
    ```

1. process 4
    ```bash
    
    ```

What happens? (症状)
---------------------
custom CSS、Markdown settingsのcustom whitelistの内容が復帰されない

- symptom 1
- symptom 2

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------
custom CSS、Markdown settingsのcustom whitelistの内容が インポート先へ反映される。
- 
- 

Note
----

- 
-

**Comment by yuki-takei** [comment]
fixed on v3.5.25
