### ISSUE TITLE
コメント更新時にCurrent user is not accessible to this pageエラー

### ISSUE THREAD

**Issue by naomichi-y** [weseek/growi#1464]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |  (growi.cloud)  |
|GROWI     | 3.5.18 |
|node.js   | (growi.cloud) |
|npm       | (growi.cloud) |
|Using Docker| (growi.cloud) |
|Using [growi-docker-compose][growi-docker-compose]| (growi.cloud) |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Mac 10.14.6 |
|browser   | Chrome  78.0.3904.108 |

How to reproduce? (再現手順)
---------------------------

1. ページに対しコメント追加
2. コメントを編集して更新

What happens? (症状)
---------------------

コメント更新時に `Current user is not accessible to this page` エラーが出る。

What is the expected result? (期待される動作)
-------------------------------------------

- コメントが更新される

**Comment by haruhikonyan** [comment]
@naomichi-y 
こちら growi.cloud 上で試したのですが再現されませんでした。
現在も同じ手順で再現するかどうか確かめていただけますでしょうか？
(growi.cloud では強制アップデートが行われて GROWI のバージョンは 3.6.2 になってると思います)
また、growi.cloud 固有の問題の可能性もございますので念のため growi.cloud サポートまで問い合わせいただければと思います。
growi-cloud-support@weseek.co.jp

以上、よろしくお願いいたします。

**Comment by naomichi-y** [comment]
@haruhikonyan こちらgrowi.cloudで問題なく編集できるようになったことを確認できました。
バージョンアップした関係かもしれません。ありがとうございます!
