### ISSUE TITLE
MongoDB rejects growi authentication

### ISSUE THREAD

**Issue by mzch** [weseek/growi#1468]
3.6.0 を試したところ、MongoDB から syslog に以下のエラーが出て起動しません。

```
Dec 13 01:26:23 Macmini docker-compose[18874]: #033[33mmongo_1          |#033[0m 2019-12-12T16:26:23
.866+0000 I  ACCESS   [conn12] Supported SASL mechanisms requested for unknown user 'growi@admin'
Dec 13 01:26:23 Macmini docker-compose[18874]: #033[33mmongo_1          |#033[0m 2019-12-12T16:26:23
.872+0000 I  ACCESS   [conn12] SASL SCRAM-SHA-1 authentication failed for growi on admin from client
 172.18.0.1:56212 ; UserNotFound: Could not find user "growi" for db "admin"
```
3.5.x とは認証周りが変わっているのでしょうか。

_Originally posted by @mzch in https://github.com/weseek/growi/issues/1443#issuecomment-565086969_

**Comment by yuki-takei** [comment]
環境変数 `MONGO_URI` は設定している状態でしょうか？

その場合、どういった形式か教えてください。
`mongodb://example.com/dbname`
なのか、
`mongodb://username:password@example.com/dbname?key=value`
なのかといったあたりです。

**Comment by mzch** [comment]
```
MONGO_URI=mongodb://password@localhost:27017/growi
```
として設定しています。

**Comment by yuki-takei** [comment]
@mzch 度々のご連絡ありがとうございます。
手元で同様の環境を作ったところ、確かに parse 部分で不具合がありました。おかげさまで今度こそこの問題を修正できたと思います。

v3.6.1 としてリリースして v3.6.0 は廃版とすることにします。リリースまで少々お待ちください。
