### ISSUE TITLE
ページ編集ツールの視認性が著しく低下する。

### ISSUE THREAD

**Issue by is984** [weseek/growi#1514]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.7.1908|
|GROWI     |3.6.1|
|node.js   |10.18.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Firefox 72.0b10|

How to reproduce? (再現手順)
---------------------------

1. /admin/customize へ移動する
1. テーマをダーク色ベースのものに変更する(blue-nightなど背景が黒系のもの)
1. ページ編集画面を開く

What happens? (症状)
---------------------

- 編集ボックス上部の編集ツールの背景色が黒系に変更されるが、ボタン色が黒のため視認性が低下する。
![image](https://user-images.githubusercontent.com/22042489/71452118-ab588580-27c4-11ea-9a0f-dd62c906c01f.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 編集ツールの背景色は白色固定になっている
![image](https://user-images.githubusercontent.com/22042489/71452141-f5da0200-27c4-11ea-9acf-bbb138e3f43e.png)

Note
----

- カスタムCSSの設定で背景色に白を指定すれば問題は回避できる。

**Comment by yuki-takei** [comment]
fixed by #1525

**Comment by yuki-takei** [comment]
@is984 master に取り込まれました。次回リリースをお待ちください。
