### ISSUE TITLE
Bug: ファイルをローカルにアップロードできない

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#1526]
3.5.23から3.6.2にアップグレードしたところ、掲題の現象が発生しました。
```
environment:
　-FILE_UPLOAD=local 
```
として運用しております。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 4.9.110|
|GROWI     |3.6.2|
|node.js   |12.14.0|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | Windows10|
|browser   |Google Chrome 79.0.3945.88|

How to reproduce? (再現手順)
---------------------------

1. 3.6.2にアップグレードする（DBのマイグレーションは行っておりません）
1. 任意の記事の編集画面に遷移する
1. 任意のファイルや画像をアップロードまたはペーストする

What happens? (症状)
---------------------

- 添付のようなエラーダイアログが出てアップロードできない。
![growi_error](https://user-images.githubusercontent.com/48038803/71860170-2ad74480-3135-11ea-8219-b01da81362d4.png)

What is the expected result? (期待される動作)
-------------------------------------------

- ファイルや画像が正常にアップロードできる。

Note
----

- 暫定対処として、コンテナ内の /data/uploads/attachment までのパーミッションを777にしたところ、アップロードできるようにはなりました。
- アップロードされたファイルを見ると、ユーザーがnodeになっているので、この辺に原因があるのかと推測します。

```
-rw-r--r--    1 root     root         83848 Dec 26 07:42 255c938a71560a7ccd09bda771782f6b.png
-rw-r--r--    1 node     node         48230 Jan  7 00:54 97a11b44ee3b0d1883276b85b0f6b810.png
```

よろしくお願いします。

**Comment by yuki-takei** [comment]
@hide-o-mvd 
ご報告ありがとうございます。
質問なのですが、利用されている weseek/growi-docker-compose のローカルリポジトリのコミットハッシュを教えていただけますでしょうか。

**Comment by hide-o-mvd** [comment]
こちらでよろしいでしょうか。

$ git rev-parse HEAD
b5b96cf33c81330de2d90fb117895ac428996e3a

**Comment by yuki-takei** [comment]
なるほど、そちらも最新版なんですね。

GROWI 本体 の v3.6 系では公式 Docker イメージの作りが変わり、CMD を node ユーザーで動かすようになったんですが
https://github.com/weseek/growi/blob/master/docker/docker-entrypoint.sh#L14

これのせいで「過去に作られた root 権限で作られたディレクトリ」に書き込みができなくなっている模様。

ちょっと解決策考えます。

**Comment by yuki-takei** [comment]
@hide-o-mvd `docker-entrypoint.sh` を改修し、再起的に owner を変えるようなコードに変更しました。
