### ISSUE TITLE
テーブル編集ツールの視認性が低下する

### ISSUE THREAD

**Issue by is984** [weseek/growi#1527]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.7.1908|
|GROWI     |3.6.1|
|node.js   |10.18.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Firefox 73.0b1|

How to reproduce? (再現手順)
---------------------------

1. /admin/customize へ移動する
1. テーマをダーク色ベースのものに変更する(blue-nightなど背景が黒系のもの)
1. ページを作成し、テーブル編集ツールで表を右クリックします

What happens? (症状)
---------------------

- テーマに合わせて文字色が白系に変更されますが、テーブル編集ツールの背景色が白のままなので文字が読みにくくなります。

![image](https://user-images.githubusercontent.com/22042489/71941471-2f673000-31fd-11ea-9759-37a812bbcea5.png)

What is the expected result? (期待される動作)
-------------------------------------------
以下の挙動が望ましいかと思います
- テーブル編集ツールの背景色もテーマに合わせて変更される  

Note
----
- #1514 の対策として一時的に設定しているCSSは無効にしています。
- この画面だけツールバーの色が白色でデザイン的にも少し違和感がありますので修正していただけるとうれしく思います。

**Comment by yuki-takei** [comment]
@is984 ご報告ありがとうございます。
数カ所対応が必要な部分があるので、分割してやっていきます。

## Data Import ボタンをクリックした後のプルダウンする部分
Issue では触れられていませんでしたが視認性が悪くなっていたので、#1549 で対応しました。

## Handsontable そのもの
こちらはテーマの scss に関わる部分なのですが、現在別ブランチで Bootstrap 4 への移行が進んでおりコンフリクトしてしまうので、そちらが終わってからの対応になります。つまり、修正版リリースは先延ばしになります。

上記へのご理解と、少々お時間いただくことをご了承願います。

**Comment by is984** [comment]
@yuki-takei 
Data Import部分については気づけていませんでしたが修正いただきありがとうございます。
テーブル本体の修正については承知しました。修正までの間は白色ベースのテーマを利用するなどして対応します。

**Comment by yuki-takei** [comment]
@is984 一旦こちらで確認してから起票します。

@itizawa Handsontable と同様、解決策を検討してください。

もし bs4 化に抵触するようなら「handsontable と diff2html 部を修正する」スコープの新たな issue を作成、抵触しないようなら「handsontable を修正する」スコープの新たな issue を作成して、diff2html 対応はこの issue のスコープとして処理してください。

**Comment by yuki-takei** [comment]
@is984 一旦こちらで確認してから起票します。

## 業務連絡
@itizawa @KazuyaNagase 

Handsontable と同様、解決策を検討してください。

もし bs4 化に抵触するようなら「handsontable と diff2html 部を修正する」スコープの新たな issue を作成、抵触しないようなら「handsontable を修正する」スコープの新たな issue を作成して、diff2html 対応はこの issue のスコープとして処理してください。

**Comment by itizawa** [comment]
https://github.com/weseek/growi/issues/1577 を起票しました。
handsontable に関しての修正は BootStrap 4 移行後に行います。

差分確認画面についてはただいま対応しております。

**Comment by yuki-takei** [comment]
diff2html は v3.6.5 で修正されます。
残る handsontable については、#1577 が起票されたのでこちらは閉じます。
