### ISSUE TITLE
Feature: Anchor link for comments

### ISSUE THREAD

**Issue by naomichi-y** [weseek/growi#1530]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | (growi.cloud) |
|GROWI     |3.6.2 |
|node.js   |12.14.0|
|npm       |6.13.4|
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac 10.14|
|browser   |chrome 79 |

How to reproduce? (再現手順)
---------------------------

1. 記事にコメントを書く

What is the expected result? (期待される動作)
-------------------------------------------

コメントの日付などをクリックしたとき、コメントにリンクするURLフラグメントを取得したい。

**Comment by yuki-takei** [comment]
fixed by #1622
