### ISSUE TITLE
Improvement: Google OAuth で新規ログインしたアカウントの username をメールアドレスから取得する

### ISSUE THREAD

**Issue by osamuban** [weseek/growi#1536]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.6.1810 (Core)|
|GROWI     |v3.6.3|
|node.js   |v10.17.0|
|npm       |6.11.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   |Chrome 79.0.3945.88|

How to reproduce? (再現手順)
---------------------------
※Google認証の設定済み
1. Googleアカウントで新規ログイン
2. 自身のアイコンから「ユーザー設定」→「ユーザー情報」と遷移

What happens? (症状)
---------------------

- Google認証にて新規ログインして作成されたアカウントのメールアドレスが空白または「change-it-=uMQ=wd!laQl@example.com」の文字列が設定されている。
- 作成されたGrowiのアカウントのusernameが、Googleアカウントのユーザー名（メールアドレスのドメインを除いた文字列）ではなく、日本語表記の名前（Googleアカウントの姓＋名）になっている。

What is the expected result? (期待される動作)
-------------------------------------------

- Googleアカウントのメールアドレスが、新規ログインして作成されたアカウントの初期メールアドレスとなる。 
- 作成されたアカウントのusernameがメールのドメインを除いた文字列になる。

**Comment by yuki-takei** [comment]
@osamuban 
Issue 作成ありがとうございます。
Bug として起票いただいたところ恐縮ですが、実はこれまでの挙動は仕様の側面が強かったです。

## これまでの経緯と仕様

* 各 OAuth Provider で、メールアドレスリストの属性が必ずしも存在する(かつ空ではない)とは限らない
    * Google OAuth の場合も、ログインIDがそのまま取得出来るメールアドレスリストに入ってくるはずという確証がなかった
* そのため、これまでは確実に存在する Display Name を username として用いることにしていた
* メールアドレスは、取得できたとしてもできなかったとしてもダミーを入れ、当事者が変更すれば良いというスタンスであった

## 改修予定

より詳しく調べたところ、Google OAuth ではどうやら「取得出来るメールアドレスリストの最初の要素が、ログインIDそのものである」らしいことがわかりました。
そのため、以下のように改修することにしました。

1. メールアドレスリストが存在する場合は、その最初の要素を email として扱い、かつ username は email の @ 以前を使う
2. メールアドレスリストが存在しない場合は、これまで通りの仕様
    * username は Display Name を利用
    * email は当該ユーザーが自分で変更する前提でダミーをセット

**Comment by yuki-takei** [comment]
#1547 で改修され、 master にマージされました。
次のリリースをお待ちください。

**Comment by osamuban** [comment]
仕様にもかかわらず改修頂きありがとうございます。
