### ISSUE TITLE
A11y: Improve accessibility for Handsontable under dark themes

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1577]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.7.1908|
|GROWI     |3.6.1|
|node.js   |10.18.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Firefox 73.0b1|

How to reproduce? (再現手順)
---------------------------

1. /admin/customize へ移動する
1. テーマをダーク色ベースのものに変更する(blue-nightなど背景が黒系のもの)
1. ページを作成し、テーブル編集ツールを表示する

What happens? (症状)
---------------------

- テーマに合わせて文字色が白系に変更されるが、テーブル編集ツールの背景色が白のままなので文字が読みにくくなる。

![image](https://user-images.githubusercontent.com/22042489/71941471-2f673000-31fd-11ea-9759-37a812bbcea5.png)

What is the expected result? (期待される動作)
-------------------------------------------
- テーブル編集ツールの色合いもテーマに合わせて変更される  

Note
----
- handsontable は bs4 化に抵触するため bs4化後に対応

**Comment by yuki-takei** [comment]
Fixed on v4.0.1.
