### ISSUE TITLE
Imprv: Show toastr when markdown document is empty

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1594]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | mac|
|GROWI     |3.6.2|
|node.js   |v12.13.0|
|npm       |6.12.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
|---|---|
|OS        |mac|
|browser   |Chrome 79.0.3945.79|

How to reproduce? (再現手順)
---------------------------

1. ページ作成画面を開く
1. 本文を入力せずに Create ボタンを押す

What happens? (症状)
---------------------

- 400 エラーが返ってくるはずが、 200 エラーが返ってくる
```
POST /_api/pages.create 200 0.451 ms -
```

What is the expected result? (期待される動作)
-------------------------------------------

- 正しいエラーコードが返ってきて、Toaster などでユーザーがリクエストの間違いに気づける

Note
----

- 旧 api を使用している箇所では同様の問題が発生しているものと思われる
- 200 が返ってくるが、ページは作成されていない

**Comment by yuki-takei** [comment]
200 が返って来るのは、Crowi 由来の API の仕様で、他の route でもそうなっている。

`return res.json(ApiResponse.error(err));` の形をしているレスポンスは、全て 200 が返る代わりに、body に `ok: false` が入っているはず。

利用箇所は非常に多いので、これを全て直すのは得策ではない。

What happens? (症状)
---------------------

調査したところ、 `PageContainer` の `createPage`, `updatePage` では、Crowi 由来の API の挙動に対応しており、 `ok: false` があれば Error を throw するようになっている。

ところがこれを使う側で try-catch していない(かつ async function を await していない)ため、結果的に例外が握りつぶされる形になっている。


What is the expected result? (期待される動作)
-------------------------------------------

- クライアント側で適切に例外処理を行いって Toaster を表示し、ユーザーに保存失敗したことを通知する
