### ISSUE TITLE
Bug, Question: 数式内で<, >を使用すると正しく表示されない

### ISSUE THREAD

**Issue by paruma** [weseek/growi#1597]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |(growi.cloud)|
|GROWI     |3.6.2|
|node.js   |12.14.0|
|npm       |6.13.4|
|Using Docker| (growi.cloud)|
|Using [growi-docker-compose][growi-docker-compose]|(growi.cloud)|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.2|
|browser   |Google Chrome 79.0.3945.130|

How to reproduce? (再現手順)
---------------------------
ページを作成して、markdownで
```markdown
$x<0, y>1$
```
と書く。

What happens? (症状)
---------------------
Viewで
![image](https://user-images.githubusercontent.com/19905365/73843960-fbfedc00-4862-11ea-9def-e281c7d6bdfe.png)
と表示される。(`<0, y>`の部分が無視される。HTMLのタグと認識されている？)

参考: [growi.cloudでの再現](https://parumatest.growi.cloud/user/paruma/%E6%95%B0%E5%BC%8F%E5%86%85%E3%81%AE%E4%B8%8D%E7%AD%89%E5%8F%B7%E3%81%AE%E3%83%90%E3%82%B0)
![image](https://user-images.githubusercontent.com/19905365/73844052-25b80300-4863-11ea-9ffe-c30b195157ea.png)

What is the expected result? (期待される動作)
-------------------------------------------

Viewで
![image](https://user-images.githubusercontent.com/19905365/73844078-2fda0180-4863-11ea-9f10-3aa2f4b7daf0.png)
と表示されることが期待される。

**Comment by yuki-takei** [comment]
@paruma 
ご報告ありがとうございます。

この症状はGROWIが搭載している XSS 対策機能によるもので、既知の問題ではあるのですが、抜本的な対応時期は今のところ未定です。

回避策としては管理画面の Markdown Settings に於いて Enable Xss Prevention のチェックをオフにして設定を保存することで、期待される動作をさせることができます。
ただしセキュリティ面でのトレードオフがあり、 Markdown 文書中で XSS 可能となってしまいます。クローズドなメンバーでの利用 かつ クローズドな Wiki であるような環境でのみの措置とすることをお勧めします。

**Comment by yuki-takei** [comment]
関連 Issue: #981
