### ISSUE TITLE
Bug: Admin Customise page doesn't restore Custom HTML Header

### ISSUE THREAD

**Issue by yuki-takei** [weseek/growi#1605]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |v3.6.6|
|node.js   |12.13.1|
|npm       |6.12.1|

How to reproduce? (再現手順)
---------------------------

1. Go to `/admin/customize`
1. Input something to Custom HTML Header textarea and Update
1. Reload browser

What happens? (症状)
---------------------

- Custom HTML Header textarea is empty

What is the expected result? (期待される動作)
-------------------------------------------

- Custom HTML Header textarea is filled 

Note
----

- 
-

**Comment by itizawa** [comment]
調査の結果、getConfig() ではタグが抑制されてしまうことが判明した。
解決策として api で取得する方法をとったが、その場合現在の方法では入力時の操作性が極端に悪くなるため、render 前に 値を取得する方法にリファクタリングした。

**Comment by yuki-takei** [comment]
fixed by #1617
