### ISSUE TITLE
Feature: Support Foce login by SAML provider

### ISSUE THREAD

**Issue by sahya** [weseek/growi#1611]
Environment

|item|version|
|:---:|:---:|
|OS||
|GROWI|3.6.3|
|node.js|12.14.0|
|npm|6.13.4
|yarn|1.21.1|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1.  no trouble(this is request)

What happens? (症状)
---------------------

1.  no trouble(this is request)

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------
- Force SAML login
    - UI: Checkbox or toggle switch (up to you.)
- Note: The option is dangerous. Because if it switches to on,  then it cannot log in by Growi local user. So I think it should be better to put a description. 
It profits for end-user that doesn't select the login method button.

Related issue
-------------------------------------------
#615: Feature: Support mostly setting items of SAML provider

**Comment by yuki-takei** [comment]
This request will be resolved by configuration in admin page.

Solution
----------

Turn off "ID/Pass" Authentication in "Authentication Mechanism Settings" of `/admin/security`

**Comment by sahya** [comment]
@yuki-takei Thank you for your advice.
In fact, I set it up exactly as you said and found that Growi should have auto-redirect.
So I will try to find out if the function can be implemented.
