### ISSUE TITLE
Question: ファイルアップロード先をS3に指定した場合、"File uploading is disabled" と表示される

### ISSUE THREAD

**Issue by sugoto911** [weseek/growi#1618]
Question
------------

以下のページを参考に、GrowiにアップロードしたファイルがS3バケットに保存されるように設定いたしました。
設定後にファイルのアップロードを試みたところ、ページの編集画面に「File uploading is disable」と表示され、アップロードを行えませんでした。
手元にありますGrowiの別環境（Ver. 3.5.5）では正常にS3バケットへアップロードが可能であったため、バージョン差分による問題かと思い、質問させていただきました。
またS3バケットの設定は、その別環境と同等にしております。

[AWS S3 Bucket のセットアップ \| GROWI Docs](https://docs.growi.org/ja/admin-guide/management-cookbook/aws-s3-bucket-setting.html)
[GROWI で画像をアップロードできるようにする \(AWS S3の設定\) \- zuglab](https://www.zuglab.tech/entry/2019/09/21/020910)

また、以下のissueは確認済みです。
[Question:S3にアップロードしようとすると失敗する · Issue \#774 · weseek/growi](https://github.com/weseek/growi/issues/774)

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2 (ECS Optimized)|
|GROWI     |3.6.6|
|node.js   | 12.14.1 |
|npm       | 6.13.4 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Mojave 10.14.6 |
|browser   |Google Chrome 79.0.3945.130|

### システム構成

- Amazon ECS上でGrowiを動かしています。
  - 「growi-docker-compose」の docker-compose.yml を参考に、ECS周りの設定をしています。
- S3アップロード用のアクセスキーに紐付くIAMユーザーには、S3FullAccessの権限を与えています。
- S3のアクセス権限周りの設定（ACL、バケットポリシー等）は特に設定しておりません。

How to reproduce? (再現手順)
---------------------------

1. 「管理」->「アプリ設定」からS3の設定を実施
2. テスト用のページを作成後、ドラッグアンドドロップでファイルをアップロードする

What happens? (症状)
---------------------

- 「File uploading is disable」と表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- ファイルがアップロードでき、アップロードしたファイルがS3バケット内に保存されている。

Note
----

- FILE_UPLOAD=local を設定した場合、ファイルアップロードは可能です。
- Docker Desktop for Macで「growi-docker-compose」の docker-compose.yml をrunしたところ、同一の事象が発生しました。
  - localを指定した場合、アップロードは可能でした。

**Comment by yuki-takei** [comment]
@sugoto911 こちら close されてますが、解消したんでしょうか？

**Comment by sugoto911** [comment]
@yuki-takei ご返信ありがとうございます。#1599 と関連性の強い事象と判断し、クローズさせていただきました。
（その旨コメントできておらず、申し訳ございません。）
