### ISSUE TITLE
カスタムスクリプトで＜，＞で囲まれた部分が正常に反映されない

### ISSUE THREAD

**Issue by tsumtsumyuma** [weseek/growi#1624]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI     |3.6.6|
|node.js   |12.14.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome|

How to reproduce? (再現手順)
---------------------------
カスタマイズ > カスタムスクリプトで以下の文字列を入力し「更新」すると「＜＞」で囲まれた部分が除外され正常に反映されていないようです．

入力した文字列
    ```
    return '<li class="tbd"><a href="' + href + '">' + name + '</a></li>'
    ``` 

「更新」後の文字列
    ```
    return ' ' + name + ' '
    ```

What happens? (症状)
---------------------
「＜＞」で囲まれた部分が除外され正常に反映されていない

What is the expected result? (期待される動作)
-------------------------------------------
「＜＞」で囲まれた部分が正常に反映される

Note
----

- 本事象はv3.6.2より継続して発生しています．

**Comment by itizawa** [comment]
ご報告いただきありがとうございます。
該当の問題はカスタム CSS と同様 v3.6.7 にて解消致しました。
v3.6.7 リリースをお待ちください。

**Comment by tsumtsumyuma** [comment]
ご対応いただきありがとうございます．
v3.6.7で解消されたとのこと承知しました．
本件クローズさせていただきます．
