### ISSUE TITLE
Bug: springテーマでwiki内のリンクが見えなくなる

### ISSUE THREAD

**Issue by ham-katsu** [weseek/growi#1626]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu 18.04|
|GROWI     |3.6.6|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.3|
|browser   |chrome 80.0.3987.87|

How to reproduce? (再現手順)
---------------------------

 themeをspringにする

What happens? (症状)
---------------------

バックグラウンドの色とリンクの色(.wiki a)がおなじになるためテキストが見えなくなる．

<img width="679" alt="スクリーンショット 2020-02-11 14 46 47" src="https://user-images.githubusercontent.com/7610144/74213914-b1f07d00-4cde-11ea-9fe3-ae0bb3afd3bd.png">

What is the expected result? (期待される動作)
-------------------------------------------

- リンクの色を変えてほしい

Note
----
https://github.com/weseek/growi/blob/a37b660f657fc1f77cfed4d36b16b2fbeb21a9ce/src/client/styles/agile-admin/inverse/colors/spring.scss#L4-L26
で，`$linkcolor`の設定がない？

**Comment by kaoritokashiki** [comment]
はむかつさん
報告して頂きありがとうございます。
リンクが見えなくなってしまっている問題につきまして
確認いたしますので、少々お待ちください。

**Comment by kaoritokashiki** [comment]
問題の確認を致しました。
直しますのでもうしばらくお待ちください。
申し訳ございません。

**Comment by ham-katsu** [comment]
ありがとうございます．
よろしくおねがいします

**Comment by kaoritokashiki** [comment]
@ham-katsu 
お待たせしました
v3.6.7で解消しました。
バージョンupして確認してみてくだい。
今後もGROWIとspringテーマをよろしくお願いいたします。
