### ISSUE TITLE
Bug: When hovering over a link in the wiki with the spring theme, characters disappear.

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1637]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.6.7|
|node.js   |12.13.1|
|npm       |6.12.1|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------

- Choose Spring Theme

What happens? (症状)
---------------------

![スクリーンショット 2020-02-15 16 10 22](https://user-images.githubusercontent.com/48426654/74583781-feed8f80-500d-11ea-8fba-9cb1d08b7f79.png)

- When hovering over a link in the wiki with the spring theme, characters became white.

What is the expected result? (期待される動作)
-------------------------------------------

- characters is shown

Note
----
```
.wiki a:hover {
    color: #fff;
}
```
It seems to be invisible because white is specified, sorry to trouble you, 
but it will be helpful if you can correct it.

**Comment by yuki-takei** [comment]
fixed by #1639
