### ISSUE TITLE
スレッド形式コメントが4件以上連なると、中間のコメントが閲覧できなくなる

### ISSUE THREAD

**Issue by dakesan** [weseek/growi#1643]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |3.6.7|
|node.js   |12.16.0|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 Pro|
|browser   |Google Chrome 80.0.3987.116(Official Build)|

How to reproduce? (再現手順)
---------------------------

1. 任意のコメントに対してリプライコメントを追加する
2. リプライコメントに対するリプライコメントを追加する
3. 2の操作が合計三回以上行われる

What happens? (症状)
---------------------

- 最も新しい2件のリプライ以外は省略される（...moreの表示）
- 省略されたリプライは閲覧できない

What is the expected result? (期待される動作)
-------------------------------------------

...moreをクリックすることで省略されたコメントを閲覧できる
または
管理画面から省略のON/OFFを選択できる

といったことが実現できれば良いと思います。
お手数おかけしますがご検討お願いいたします。

**Comment by itizawa** [comment]
Issue を起票いただきありがとうございます。
該当の件につきまして再現確認いたしました。
修正いたしますので少々お待ちください

**Comment by itizawa** [comment]
https://github.com/weseek/growi/pull/1654
にて改修されました。
「管理画面から省略のON/OFFを選択できる」も実装しましたのでご確認ください。

次リリースの v3.6.8 に含まれますので少々お待ちください

**Comment by dakesan** [comment]
v3.6.8 にて、「...moreをクリックして展開」・「返信コメントを全て表示する」ともに正常に動作していることを確認しました。

大変迅速な対応、感謝です！
