### ISSUE TITLE
/_api/pages.update 利用時のエラー

### ISSUE THREAD

**Issue by netsugo** [weseek/growi#1650]
APIを利用してページの更新を試みたところ、エラーが発生しました。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS       | Ubuntu 18.04.4 LTS|
|GROWI     |3.6.7|
|node.js   |12.16.0|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.84.4 LTS (同上)|
|browser  |curl 7.58.0|

How to reproduce? (再現手順)
---------------------------

1. curlで更新するページを送信する。example_token, example_idは適宜置き換える。
    ```bash
    curl -X POST -H "Content-Type: application/json" \
    -d '{"access_token":"example_token","body":"# example page","page_id":"example_id"}' \
    http://localhost:3000/_api/pages.update
    ```
1. 以下のエラーレスポンスが返ってくる。
    ```json
    {"ok":false,"error":"TypeError: Cannot read property 'body' of null"}
    ```

What happens? (症状)
---------------------
- APIを通じて送信したページ更新データがHost側で認識されない。

```
# POSTした時のコンソールログ
app_1            | [2020-02-23T15:30:56.266Z] ERROR: growi:routes:page/77 on 1ecfff48ba9d:
app_1            |   error on _api/pages.update TypeError: Cannot read property 'body' of null
app_1            |       at api.update (/opt/growi/src/server/routes/page.js:941:69)
app_1            |       at runMicrotasks (<anonymous>)
app_1            |       at processTicksAndRejections (internal/process/task_queues.js:97:5)
app_1            | [2020-02-23T15:30:56.267Z]  INFO: express/77 on 1ecfff48ba9d: ::ffff:172.31.0.1 <-- POST /_api/pages.update HTTP/1.1 200 69 - curl 7.58 Other 0.0.0 4.140889 ms (req_id=55fba8bd-8603-4ffb-95ef-85d0406ebcd1)
```

What is the expected result? (期待される動作)
-------------------------------------------

- 送信したデータが認識され、正常にページが更新される。

**Comment by itizawa** [comment]
GROWI のご利用ありがとうございます。

ページのアップデートには、上記のパラメータと `revision_id` が必要となります。
リクエスト body に該当ページの `revision_id` を追加して送信してみてください。

ご確認よろしくお願いいたします

**Comment by netsugo** [comment]
対応ありがとうございます。

リクエストに`revision_id`を追加して送信したところ、正常にページが更新されたことを確認できました。

**Comment by itizawa** [comment]
正常にページが更新されたようで良かったです。
本件クローズさせていただきます。
