### ISSUE TITLE
Bug: No list shown by growi-plugin-lsx@3.1.0

### ISSUE THREAD

**Issue by k13nismo** [weseek/growi#1658]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS  7.7|
|GROWI     |3.6.7|
|node.js   |12.16.1|
|npm       |6.14.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 79.0|

How to reproduce? (再現手順)
---------------------------

1. Install plugin
I tried both yarn and npm.
`yarn add growi-plugin-lsx` / `npm install --save growi-plugin-lsx`
1. Run growi
1. Add some pages, and write `$lsx(/)` at newest page.

What happens? (症状)
---------------------

- No list shown.
![image](https://user-images.githubusercontent.com/25317392/75403710-d178de00-594b-11ea-96d0-4bb30056d9e5.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Page list shown.

Note
----

- 一部のページタイトルには日本語が含まれます
- 何か足りない情報や試せそうなことはあるでしょうか
- growiの初回起動時に`$lsx(/)`の文字列が見えていて、用途がわかると使いたくなって
プラグインを入れてみたものの表示されないという状況です

**Comment by yuki-takei** [comment]
@k13nismo 2の Run growi は、どのようなコマンドを実行していますか？

プラグインのインストール操作後は、クライアントビルドが必要です。

https://docs.growi.org/ja/dev/startup/launch.html#npm-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%83%AA%E3%82%B9%E3%83%88

のコマンド表を参考に、`yarn build:prod` を実行しているかどうかを確認してください。
また、起動時のサーバー側ログとブラウザコンソールに出ているログがあると原因を特定しやすいです。

**Comment by k13nismo** [comment]
@yuki-takei 

起動コマンドは[ここ](https://docs.growi.org/ja/admin-guide/admin-cookbook/launch-with-systemd.html#%E6%A6%82%E8%A6%81)を参考に growi.service を作成して`sytemctl start growi`でしたので実際は`npm start`だと思います。
growi.service 内の npm も yarn に置き換えたほうがいいのでしょうか。

ログを確認したところ `npm build:prod` は実行していました。
改めて `yarn build:prod` を実行しましたが事象としては変化なしでした。

* コンソールログ
[console.log](https://github.com/weseek/growi/files/4259426/console.log)
* 起動時ログ
[exec.log](https://github.com/weseek/growi/files/4259460/exec.log)
前述のとおりsytemctlを使って起動していたので /var/log/messages から抜き出しました。
コンソールは生データですが、こちらはIPアドレスの部分を編集しています。

**Comment by yuki-takei** [comment]
@k13nismo 再現確認しました。
growi-plugin-lsx の v3.1.0 で出る症状ですので、一旦 v3.0.7 をインストールしていただければ暫定的に回避できると思います。

修正次第次のバージョンをリリースします。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@k13nismo 
growi-plugin-lsx の方の修正が完了し、[v3.1.1](https://github.com/weseek/growi-plugin-lsx/releases/tag/v3.1.1) をリリースしました。また、v3.1.0 は廃版となりました。

v3.0.7 または v3.1.1 で正常動作するはずですのでご確認いただければと思います。

**Comment by k13nismo** [comment]
@yuki-takei 

v3.1.1 にてリスト表示を確認しました。
ご対応ありがとうございます。
