### ISSUE TITLE
Slack通知がproxy環境下で送られてこない

### ISSUE THREAD

**Issue by Childish-developer-yt** [weseek/growi#1693]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu-16.04.5|
|GROWI     |3.6.4|
|node.js   |8.11.3|
|npm       |6.13.7|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Mojave|
|browser   |Chrome  80.0.3987.132|

How to reproduce? (再現手順)
---------------------------
Webhookを用いてSlackに通知するようにページ更新する
proxyは環境設定に設定済み

What happens? (症状)
---------------------
slackに通知が送られてこない

What is the expected result? (期待される動作)
-------------------------------------------
通知が送られてくること

**Comment by yuki-takei** [comment]
@Childish-developer-yt 

いくつか質問をさせてください。

1. proxy というのは、どういった種類のもので、どのような設定をされているでしょうか？
1. その proxy が存在しない環境では通知が送られるのでしょうか？

あとはあまり関係ないかもしれませんが、node 8.x は GROWI v3.x 以降ではサポートしていないので、10.x 以上に上げていただいた方がトラブルが少ないと思います。

**Comment by Childish-developer-yt** [comment]
返答ありがとうございます。
node(12.14.1)とnpm(6.13.4)アップデートしましたが、変わらずでした
1.社内NWからインターネットに疎通する際に社内WebProxyからのみ疎通が許可されている状態です
2.同じ設定でProxy環境外でしたら通知が送られてきています
（社内VMを利用している都合、proxy環境外での利用はできないです:cry:）

**Comment by yuki-takei** [comment]
社内NWにある GROWI サーバーから slack の web hook の URL への疎通が制限されているということでしょうか？であればその Proxy 側の設定か、あるいは GROWI を載せているホストのサーバーの設定起因だと思います。

いずれにせよ導入のご相談かと思いますので、Slack からコミュニティのメンバーに相談してみてください。その際、GROWI をビルドする時はどうしたのか(ビルド時もインターネットに出る必要があるはずなので)等の情報を添えていただけると解決策が見つかりやすいかと思います。

**Comment by yuki-takei** [comment]
環境上の問題と判断しクローズします。
本体の挙動がおかしい場合はリオープンしますのでその場合は再度コメントをお願いします。

**Comment by tWatanabeCTC** [comment]
上記と同様の環境ですが、systemdで起動するときに環境変数でhttp_proxyとhttps_proxyの情報を記載することで解決しました。

具体的には Environmentfileを作成して、その中に環境変数を記載してgrowi.serviceでEnvironentFileを読み込む形で動作可能です。
