### ISSUE TITLE
Improvement: Notification Control for private pages

### ISSUE THREAD

**Issue by noymer** [weseek/growi#1695]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.6.6|
|node.js   |10.18.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

it is independent to clients

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------

1. process 1

slackへのincoming webhookの設定を行う。

1. process 2

`/admin/notification` にて、以下のように `/*` のトリガーパスでglobal notificationの設定を行う。
（試した状況において、通知チャネル先はprivate channelです）
![image](https://user-images.githubusercontent.com/8816130/76065394-f1a14080-5fce-11ea-9639-f0bf7edbe48f.png)

1. process 3

`/user/noymer/メモ/2020/03/06/private memo` のページを、公開対象を「自分のみ」として作成

1. process 4

なお、`/admin/security` の「ページのリスト表示と検索　'自分のみ'に閲覧制限しているページ」はoffです。

![image](https://user-images.githubusercontent.com/8816130/76066070-2eba0280-5fd0-11ea-9abf-ca935963e1de.png)

What happens? (症状)
---------------------

- symptom 1

設定したslackのチャネルに、自分のみ公開にもかかわらず通知が表示されてしまう。
<img src="https://user-images.githubusercontent.com/8816130/76065781-9facea80-5fcf-11ea-8332-b9b53f674b72.png" width="350px">

What is the expected result? (期待される動作)
-------------------------------------------

- 「自分のみ」公開のページは、「ページのリスト表示と検索　'自分のみ'に閲覧制限しているページ」がoffである場合、
global notificationの設定によって通知が送られるべきではないと思います。

Note
----

- 何らかの意図上のもと、このような挙動になっているのかもと思ってもいます。
- GROWIを大変便利に使わせてもらってます、ありがとうございます！

**Comment by itizawa** [comment]
GROWI のご利用ありがとうございます。

同様の現象を確認できました。
修正いたしますので少々お待ちくださいませ。

**Comment by yuki-takei** [comment]
マージされました。v3.7.1 リリースをお待ちください。

**Comment by noymer** [comment]
遅ればせながら、ありがとうございました！！
