### ISSUE TITLE
Improvement: テーブル編集時の自動整形を一時的にでも無効にしたい

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#1697]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.4 LTS|
|GROWI     | 3.6.6 |
|node.js   | 10.19.0|
|npm       |6.13.4|
|Using Docker|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |80.0.3987.132|

How to reproduce? (再現手順)
---------------------------
1. テーブルの行を改行する

What happens? (症状)
---------------------
1. markdownの該当テーブル全体が自動整形される

What is the expected result? (期待される動作)
-------------------------------------------
- 例えばCtrl+Iといったコマンドを入力した時だけ、選択範囲のみ整形されるようになってほしい

Note
----
- テーブルの途中からテーブルを分割したい時など、Enterを押すと空白行が作られるため、何もない行を作るのが少し大変に感じています。
- 自動整形は、セルの中で改行していたり、長い文字列が入っている場合など整形の結果テーブルが見にくく、編集しにくくなって不便なケースもあると感じています。
- デフォルトの挙動も便利です。でもオプションで一時的でも変更できればもっと嬉しいです。

**Comment by yuki-takei** [comment]
@hanapage 確かに Mathjax のレンダリングを同様、ON/OFF のスイッチがあるとよりユーザーフレンドリーですね。

一応ワークアラウンドとして、改行を「Shift + Enter」で行う事で整形されるのを回避できます。お試しください。
