### ISSUE TITLE
MongoDB を作り直すと、Chrome で Internal Server Error が起きる

### ISSUE THREAD

**Issue by mzch** [weseek/growi#1702]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Debian 10.3|
|GROWI     |3.6.9|
|node.js   |v10.17.0|
|npm       |6.11.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.3|
|browser   |Google Chrome 80.0.3987.132|

How to reproduce? (再現手順)
---------------------------

1. Chrome で Growi にログインする
1. MongoDB の DB を drop して create する
1. growi を再起動する
1. Chrome で再読み込みをする
1. HTTP 500 (Internal Server Error) が返る

What happens? (症状)
---------------------

- Growi が `Internal Server Error (HTTP 500) を返す。

```
Mar  6 18:56:01 n08 npm[5832]: #033[90m  #033[36mUnhandled Rejection: Promise: Promise {
Mar  6 18:56:01 n08 npm[5832]:     <rejected> { Error: Request Timeout after 5000ms
Mar  6 18:56:01 n08 npm[5832]:         at /srv/growi/growi/node_modules/elasticsearch/src/lib/transport.js:362:15
Mar  6 18:56:01 n08 npm[5832]:         at Timeout.<anonymous> (/srv/growi/growi/node_modules/elasticsearch/src/lib/trans
port.js:391:7)
Mar  6 18:56:01 n08 npm[5832]:         at ontimeout (timers.js:436:11)
Mar  6 18:56:01 n08 npm[5832]:         at tryOnTimeout (timers.js:300:5)
Mar  6 18:56:01 n08 npm[5832]:         at listOnTimeout (timers.js:263:5)
Mar  6 18:56:01 n08 npm[5832]:         at Timer.processTimers (timers.js:223:10)
Mar  6 18:56:01 n08 npm[5832]:       status: undefined,
Mar  6 18:56:01 n08 npm[5832]:       displayName: 'RequestTimeout',
Mar  6 18:56:01 n08 npm[5832]:       message: 'Request Timeout after 5000ms',
Mar  6 18:56:01 n08 npm[5832]:       body: false } } Reason: { Error: Request Timeout after 5000ms
Mar  6 18:56:01 n08 npm[5832]:       at /srv/growi/growi/node_modules/elasticsearch/src/lib/transport.js:362:15
Mar  6 18:56:01 n08 npm[5832]:       at Timeout.<anonymous> (/srv/growi/growi/node_modules/elasticsearch/src/lib/transpo
rt.js:391:7)
Mar  6 18:56:01 n08 npm[5832]:       at ontimeout (timers.js:436:11)
Mar  6 18:56:01 n08 npm[5832]:       at tryOnTimeout (timers.js:300:5)
Mar  6 18:56:01 n08 npm[5832]:       at listOnTimeout (timers.js:263:5)
Mar  6 18:56:01 n08 npm[5832]:       at Timer.processTimers (timers.js:223:10)
Mar  6 18:56:01 n08 npm[5832]:     status: undefined,
Mar  6 18:56:01 n08 npm[5832]:     displayName: 'RequestTimeout',
Mar  6 18:56:01 n08 npm[5832]:     message: 'Request Timeout after 5000ms',
Mar  6 18:56:01 n08 npm[5832]:     body: false }#033[39m
Mar  6 18:56:05 n08 npm[5832]: #033[39mError: user not found
Mar  6 18:56:05 n08 npm[5832]:     at passport.deserializeUser (/srv/growi/growi/src/server/service/passport.js:668:17)
Mar  6 18:56:05 n08 npm[5832]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Mar  6 18:56:50 n08 npm[5832]: Error: user not found
Mar  6 18:56:50 n08 npm[5832]:     at passport.deserializeUser (/srv/growi/growi/src/server/service/passport.js:668:17)
Mar  6 18:56:50 n08 npm[5832]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

What is the expected result? (期待される動作)
-------------------------------------------

- ログイン中を示す token(?) が不正なら、ログイン画面に戻るようにして欲しい

Note
----

- Chrome の Cookie を削除すれば、正常にアクセスできました。

**Comment by yuki-takei** [comment]
@mzch こちら再現確認を行ったのですが再現しないです。

以下こちらの環境です。

## 動作確認環境
### Host

| item     | version |
| ---      | --- |
|OS        | Win 10 Home |
|GROWI     |3.6.9|
|node.js   |v12.16.0|
|npm       |6.13.4|
|yarn       | 1.22.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Win 10 Home|
|browser   |Google Chrome 80.0.3987.132|

## やったこと
1. 新規 GROWI ビルド、起動
    1. `yarn build:prod`
    1. `yarn server:prod`
1. セットアップ(最初の admin ユーザーを作成)
1. Chrome で `/` を表示
1. MongoDB の DB を削除
1. (MongoDB で同名の DB を作成) <-- これはやってもやらなくても同じ結果
1. サーバーダウン
1. サーバー起動(`yarn server:prod`)
1. Chrome で `/` をリロード

## 症状
`/installer` にリダイレクトされた

**Comment by yuki-takei** [comment]
Redis を利用しているとかそういった違いはありますか？

**Comment by mzch** [comment]
@yuki-takei 確かに、redis を利用しています。それのせいでしょうか？

**Comment by yuki-takei** [comment]
## 症状について
それの可能性は高いですね。その環境だとセッションの情報は Redis を見に行くようになりますので、MongoDB のデータは存在しないもののブラウザのクッキーを参考に Redis から情報を引っ張ってきて `passport.deserializeUser` が走ってしまう、という流れなのかなと。

再現確認ですが、できれば Redis のデータも削除した上での症状のテストをいただけると大変助かります。

## 今後の対応について
以下は Redis に情報が残っているのが原因だと仮定した上での話ですが、

GROWIとして参照する DB にデータが残っていなければ再インストール、という動きになるよう実装されています。ただ Redis という DB の一部分に旧環境の情報が残っているという状況は想定していないので、もし過程が正しければこの件は won't fix になります。

よろしくお願いいたします。

**Comment by mzch** [comment]
試しました。

1. MongoDB の DB を削除
1. Internal Server Error 発生を確認
1. redis DB を削除
1. redis を再起動
1. growi を再起動
1. インストーラー画面の表示を確認

ということで、redis に情報が残っていたためのようです。

**Comment by yuki-takei** [comment]
異なるデータストア間のデータ整合性が取れていないケースで発生する問題なので、システムとしては仕様通りという結論です。クローズします。
