### ISSUE TITLE
Feature: LDAP認証のAttribute Mappingで複数属性の組み合わせ

### ISSUE THREAD

**Issue by m1na1p** [weseek/growi#1706]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS8|
|GROWI     |3.6.9|
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

What is the expected result? (期待される動作)
-------------------------------------------

セキュリティ設定のLDAP認証にあるAttribute Mapping(オプション）の
usernameやName欄ですが、複数の属性を組み合わせることはできないでしょうか？
例えば現在はsAMAcountNameを指定しているのですが、
これをsn + givenNameのように複数属性連結できると嬉しいです。

**Comment by yuki-takei** [comment]
@m1na1p 
現状そういった機能はなく、また将来的にも実装はあまり考えていないです。
(ただ、外部からPRが送られてくるなら取り込むのも吝かではない)

LDAPの場合だと、そういった連結済みの attribute を事前に用意しておく、という解になるんじゃないでしょうか。

**Comment by yuki-takei** [comment]
クローズします。
