### ISSUE TITLE
 Sign up screen design collapse

### ISSUE THREAD

**Issue by TsuyoshiSuzukief** [weseek/growi#1713]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.7.0-RC|
|node.js   |3.2.7|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | windows |
|browser   | Firefox 73.0.1 (64-bit) |

How to reproduce? (再現手順)
---------------------------

1. 管理メニューのセキュリティ設定　ID/Password 設定の登録の制限で、`制限(登録完了には管理者の承認が必要)` を設定する
1. ログイン画面の Sign up リンクをクリック

What happens? (症状)
---------------------

添付の画像の通り、Sign up 画面レイアウトでデザイン崩れ。
![securitysettings_ui1](https://user-images.githubusercontent.com/42988650/76409297-85a94880-63d1-11ea-9633-6cbbbd6f2f7c.png)

- 登録許可メールアドレスのホワイトリスト に入力した時にもレイアウト崩れが発生する
![securitysettings_ui2](https://user-images.githubusercontent.com/42988650/76409643-00726380-63d2-11ea-8acb-c6f3b05f4c1b.png)

What is the expected result? (期待される動作)
-------------------------------------------

`公開(だれでも登録可能)` を設定した状態のレイアウト同様、ボタンや入力欄が背景色違いの枠内に収まる事
![securitysettings4](https://user-images.githubusercontent.com/42988650/76409345-98bc1880-63d1-11ea-9eab-a2cea6ddc879.png)

Note
----

- 
-

**Comment by yuki-takei** [comment]
v4.0.0 で修正されました。
