### ISSUE TITLE
Bug: The page isn’t redirecting properly

### ISSUE THREAD

**Issue by TsuyoshiSuzukief** [weseek/growi#1722]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.6.9|
|node.js   |v12.16.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10|
|browser   |Firefox 74.0 (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. 管理メニュー　セキュリティ設定で、ID/Pass の登録の制限を「制限」にする
1. ユーザーが Sign up で新たなユーザーを作成する
1. ユーザーが管理者に承認される前に、ユーザー側でログインする
1. ユーザー側の画面は登録完了の画面へリダイレクトされる
1. ユーザー側で、login 画面へ遷移しようとして URL 直接遷移を試みる

What happens? (症状)
---------------------

- ログイン画面へ遷移したいが、登録完了画面へリダイレクトされる
- この時更に 管理者が承認せずユーザーを削除する
- その後、ユーザー側画面が以下のようになり、GROWI ページのどこにも遷移できなくなる

![image](https://user-images.githubusercontent.com/42988650/76593435-a4c2ea00-6539-11ea-9cdb-9067a59c479c.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 登録完了画面へリダイレクト時も、ログイン画面への URL 直接遷移は出来ること
- 承認前のユーザーで、ログインしリダイレクトされるユーザー側画面も、管理者によるユーザー削除後に正常画面遷移できること

Note
----

- v3.6.8 では発生していない現象です、v3.6.8 では正常にログイン画面へ遷移できます

**Comment by TsuyoshiSuzukief** [comment]
制限ではなく「公開」にした状態だと、Sign アップ後のログインは正常に行えます。

リダイレクトされる状態になったブラウザには、キャッシュでログイン状態が残ってしまうのか、別アカウントへの切り替えをしようとログイン画面URL叩いても `The page isn't redirecting properly` 画面になります。

**Comment by yuki-takei** [comment]
Fixed by #1729 and #1730
