### ISSUE TITLE
MathJaxを使ったページの表示が不安定になる

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#1754]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.4 LTS|
|GROWI     | 3.7.0 |
|node.js   | 10.19.0|
|npm       |6.13.4|
|Using Docker|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |80.0.3987.149|

How to reproduce? (再現手順)
---------------------------
1. 下記のようなmathjaxの式をページに含める
  $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

What happens? (症状)
---------------------
1. [Math Processing Error]と表示され、数式が表示されない時がある。
1. \[x = {-b \pm \sqrt{b^2-4ac} \over 2a}\]と表示され、数式が表示されない時がある。
1. ページが真っ白になって何も表示されなくなり、ブラウザからこのウェブサイトは応答がありませんというようなダイアログが出る時がある。

What is the expected result? (期待される動作)
-------------------------------------------
1. MathJaxによってレンダリングされた式が毎回正しく表示される

Note
----
- 毎回発生するわけではありませんが頻度は多いです。 
- 更新ボタンを押してリロードすると表示される時もあります。
- clowd版を3.6.2 -> 3.7.0に変更しても発生しました。
  ヘルプのMathJaxの書き方のあたりで更新すると再現しやすいです。

**Comment by kaishuu0123** [comment]
@yuki-takei 

この問題は v3.7.0 から起きている事象かもしれません。
draw.io が内部で MathJax を draw.io 自身のために初期化しており、これが GROWI の MathJax と競合しているため、問題が起きているように見えます。

直し方としては、2 案あって、

1. GROWI の MathJax を 3.0 系に上げて、とりあえずの対応とする
    * cdn-manifest.json の mathjax のところを `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js` にする
    * `RevisionBody.jsx` 内にある `renderMathJax()` 内で null チェックを行うようにする (` if (MathJax != null && MathJax.Hub != null)` ガードを入れる )
    * 結果、それっぽくレンダリングされる
2. MathJax の後方互換性を切ってしまって、 blockdiag や draw.io のようにブロックで記述できるように仕様を変更する
    * MathJax 3 では Server-Side Rendering に対応したので、 `markdown-it` の plugin としてレンダリング可能にできそうな気がします。
    * が、今まで MathJax を愛用してきたユーザからすると、アップグレードして上手く動かない感じになるので、この案は私も迷っています。

**Comment by yuki-takei** [comment]
refs: https://github.com/jgraph/drawio/pull/833

ワークアラウンドのPRは適用済みです。v3.7.3 リリースをお待ちください。
