### ISSUE TITLE
draw.ioを含むページを編集するときに編集画面のスクロール位置が移動してしまう

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#1755]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.4 LTS|
|GROWI     | 3.7.0 |
|node.js   | 10.19.0|
|npm       |6.13.4|
|Using Docker|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |80.0.3987.149|

How to reproduce? (再現手順)
---------------------------
1. draw.ioを使って図を描き保存する
2. 編集画面でページスクロールが発生するまで行を増やす。
3. さらに２〜３行増やして最終行を編集する

What happens? (症状)
---------------------
- 文字を入力するごとに、編集画面が先頭にスクロールし、編集が難しくなる

What is the expected result? (期待される動作)
-------------------------------------------
- 文字を入力しても画面スクロールが発生しない 

Note
----
- 発生するのは最終行付近を編集している時のみ
- 先頭に近い部分ではスクロールの移動は発生しない
- draw.ioのコードおよび図が見えなくなるくらい行を伸ばすと発生しなくなる

**Comment by kaishuu0123** [comment]
@hanapage 
手元で再現することを確認しました〜。こちら修正 PR を送ってみようと思います。
