### ISSUE TITLE
コメントに画像をアップロードできない

### ISSUE THREAD

**Issue by tachibanayu24** [weseek/growi#1758]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI  3.6.9 |
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS v10.15.3|
|browser   |Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. コメントのテキストエリアに画像ファイルをドラッグアンドドロップする

What happens? (症状)
---------------------

`File uploading is disabled` と表示される

What is the expected result? (期待される動作)
-------------------------------------------

コメントにもドラッグアンドドロップで画像をアップロードしたいが、上記のように表示されてしまう。
AWS設定は完了しており、プロフィール写真を設定したり、コメントではなく投稿に画像をアップロードすることは問題なくできている。

**Comment by itizawa** [comment]
GROWI のご利用ありがとうございます。
上記の問題について再現しました。

修正いたしますので少々お待ちくださいませ

**Comment by yuki-takei** [comment]
修正完了しました。v3.7.1 リリースをお待ちください。

**Comment by tachibanayu24** [comment]
@yuki-takei 
早速のご対応ありがとうございます！
はい、お待ちしております。
