### ISSUE TITLE
Improve: Slack Notification

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#178]
Slackの通知機能に以下のような機能があるとベターだと思いました。

- 編集以外の削除・移動の通知
- ユーザ登録の通知
- コメント投稿の通知
- 編集通知のチェックボックスのデフォルト設定

**Comment by yuki-takei** [comment]
@shield-9 コメント投稿は確かに欲しい…

ただ Slack 連携という特定のサービス用のコードのトリガをいろんなところに仕込むとコードのスパゲティ化が進みそうなので、plugin 化するのを検討したいです。

そして今LDAP周りの実装を優先しているので他の機能は優先度が落ちます。気長にお待ちくださいませ。

**Comment by TatsuyaIse** [comment]
- [ ] 編集以外の削除・移動の通知
  - 通知内容
    - [ ] 操作内容（削除・移動）
    - [ ] 操作したユーザ
    - [ ] ページへのリンク（移動・削除後）
    - [ ] ページ内容の一部（先頭数行）
- [ ] ユーザ登録
  - 通知内容
    - [ ] 操作内容（ユーザ登録）
    - [ ] 操作したユーザ
    - [ ] ユーザ管理画面へのリンク？
    - [ ] 追加されたユーザ名、ロール？
- [ ] コメント投稿
  - 通知内容
    - [ ] 操作内容（コメント投稿）
    - [ ] 操作したユーザ
    - [ ] ページへのリンク
    - [ ] コメント内容
- [ ] 編集通知のチェックボックスのデフォルト設定
  - [ ] user のコレクションに通知のデフォルト設定を持つ？

**Comment by yuki-takei** [comment]
@TatsuyaIse これプラグインとして設計したいのでペンディングで。

**Comment by yuki-takei** [comment]
プラグイン化は断念、本体に実装します

**Comment by yuki-takei** [comment]
一旦コメント投稿時に投稿者が通知するかどうかを選ぶ形式での実装では完了したので close します。

IFTTT 連携や、システムグローバルなイベントトリガでの通知は別途 #229 , #547 で対応。
