### ISSUE TITLE
ver 3.7.1で数式が表示されない

### ISSUE THREAD

**Issue by YoshitakaMo** [weseek/growi#1808]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 8.1.1911|
|GROWI     |3.7.1|
|node.js   |10.19.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.4|
|browser   |Google Chrome 80.0.3987.149|

How to reproduce? (再現手順)
---------------------------
1. https://github.com/weseek/growi/issues/1717 で「数式が表示されない」をver 3.6.9のときに立てた者です。3.6.9では数式が表示されることを確認しました。この後、3.7.1のリリースに合わせて3.6.10, 3.7.0を経ずにアップグレードしました。
```
cd /opt/growi
git pull
git checkout -b v3.7.1 refs/tags/v3.7.1
yarn
systemctl restart growi
systemctl restart nginx
systemctl restart elasticsearch
```

2. ver 3.7.1で数式が含まれるページを表示しようとしたところ、うまく数式が表示されませんでした。以下の手順でver 3.6.9に戻したところ、こちらのバージョンでは数式が表示されました。
```
git checkout v3.6.9
yarn
systemctl restart growi
systemctl restart elasticsearch
```

What happens? (症状)
---------------------
$ E = mc^2 $など、ドルマークで挟んだTeX形式の数式が正しく反映されず、そのまま出力されてしまう。

What is the expected result? (期待される動作)
---------------------
MathJaxによってレンダリングされた式が毎回正しく表示される

**Comment by yuki-takei** [comment]
refs: https://github.com/jgraph/drawio/pull/833

ワークアラウンドのPRは適用済みです。v3.7.3 リリースをお待ちください。

**Comment by yuki-takei** [comment]
v4.0.8 時点で `/Sandbox/Math` ページで「Inline Formula」の

> When $a \ne 0$, 

の記述が正常にレンダリングされたことを確認しましたので、本 Issue は close します。
