### ISSUE TITLE
Feature: Readonly user

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#181]
登録せずにアクセスできる機能はありますが、それとは閲覧だけができるユーザが作れると便利だと思いました。

イメージとしては、既存の「管理者」「一般ユーザ」に加え、3つ目のロールとして「閲覧専用ユーザ」が選択できる感じです。

# 前提
* 外部には非公開
* どこからでもアクセスできる (接続元IPなどは限定しない)
* 利用者は不定期に増減することがある
* 編集するユーザと閲覧のみを行う利用者がはっきり分かれている

# 解決したい問題
* Basic認証+ゲストユーザのように共有の認証情報だと、定期的な変更を行わないとセキュリティが保てない
* ユーザを作成すると、本来、閲覧ができれば十分なユーザが編集もできてしまう

**Comment by yuki-takei** [comment]
#199 で Group ACL を実装中なのですが、一旦こちらで対応できるかなと思うので close します。

## ROM との細かい部分での違い

Group ACL 実装後のイメージとしては、「特定グループしか編集できないページ」を用意することで、それらのページに対しては新規ユーザーを ROM 扱いできます。

 > ユーザを作成すると、本来、閲覧ができれば十分なユーザが編集もできてしまう

と厳密には同一の機能にはなりませんが(普通にページ作ったり、全体公開ページは編集できてしまうので)、運用でカバーできる範囲かなと思います。

もっと ROM の実現に近づけるなら、admin page に Group ACL を使ったグローバル設定を設けるとかですかね。例えば、「指定グループに入っていないユーザーを ROM として扱う」とか。

**Comment by yuki-takei** [comment]
「閲覧専用ユーザ」の要望を別の方からいただいたので reopen します。
優先度は相変わらず低いままなので、実装者募集中です。

**Comment by yuki-takei** [comment]
起票から6年、Group ACL 実装から4年越し…

[v6.1.0](https://github.com/weseek/growi/releases/tag/v6.1.0) で実装されました。
