### ISSUE TITLE
添付ファイルが多いページで右側の目次リンクが機能しない

### ISSUE THREAD

**Issue by naomichi-y** [weseek/growi#1810]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | (growi.cloud) |
|GROWI     |3.6.10|
|node.js   | 12.16.1 |
|npm       |6.13.4|
|Using Docker|(growi.cloud)|
|Using [growi-docker-compose][growi-docker-compose]|(growi.cloud)|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Mac OS 10.14|
|browser   |Chrome 80.0.3987.149 |

How to reproduce? (再現手順)
---------------------------

添付ファイルが多いページで、`Attachments` のdivクラスに目次が乗ると、その上のリンクが押せなくなります。

<img width="1035" alt="Screen_Shot_2020-03-30_at_1_49_04" src="https://user-images.githubusercontent.com/1632478/77855047-f7ceb980-7228-11ea-9551-ee0345e0df74.png">

What is the expected result? (期待される動作)
-------------------------------------------

リンクが押せること。

**Comment by itizawa** [comment]
GROWI のご利用ありがとうございます。
上記の問題について再現確認しました。

修正いたしますので少々お待ちくださいませ

**Comment by yuki-takei** [comment]
@naomichi-y 修正マージされました。
次回リリースをお待ちください。

**Comment by naomichi-y** [comment]
ご対応ありがとうございました!
