### ISSUE TITLE
ゲストユーザーのアクセスで表示と内部状態とが異なっている

### ISSUE THREAD

**Issue by kiytech** [weseek/growi#1844]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.6 |
|GROWI     |3.7.0|
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10  1909 (Build: 18363.720)|
|browser   |Google Chrome 80.0.3987.149（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------
1. ログイン
2. Wiki管理トップからセキュリティ設定に移動
3. ゲストユーザーのアクセスを "許可" に設定
4. F5 でページをリロード

What happens? (症状)
---------------------

- ゲストユーザーのアクセス表示が "拒否" になっている
- ログアウト後にアクセスすると閲覧が可能な状態

What is the expected result? (期待される動作)
-------------------------------------------

- ゲストユーザーのアクセスの変更と表示の同期

Note
-------
3.7.2 でも確認しましたが、同様の症状がでています。

**Comment by itizawa** [comment]
Issue の報告ありがとうございます。

こちらの問題ですが、再現いたしました。
表示の問題で設定時に問題がある訳ではないようです。

修正いたしますので少々お待ちください。

**Comment by yuki-takei** [comment]
マージしてました。v3.7.3 リリースをお待ちください。

**Comment by kiytech** [comment]
ご対応ありがとうございました。
