### ISSUE TITLE
Trash page can be edited

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1848]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.7.2|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

How to reproduce? (再現手順)
---------------------------

1. access trash page
2. append `#edit` to end of path

What happens? (症状)
---------------------

- open page editor 

![スクリーンショット 2020-04-03 20 22 32](https://user-images.githubusercontent.com/48426654/78355575-e1d64580-75e8-11ea-8d60-f98553e2df63.png)

What is the expected result? (期待される動作)
-------------------------------------------

- [ ] Can't open page editor
- [x] Disappear edit icon

**Comment by yuki-takei** [comment]
dev/4.0.x ブランチで修正する

**Comment by yuki-takei** [comment]
v3.7.5 で修正済み
