### ISSUE TITLE
アカウント登録制限をかけている場合に新規登録画面でレイアウト崩れる

### ISSUE THREAD

**Issue by nyamane** [weseek/growi#1870]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |alpine 3.11.3|
|GROWI     |3.7.2|
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Catalina 10.15.3|
|browser   |Google Chrome 80.0.3987.149（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. `管理`→`セキュリティ設定`→`認証機構設定`→`ID/Password`
1. `登録の制限` を `制限（登録完了には管理者の承認が必要）` に設定する
1. `{GROWI_URL}/login` にアクセスして、`新規登録はこちら` をクリック

What happens? (症状)
---------------------

- 登録制限をかけている場合に出現するアラートメッセージが表示されるとレイアウトが崩れてしまう

```
<p class="alert alert-warning">
      この Wiki への新規登録は制限されています。<br>
      利用を開始するには、新規登録後、管理者による承認が必要です。
</p>
```

![スクリーンショット](https://user-images.githubusercontent.com/30485373/78738252-5c59e900-798c-11ea-9c76-a0facd15a5bd.png)

What is the expected result? (期待される動作)
-------------------------------------------

- アラートメッセージが表示される場合も枠内にコンテンツが納まること

**Comment by yuki-takei** [comment]
@nyamane ご連絡ありがとうございます。
こちら既知のバグで、#1713 で起票されています。

別の試作で bootstrap4 化が進んでおり、そちらのリリースと同時に対応完了する予定です。今しばらくお待ちいただければと思います。

**Comment by yuki-takei** [comment]
重複している Issue のため、クローズします。
