### ISSUE TITLE
SMTP設定でユーザ名が消える

### ISSUE THREAD

**Issue by Conoe** [weseek/growi#1883]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04 LTS|
|GROWI     |3.7.2|
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome|

How to reproduce? (再現手順)
---------------------------

1. 管理者権限のあるアカウントでログイン
2. 管理画面を開く
3. SMTP設定を入力し、更新、メールが届くことを確認

What happens? (症状)
---------------------
- 画面をリロードするとユーザ名のみが消えている

What is the expected result? (期待される動作)
-------------------------------------------
- ユーザ名にメールアドレスが表示されていること

Note
-

**Comment by itizawa** [comment]
issue の報告ありがとうございます。

同様の現象を確認できました。
修正しますので、少々お待ちください。
