### ISSUE TITLE
Bug: One request is sent three times

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#1896]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.4|
|GROWI     |3.7.3-RC|
|node.js   |12.14.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.4|
|browser   |chrome 80.0.3987.163 |

How to reproduce? (再現手順)
---------------------------

1. Drop DB, then restart the server without `yarn build`.
2. Send a request on the management screen etc.
 
What happens? (症状)
---------------------

- One request is sent three times.

<img width="1195" alt="スクリーンショット 2020-04-10 16 49 41" src="https://user-images.githubusercontent.com/48426654/78977965-f750ef80-7b53-11ea-8d1d-66410263460e.png">

What is the expected result? (期待される動作)
-------------------------------------------

- One request is sent only one time.

Note
----

- May not be relevant, asterisks appear when opening comment editor.
<img width="1075" alt="スクリーンショット 2020-04-10 17 00 02" src="https://user-images.githubusercontent.com/48426654/78978064-1f405300-7b54-11ea-8923-dd89a2157d8f.png">

**Comment by yusuketk** [comment]
memo:
`onclick` fires 3 times.
ex.  Set `<button id="i" onClick="console.log('hoge')">hoge</button>` in any html file in server/views. And click the button, log appears 3 times.
But it's not working before installing an app.

**Comment by yuki-takei** [comment]
This problem does not occur at least in v6.3.2 and v7.0.0.
