### ISSUE TITLE
Feature: Empty Trash

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2002]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.7.4|
|node.js   |12.16.2|
|npm       |6.14.4|

How to reproduce? (再現手順)
---------------------------

1. Go to `/trash`.

What happens? (症状)
---------------------

- To delete all pages in the trash (around 100 pages), you need to repeat:
  1. Open a trashed page from list.
  2. Click "Delete Completely".
  3. Go back to `/trash`.

What is the expected result? (期待される動作)
-------------------------------------------

- "Empty Trash" (or "Delete All Trashed Pages") button in `/trash`

**Comment by itizawa** [comment]
Thank you for reporting the feature suggestion.

I think it's inconvenient, too.

<img width="859" alt="スクリーンショット 2020-04-22 16 21 00" src="https://user-images.githubusercontent.com/48426654/79952573-990e0000-84b5-11ea-8598-45887123821c.png">

How about the "Empty Trash"  button appearing in an alert like this.

**Comment by shield-9** [comment]
That's brilliant!

**Comment by itizawa** [comment]
Implemented remove button.
Please wait for the next release !
