### ISSUE TITLE
Style issue in "Create External Account" modal

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2003]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.7.4|
|node.js   |12.16.2|
|npm       |6.14.4|

How to reproduce? (再現手順)
---------------------------

1. Go to `/me`
1. Open "External Accounts" tab.
1. Click "Add".

What happens? (症状)
---------------------

- Styling issue in modal.
![ユーザー設定](https://user-images.githubusercontent.com/3660715/79865925-f4d57c00-8416-11ea-94d1-6a468fe60ae5.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Fix layout style.

**Comment by itizawa** [comment]
Thank you for reporting the issue.

This Styling issue is occurring on some layouts, island, christmas, and antarctic.

Please wait a moment for investigate and fix.
