### ISSUE TITLE
Bug: 各userトップページでAttachmentsリストが表示されない

### ISSUE THREAD

**Issue by hiron-jp** [weseek/growi#2035]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.4 LTS|
|GROWI     |3.7.0|
|node.js   |12.16.2|
|npm       |6.14.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10, Ubuntu18.04, Mint 19.0|
|browser   |Firefox 75.0 etc|

How to reproduce? (再現手順)
---------------------------

1. GROWIにログイン
1. /user/(user_name)に移動
1. 画像やファイルをアップロード

What happens? (症状)
---------------------

- 他のページではページ最下部に出るAttachmentsリストが表示されない
- アップロードには成功している

What is the expected result? (期待される動作)
-------------------------------------------

- /user/(user_name)にもAttachmentsリストが表示されるようにしたい

Note
----

- ユーザートップページ以外、/user/(user_name)/xxxではAttachmentsリストが表示される
- 確かめてないですが、GROWIが自動で作成するページでは同様のことが起こる？

**Comment by yuki-takei** [comment]
@hiron-jp ご報告ありがとうございます。
GW明けあたりに着手しようと思います。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
修正完了しました。v3.7.5 リリースをお待ちください。
