### ISSUE TITLE
Feature: Fetch existing internal links during editing 

### ISSUE THREAD

**Issue by shivams** [weseek/growi#2046]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04 |
|GROWI     |3.7.4 |
|node.js   |12.16.2|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

What is the expected result? (期待される動作)
-------------------------------------------

In the editor, we add an internal by using a syntax such as this: `[[this is title>../samplepage]]`. However, this can get complicated when we have to add a link which is very far from the current page in hierarchy. A desired workflow would be that a pop-up opens when adding an internal link which searches for existing pages (much like the one that opens when we click on the `New` button on the top menu. 

Here is a demo:

![growi_linking_feature_request_8](https://user-images.githubusercontent.com/6936383/80259645-bdc7ca80-86a3-11ea-9c60-388c9cef7b07.gif)

**Comment by yuki-takei** [comment]
@shivams 
Thank you for your request.

In fact, we were talking about a feature within the dev team that was similar to the idea you came up with. (Sorry, the minutes of a meeting is written in Japanese)

/GROWI村議議事録/20200227
https://dev.growi.org/5e5751ad1337da0048e5fc57


However, I think it will be a while before we start considering it. Please wait a moment. Thanks.

**Comment by itizawa** [comment]
@shivams  

Thank you for your wonderful request.
The ability to edit links has been released at v4.2.3.

Please see here for the operation.
https://twitter.com/weseek_inc/status/1338496274677510147

Please create an issue if you have other requests.
This issue will be closed.

**Comment by shivams** [comment]
Wow!! Thanks @itizawa I will check it out. Very happy to hear this.
