### ISSUE TITLE
Question: HTML tags aren't displayed at all

### ISSUE THREAD

**Issue by kaoritokashiki** [weseek/growi#2072]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |mac OS 10.14.6|
|GROWI     |3.7.4|
|node.js   |12.14.1|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS 10.14.6|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. Create a new page and write a title with HTML tags.
1.  Look at the new page title you created

What happens? (症状)
---------------------
- the tags you wrote aren't displayed at all.

- test1
<img width="764" alt="Screen Shot 0002-04-28 at 18 28 28" src="https://user-images.githubusercontent.com/59536731/80471991-20101c00-897f-11ea-9416-94988cbf36ef.png">
↓↓↓
<img width="764" alt="Screen Shot 0002-04-28 at 18 28 50" src="https://user-images.githubusercontent.com/59536731/80471988-1e465880-897f-11ea-85fc-353a34649af4.png">

- test2
<img width="764" alt="Screen Shot 0002-04-28 at 18 35 23" src="https://user-images.githubusercontent.com/59536731/80472059-3027fb80-897f-11ea-8a1c-772f8738eb7b.png">
↓↓↓
<img width="555" alt="Screen Shot 0002-04-28 at 18 35 37" src="https://user-images.githubusercontent.com/59536731/80472055-2ef6ce80-897f-11ea-9802-a16735dc06c7.png">

- test3
<img width="780" alt="Screen Shot 0002-04-28 at 18 57 41" src="https://user-images.githubusercontent.com/59536731/80474280-3ec3e200-8982-11ea-9197-49ab509645fe.png">
↓↓↓
<img width="489" alt="Screen Shot 0002-04-28 at 18 58 01" src="https://user-images.githubusercontent.com/59536731/80474297-41bed280-8982-11ea-9887-0f89264a42dc.png">

What is the expected result? (期待される動作)
-------------------------------------------

- I hope markdown would be applied.

**Comment by yuki-takei** [comment]
@kaoritokashiki This is not a bug.

Page path that user creates is used as URL, so special characters will be sanitized for preventing XSS and it's correct behavior of GROWI.
