### ISSUE TITLE
Bug: Unable to rename "Anyone with the link" page in the case with the recursive option 

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2079]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |3.7.4|
|node.js   |12.16.2|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.208|
|browser   |Google Chrome 81.0.4044.129|

How to reproduce? (再現手順)
---------------------------

1. Create an "Anyone with the link" page, `/PageA`.
1. Rename that page to `/PageB`.

What happens? (症状)
---------------------

- `/PageB` does not exist.
- `/PageA` still exists.

What is the expected result? (期待される動作)
-------------------------------------------

- `/PageB` exists.
- `/PageA` does not exist.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report.

## How to reproduce STRICTLY?

1. Create an "Anyone with the link" page, /PageA.
1. Rename that page to /PageB **with the recursive option**.


## Summary

- When the recursive option is true, the system exclude the pages that are set to "Anyone with the link"
- In this case, it is is undesirable that allowing the user to select the recursive option

**Comment by yuki-takei** [comment]
Fixed. Please wait v3.7.5 release.
