### ISSUE TITLE
Bug: データインポートで構築したサイトの「自分のみ」のページにアクセスできなくなる

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#2080]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.7.1908|
|GROWI     |3.7.4|
|node.js   |12.16.2|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 81.0.4044.129|

How to reproduce? (再現手順)
---------------------------
サーバー刷新により移行の必要性があり、新旧同VerのGrowiサイトを立ち上げ、下記手順を実施しました。

1. 旧サイトのデータをエクスポートする。
1. 新サイトにてインポートする。
1. ログインし、「自分のみ」に権限設定していたページにアクセスする

What happens? (症状)
---------------------

- Forbidden "Browsing of this page is restricted" と表示され、記事内容が表示されない。

What is the expected result? (期待される動作)
-------------------------------------------

- "Just me (Browsing of this page is restricted)" と表示され、記事内容が表示される。

Note
----
- インポート時は全項目にチェックを入れ実施しました。
- 新サイトにて「自分のみ」に設定した場合は正しい挙動になります。旧サイトからの移行ページのみに発生しています。

インポート時の設定や内部情報データの修正で対処できるのであれば、ご教示いただけると助かります。

**Comment by yuki-takei** [comment]
@hide-o-mvd 
実際のデータを見てみないとなんとも言えませんが、新GROWIでのインポート時にエラーが出ているコレクションがないかどうかをチェックしてみてください。

## 起こり得るシチュエーション
ここからは予測になりますが、旧GROWIと同じ username のユーザーがデータインポート前の新GROWIに存在している、ということはないでしょうか？

Users あたりでエラーが出ていて、ログが
```
{"index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: growi.users index: username_1 dup key: { : \"dummyuser\" }" ...
```
のようになっていた場合は、旧GROWIの `dummyuser` ユーザーのインポートはスキップされています。その結果、新GROWIの `dummyuser` と旧GROWI の `dummyuser` のユーザーIDが異なる状態になってしまい、「自分のみ」設定のページは誰からも閲覧できない状態になってしまいます。

## 対策1
新GROWIの最初に作るユーザーを、旧GROWIには存在しない username で作成してください。

## 対策2
MongoDB の users collection 内のデータを編集し、新GROWIの対象ユーザーの `_id` を、旧GROWIと同じ値に変更してください。

## 備考

ページデータ取得時のソースは以下

https://github.com/weseek/growi/blob/d9ec99499fe50c43271f3576eb8e4d1ba89bed07/src/server/models/page.js#L236

**Comment by yuki-takei** [comment]
対策1を施して再現実験してみたのですが、再現してしまいました。バグだと思われます。
修正次第新バージョンをリリースしますのでしばしお待ちください。

**Comment by yuki-takei** [comment]
@hide-o-mvd 修正完了しました。v3.7.5 リリースをお待ちください。

**Comment by hide-o-mvd** [comment]
ご対応ありがとうございます。
追加の質問となり恐縮ですが、Growi 3.7.4でインポートしたサイトのDBは新規に作り直す必要がありますか？
新旧双方を3.7.5に更新し、データを旧サイトからエクスポート、新サイトで再インポートしようとするとRevisionデータが含まれるとアップロードが完了しません。
※新サイトには記事更新が入ってしまっているため、できることなら再構築は避けたいなと・・・

**Comment by hide-o-mvd** [comment]
もう1つ新規サイトを立ち上げて再構築し、差分をupsertすることで対応できました。
もし何かご検討いただいていたら申し訳ありません。
ご対応ありがとうございました。
