### ISSUE TITLE
Bug: Unintended values ​​come in due to automatic input by google chrome

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#2152]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.4|
|GROWI     |3.8.1-RC|
|node.js   |12.14.0|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.4|
|browser   |chrome 80.0.3987.163 |

How to reproduce? (再現手順)
---------------------------

1. Make google remember password at login.
1. Access to user settings page

What happens? (症状)
---------------------

- There is a name in the field to enter the email address

![スクリーンショット 2020-05-12 9 18 55](https://user-images.githubusercontent.com/48426654/81624888-54c9ac00-9432-11ea-9010-a6cd813e74dd.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Email address comes in automatically

**Comment by Yohei-Shiina** [comment]
Attempted to fix this issue here(https://github.com/weseek/growi/releases) but it's still happening in dev/4.5.x.
Currently looking for an implementer

**Comment by Shunm634-source** [comment]
Fixed the issue in all the versions
