### ISSUE TITLE
Feature: Configure max-lines of "List"

### ISSUE THREAD

**Issue by knaou** [weseek/growi#2191]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 10 buster|
|GROWI     |3.7.3|
|node.js   |12.16.2|
|npm       |6.14.4 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 1909|
|browser   |Chrome 81.0.4044.138（Official Build）|

What is the expected result? (期待される動作)
-------------------------------------------

Each page has "List" view at the bottom.
I feel that this list contains too many lines in each page.
Sometimes, pages with trivial contents are occupied by this large list...

![image](https://user-images.githubusercontent.com/14961871/82055640-c5571e00-96fb-11ea-80e8-23434edb5ef2.png)
Captured by https://demo.growi.org/

I suggest to Implement system property for changing max-lines of list.

Note
----

- 
-

**Comment by itizawa** [comment]
@knaou 
Thank you for your request.

This is a good idea. 
Many sites allow you to choose how many to display.


I want to be able to set.
However, I think it will be a while before we start to development. Please wait a moment. Thanks.

**Comment by hakumizuki** [comment]
This user interface has been deprecated since version 4.2.x.
