### ISSUE TITLE
Bug: Duplicate page source is overwrited

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#2215]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.8.0|

How to reproduce? (再現手順)
---------------------------

1. create `/parent/child` path page
1. create `/parent` path page
1. duplicate `/parent` into `/parent2`

What happens? (症状)
---------------------

- `/parent2` duplicates the contents of `/parent/child`
- delete `/parent` but `/parent/child` is delered

What is the expected result? (期待される動作)
-------------------------------------------

- Parent page is duplicated
- Parent page is deleted

**Comment by yuki-takei** [comment]
It was fixed and v3.7.7 and v3.8.1 is now released.
