### ISSUE TITLE
Question: growi-docker-composeでv4.0.0にアップグレードできない

### ISSUE THREAD

**Issue by tsumtsumyuma** [weseek/growi#2291]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu 18.04.4 LTS|
|GROWI     |3.8.1|
|node.js   |12.16.3|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome|

How to reproduce? (再現手順)
---------------------------
v3.8.1からv4.0.0にアップグレードするため，下記のUpgradeの手順に従い作業を行いましたがv4.0.0にアップグレードできないようです．

https://github.com/weseek/growi-docker-compose#upgrade

Upgradeのコマンド実行時には特にエラー等は表示されませんでしたが作業後docker-compose upを実行するとv3.8.1のまま起動してしまいます．

growi-docker-composeではまだv4.0.0へのアップグレードがサポートされていない等ございますでしょうか．

What happens? (症状)
---------------------
v3.8.1からv4.0.0にアップグレードするため，Upgradeの手順に従い作業を行いましたがv4.0.0にアップグレードできないようです．

What is the expected result? (期待される動作)
-------------------------------------------
v4.0.0にアップグレードできるようにする．

**Comment by m1na1p** [comment]
私も同じ問題になりましたが、Dockerfileの```FROM weseek/growi:3```を```FROM weseek/growi:4```に書き換えるとできました
以降はアップグレードの際の```docker rmi weseek/growi:3```は```docker rmi weseek/growi:4```に置き換える必要があります。

**Comment by yuki-takei** [comment]
昨日リリースされた v4.0.0 ですが、レイアウト崩れを中心としたバグがあるため、現在その修正版となる v4.0.1 のリリースを準備しています。growi-docker-compose での 4 系の利用は tminai さんが書いてくださった方法で可能ではあるのですが、ファイルとアップグレードガイドの修正は v4.0.1 のリリース後に行う予定です。

**Comment by tsumtsumyuma** [comment]
@tminai さん
v4.0.0へのアップグレード手順をご教示いただきありがとうございます．
上記手順にてv4.0.0へのアップグレードすることができました．

@yuki-takei さん
ご対応いただきありがとうございます．
v4.0.0にてレイアウト崩れを中心としたバグがあるとのこと，またgrowi-docker-compose でのファイルとアップグレードガイドの修正は v4.0.1 のリリース後とのこと承知いたしました．

本件，ファイルとアップグレードガイドの修正がされ次第，クローズとさせていただきます．

どうぞよろしくお願いいたします．

**Comment by yuki-takei** [comment]
@tsumtsumyuma 本体リリースと growi-docker-compose のアップデートを完了しました。ご確認ください。

**Comment by tsumtsumyuma** [comment]
@yuki-takei さん
上記確認し，v4.0.1にアップグレードできることを確認いたしました．
ご対応いただきありがとうございました．

本件クローズとさせていただきます．
