### ISSUE TITLE
Bug: PlantUML図でリンクが作れない

### ISSUE THREAD

**Issue by Ichinose5** [weseek/growi#2309]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |3.8.0|
|node.js   |12.16.3|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows10 |
|browser   |firefox 76.0.1|

How to reproduce? (再現手順)

下記のようにPlantUMLでリンク付きの図を作成する。

@startuml
class Car {
  - Some field [[[http://plantuml.com]]]
  Some method() [[[http://plantuml.com/link]]]
}
@enduml

What happens? (症状)
---------------------
図でリンクが作られない。

What is the expected result? (期待される動作)
-------------------------------------------
リンク付きの図が作られ、クリックでページが遷移する。

**Comment by yuki-takei** [comment]
@Ichinose5 ご報告ありがとうございます。

レンダリングエンジンの抜本対策を行わない限り修正できない問題となります。
#2557 の修正をお待ちいただければと思います。

**Comment by yuki-takei** [comment]
アップデート : https://github.com/weseek/growi/pull/6604

2022年冬リリース予定の GROWI v6 をお待ちください

**Comment by yuki-takei** [comment]
This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).

**Comment by yuki-takei** [comment]
@Ichinose5 This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。

**Comment by iosory7** [comment]
Growi v6を使わせていただいております。リンクを張ると、青字に下線が引かれるものの、リンク先には飛べないのですが(クリッカブルでない)、これは仕様でしょうか？
