### ISSUE TITLE
Error when pressing edit tab on mobile

### ISSUE THREAD

**Issue by ryohek** [weseek/growi#2311]
Environment
------------

### Client

| item     | version |
| ---      | --- |
|OS        |iOS 12.4.1|
|browser   |Safari|

How to reproduce? (再現手順)
---------------------------

1. login growi.
1. Access to some page.
1. Click Edit tab.

What happens? (症状)
---------------------

- An error message is displayed and the editing function cannot be used.
![IMG_6494](https://user-images.githubusercontent.com/27404438/83400252-7a4c4300-a43d-11ea-9a92-a1f3695918c0.PNG)

What is the expected result? (期待される動作)
-------------------------------------------

- Editing function can be used

**Comment by yuki-takei** [comment]
Fixed.
Please wait next release v4.0.3.
