### ISSUE TITLE
draw.ioを含むページのプレビューが表示されない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#2314]
Environment
------------
### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.4 LTS|
|GROWI     |4.0.2|
|node.js   | 10.20.1|
|npm       |6.14.4|
|yarn       | 1.22.4 |
|Using Docker|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |Safari 13.1.1|

How to reproduce? (再現手順)
---------------------------

1. draw.ioを使ったページを作成する
　draw.ioの部分より前に2~3ページ分の行数を入れておくとより良い。
2. draw.ioを使ったページを編集し、スクロールする。
　2.1. draw.ioの部分の消してスクロールする
　2.2 draw.ioの部分を戻してスクロールする

What happens? (症状)
---------------------

1. draw.ioが編集画面およびプレビューに無いときは正しくプレビューが表示される。
2. 編集部分もしくはプレビューにdraw.ioの部分に差し掛かるとプレビューのペインが表示されなくなる。
　2.1 draw.ioの部分を削除してスクロールするとプレビューのペインが正しく表示される。
　2.2 draw.ioの部分を戻してスクロールすると再びプレビューのペインが表示されなくなる。

What is the expected result? (期待される動作)
-------------------------------------------

- draw.ioの有無にかかわらずプレビューが常に表示されてほしい。

Note
----

- なし

**Comment by yuki-takei** [comment]
@hanapage ご報告ありがとうございます。
症状についてですが、「プレビューペインが消失する」わけではなく、#2322 と同様、エディターペインがとプレビューペインが共に横に長くなってしまい、ページ右方にスクロールしないと見えない、という症状かと推察いたしますが、いかがでしょうか？

同じでない場合、もう少し詳しい情報をいただければと思います。よろしくお願いいたします。

**Comment by hanapage** [comment]
問題再確認しました。

最初は気づきませんでしたが、ご指摘の通り右側にスクロールするとプレビューペインがありました。
当該のIssueと同じ問題・症状であると思います。

**Comment by yuki-takei** [comment]
こちら #2325 で修正したのでクローズします。
v4.0.3 リリースをお待ちください。
