### ISSUE TITLE
Styling issue in access counter

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2320]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.2|
|node.js   |12.17.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.264|
|browser   |Google Chrome 83.0.4103.61|

How to reproduce? (再現手順)
---------------------------

1. Create tens or hundreds of users.
2. Access `/` from all users.

What happens? (症状)
---------------------

- Styling issue in access counter
![user-activities](https://user-images.githubusercontent.com/3660715/83516190-99b4a000-a511-11ea-8dfe-11f38a2c6f8d.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Properly styled.

**Comment by yuki-takei** [comment]
@shield-9 Fixed.
Please wait next v4.0.3 release.
