### ISSUE TITLE
Styling issue in Customize page (admin panel)

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2321]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.2|
|node.js   |12.17.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.264|
|browser   |Google Chrome 83.0.4103.61|

How to reproduce? (再現手順)
---------------------------

1. Access `/admin/customize`

What happens? (症状)
---------------------

- extremely wide.
![customize](https://user-images.githubusercontent.com/3660715/83516450-0b8ce980-a512-11ea-9a38-ca89c73786bb.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Properly styled.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report, but I couldn't reproduce.

| item | version|
|:--:|:--:|
|OS|Windows 10 Home 2004 19041.264|
|browser|Google Chrome 83.0.4103.61|

![image](https://user-images.githubusercontent.com/1638767/83529689-a4793000-a525-11ea-91c8-697be50783ef.png)

In my environment, `col-lg-3` looks to affect correctly.

**Comment by shield-9** [comment]
oops, I found additional condition to reproduce this issue:
* Paste very long snippet to Custom Script
   * e.g. `window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(e){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var e=this.createElement("script");n&&(this.domain=n),e.id="js-iframe-async",e.src="https://assets.zendesk.com/embeddable_framework/main.js",this.t=+new Date,this.zendeskHost="hogehoge.zendesk.com",this.zEQueue=a,this.body.appendChild(e)},o.write('<body onload="document._l();">'),o.close()}();`

**Comment by yuki-takei** [comment]
@shield-9 #2325 has also fixed this.
Please wait next v4.0.3 release. Thanks.
