### ISSUE TITLE
Styling issue in editor

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2322]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.2|
|node.js   |12.17.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.264|
|browser   |Google Chrome 83.0.4103.61|

How to reproduce? (再現手順)
---------------------------

1. Open editor
2. Insert figures with Draw.io integration.

What happens? (症状)
---------------------

- extremely wide.
https://photos.app.goo.gl/N8ftAvFSewFWPpzM9

What is the expected result? (期待される動作)
-------------------------------------------

- Properly styled.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report.
Please wait next v4.0.3 release.
