### ISSUE TITLE
Styling issue in login page w/ dark mode

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2336]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.2|
|node.js   |12.17.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.264|
|browser   |Google Chrome 83.0.4103.61|

How to reproduce? (再現手順)
---------------------------

1. Login to GROWI.
2. Set GROWI to dark mode.
3. Logout from GROWI.
4. Access login page.

What happens? (症状)
---------------------

- It's hard to read some texts for poor contrast.
![ログイン_GROWI_Demo](https://user-images.githubusercontent.com/3660715/83622098-831e4f80-a5ca-11ea-97d2-33d799c91d30.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Easier to read these texts.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report.
This issue has fixed. Please wait next v4.0.3 release.
