### ISSUE TITLE
国际化支持 example chinese

### ISSUE THREAD

**Issue by rs-frank** [weseek/growi#2344]
国际化增加方便支持中文的方式。目前的 项目结构中 需要调整的地方 可能会比较多。
是否可以增加调整策略比如直接遍历 国际化语言增加 对于多语言的支持。

**Comment by yuki-takei** [comment]
@rs-frank Thank you for your comment.
I think GROWI should support other languages like chinese, french and etc..
However there is no member who speak chinese among us currently.

If you or other person send us some PR, we will apply it.

**Comment by rs-frank** [comment]
目前我本地在修改 中文的支持，不过遇到问题可能会造成冲突。有几个方面  可能 需要修改
1、InstallerForm.jsx
![image](https://user-images.githubusercontent.com/27323629/84557703-e42eeb80-ad5f-11ea-9805-526e22818fff.png)
2、AppSetting.jsx
![image](https://user-images.githubusercontent.com/27323629/84557721-fdd03300-ad5f-11ea-9983-481f27a53952.png)
3、PersonalSettings.jsx
![image](https://user-images.githubusercontent.com/27323629/84557750-28ba8700-ad60-11ea-9ede-af01eff68137.png)
会有语言的枚举列表。是否可以吧默认语言放置到 config中 这样可能会方便点。

pr提交的话 提交到哪个分支？

**Comment by yuki-takei** [comment]
#2412 has merged.
