### ISSUE TITLE
Bug: cannot create a new page by the shortcut key

### ISSUE THREAD

**Issue by hkato312** [weseek/growi#2381]
![Clipboard01](https://user-images.githubusercontent.com/2064197/84277209-285a9a00-ab6e-11ea-9b31-95d1fcb1f94b.jpg)

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.0.4|
|node.js   |12.18.0|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | windows 10 |
|browser   |chrome 83|

How to reproduce? (再現手順)
---------------------------

1. press `c`
1. click `create`

What happens? (症状)
---------------------

- nothing

What is the expected result? (期待される動作)
-------------------------------------------

- create a new page

**Comment by yuki-takei** [comment]
@hkato312 Thank you for your report.
This problem has fixed. Please wait the next release v4.0.5.
