### ISSUE TITLE
Feature: Slack unfurling

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2395]
With Slack unfurling support, Slack users could preview contents without clicking the link and could continue conversations.
https://api.slack.com/reference/messaging/link-unfurling

And support for authenticated unfurling would be great for private GROWI deployments.
https://api.slack.com/reference/messaging/link-unfurling#authenticated_unfurls

**Comment by shield-9** [comment]
FYI: This feature is available with crowi.
https://github.com/crowi/crowi/pull/204

**Comment by ozasuke** [comment]
+1
