### ISSUE TITLE
Bug: some profile images are not rendered in list view

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2404]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.6|
|node.js   |12.18.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.329|
|browser   |Google Chrome 83.0.4103.97|

How to reproduce? (再現手順)
---------------------------

1. Create some users and create pages using these users.
1. Access `/`.

What happens? (症状)
---------------------

- Some profile images are not rendered in list view.
  ![_GROWI_Demo](https://user-images.githubusercontent.com/3660715/84722457-3ec58300-afbe-11ea-8ba4-b942500bf35d.png)

What is the expected result? (期待される動作)
-------------------------------------------

- all profile images are rendered in list view.

**Comment by yusuketk** [comment]
起票ありがとうございます。
[PR-2375](https://github.com/weseek/growi/pull/2375) のマージによるものだと思われるので調査、修正します。

**Comment by yuki-takei** [comment]
Fixed.
Please wait the next release v4.1.0
