### ISSUE TITLE
Bug : Fail to rebuild index for GROWI.cloud

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#2407]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.0.4|

How to reproduce? (再現手順)
---------------------------

1. push rebuild 

What happens? (症状)
---------------------

- fail to rebuild index

<img width="1012" alt="スクリーンショット 2020-06-16 16 38 24" src="https://user-images.githubusercontent.com/48426654/84745868-279f8900-aff0-11ea-8aa5-4dbe4e89cda9.png">

What is the expected result? (期待される動作)
-------------------------------------------

- succeed to rebuild index

Note
----

- Local, succeed to rebuild index

**Comment by yuki-takei** [comment]
`ELASTICSEARCH_REQUEST_TIMEOUT` was added.
