### ISSUE TITLE
サイドバーのドラフトのアイコンが表示されてない

### ISSUE THREAD

**Issue by shukmos** [weseek/growi#2409]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.0.6|
|node.js   |v10.20.1|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Catalina 10.15.5|
|browser   |Chrome 83.0.4103.97 |

How to reproduce? (再現手順)
---------------------------

1. GROWIを開く

What happens? (症状)
---------------------

- サイドバーのドラフトのアイコンが表示されてない
- ![image](https://user-images.githubusercontent.com/20252919/84769317-98569d80-b010-11ea-992e-0e86f95b0967.png)

What is the expected result? (期待される動作)
-------------------------------------------

- アイコンが表示されている

Note
----

- GROWIのバージョン4.0.5でも確認

**Comment by yuki-takei** [comment]
@shukmos こちらではちょっと再現しないのですが、ブラウザキャッシュを消してリロードしてみてもらえますか？

**Comment by shukmos** [comment]
material icon のフォントがClient側のPCにインストールされている場合に再現します。
CDNで引っ張ってくるものよりも、PCにインストールされているフォントのほうが優先される為だと思われます
