### ISSUE TITLE
Wikiに長いテキストを入れると、右側の目次に文字がかぶる。

### ISSUE THREAD

**Issue by kaoritokashiki** [weseek/growi#2413]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |mac|
|GROWI     |4.0.6|
|node.js   |v12.14.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Mojave 10.14.6|
|browser   |Chrome  83.0.4103.97|

How to reproduce? (再現手順)
---------------------------

1. process 1
Wikiに長いテキストをかく

What happens? (症状)
---------------------
長いテキストを入れると、右側の目次に文字がかぶる。
<img width="1363" alt="スクリーンショット 0002-06-17 21 08 32" src="https://user-images.githubusercontent.com/59536731/84896665-4df02200-b0df-11ea-95bf-ab848e2385dc.png">

What is the expected result? (期待される動作)
-------------------------------------------
Wikiコンテンツの幅を指定して、テキストを折り返すようにする

**Comment by yuki-takei** [comment]
修正完了しました。v4.0.7 リリースをお待ちください。
