### ISSUE TITLE
request: ページの複製を改装

### ISSUE THREAD

**Issue by safari029** [weseek/growi#2440]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.0.4|

How to reproduce? (再現手順)
---------------------------

What happens? (症状)
---------------------

What is the expected result? (期待される動作)
-------------------------------------------

- 移動は階層全て可能なのに、複製は単一のページしか行えない。
- 階層構造の内容含めてテンプレート（ポストモーテム、設計図、議事メモ）として用意しているのだが、親ページとその配下のテンプレートは別々にコピーするのが手間になるので、そういった利用が可能になるように階層構造含めた複製ができる

Note
----

**Comment by yuki-takei** [comment]
お待たせしました。v4.2.3 で実装されました。
リリースをお待ちください。
