### ISSUE TITLE
request: リバースプロキシにファイル配信を任せたい

### ISSUE THREAD

**Issue by Daiki51** [weseek/growi#2470]
## 環境
Growiをnginxのリバースプロキシを通して運用しています．添付ファイルのアップロード先を「ローカルファイルシステム」に設定している場合に限られた話になるかもしれません．

## 要望

大きな添付ファイルをダウンロードしようとすると非常に時間がかかってしまうため，ファイルの配信をnginxなどのリバースプロキシに任せるオプションを追加できませんでしょうか．

技術的には，ファイルのデータ自体ではなく，X-SendFileやX-Accel-Redirectヘッダを返却することで，リバースプロキシにファイルの配信を任せることが可能ではないかと思います．

publicフォルダ自体をnginxのルートディレクトリに設定する方法もありますが，ユーザー問わず誰でもアクセスできるようになってしまうので，できるだけ避けたいです...

ぜひご検討よろしくお願いいたします．

**Comment by yuki-takei** [comment]
@Daiki51 ご要望ありがとうございます。
attachment 周りの改善はそこまで手が回っていないのが実情です。

## 開発優先度
昨年 [AWS S3, GCP GCS 向けの presigned url 対応を検討](https://dev.growi.org/5db1295cc41146005085b043)し、一時優先度高めに設定されたのですが、そちらは後回しになりました。attachment 周りに手を入れる稼動が取れるようになったらこちらを優先すると思います。

## ご提案の手法について
現在はサーバーのローカルFSアップロードモードでは既にファイルが存在するので、仰る通り nginx に任せる方が賢いです。ただ全ての file upload モジュール file stream 処理を行う形に統一してしまっているので、ローカルFSだけ別挙動にするという改修は腰が重いですね…実装者募集中です。

**Comment by Daiki51** [comment]
なるほど...そういった経緯があったんですね
丁寧な回答ありがとうございます

不慣れですが，自分でコードを編集して試してみたいと思います．
形になるものができたらこちらにプルリクエストを送らせてもらってもよろしいでしょうか？

**Comment by yuki-takei** [comment]
はい、PR大歓迎です！

**Comment by yuki-takei** [comment]
@Daiki51 
素晴らしい PR をありがとうございました。

v4.0.9 リリースまでしばらくお待ちください。

**Comment by Daiki51** [comment]
マージして下さりありがとうございました。
