### ISSUE TITLE
Improvement: Make emoji work well even when NO_CDN=true

### ISSUE THREAD

**Issue by TaroTanaka2020** [weseek/growi#2472]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI     |3.8.0-nocdn, 4.0.7-nocdn|
|node.js   |12.18.1|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Catalina 10.15.5|
|browser   |Google Chrome 83.0.4103.116 64bit|

How to reproduce? (再現手順)
---------------------------

1. インターネットに繋がらない環境にて、NO_CDN=trueの状態でgrowiを起動する
1. Wikiページ編集画面にて、`:sushi:`のようにコロンで挟む記法で絵文字を入力する

What happens? (症状)
---------------------

- 絵文字1つ1つの前に画像の読み込みエラーのマークが表示される
    - 編集中、編集後のページ、およびコロン入力中の絵文字サジェストの部分にてこの症状が出る
- 下の画像は上側のブラウザがGoogle Chrome、下側がFirefoxであり、Firefoxではこの症状が発生していない
- 読み込めていない画像は`cdn.jsdelivr.net`からデータを取得しようとしている

<img width="1164" alt="画像読み込みエラー" src="https://user-images.githubusercontent.com/64360353/85920158-53522700-b8ac-11ea-9487-762d42dccc20.png">

What is the expected result? (期待される動作)
-------------------------------------------

- 画像の読み込みエラーのマークが表示されない
- NO_CDN設定がtrueの場合、絵文字データもCDNから取得しない

Note
----

- Windows環境でも試しましたが同じくGoogle chromeで症状あり、Firefoxでは症状なしでした

**Comment by yuki-takei** [comment]
@TaroTanaka2020 ご報告ありがとうございます。一旦こちらで再現を確認します。

**Comment by yuki-takei** [comment]
この問題放置してしまっていて申し訳ないです。再現を確認しました。

## 調査結果

GROWI は `:sushi:` という文字列を `emojione.shortnameToImage` で img タグに変換していますが、こちらは特に設定を変更しなければ jsdelivr の png を参照するようになるようです。NO_CDN 対応するにはイメージの参照先を GROWI Server に向けることになりますが、そのためには相当量の png をビルド時にダウンロードしておかなければならず、その zip アーカイブ等を手に入れる方法もなさそうです。

そのため、現時点では GROWI は NO_CDN での emoji 表示にはコードベースでは対応していません。
(意図してこの仕様になっているわけではなく、今回の調査でその認識となりました)

## 代替案

いずれも GROWI の改修が必要です。

1. emojione の svg フォントを読み込み、フォントとして表示する
    - svg フォントは GitHub リポジトリに入っている
    - png を利用する手法から変える必要がある
    - クライアント側コストとして、数MBのフォントファイル読み込みが必要になる
2. emojione 以外の選択肢を検討する(twemoji 等)

**Comment by yuki-takei** [comment]
@TaroTanaka2020 

症状についてですが、ブラウザで挙動が変わるというのはちょっと合点がいかないので、chrome, firefox それぞれで当該 img タグの src はどうなっているか教えていただけないでしょうか。おそらくブラウザキャッシュで一時的に見える状態になっているだけなんじゃないのかと推測しています。

**Comment by HeavyMoon** [comment]
どちらのブラウザで見ても以下の様なタグになっていますが，jsdelivr の応答待ち時の挙動がブラウザによって異なるかもしれません．Chromeではsrc，Firefoxではalt，の表示を優先しているように見えます．（Chromeではjsdelivrからの応答が得られず画像の読み込みエラーのマークとaltが表示されているが，Firefoxではaltのみ表示されている）

```
<img class="emojione" alt="😀" title=":smile:" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f603.png">
```

**Comment by yuki-takei** [comment]
@TaroTanaka2020 @HeavyMoon こちらでの報告が遅くなりましたが、[v5.0.6](https://github.com/weseek/growi/releases/tag/v5.0.6) から絵文字の表示にはデバイスフォントを利用するようになったため、この問題は解消されました。

## v6 について

最新版の v6 系では nocdn variant がなくなり、通常の公式イメージがこれまでの nocdn 相当の挙動となるよう整備されました(まだ完全ではありませんが)。詳しくは[v6.0.x へのアップグレードガイド](https://docs.growi.org/ja/admin-guide/upgrading/60x.html#%E7%AE%A1%E7%90%86%E8%80%85%E5%90%91%E3%81%91)をご覧ください。
