### ISSUE TITLE
表記した内容と違うblockdiag(seqdiag)図が表示される

### ISSUE THREAD

**Issue by tetsukazu** [weseek/growi#2478]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |???|
|GROWI     |4.0.7|
|node.js   |???
|npm       |???|
|Using Docker|???|
|Using [growi-docker-compose][growi-docker-compose]|???|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Mac|
|browser   |Google Chrome 83.0.4103.116|

How to reproduce? (再現手順)
---------------------------
1. 新規ページを作成
2. 以下をページに記載
```
<div style="max-width: 600px">
::: seqdiag
seqdiag {
  browser  -> webserver [label = "GET /index.html"];
  browser <-- webserver;
  browser  -> webserver [label = "POST /blog/comment"];
              webserver  -> database [label = "INSERT comment"];
              webserver <-- database;
  browser <-- webserver;
}
:::
</div>
```

What happens? (症状)
---------------------
生成された、blockdiag(seqdiag)図が想定したものと違う
https://demo.growi.org/user/guest1/%E3%83%A1%E3%83%A2/2020/06/29/DiagramTest

What is the expected result? (期待される動作)
-------------------------------------------
以下のような図が表示されて欲しい
![image](https://user-images.githubusercontent.com/2697802/86007933-15433780-ba53-11ea-94e0-592acae0ea7b.png)

Note
----
以下URLが欠損していると思われる
https://blockdiag-api.com/api/v1/seqdiag/inflate/K04tTMlMTFeo5lJQSCrKLy9OLVJQ0LVTKE9NAjLLgLzonMSk1BwFWwUld9cQBf3MvJTUCr2MktwcpVhrZE3YdAT4BwO1JOXkp-sn5-fmpuaVQDQhA4Q-kL0piSWJSYnFqUiGePoFuwaFKBBhgI2uLtwAZLeBxOGqrLlqAQ==

**Comment by yuki-takei** [comment]
@tetsukazu ご報告ありがとうございます。
以下 issue と同じ症状でしょうか。

https://github.com/weseek/growi/issues/709

クローズド Wiki であれば暫定的な対策として XSS 対策オプションを無効化する選択肢を検討してください。
オープン Wiki の場合は申し訳ないのですが抜本対応はまだ先になります。

**Comment by tetsukazu** [comment]
すみません、<>の部分がおかしくなっていたので同じ問題でした。
