### ISSUE TITLE
Bug: $lsx(num=1) may not work properly in some cases

### ISSUE THREAD

**Issue by hkato312** [weseek/growi#2483]
![growi_lsx](https://user-images.githubusercontent.com/2064197/86209315-4d5e8d80-bbad-11ea-86b7-3c4c588d18da.jpg)

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.0.7|
|node.js   |12.18.1|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|
|growi-plugin-lsx| 4.0.0|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | windows 10 |
|browser   |chrome 83|

How to reproduce? (再現手順)
---------------------------

1. $lsx(/user, num=1) 

What happens? (症状)
---------------------

- Two items are displayed when the parent folder is empty.

What is the expected result? (期待される動作)
-------------------------------------------

- It shows one of them.

**Comment by yuki-takei** [comment]
@hkato312 Thank you for your report. I'll fix it, but it will be late for priority.

**Comment by yuki-takei** [comment]
This issue has fixed.
Wait a moment until GROWI v4.1.0 (with growi-plugin-lsx@v4.0.1) is released.
