### ISSUE TITLE
MathJaxが機能していない

### ISSUE THREAD

**Issue by KTaskn** [weseek/growi#2494]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows10 Pro|
|GROWI     |4.0.7|
|node.js   |12.18.1|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

プロジェクトのデモサイトでも発生します
https://demo.growi.org/Sandbox/Math

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro|
|browser   |Microsoft Edge バージョン 83.0.478.58 (公式ビルド) (64 ビット)|

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro|
|browser   |Google Chrome バージョン: 83.0.4103.116（Official Build） （64 ビット）|

| item     | version |
| ---      | --- |
|OS        |iOS13.3.1|
|browser   |Safari 13.0.5|

How to reproduce? (再現手順)
---------------------------

docker-compose.yml
MATHJAX = 1
は設定済み

What happens? (症状)
---------------------

数式が表示されない

Microsoft Edge(chromium)
![image](https://user-images.githubusercontent.com/8474919/86672491-ab69f580-c031-11ea-9311-564a180cbb5c.png)

Google Chrome
![image](https://user-images.githubusercontent.com/8474919/86672616-cb99b480-c031-11ea-97e7-425085189f2c.png)

What is the expected result? (期待される動作)
-------------------------------------------

数式が表示される

**Comment by yuki-takei** [comment]
@KTaskn 7/10 現在、https://demo.growi.org/Sandbox/Math で v4.0.7 で正常に表示できているようです。

Demo にディプロイされている版は no-cdn 版ではないので、https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js を参照しに行きます。当該ファイルがたまたまその時間帯にアクセスできなかったか、もしくはそちらのクライアント環境が当該CDNへのアクセスを許可していないような環境である場合は、ご報告いただいている事象が発生すると思います。

**Comment by KTaskn** [comment]
@yuki-takei 

ご回答ありがとうございます。
再度デモ版をみましたところ、
* MathJaxが動く場合/動かない場合があるようです

下記が動かない場合のログです

```  javascript
Math:687 k.fn.init [prevObject: k.fn.init(1)]

config.js?V=2.7.2:19 Uncaught TypeError: Cannot read property 'directory' of undefined
    at config.js?V=2.7.2:19
(anonymous) @ config.js?V=2.7.2:19

Math:690 config:  {crowi: {…}, upload: {…}, registrationWhiteList: Array(0), layoutType: "growi", themeType: "mono-blue", …}

```

動作しない場合もMathJax.jsに対するGETリクエストは200を返しているようです。

**Comment by KTaskn** [comment]
@yuki-takei

>クライアント環境が当該CDNへのアクセスを許可していないような環境

ご回答いただきましたとおり、アクセスの問題だったようです。
クライアントが認証プロキシを介して接続する環境で利用しております。

nocdn版を使った場合でも、下記の要素が外部接続が必要なため、レンダリングはできないようです。

``` javascript
<script type="text/javascript" src="https://app.diagrams.net/math/MathJax.js"></script>
```

認証プロキシのない環境 + nocdn版で、上記URLのアクセスを止めたところ、
認証プロキシと同じ状況が再現できました。
