### ISSUE TITLE
<>のエスケープ方法について

### ISSUE THREAD

**Issue by teraphon** [weseek/growi#2508]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.8.2003|
|GROWI     |4.0.7|
|node.js   |10.21.0|
|npm       |6.14.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10|
|browser   |GoogleChrome|

How to reproduce? (再現手順)
---------------------------

1. ページの編集
2. \<何かしらの文字(列)>を入力  

What happens? (症状)
---------------------
 \を記載してもエスケープされなく、<何かしらの文字(列)>の部分がコメントアウトしてしまう。

What is the expected result? (期待される動作)
-------------------------------------------

<何かしらの文字列>⇒コメントアウト
\<何かしらの文字列>⇒<何かしらの文字列>

Note
----
設定や記法が間違っているのでしょうか。

**Comment by yuki-takei** [comment]
@teraphon セキュリティ対策の仕様となります。
`<>` を許すと様々な HTML タグを埋め込めることになるので、デフォルトではカットされる設定になっています。

管理画面の Markdown Settings から Prevent XSS(cross site scripting) setting の設定を参照してください。カスタムホワイトリストに追加するか、もしくは Prevent XSS 自体を無効化することで任意のタグを記述可能です。

**Comment by yuki-takei** [comment]
#2557 での抜本対策をお待ちください。

**Comment by jujuohoh** [comment]
コードの外では `&lt; 何かしらの文字列 &gt;` でエスケープできますが、コードの中では `while (i < n && j > m)` をエスケープすることができず、 `while (i &lt; n && j &gt; m)` と書いても、&amp;lt; と &amp;gt; は変換されずにそのまま表示されます。 また、< と > が何行離れていてもその間の中身が消えます。

そのため、少し長めのプログラムのコードを書く場合は、現状、マークダウン設定で「 XSSを抑制する」 を無効化するしかないですね。

**Comment by yuki-takei** [comment]
This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).

**Comment by yuki-takei** [comment]
@teraphon @jujuohoh This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
