### ISSUE TITLE
no-cdn+drawioコンテナにて、リッチなアイコンが表示できない

### ISSUE THREAD

**Issue by kytTJ** [weseek/growi#2509]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |RHEL7|
|GROWI     |4.0.7|
|node.js   |12.8.1|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Win10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. drawioのリッチのアイコンを表示
 例：AWS17のアイコン等

条件：no-cdn版かつ社内ネットワーク内のみ（外部接続不可）

What happens? (症状)
---------------------

- Growiでアイコンやテンプレートを使用し、保存した後にアイコンが綺麗に表示されない（ただの四角のアイコンになる）

What is the expected result? (期待される動作)
-------------------------------------------

- Growiでアイコンやテンプレートを使用し、保存した後にアイコンが綺麗に表示される

Note
----
こちらで確認した結果、https://www.draw.ioの「stencils/aws3.xml」などにアクセスを行おうとしているが、社内ネットワークのため、接続エラーが発生している。
/opt/growi/public/js/cdm/drawio-viewer.jsに定義されている。
drawioはコンテナは内部の情報から表示できているが、growi側は、表示する際に外部にアクセスを行おうとしている。

**Comment by yuki-takei** [comment]
@kytTJ draw.io で動的に追加するアイコン群は流石に no-cdn では利用不可能な気がします。(highlight.js のテーマ変更も同様の理由で利用できません)

@kaishuu0123 一応少し調べてみてもらえますか。

**Comment by kaishuu0123** [comment]
あくまでまだ予測ですが、 `window.DRAWIO_BASE_URL` を drawio-viewer.js の前に仕掛けられればできる、かもしれませんね。

https://github.com/jgraph/drawio/blob/f9f6c97197862380c1cc11d5f4303010adca5a82/src/main/webapp/js/diagramly/Init.js#L20

継続調査中です @yuki-takei @kytTJ

**Comment by kaishuu0123** [comment]
@kytTJ 
コードは修正されて Merge されたので次リリースからですが、注意点があります。
PR にも記載していますが、GROWI と draw.io の間に `Access-Control-Allow-Origin` ヘッダを付与してくれるリバースプロキシを設置する必要があります。

PR #2543 に記載した docker-compose.yml に記載している `kaishuu0123/cors-reverse-prooxy` を利用するか、もしくは Apache や Nginx container  などで draw.io からのレスポンスに `Access-Control-Allow-Origin` ヘッダを付与する設定を行なってください

**Comment by kaishuu0123** [comment]
https://github.com/weseek/growi/issues/2561#issuecomment-666334944
こういった情報もありますのでご参考までに。

**Comment by kytTJ** [comment]
ご対応ありがとうございます。
次リリースが出た際に、こちらでもアップデートをさせていただき、確認いたします。
