### ISSUE TITLE
Editing page does not reflect the current access restriction setting.

### ISSUE THREAD

**Issue by gucchy55** [weseek/growi#2516]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 16.04 |
|GROWI     |4.0.8|
|node.js   |12.18.2|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | macOC 10.15.5, Windows 10, ...|
|browser   |Google Chrome 83.0.4103.116|

How to reproduce? (再現手順)
---------------------------

1. Open for editing a page with access restriction other than "Public".
 
What happens? (症状)
---------------------

- The selection of access restriction is set as "Public" regardless of the current setting of the page.

What is the expected result? (期待される動作)
-------------------------------------------

- Should it be same as the current setting of the page?

**Comment by yuki-takei** [comment]
@gucchy55 Thank you for your report.
New version v4.0.9 fixed this issue. Please update.

Thanks.
