### ISSUE TITLE
Bug: pagination not displayed in bookmark list

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2524]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |cos-beta-81-12871-44-0|
|GROWI     |4.0.6|
|node.js   |12.18.0|
|npm       |6.14.4|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 2004 19041.329|
|browser   |Google Chrome 83.0.4103.97|

How to reproduce? (再現手順)
---------------------------

1. Bookmark 10+ pages
1. Open user home (e.g. https://demo.growi.org/user/admin1)

What happens? (症状)
---------------------

- Older bookmarks are not displayed.
![image](https://user-images.githubusercontent.com/3660715/87291661-9b26ae80-c53a-11ea-92e7-12ca33411b9b.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Older bookmarks are displayed with pagination.

Note
----

- Confirmed with 3.5.17, 4.0.6, 4.0.7

**Comment by yuki-takei** [comment]
Fixed in v4.2.x
