### ISSUE TITLE
Improvement: ページ内リンク遷移時にページタイトル表示分オフセットして欲しい

### ISSUE THREAD

**Issue by tminai** [weseek/growi#2526]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 8|
|GROWI     |4.0.9|
|node.js   |12.18.2|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 83.0.4103.116|

What is the expected result? (期待される動作)
-------------------------------------------

ページ内のリンク(例えば/ABC/DEF#GH)を表示したときに、  
ブラウザはそのセクションの位置にスクロールした状態でページを表示しています。  

しかし、ページが長い場合は画面上部にページタイトルが半透明で表示されているため、  
セクションの表示位置とページタイトルの表示位置が重なり見づらいです。

セクションのリンク(~~~#GH)に遷移したときページタイトルが上部に表示されていたときに
そのページタイトルの幅分下方向にオフセットして表示すると見やすくなると思います。

Note
----

※以下のような、状態のことです（Bootstrap4#Typographyへ遷移させた例）
![image](https://user-images.githubusercontent.com/56664277/87365674-ca2c3700-c5b1-11ea-8c55-87a8a7beba4a.png)

**Comment by yuki-takei** [comment]
@tminai ご報告ありがとうございます。ただいま修正中です。今しばらくお待ちください。

https://youtrack.weseek.co.jp/issue/GW-3096

**Comment by yuki-takei** [comment]
修正完了しました。v4.1.0 のリリースをお待ちください。
