### ISSUE TITLE
wiki文中の添付ファイル参照の横にも雲マーク（元のファイル名でのダウンロードリンク）を付けて欲しい

### ISSUE THREAD

**Issue by hisashiyashiro** [weseek/growi#2529]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8|
|GROWI     |4.0.10-RC|
|node.js   |10.21.0|
|npm       |6.14.5|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.13.6 |
|browser   | Chrome |

How to reproduce? (再現手順)
---------------------------
Wiki 文中に展開されるURLをクリックして添付ファイルをダウンロードする

What happens? (症状)
---------------------
ファイル名がオブジェクトID＋元の拡張子でダウンロードされる。

What is the expected result? (期待される動作)
-------------------------------------------
Wiki 文中でもアップロード時の元のファイル名でダウンロード出来る方法が用意されて欲しい。

Note
----
#618 #616 とほぼ同じ要望です。基本仕様として現状のダウンロードリンクを維持する方針であれば、すくなくともダウンロードしないと開けないようなファイル属性の場合、その横にフッター部分と同じ雲マークでのダウンロードリンクを自動で付加してくれる機能を要望します。

ユーザは自分がアップロードしたファイルをダウンロードするとき、ほとんどの場合wiki文中のリンクをクリックします。我々は研究会の内容を1枚のwikiページにまとめるとき、各自が作成した会議資料として、20〜30個のwordファイルやpptファイルをアップロードし、各発表の概要と併せてファイルへのリンクを文中に付けておいています。
「資料が欲しい場合はリンクは押さず、フッターまで探しに行ってダウンロードして下さい」と、今までも何度も新規初心者ユーザに説明してきました。あまりに皆が同じ動作を期待するので、これについて考慮して頂けるとありがたいと思っています。

**Comment by shield-9** [comment]
RFCを軽く読んだだけですが、`/attachment/*` のレスポンスに `content-disposition: inline; filename=aaa.png` とかをつけてあげれば、
* ブラウザで開ける種類の添付ファイルなら、ブラウザで開かせる
* ブラウザで開けない種類の添付ファイル or 明示的に保存を選択されたら、アップロード時の名前で保存させる
を両立させること自体はできそうですね。

**Comment by jam411** [comment]
@hisashiyashiro This issue was fixed by [v6.0.10](https://github.com/weseek/growi/releases/tag/v6.0.10).
この問題は [v6.0.10](https://github.com/weseek/growi/releases/tag/v6.0.10) で修正されました。
