### ISSUE TITLE
Is there a way to access portal pages after moving to Simplified Behavior. (Simplified Behaviorに変更した後ポータルページのコンテンツにアクセスする方法はありますか)

### ISSUE THREAD

**Issue by s2terminal** [weseek/growi#2530]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux|
|GROWI     |3.4.2|
|node.js   |10.15.2|
|npm       |6.4.1|
|Using Docker|yes|
|Using growi-docker-compose|no|

### Client

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8 gnome|
|browser   |Chrome 83.0|

How to reproduce? (再現手順)
---------------------------

1. Set `Crowi Classic Behavior` at `/admin/customize`
1. Create both `/hoge` page and `/hoge/` (portal) page.
1. Set `GROWI Simplified Behavior (Recommended)` at /admin/customize`

What happens? (症状)
---------------------

- Cannot access `/hoge/` (portal) page's contents.

What is the expected result? (期待される動作)
-------------------------------------------

- Can I access the content of the portal pages in some way?
- Or is there a way to restore the content of the portal page?

Note
----

I want to move to `GROWI Simplified Behavior`. However, we have been using `Crowi Classic Behavior` for a long time and there are pages that contain the necessary information for both `/hoge/` and `/hoge`

**Comment by yuki-takei** [comment]
> Can I access the content of the portal pages in some way?

Unfortunately, NO.
If you would like to salvage portal page contents, you have to store all of them somehow, and restore them manually.

**Comment by s2terminal** [comment]
Thanks. I'll build another Growi with the same data from the backup, and make it into Classic Behavior, to restore them manually.
