### ISSUE TITLE
Bug: MathJaxのマクロが動かない

### ISSUE THREAD

**Issue by s-ponta** [weseek/growi#2531]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |4.0.9|
|node.js   |12.18.2|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Window 10|
|browser   |Google Chrome 84.0.4147.89|

How to reproduce? (再現手順)
---------------------------

1. 管理画面の`カスタマイズ`->`カスタムスクリプト`に下記のスクリプトを加える。
    ```
    MathJax.Hub.Config({
      TeX: {
        equationNumbers: {
          autoNumber: "AMS"
        },
        Macros: {
          bra: ['\\left< #1 \\right|', 1],
          ket: ['\\left| #1 \\right>', 1],
          braket: ['\\left< #1 \\left| #2 \\right| #3 \\right>', 3],
          abs: ['\\lvert #1 \\rvert', 1]
        }
      }
    });
    ```
1. 適当な記事を作成し、数式中で`\bra{\psi}`等を使う。

What happens? (症状)
---------------------

- 以前は上記の設定でマクロが使えていた。
- [growi-docker-compose][growi-docker-compose]をもとにv4.0.9にアップデートをすると使えなくなった。(バージョンのログを取り損ねていて申し訳ないのですが、昨年12月頃にインストールした際は上記で出来ていました。)
- 現状赤字で`\bra`等と表示される。

```
Stack Trace
```

None

What is the expected result? (期待される動作)
-------------------------------------------

- マクロが正しくレンダリングされる

Note
----

None

**Comment by yuki-takei** [comment]
@s-ponta こちらの問題はカスタムスクリプト利用が条件というのもあり、大変申し訳ありませんが開発チームで対処する問題の対象外とさせていただきたいです。おそらくは `<` や `>` が入っていることにより、現行の XSS Filter でカットされてしまうのではないかと推測します。

また #2557 が現行 XSS Filter の仕様を抜本から変える施策になりますが、同時に KaTeX を利用することを検討するため、もしそちらに舵を切った場合は MathJax のマクロは利用できなくなります。ご了承をお願いいたします。

**Comment by s-ponta** [comment]
@yuki-takei ご確認ありがとうございます。このissueそのものは開発チームでの対応は対象外ということと、#2557 で他issue絡みで対応できるかもしれないとのこと、理解しました。
KaTeXのほうが動作がかなり軽いので、その点でもありがたい案だと思います。KaTeXの場合に動くマクロは実装されてから考えてみます。

ただXSS Filterとは原因が異なるのかもしれません。とりあえず現状試してみたことと、work aroundを残しておきます。

1. #2557 と関連issueを確認して、XSS抑制をoffにする
   - 変化なし
1. `<`, `>`を使わないように`\langle`, `\rangle`に差し替え
   - 変化なし (XSS抑制on/off両方)
1. 全体設定でなく各記事の先頭に下記のようにマクロ埋め込み(work around)
   ```
   $$
   \def\bra#1{\left \langle #1 \right|}
   \def\ket#1{\left| #1 \right \rangle}
   \def\braket#1#2#3{\left \langle #1 \left| #2 \right| #3 \right \rangle}
   $$
   ```
   - 正常にレンダリングされるが、ページ先頭から本文開始までにこの`def`パートの分だけ記事に空白ができる
   - 全ページの先頭に埋め込んで回らないといけない点で微妙(現状数ページだけなのであまり気になりませんが...)

とりあえず動くようには出来たので、XSSではないかもしれない点に関して、何か私の方で試せる事がなさそうでしたらcloseしようかと思います。
