### ISSUE TITLE
no-cdn + drawio コンテナで、drawioの図を拡大表示すると `app.diagrams.net` 配下で描画される

### ISSUE THREAD

**Issue by m-bird** [weseek/growi#2561]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.6.1810|
|GROWI     |4.0.10|
|node.js   |12.18.2|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 Pro 1809|
|browser   |Google Chrome 84.0.4147.89 / Firefox 78.0.2|

How to reproduce? (再現手順)
---------------------------

1. 内部にプライベート drawioサービス（今回の場合コンテナによる）を稼働
   + 仮に、ここではプライベートインスタンスのURIを`https://drawio.example.jp/`とする
2. no-cdn版のイメージを用いて稼働
   + `NO_CDN`を有効にする
   + `NO_CDN=true`, `DRAWIO_URI=https://drawio.example.jp/`
3. growiにログイン、drawio連携機能を用いて作図する
4. 作図完了後、保存
5. 通常のビュー画面で、drawioで作図した図をクリック、拡大表示する
6. 拡大した図が描画されるが、ブラウザのURL欄を見ると、`https://app.diagrams.net/` 配下となっている

What happens? (症状)
---------------------

 - no-cdn イメージかつ`NO_CDN` オプションを有効にしても、外部サービス(`app.diagrams.net`)に依存してしまう

What is the expected result? (期待される動作)
-------------------------------------------

no-cdn版のイメージかつ`NO_CDN`オプションを有効にした場合において、次のような挙動をすること。

 - drawioの図の拡大表示の際に、外部サービス(`app.diagrams.net`)に依存しない
 - drawioの図の拡大表示の際に、`DRAWIO_URI` で定義したサービス配下で描画されること

Note
----

lightbox では、ハードコーディングされてしまっているとのこと。

https://github.com/jgraph/drawio/blob/f247b0bdc1ff40d22605d1a9abc7e15f1aca3754/src/main/webapp/js/diagramly/GraphViewer.js#L1430-L1440

```
			var domain = 'app.diagrams.net';
			
			if (urlParams['dev'] == '1')
			{
				param.dev = '1';
				param.drawdev = '1';
				domain = 'test.draw.io';
			}
			
		    this.lightboxWindow = window.open('https://' + domain +
		    		'/#P' + encodeURIComponent(JSON.stringify(param)));
```

**Comment by kaishuu0123** [comment]
@m-bird 
PR #2543 が Merge されて問題は修正しましたが、
通常(cdn 版) の GROWI と no-cdn 版で若干挙動が異なりますのでご注意ください
また、**draw.io の最新版(厳密に言うと 13.5.5 以降) をお使いください**

通常版の GROWI は draw.io の図をクリックすると lightbox (白背景で図が大きく表示される) となりますが、
no-cdn 版だと、リンク先は正しいのですが、エディタ画面が開きます。
これはさすがに draw.io 側の挙動なので、GROWI 側ではこれ以上の対応は厳しいのでご容赦ください

**Comment by kaishuu0123** [comment]
https://github.com/weseek/growi/issues/2509#issuecomment-666333074
こういった情報もあるのでご参考までに。

**Comment by m-bird** [comment]
@kaishuu0123 ご対応ありがとうございます、大変助かります。感謝いたします。遅くとも次回リリース、できれば `master` 引っ張ってきて試験利用をしてみたいと思います。
