### ISSUE TITLE
Bug: I can't delete the mail settings I entered once

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#2562]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.0.10|

How to reproduce? (再現手順)
---------------------------

1. Access to `/admin/app` page
1. Update by emptying any text input
1. Reload page

What happens? (症状)
---------------------

- The value of the empty text input has not been updated (the old value remains)

What is the expected result? (期待される動作)
-------------------------------------------

- Empty values ​​cannot be updated by validation
- All settings can be erased with a reset button

Note
----

- 
-

**Comment by yuki-takei** [comment]
fixed in v4.1.3
