### ISSUE TITLE
Bug: iOSで漢字変換ができない

### ISSUE THREAD

**Issue by inductor** [weseek/growi#260]
Environment
------------

### Host

Demo環境

### Client

| item     | version |
| ---      | --- |
|OS        | iOS 11 |
|browser   |Chrome/Safari|

How to reproduce? (再現手順)
---------------------------

1. process 1
編集ページにて日本語入力を試みる

What happens? (症状)
---------------------

- ひらがなで確定されてしまい、濁点の追加や漢字変換ができない

What is the expected result? (期待される動作)
-------------------------------------------

- 漢字変換ができること

Note
----

- 特になし

**Comment by kelaductor** [comment]
https://github.com/codemirror/CodeMirror/issues/3137 のバグっぽい

**Comment by yuki-takei** [comment]
Working on https://github.com/weseek/growi/tree/inprv/better-input-on-mobile
