### ISSUE TITLE
no-cdn+drawioコンテナで、一部アイコンが表示されない。

### ISSUE THREAD

**Issue by kytTJ** [weseek/growi#2643]
Environment
------------

### Host
#2509 

| item     | version |
| ---      | --- |
|OS        |RHEL7|
|GROWI     |4.1.2|
|node.js   |14.7.0|
|npm       |6.14.7|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Win10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------
drawioの一部アイコンが表示されない
1. drawioのClipartのアイコン等が上手く表示されない。
　例：Clipart、Misc(Image(FixedAspect))
条件：no-cdn版かつ社内ネットワーク内のみ（外部接続不可）

What happens? (症状)
---------------------

- Growiでアイコンを使用して、保存した後にアイコンが上手く表示されない（画像のイメージになる）

What is the expected result? (期待される動作)
-------------------------------------------

- Growiでアイコンを使用して、保存後にアイコンが綺麗に表示される（Clpiart等が表示される）

**Comment by yuki-takei** [comment]
@kytTJ こちらは仕様になります。
自身でサーバーを用意して `DRAWIO_URI` 環境変数に入れる事で回避できます。

https://docs.growi.org/ja/admin-guide/admin-cookbook/env-vars.html
