### ISSUE TITLE
Markdownの絵文字の表示がおかしい

### ISSUE THREAD

**Issue by kytTJ** [weseek/growi#2644]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |RHEL7|
|GROWI     |4.0.7|
|node.js   |12.18.1|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Win10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. ページを作成
2. Markdownの絵文字を入力し、保存すると上手く表示されない

例
```
:arrow_backward
```
条件：条件：no-cdn版かつ社内ネットワーク内のみ（外部接続不可）

What happens? (症状)
---------------------

- Growiで、Markdownの絵文字を使用して、保存した後に絵文字が上手く表示されない。

What is the expected result? (期待される動作)
-------------------------------------------

- Growiで、Markdownの絵文字を使用して、保存した後に絵文字が綺麗に表示される。

Note
----
Growiのバージョンが3.6.7の時には、綺麗に表示がされていました。  
4.0.7にバージョンを挙げてから、上手く表示ができなくなりました。

**Comment by yuki-takei** [comment]
@kytTJ ご報告ありがとうございます。

症状としては #2472 と重複しておりますので、この issue はクローズさせていただきます。

またこちらでも 3.6.7 で動作を確認しましたが、そちらのバージョンでも jsdelivr という CDN を利用するコードなのは変わっていませんでした。同環境で絵文字の img タグがどのような状態になっているか、確認可能でしょうか？もし調査結果がわかりましたら、そちらも #2472 の方にコメントいただけると助かります。
