### ISSUE TITLE
Failed to rebuild an index with MongoDB 4.2

### ISSUE THREAD

**Issue by rshindo** [weseek/growi#2683]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.1.2|
|MongoDB (MongoDB Atlas)|4.2.8|
|Elasticsearch (SearchBox)|6.8.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. Deploy to HerokuボタンでHerokuにデプロイ
1. MongoDB AtlasでMongoDB 4.2のクラスタを作成
1. MONGO_URI を2で作成したクラスタのものに編集してHeroku Appを再起動
1. HerokuにデプロイしたGrowiにアクセスした後、全文検索管理でインデックスのリビルドを実行

※docker-composeでMongoDBのバージョンを4.0以降にした場合も同様

What happens? (症状)
---------------------

- インデックスのリビルドに失敗し、下記のログが出力される

```
Uncaught Exception:  MongoError: Failed to parse: { find: "pages", filter: { $and: [ { redirectTo: null } ] }, projection: {}, returnKey: false, showRecordId: false, snapshot: true, lsid: { id: UUID("2885dbb9-1d56-4447-946d-53688a971e31") }, $clusterTime: { clusterTime: Timestamp(1598076774, 1), signature: { hash: BinData(0, 193CDFF16299DD5B5B620B345B5F36D3080719BC), keyId: 6854399949057032195 } }, $db: "growi" }. Unrecognized field 'snapshot'.
    at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:713:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1598076774 },
  ok: 0,
  code: 9,
  codeName: 'FailedToParse',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1598076774 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
```

What is the expected result? (期待される動作)
-------------------------------------------

- インデックスのリビルドが成功する

Note
----

サポート対象はMongoDB 3.xですが、HerokuのmLabプラグインが2020年11月で提供終了かつmLabが移行推奨としているMongoDB Atlasが基本的に4.2以降のみをサポートしているという状況のため、起票しました。

例外が発生している箇所は `src/server/service/search-delegator/elasticsearch.js` の下記の行です。

```js
    const readStream = findQuery
      // populate data which will be referenced by prepareBodyForCreate()
      .populate([
        { path: 'creator', model: 'User', select: 'username' },
        { path: 'revision', model: 'Revision', select: 'body' },
      ])
      .snapshot()
      .lean()
      .cursor();
```

この `snapshot()` によって、MongoDB 3.2から非推奨となっている`$snapshot`オペレータを呼び出しているようですが、MongoDB 4.0以降で上記の例外が発生します。

**Comment by yuki-takei** [comment]
@rshindo ご報告ありがとうございます。MongoDB の最新バージョンにもだいぶ置いて行かれているので、4系への対応に着手しようと思います。次のバージョンリリースまで少々お待ちください。

**Comment by yuki-takei** [comment]
進捗報告です。snapshot を含むクエリを廃した v4.1.3 をリリースしました。
手元では MongoDB 3.6 での正常動作を確認するに留まっていますが、今後4.x系への動作確認を終え次第、[https://github.com/weseek/growi-docker-compose](weseek/growi-docker-compose) が依存している MongoDB も4.x系に切り替えていく予定です。

**Comment by shield-9** [comment]
自分の手元での動作確認の結果です。

GROWI 4.1.5+MongoDB 3.6.19の環境をMongoDB 4.0.20→4.2.2.9→4.4.1の順番に更新してみました。
それぞれのバージョンで以下の操作を試しましたが、正常に動作しているようです。

- ページの閲覧
- ページの編集
- インデックスのリビルド
- ログイン/ログアウト

**Comment by yuki-takei** [comment]
開発チームでの動作確認結果も問題ないようなのでこの issue は close します。

**Confirmed versions**

| GROWI | MongoDB |
|---|---|
|v4.1.2 <= | v3.3, v3.6 |
| <= v4.1.3| v3.3, v3.6, v4.0, v4.2, v4.4 |
