### ISSUE TITLE
SAML認証で利用するメタデータの生成はできますか？

### ISSUE THREAD

**Issue by episodehand** [weseek/growi#2696]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux 7.6|
|GROWI     |4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10|
|browser   |GoogleChrome|

What happens? (症状)
---------------------

- SAML認証おけるServiceProvider側（Growi）のメタデータを生成できない

What is the expected result? (期待される動作)
-------------------------------------------

- SAML認証おけるServiceProvider側（Growi）のメタデータを生成し、「発行者」として登録できる

Note
----

- 上記について、方法があればご教授頂きたく

**Comment by yuki-takei** [comment]
@episodehand 
すみません、「期待される動作」をもう少し詳しく教えていただけないでしょうか。
例えば、どことどこの間の通信で、どういうデータ(key, value)が生成されて欲しいが、現在はどのようである、といった内容です。

よろしくお願いいたします。

**Comment by episodehand** [comment]
こちらSAML 2.0で利用されるメタデータを用いたIDP-SP間の認証は可能か、という質問でした
[https://www.npmjs.com/package/passport-saml-metadata](https://www.npmjs.com/package/passport-saml-metadata)
上記、リンクの通り別途パッケージが必要なことを理解したため、本isssueはクローズさせて頂きます
失礼しました
