### ISSUE TITLE
更新履歴で編集者の名前が正しく表示されない

### ISSUE THREAD

**Issue by YDKK** [weseek/growi#2709]
Environment
------------

### Host
公式デモサイト（ https://demo.growi.org/ ）で再現します。
| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.1.2|
|node.js   |14.7.0|
|npm       |6.14.7|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|Windows 10        |2004|
|Microsoft Edge|84.0.522.63|

How to reproduce? (再現手順)
---------------------------

1. https://demo.growi.org/#revision-history にアクセス

What happens? (症状)
---------------------

- `差分を表示` をクリックするまで編集者の名前が正しく表示されない
![image](https://user-images.githubusercontent.com/3415240/91521053-c79f5a00-e931-11ea-967d-4e388ee96f2e.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 編集者の名前が正しく表示される

**Comment by itizawa** [comment]
ご報告いただきありがとうございます。
こちらでも再現確認いたしました。

修正しますので少々お待ちください

**Comment by itizawa** [comment]
こちら v4.1.3 にて改修しておりました。
デモサイトもバージョンを上げたため解消しているかと思います。

この度は報告いただきありがとうございます。
close とさせていいただきます。
