### ISSUE TITLE
ページ印刷時のページタイトル表示の扱いに関して

### ISSUE THREAD

**Issue by tminai** [weseek/growi#2711]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 8|
|GROWI     |4.1.3|
|node.js   |14.8.0|
|npm       |6.14.7|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------
スクロールバーが表示される程度に文量のあるページをブラウザの機能で印刷する

What happens? (症状)
---------------------

ページをスクロールすると追従するページタイトルが、
印刷時にも追従しており、何個もページタイトルが表示される。
![image](https://user-images.githubusercontent.com/56664277/91523646-439ca080-e938-11ea-9a60-ac00f4d8f8e6.png)

What is the expected result? (期待される動作)
-------------------------------------------

ページタイトルの表示は1ページ目の頭のみ

**Comment by takeru0001** [comment]
ご報告いただきありがとうございます。
こちらでも再現確認いたしました。

修正しますので少々お待ちください

**Comment by takeru0001** [comment]
修正しました。次のバージョンをお待ち下さい。
