### ISSUE TITLE
画像添付時にページが非公開になる

### ISSUE THREAD

**Issue by kskzk** [weseek/growi#2736]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.7|
|GROWI     |4.1.3|
|node.js   |14.8.0|
|npm       |6.14.7|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 85.0.4183.83|

How to reproduce? (再現手順)
---------------------------
1. ページを作成する
1. 適当にページを執筆し、Drag&Dropで画像を添付する
1. 公開範囲が"公開"になっていることを確認し、更新をクリックする
    
What happens? (症状)
---------------------
- ページが非公開になり、Only me (Browsing of this page is restricted)がページ上部に表示される

What is the expected result? (期待される動作)
-------------------------------------------
- ページが公開される

Note
----
- 明示的に公開をクリックすると、公開されます
- 画像を添付しない場合は事象は発生していません

**Comment by kaoritokashiki** [comment]
@kskzk 様

issueの報告ありがとうございます。
再現確認致しましたので、修正作業に入ります。
ご不便をおかけして大変申し訳ないのですが、issue解消までもうしばらくお待ちいただけますようお願いします。

**Comment by itizawa** [comment]
@kskzk 様

issue の報告ありがとうございます。
新規作成エディター上で画像を添付した際にページの公開範囲が **自分のみ** となる現象ですが、
こちらは GROWI の仕様となります。

現状公開範囲が変わらずバグのように見える挙動でしたので、
添付した時に公開範囲が変化するように修正いたします。
https://github.com/weseek/growi/pull/2803

今後とも GROWI をよろしくお願いいたします。
