### ISSUE TITLE
プレゼンテーションモーダルが表示されない

### ISSUE THREAD

**Issue by makotoshiraishi** [weseek/growi#2766]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.6|
|GROWI     |v4.1.5|
|node.js   |v14.5.0|
|npm       |v6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS 10.15.6|
|browser   |Chrome 85.0.4183.83|

How to reproduce? (再現手順)
---------------------------

1.  ページを作成する。
2. そのページのプレゼンテーションボタンをクリックする。

What happens? (症状)
---------------------
真っ黒な画面が表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- プレゼンテーションモーダルが現れ、wikiが表示される。

**Comment by itizawa** [comment]
修正完了
v4.1.6 or v4.2.0 にて反映される予定
