### ISSUE TITLE
Bug: PlantUML でタイミングチャートが描画されない

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/growi#278]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.4.1|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](crowi-plus-docker-compose)|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

How to reproduce? (再現手順)
---------------------------

1. crowi-plus v2.4.0 以降のバージョンで以下をページに記載

```
@startuml
robust "ウェブブラウザ" as WB
concise "ユーザ" as WU

@0
WU is アイドル
WB is アイドル

@100
WU is 待機
WB is 処理中

@300
WB is 待機
@enduml
```

What happens? (症状)
---------------------

- ダイアグラムが描画されない

What is the expected result? (期待される動作)
-------------------------------------------

- 以下のような描画が行われる
![chart](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuIhAJoejBb5GUjoqx77JyiVDqy1e9PYxJKaXiLWXt8ahEJylERCu5QYgUTdZvZrmcL0kBWS3hl1GXSnYXSTDYnutBNdStFcuUJLNk1E649U3eG5CxTDzhSzMpeUgUjg-xFc4jYSxrWAL68EKE24fSKZDIm4w4m00)

Note
----

- デモサイトの以下のページで再現確認頂けます。
https://demo.crowi-plus.org/Sandbox/plantuml_test#timinig-chart
- 2.4.0 にアップデートする前までは描画されていました

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございます。再現しました。
`@` が入ってるとダメっぽいですね。修正方法考えてみます。

**Comment by takuma-watanabe** [comment]
@yuki-takei ご確認ありがとうございます。
どうにか表示できないかと、色々試していたのですが、以下のように `@startuml` から `@enduml` までの間をインデントしてあげると、以下のケースでは表示が可能となることがわかりました。
```
@startuml
    robust "ウェブブラウザ" as WB
    concise "ユーザ" as WU
    
    @0
    WU is アイドル
    WB is アイドル
    
    @100
    WU is 待機
    WB is 処理中
    
    @300
    WB is 待機
@enduml
```

ただし、以下のように `<` や `>` を含むケースでは、うまく表示されません（コンパイルエラーとなっていました）。

```
@startuml
    robust "ウェブブラウザ" as WB
    concise "ユーザ" as WU

    WB is 初期化中
    WU is 不在

    @WB
    0 is アイドル
    +200 is 処理中
    +100 is 待機
    WB@0 <-> @50 : {50 ms lag}

    @WU
    0 is 待機
    +500 is ok
    @200 <-> @+150 : {150 ms}
@enduml
```
なんとなく、 `<` や `>` が除外された文字列で plantumlのサーバにデータが飛んでいるように見えました。

私の試した限り、行頭の `@` と 文中に `<` `>` が含まれる場合に問題があるように見えました。

**Comment by yuki-takei** [comment]
@takuma-watanabe 1年も前の Issue になりますが、markdown-it-plantuml パッケージを最新版にアップグレードしたところ、こちらの挙動は修正されました。

v3.3.5 リリースをお待ちください。

**Comment by takuma-watanabe** [comment]
ありがとうございます！
v3.3.6 にて修正された事を確認しました。
