### ISSUE TITLE
DRAWIO_URI を設定するとパーマネントリンクが書き換わってしまう

### ISSUE THREAD

**Issue by kunitake** [weseek/growi#2785]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.6|
|GROWI     |4.1.5|
|node.js   |14.9.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.6|
|browser   |Google Chrome 85.0.4183.102（Official Build）|

How to reproduce? (再現手順)
---------------------------

1. docker-compose.yml などに DRAWIO_URI をセットしてGrowiを起動

```
    environment:
      - DRAWIO_URI=http://drawio.example.jp:8080
```

What happens? (症状)
---------------------
Copy to clipboard の Permanent link を含むリンクが DRAWIO_URI で書き換わる。

![DRAWIO_URI_and_permanent_link](https://user-images.githubusercontent.com/1456158/93168439-d07b9280-f75d-11ea-9ac4-f32a13da09e6.png)

What is the expected result? (期待される動作)
-------------------------------------------

- Permanent link には、APP_SITE_URL などのサイトURLが利用される。

Note
----
Growi 4.1.0 でも再現しました。generatePermalink() の origin が overwrite されているのかもしれません。

**Comment by itizawa** [comment]
Issue の起票ありがとうございます。
再現確認いたしました。

修正しますので少々お待ちください。
