### ISSUE TITLE
Feature:ドラフト(下書き)保存機能が欲しい

### ISSUE THREAD

**Issue by Tatsuki-I** [weseek/growi#279]
メールやQiitaの記事を書く時のように, 新規ページ作成をした時に, 投稿せずに書きかけで下書きを置いておく機能と, 更新をする時にその更新をすぐに反映せずに置いておく機能があるととても有難いです(もし既に存在していて僕が気付いていないだけならすみません).

**Comment by yuki-takei** [comment]
まず、localStorage に書きかけのものを保存しておく機能はあります(本家Crowi由来)。ただし取り出してくる条件とかタイミングが不明瞭、かな。裏側で暗黙に動くので、ユーザーが意図的にトリガできる機能ではないです。

懸念点としては、「下書きは公開されるのかされないのか」があって、

* 公開されるんだとすると、esa.io の WIP 機能とそう変わらないかも？
    * esa.io の WIP 機能相当だとすると、ページタイトルに「WIP」付けたりでいいかも？
* 公開されないのだとすると、それは「自分だけ」が見られるページと変わらないのではないか？

あとは、

* 「更新をする時にその更新をすぐに反映せずに置いておく機能」は、History を使って前の状態に戻すという操作で代用できないか？

あたりでしょうか。仕様検討の余地があるかなと思います。

**Comment by yuki-takei** [comment]
長らく議論がないので close します。
再度仕様検討したい方は、メンション飛ばしてください。reopen します。
