### ISSUE TITLE
画像添付時にEmail通知が機能しない

### ISSUE THREAD

**Issue by kskzk** [weseek/growi#2826]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.7|
|GROWI     |4.1.3|
|node.js   |14.8.0|
|npm       |6.14.7|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 85.0.4183.121|

How to reproduce? (再現手順)
---------------------------

1. アプリ設定のメール設定より、FromアドレスおよびSMTP設定を行う。
1. 通知設定のGlobal notificationより、通知設定を行う。  
トリガーパスは任意、通知先はEmailアドレスとし、トリガーイベントにはCREATEを指定する。
1. 上記で設定したトリガーパス以下に記事を作成する。
1. Drag＆Dropで画像を添付する。
1. 公開を選択し、更新をクリックする。

What happens? (症状)
---------------------
- 通知先に設定したEmailアドレスに通知がされない

What is the expected result? (期待される動作)
-------------------------------------------
- 通知先に設定したEmailアドレスに通知がされる

Note
----
- 画像を添付しない場合、期待通りに通知が行われます
-  #2736 でご教示頂いた仕様を考慮し、画像添付後に改めて"公開"を選択したのち更新しています

**Comment by itizawa** [comment]
Issue を報告いただきありがとうございます。

Drag＆Dropで画像を添付した状態でページは新規作成されるので、
更新をクリックする段階では トリガーイベント EDIT に反応するはずです。

ただ、添付の段階で CREATE に反応していないのは bug かと思われます。
調査、修正いたしますので少々お待ちください。
