### ISSUE TITLE
Feature: Custom `title` tag contents

### ISSUE THREAD

**Issue by kazuemon** [weseek/growi#284]
公開用にページ名をURLとは別に設定できるようにしてほしいです。
何度も要望申し訳ありません。

**Comment by kazuemon** [comment]
ページタイトルの方が正しいかもしれません...
現在 : /page · /page (Wiki名)
要望 : ページ名 · /page (Wiki名)

**Comment by yuki-takei** [comment]
要望はいつでも歓迎です 😃 
`<title>` タグのコンテンツをカスタムできたらよい、ということでしょうか？

**Comment by kazuemon** [comment]
そうですね。
外部に公開したりするときに、見栄えがよくなると思います。
またブラウザのブックマークなどを頻繁に利用するなどの場合、ページの日本語タイトルがあれば非常に便利になるかと思います。

**Comment by yuki-takei** [comment]
`/admin/customize` のページに専用の textarea を作る方向で。
サポートは @kainosuke 
直近でカスタムヘッダーを実装してるから @haruhikonyan も詳しい。

**Comment by yuki-takei** [comment]
`/lib/views/layout/layout.html` の `<title>` タグが書き換え対象

**Comment by kazuemon** [comment]
すみません、ページ名は「ページごとの表示名」を指しています

**Comment by kazuemon** [comment]
すいません、タイトルタグというよりかは、ページごとの名前をURLをそのままに変えられるように、という方が正しいかもしれません

**Comment by yuki-takei** [comment]
@kazuemon 
もしかすると要望に対して乖離が発生しているかもなとは思っていたのですが…
カスタムタイトルタグをユーザーが設定できるように、というのは需要として既にあるので、申し訳ないですがこの issue はこのまま走ります。(もう詳細設計終えてしまったので)

で、
> ページごとの名前をURLをそのままに変えられるように
というご要望は正直どこがゴールかよくわからなくなってしまったので、お手数ですが別途 issue を上げていただけますでしょうか。

* どのページ(URL)のどこで、どういうものを設定したいのか
* 上記で設定したものは、どの画面のどこに、どのように出て欲しいのか
    * こちらはスケッチか、スクリーンショットにちょっと落書きしたようなイメージがあると把握しやすいです

上げていただいた後に実装方針の検討からやりたいと思います。
よろしくお願いします。

**Comment by kazuemon** [comment]
わかりました。

**Comment by yuki-takei** [comment]
Implemented in v3.0.0
