### ISSUE TITLE
Bug: Set correct lang param when using drawio (diagrams.net)

### ISSUE THREAD

**Issue by kaz-on** [weseek/growi#2854]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Windows 10 |
|GROWI     | 4.1.6 |
|node.js   | 14.11.0 |
|npm       | 6.14.8 |
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]| yes |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10 |
|browser   | Firefox 81.0.1 |

How to reproduce? (再現手順)
---------------------------

1. GROWIのユーザーの言語設定を日本語にする。
2. draw.ioの図の編集画面を開く。

What happens? (症状)
---------------------

- draw.ioの言語設定が英語になっている。

What is the expected result? (期待される動作)
-------------------------------------------

- draw.ioの言語設定が日本語になる。

Note
----

- draw.ioのURLパラメータに `lang=ja_JP` を渡しているため英語になっているようです。
- URLパラメータに `lang=ja` を渡せば日本語になると思われます。
- Ref: https://desk.draw.io/support/solutions/articles/16000042546-supported-url-parameters

**Comment by yuki-takei** [comment]
@kaz-on ご報告ありがとうございます。

再現は確認しました。

だいぶ後になってしまって申し訳ないのですが、諸々の実装上の都合で、v5.x 系での修正とさせていただきます。

## memo

- 修正箇所
    - https://github.com/weseek/growi/blob/dev/4.1.x/src/client/js/components/PageEditor/DrawioModal.jsx#L128
- diagrams.net に合わせた lang パラメータの値は、各言語別のファイル(translation.json 等)に載せたい
- `DrawioModal` から上記を参照して lang パラメータを書き換えればいいだけだが、DrawioModal を withTranslation でラップすると動作しなくなってしまう
    - `CodeMirrorEditor` との関係が ref で繋がっているため(負の遺産)
- Next.js 化に伴って `DrawioModal` を functional component 化すれば `useTranslation` が使えるようになる

**Comment by kaz-on** [comment]
GROWI 4.2.13 で修正されていることを確認しましたのでクローズします。
対応ありがとうございました！
