### ISSUE TITLE
データアーカイブ→インポートした後、検索結果がヒットしない

### ISSUE THREAD

**Issue by SatoshiKawagucchi** [weseek/growi#2855]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7.8|
|GROWI     |4.0.10|
|node.js   |12.18.2|
|npm       |6.14.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |CentOS7.8|
|browser   | Chrome 85.0.4183.121|

How to reproduce? (再現手順)
---------------------------

1. GROWI 4.0.10を新たに作る  -1
1. GROWI 4.0.10でデータアーカイブ -2
1. 1のGROWIに2.のデータをインポート→成功する
1.1.及び2.環境にて「検索」を行う

What happens? (症状)
---------------------
- 1.環境でヒットしていたものが2.環境でヒットしない
- 2.環境では検索結果はヒットしない、色んな検索キーワードでも空振り状態

What is the expected result? (期待される動作)
-------------------------------------------
- 1.環境及び2.環境で検索すれば同じ結果を得たい

Note
----
- Elasticsearch接続及びインデックス状態は正常
- インデックスりビルドが 進まない（いま見えるところでは 4/121 で止まってしまう）→サーバリブートのたびに分子は1つ進むような感じになっている。

対応策を教えて頂きたい。

**Comment by yuki-takei** [comment]
@SatoshiKawagucchi 

GROWI のご利用ありがとうございます。
再現手順についてですが、いくつか確認させてください。

1. アーカイブは全てのコレクションを対象にしていますか？それとも一部でしょうか？
1. インポートは上記のアーカイブされたコレクション全てを対象にしていますか？
1. 「1のGROWIに2.のデータをインポート→成功する」の際に、skip は 0 件で、全て insert または update に成功していますか？
1. データインポートマニュアルにあるように旧環境と新環境で username が重複しているユーザーがいないかどうか、ご確認いただけますでしょうか
    https://docs.growi.org/ja/admin-guide/management-cookbook/import.html#growi-%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96%E3%83%87%E3%83%BC%E3%82%BF%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88

以上、よろしくお願いいたします。

**Comment by SatoshiKawagucchi** [comment]
ご回答ありがとうございます。4.制約は澪としておりました。
早速作り直して再実行したところ事象再発しております。
１．全てのコレクション
２．すべてを対象
３．スキップ0件、エラーなし
を確認しております。
インデックスリビルドができていないのですがsuccessful で終わってしまいます。

一方、9月15日に一度exportしたものがありましたのでやってみるとこちらのデータではうまくいく状況となっております。
一度検索が効かない状態に陥ったデータをExportしたものはインポートしても再現してしまう、ということでしょうか。

もしそうならばあきらめます。
よろしくお願いします。

**Comment by yuki-takei** [comment]
## ご報告いただいている事象について
「検索が効くかどうか」に関してですが、v4.1.7 以前までは以下のような判定になっており、

- ページの作成者データがない
- リビジョン(本文)データがない
- リダイレクト専用ページになっている

の3点です。

https://github.com/weseek/growi/blob/v4.1.7/src/server/service/search-delegator/elasticsearch.js#L54

そのため追加の確認事項 1-3 で「ページの作成者データが正常にインポートされているか」を疑って質問させていただいたのですが、ご報告いただいた通りだとすればそれで検索対象にはなるはずで、これ以上はそのバックアップデータをいただくなりしないと事象を追いかけることはできなさそうです…

## 新バージョンについて

ただ、先日リリースした v4.1.8 では、「ページの作成者データがない」ページもインデックス対象にするよう改修しています。

https://github.com/weseek/growi/blob/v4.1.8/src/server/service/search-delegator/elasticsearch.js#L54

お時間ありましたらこちらも試していただけますと幸いです。

**Comment by SatoshiKawagucchi** [comment]
ご説明ありがとうございます。承知しました。
新しいバージョンで検証したいのですが、諸事情により古いFireFoxを使っておりまして
ヘダーとかサイドバーが表示されない問題にぶつかっておりUpdate出来ず状態にあります。
こちらの改修が完了することを待ちます（他 issueで起票あり）。

本件はClose致します。ありがとうございました。

**Comment by yuki-takei** [comment]
> こちらの改修が完了することを待ちます（他 issueで起票あり）。

すみません、こちらの「他 issue」ってどれのことでしょうか。
