### ISSUE TITLE
Lang setting selected in installer form is not set lang of init user and global lang

### ISSUE THREAD

**Issue by fezzlk** [weseek/growi#2864]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |v4.1.6|

How to reproduce? (再現手順)
---------------------------

1. In installer page, select `日本語` as lang
2. Install an app

What happens? (症状)
---------------------

- Lang of init user is `English`
- globalLang is `English`

What is the expected result? (期待される動作)
-------------------------------------------

- Lang of init user and global lang are `日本語`(selected lang when install)

Note
----

- 
-

**Comment by yusuketk** [comment]
fix in [PR#3024](https://github.com/weseek/growi/pull/3024)
