### ISSUE TITLE
リスト表示タブとタイムライン表示 だけになってしまう ：4.1系＋Firefox68〜70

### ISSUE THREAD

**Issue by ghost** [weseek/growi#2897]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8|
|GROWI     |4.1.8-nocdn |
|node.js   |14.13.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |CentOS7.8|
|browser   |Firefox68〜70|

How to reproduce? (再現手順)
---------------------------
社内環境（非ネット接続）でGROWI利用を考えております。
ただし社内事情によりブラウザ環境が古いものに限定されています。

- 4.1.8-nocdn でのGROWI立ち上げを実施
- Fireforx68〜70で参照

What happens? (症状)
---------------------
- 「リスト表示」タグ内容と「タイムライン表示」タグ内容しか情報が出てこない。
-  Top画面向き書いたデータ表示コードの処理結果が見えない状況になる（表示されない）

たとえばこのようなコードを書いても期待する結果は表示されず空っぽ状態になる。

```
|<a href="/議事録">議事録</a>|<a href="/まとめ">Teams ディスカッションまとめ</a>
| --- |  --- | 
| $lsx(/議事録,depth=2) |$lsx(/まとめ,depth=2) |
```

What is the expected result? (期待される動作)
-------------------------------------------
- 個別に書いたコード結果もTop画面に表示される。
- FIrefox 67〜70でも最新Firefoxと同様の動作をする。

Note
----
- 4.0.11-nocdnであれば期待する動作をする。
- 4.1系になると同事象が発生してしまう。GROWI最新のバージョンに追いつけないという問題にぶつかる可能性。

**Comment by yuki-takei** [comment]
@SatoshiKawagucchi 
下記組み合わせで動作を確認しましたが、再現しませんでした。

### Host

| item     | version |
| ---      | --- |
|OS        |Win 10|
|GROWI     |4.1.8-RC, `NOCDN=true` |
|node.js   |14.13.1|
|npm       |6.14.8|
|Using Docker|no|


### Client

| item     | version |
| ---      | --- |
|OS        |Win 10|
|browser   |Firefox 81.0.2 (64bit)|

お使いのブラウザのコンソールに何かエラーログが出ていないか確認いただけますでしょうか。

**Comment by yuki-takei** [comment]
追記です。カスタムスクリプトやカスタムヘッダー等に何か独自の設定を入れている場合はそちらも貼っていただけると助かります。

**Comment by SatoshiKawagucchi** [comment]
Firefox81では再現しませんでした（手元の環境で確認しました）。会社環境はFirefox68〜70までしか提供されておらず「最新版」とは程遠い環境にあります。この前提でなにかしら回避策＋GROWI最新版-nocdnを使用したい希望です。

カスタムスクリプトやカスタムヘッダーは入れておりません。

以下firefox 68.12.0esr 64ビットに出ているコンソールログ：エラー情報となります。
お手数かけますがよろしくお願いします。

```
SyntaxError: invalid regexp group app.479e08583b1d17f756c8.bundle.js:1:6
jQuery.Deferred exception: o is undefined ./src/client/js/legacy/crowi.js/</<@http://192.168.xxx.xxx:3xxx/js/legacy.4f614ea6339bc30d4240.bundle.js:1:3402
e@http://192.168.xxx.xxx:3xxx/js/cdn/basis.js:28:29453
l/</t<@http://192.168.xxx.xxx:3xxx/js/cdn/basis.js:28:29755
```
```
TypeError: n is undefined legacy.4f614ea6339bc30d4240.bundle.js:1:6512
TypeError: o is undefinedlegacy.4f614ea6339bc30d4240.bundle.js:1:3402
```

```
ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://192.168.xxx.xxx:3xxx/js/cdn/highlight-addons.js
ソースマップ URL: /sm/d3c6feb7461c492da6746886de5ab3d513404178738d6d6525700a1e935d2846.map

ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://192.168.xxx.xxx:3xxx/js/cdn/basis.js
ソースマップ URL: /sm/93a47125a73e986c1bbf1424f95496e6e9649182b31e33a236fb02ff473c6f0e.map

ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://192.168.xxx.xxx:3xxx/js/cdn/highlight-addons.js
ソースマップ URL: /sm/d3c6feb7461c492da6746886de5ab3d513404178738d6d6525700a1e935d2846.map

ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://192.168.xxx.xxx:3xxx/js/cdn/basis.js
ソースマップ URL: /sm/93a47125a73e986c1bbf1424f95496e6e9649182b31e33a236fb02ff473c6f0e.map

ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://192.168.xxx.xxx:3xxx/js/cdn/basis.js
ソースマップ URL: /sm/93a47125a73e986c1bbf1424f95496e6e9649182b31e33a236fb02ff473c6f0e.map
```

**Comment by SatoshiKawagucchi** [comment]
```
SyntaxError: invalid regexp group app.d573200ccb2e85a27cb9.bundle.js:1:6
TypeError: n is undefined
legacy.4f614ea6339bc30d4240.bundle.js:1:6512
    js http://xxxxxxxxxxxxxxxxxxxx/js/legacy.4f614ea6339bc30d4240.bundle.js:1
jQuery.Deferred exception: o is undefined ./src/client/js/legacy/crowi.js/</<@http://xxxxxxxxxxxxxxxxxxxx/js/legacy.4f614ea6339bc30d4240.bundle.js:1:3402
e@http://xxxxxxxxxxxxxxxxxxxx/js/cdn/basis.js:28:29453
l/</t<@http://xxxxxxxxxxxxxxxxxxxx/js/cdn/basis.js:28:29755
 undefined basis.js:28:31008
TypeError: o is undefined
legacy.4f614ea6339bc30d4240.bundle.js:1:3402
ソースマップエラー: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
リソース URL: http://xxxxxxxxxxxxxxxxxxxx/js/cdn/basis.js
ソースマップ URL: /sm/93a47125a73e986c1bbf1424f95496e6e9649182b31e33a236fb02ff473c6f0e.map
```
FireFoxでのコンソールはこちらです。

**Comment by yuki-takei** [comment]
古いバージョンのブラウザへの対応を今のところ予定していないためクローズします。
