### ISSUE TITLE
ユーザがパスワードを忘れてしまった際に、ユーザーにパスワードを再設定するためのメールを送信して欲しい

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#2919]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu Server 20.04.1 LTS|
|GROWI     |4.1.8|
|node.js   |14.13.1|
|npm       |6.14.8|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.15.7|
|browser   | Safari 14.0 |

How to reproduce? (再現手順)
---------------------------
1. ユーザがログイン画面で誤ったパスワードを入力してしまう (しかも正しいパスワードを完全に忘れてしまっている)

What happens? (症状)
---------------------
- Sign in failure. と表示されログインができない。

What is the expected result? (期待される動作)
-------------------------------------------
- 現状は管理者に連絡して、パスワードを初期化してもらわなければならない
- オプションか何かで、パスワードを忘れたボタン等を表示して、パスワード再設定用のフォームへのアドレスが書かれたメールをユーザに送信して欲しい。

Note
----
- 特になし

**Comment by kaoritokashiki** [comment]
@hanapage 様

この度は、issueを起票していただき誠にありがとうございます。
これから実装に入らせていただきますので、リリースまで今しばらくお待ちください。

引き続き、GROWIをよろしくお願いいたします。

**Comment by shield-9** [comment]
SSOを経由して自動的にユーザーが登録された場合、IdPが提供するメールアドレスが実際に利用可能かどうかや、セキュアな通信手段なのか (≒サイドチャネルとして有効かどうか) はIdPに依存するので、オプションで無効化できるような実装になっているといいなと思いました。

FYI:
* https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/04-Authentication_Testing/09-Testing_for_Weak_Password_Change_or_Reset_Functionalities
* https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html

**Comment by kaoritokashiki** [comment]
@shield-9 様

コメントありがとうございます！
また、参考リンクまで貼っていただきありがとうございます。

>オプションで無効化できるような実装になっているといいな
こちらも今回の実装のスコープに入れて対応させていただきますね。

**Comment by kaoritokashiki** [comment]
@hanapage 様
@shield-9 様

パスワード機能の実装が完了し、マスターにマージされました。
次のリリース(`v4.3.4`)までお待ちください。

この度は、issueの起票やサポート、誠にありがとうございました!!
今後ともGROWIをよろしくお願いいたします!

**Comment by kaoritokashiki** [comment]
お世話になっております。
バージョン番号に誤りがありましたので訂正させていただきます。失礼いたしました。
次回リリースは **v4.4.0** になります。
よろしくお願いいたします。
