### ISSUE TITLE
編集時にdraw.ioが機能しない

### ISSUE THREAD

**Issue by rw-mnishiyama** [weseek/growi#2932]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7.8.2003|
|GROWI     |4.1.8|
|node.js   |12.16.1|
|npm       |6.13.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

Growiは4.1.0から飛び飛びではありますが、何度かバージョンアップを行っています。
発生に気が付いたのは4.1.6のときで、4.1.8にアップデートしても改善されませんでした。

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10Pro 1909 64bit|
|browser   |Chrome86.0.4240.75|

How to reproduce? (再現手順)
---------------------------

1. ブラウザで新規ページを作成
1. draw.ioのアイコンをクリック→何も起きない。
1. 既にdraw.ioで作成した図の右上にある「編集」をクリック→ページのトップに戻るだけでdraw.ioの編集画面に遷移しない。

What happens? (症状)
---------------------

draw.ioで図を作成しようとして編集画面のツールバーからdraw.ioアイコンをクリックしても編集画面に遷移しません。
また、既に作成した図を右上の「編集」からの編集も行うことができませんでした。

バージョンアップは以下の手順で実施しました。

```
# systemctl stop growi
# cd /usr/local/bin/growi
# git fetch --tags
# git stash
# git checkout v4.1.8
# yarn
# yarn add growi-plugin-lsx
# yarn add growi-plugin-pukiwiki-like-linker
# yarn add growi-plugin-attachment-refs@^2.0.0
# yarn add -D react-images@1.0.0 react-motion
# systemctl start growi
```

What is the expected result? (期待される動作)
-------------------------------------------

- 編集画面のツールバー上のdraw.ioアイコンをクリックすると、図の新規作成ができること
- View画面上でdraw.ioで作図した図の右上「編集」をクリックすると編集が行えること

**Comment by yuki-takei** [comment]
## 再現手順 その2

1. 新規ページを作成(未保存)
1. 本文を以下のように変える
    ```
    # test
    ```
    - 上記1行のみ、空行なし
1. カーソルを `# test` の行末に置き、draw.io アイコンをクリック

## 症状 その2

1. 一応起動するが以下のようなダイアログが表示される
![image](https://user-images.githubusercontent.com/1638767/96835596-c3e60a80-147e-11eb-9392-eae1626ed654.png)
1. 編集は正常にできる

**Comment by yuki-takei** [comment]
@rw-mnishiyama ご報告ありがとうございます。

いただいた再現条件では、症状は確認できませんでした。上にコメントした「再現条件 その2」ではちょっと挙動は違うようですが不具合らしき動作をするのを確認しました。こちらとは違う症状なのですよね？

追加情報として、本文の状態やカーソル位置など教えていただけますでしょうか。
また、ブラウザのコンソールにどのようなエラーが出ているかもチェックいただけると手がかりになると思います。

よろしくお願いいたします。

**Comment by rw-mnishiyama** [comment]
コメントありがとうございます。

お伝えいただいた事象とは異なっています。
現状、Growiを動作させていたテスト環境に障害が発生しており、すぐ確認することができません。
復旧しましたらまた報告させていただきますので、お待ちくださいますようお願いいたします。

**Comment by rw-mnishiyama** [comment]
@yuki-takei 大変時間がかかって申し訳ございません。動作環境を復旧して一旦4.1.6までバージョンが戻っています。

再現手順その２を実行してみたところ、先に報告させていただいたのと同じでdraw.ioは起動しませんでした。
特にエラー表示もなく、そのままです。
過去に作成した図の編集も先の報告通り、ページトップに戻るだけでした。

ChromeでF12押下してConsoleに出ていたのは以下のものになります。
![image](https://user-images.githubusercontent.com/68417096/98192384-48945680-1f5e-11eb-9e4f-4892b6e66a7f.png)

Growiが動いているCentOS7側については、内部LANのみで利用しているのでFirewalldやselinuxは無効にしています。
もし4.1.8や4.1.9のバージョンで試したほうが良ければ確認できます。

以上、よろしくお願いいたします。

**Comment by yuki-takei** [comment]
環境由来っぽいので一度クローズします。

reopen の必要がある場合は再度コメントください。
