### ISSUE TITLE
XSS Filter の影響により drawio ブロックが再編集できなくなる

### ISSUE THREAD

**Issue by aohashi084** [weseek/growi#2933]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows10|
|GROWI     |4.1.8|
|node.js   |unknown|
|npm       |unknown|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 86.0.4240.75|

How to reproduce? (再現手順)
---------------------------

* 以下のように、改行のあるHTMLタグのあとにdrawioを挿入する。

```html
<img  
    src="hogehoge.jpg">
</img>

::: drawio
jZLBboMwDIafJncgartdx7rushOHnSPikUgBo9QU6NM3DKeA0KSdcD7/xvafCJnXw8Wr1nyhBieyRA9CvossS+XpED4TGWfyEkHlrWbRAgp7B4YJ085quG6EhOjItltYYtNASRumvMd+K/tBt+3aqgp2oCiV29Nvq8nwFtlp4Z9gKxM7p8fXOVOrKOZNrkZp7FdInoXMPSLNUT3k4Cbzoi9z3ccf2edgHhr6T0E2F9yU63g3novGuKzHrtEw6RMh33pjCYpWlVO2D9cbmKHahVMawn1/HukGnmBYIZ7nAlgD+TFIOCuP7A0/Dnngc79YnUb/zMrmWKf4dqvnrxcDQsAexOPi9W9u9WLl+QE=
:::
```

What happens? (症状)
---------------------
* drawioが再編集できず以下のエラーメッセージがでる
    * `Not a diagram file (error on line 1 at column 1: Document is empty)`
* 症状を再現したデモサイトのページへのリンクを貼っておきます。
    * [/drawio再編集バグ](https://demo.growi.org/5f8f93e6ff2274004948e0c5)

What is the expected result? (期待される動作)
-------------------------------------------
* 改行のあるHTMLタグのあとにdrawioを挿入したとしても再編集ができる。

**Comment by yuki-takei** [comment]
@aohashi084 ご報告ありがとうございます。
#2558 と同じ症状ですので、draw.io に限った話ではなく、いろいろな不都合が現状の仕様で起こってしまっています。

#2557 による抜本対策をお待ちください。

**Comment by yuki-takei** [comment]
This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。

**Comment by yuki-takei** [comment]
@aohashi084 This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
