### ISSUE TITLE
Bug: Page-saving error after new page creation

### ISSUE THREAD

**Issue by inductor** [weseek/growi#296]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7だったかな|
|crowi-plus|2.4.3|
|node.js   |6.13.1|
|npm       |3.10.10|
|yarn       |1.3.2|
|Using Docker|no|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|no|

https://wiki.infra-workshop.tech/ の環境にて再現

### Client

| item     | version |
| ---      | --- |
|OS        |Mac/Windows|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

記事を新規作成時に画像を1枚アップロードした状態でもう1枚アップロードを試みると必ずエラーになる

**Comment by yuki-takei** [comment]
@kelaductor

上記再現確認してみたのですが正常にアップロードできるようです。

* 開発環境 + `FILE_UPLOAD=local`
* demo.crowi-plus.org + `FILE_UPLOAD=aws`

でテストしましたが、1枚ずつアップロードでは正常動作(2枚ともアップロードされる)、複数枚アップロードではD&D時に「Only 1 file is allowd」と表示されて1枚だけ正常にアップロードされるので仕様通りです。恐れ入りますがより詳細な再現手順と症状、エラー内容などをいただけますでしょうか。

@kainosuke 
Slack で「再現した」と書いてたけど、再現手順覚えてますか？

**Comment by kelaductor** [comment]
ログを共有します。
バックエンドの環境自体僕が握っているわけではないので、詳細が必要であれば僕の方からも管理の人に確認します。
Issueのリンクに書かれたwikiで再現はできているので、そちらで確認いただければ 😓 

```
content.js:4 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:4
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:5
VM219:20 Error: Error.
    at app.e3d8c91ec9954745c05e.bundle.js:1
window.console.error @ VM219:20
value @ app.e3d8c91ec9954745c05e.bundle.js:1
Promise.catch (async)
value @ app.e3d8c91ec9954745c05e.bundle.js:1
value @ app.e3d8c91ec9954745c05e.bundle.js:1
value @ app.e3d8c91ec9954745c05e.bundle.js:1
value @ commons.f41adf716ab095294858.bundle.js:1
l @ commons.f41adf716ab095294858.bundle.js:1
invokeGuardedCallback @ commons.f41adf716ab095294858.bundle.js:1
invokeGuardedCallbackAndCatchFirstError @ commons.f41adf716ab095294858.bundle.js:1
h @ commons.f41adf716ab095294858.bundle.js:1
v @ commons.f41adf716ab095294858.bundle.js:1
b @ commons.f41adf716ab095294858.bundle.js:1
g @ commons.f41adf716ab095294858.bundle.js:1
k @ commons.f41adf716ab095294858.bundle.js:1
Wr @ commons.f41adf716ab095294858.bundle.js:1
Oe @ commons.f41adf716ab095294858.bundle.js:1
batchedUpdates @ commons.f41adf716ab095294858.bundle.js:1
Q @ commons.f41adf716ab095294858.bundle.js:1
De @ commons.f41adf716ab095294858.bundle.js:1

```

**Comment by kwsk8910** [comment]
@inductor @yuki-takei 
デモサイトにてエラー内容再現できました。

**Comment by yuki-takei** [comment]
ってことは local か aws かっていう設定に依らず再現するんですね

**Comment by kwsk8910** [comment]
詳しく報告します。

OS:Windows
ブラウザ：Windows

手順：
デモサイトにログイン。記事を新規作成し、適当な画像（画像１、画像２）を2枚選ぶ。画像１をD&D。正常にアップロードされるので、画像２をD&D。

症状：
画像２が添付されず、ウィンドウの右上にエラーを示す赤いトースターが表示される。
その時にエラーログ：
`[object Error]: {description: "Error.", message: "Error.", stack: "Error: Error. at Anonymous function (https://demo.crowi-plus.org/js/app.7399366456406acd006c.bundle.js:1:47023)"}
description: "Error."
message: "Error."
stack: "Error: Error. at Anonymous function (https://demo.crowi-plus.org/js/app.7399366456406acd006c.bundle.js:1:47023)"

__proto__: Object`

開発環境ではサーバーに異常を示すログは出ませんでした。

**Comment by yuki-takei** [comment]
画像添付だけではなく、新規作成(初めての保存)に続くページのアップデート時に当該事象が起きることを確認。
