### ISSUE TITLE
app.diagrams.netを参照に行かない設定（非ネット接続利用）

### ISSUE THREAD

**Issue by SatoshiKawagucchi** [weseek/growi#2965]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8|
|GROWI     |4.0.11-nocdn |
|node.js   |12.18.3|
|npm       |6.14.6|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |CentOS7.8|
|browser   |Firefox68〜70|

How to reproduce? (再現手順)
---------------------------
社内環境（非ネット接続）でGROWI利用を考えております。
動作を見てると「app.diagrams.net」を参照しているようですが、そもそも非ネット環境なのでアクセスしないようにしたい。

What happens? (症状)
---------------------
つながらないサイトを見に行って切られる動作のように見える。

What is the expected result? (期待される動作)
-------------------------------------------
nocdn版を使っていることもあり、そもそもネット上のライブラリを見に行かないようにしてほしい。

Note
----

**Comment by shield-9** [comment]
どのログやコンソールにどのようなエラーメッセージが出ているのかなどを書くと、状況の理解や再現がしやすいです。

`NO_CDN`の環境だと、現状用意されている手段としては、「同一環境にdiagrams.net (旧draw.io) を構築して、 `DRAWIO_URI` で指定する」という選択肢があると思いますが、これでは要件を満たせないということでしょうか？

それとも、`NO_CDNが有効、かつDRAWIO_URIが空`のときなどに、図の挿入機能を無効にするということでしょうか？

**Comment by yuki-takei** [comment]
shield-9 さん代理で回答いただきとてもありがたいです。

ユーザーさんが情報を見つけにくいのは各機能に関してドキュメント(docs.growi.org)が網羅的でないというのもあると思っていますのでそれは申し訳ないです。一応管理社側でカスタム可能な環境変数一覧は以下にあります。ご確認ください。

https://docs.growi.org/ja/admin-guide/admin-cookbook/env-vars.html

**Comment by SatoshiKawagucchi** [comment]
解決策ご提示ありがとうございます。弊社環境では前者の方法でローカルにDraw.io構築で対処してみます。
一方で構築できない方に対しては参照に行かないようなパラメータ組み合わせも必要になるかもしれません。
