### ISSUE TITLE
複数の単語を利用しての AND 検索方法

### ISSUE THREAD

**Issue by kmyk** [weseek/growi#2971]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |4.1.9|
|node.js   |14.14.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------

1. 検索ボックスに複数の単語を入力する (例 `qkjhwqdsda` `aaaaaa` `fadjfksdufdsaufidsajfasdf`)
1. 検索する (例: <https://demo.growi.org/_search?q=qkjhwqdsda%20%20aaaaaa%20fadjfksdufdsaufidsajfasdf>)

What happens? (症状)
---------------------

- 入力した単語のいずれかひとつ以上を含むページが列挙される (例: 上記の入力例で <https://demo.growi.org/trash/test/aaaaaa>や <https://demo.growi.org/test555> などが報告されるが、これらのページは `fadjfksdufdsaufidsajfasdf` を含まない)

What is the expected result? (期待される動作)
-------------------------------------------

- 入力した単語すべてを同時に含むページが列挙される (例: 上記の入力例では、検索結果は 0 件になる)
  - これは通常期待される挙動であり、また検索ボックスのドロップダウンの説明にも「ページ名 or 本文に word1, word2 の両方を含むページを検索」とある

Note
----

**Comment by yuki-takei** [comment]
@kmyk 

ヘルプが不親切ではあるのですが、Google 同様、ダブルクォート(`"`)で括ったキーワード・フレーズは must 条件となるように実装されています。そのため、期待される動作は `"qkjhwqdsda" "aaaaaa" "fadjfksdufdsaufidsajfasdf"` と入力することで実現できます。

**Comment by kmyk** [comment]
@yuki-takei 

ありがとうございます。仕様を理解しました。
つまり、Google 検索の「含まれない: <del>検索ワード</del>」のような機能があるが、どの検索ワードが無視されたのかについては表示されない (ので混乱してしまった) ということですね。

**Comment by kmyk** [comment]
label は question になっていますし、この挙動は仕様のようなので issue は close しておきます。
