### ISSUE TITLE
Bug: Bookmarks list on other user's page displays current user's bookmarks

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#2974]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |master (2a5687ed166b1333868e0b7fd16e798db29f63d6)|
|node.js   |14.14.0|
|npm       |6.14.8|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 2004|
|browser   |Chrome 86.0.4240.111|

How to reproduce? (再現手順)
---------------------------

1. Create user *A* and *B*
1. [User A] Bookmark some pages
1. [User B] Bookmark some **other** pages
1. [User B] Visit user page of *A*

What happens? (症状)
---------------------

- Bookmarks list of user ***B*** is displayed at user page of *A*

What is the expected result? (期待される動作)
-------------------------------------------

- Bookmarks list of user ***A*** is displayed at user page of *A*

**Comment by itizawa** [comment]
Thank you for reporting Issue.
However, the problem is known to the development team.

It's the expected behavior in the topic branch.
https://github.com/weseek/growi/pull/2950

Thank you for always contributing.

**Comment by shield-9** [comment]
Confirmed fixed in master with #2988
