### ISSUE TITLE
Improvement: Draw.io diagrams not visible in presentation mode

### ISSUE THREAD

**Issue by mgmorcos** [weseek/growi#3006]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS mojave|
|GROWI     |4.1.9|
|node.js   |14.14.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS mojave|
|browser   |Chrome Version 86.0.4240.111 (Official Build) (x86_64)|

How to reproduce? (再現手順)
---------------------------

1. create document
1. add draw.io diagram to document
1. save document
1. enter presentation mode

What happens? (症状)
---------------------

- draw.io diagram is not visible in presentation modal

What is the expected result? (期待される動作)
-------------------------------------------

- draw.io diagram should be visible in presentation modal

**Comment by yuki-takei** [comment]
v6.0.6 solved this.
