### ISSUE TITLE
Text not translated on final slide of presentations

### ISSUE THREAD

**Issue by mgmorcos** [weseek/growi#3007]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS mojave|
|GROWI     |4.1.9|
|node.js   |14.14.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS mojave|
|browser   |Chrome Version 86.0.4240.111 (Official Build) (x86_64)|

How to reproduce? (再現手順)
---------------------------

1. configure language to english
1. create and save document
1. enter presentation mode
1. go to last slide

What happens? (症状)
---------------------

- text on last slide is in japanese ("おしまい")

What is the expected result? (期待される動作)
-------------------------------------------

- text on last slide should be in english ("the end")

**Comment by yusuketk** [comment]
fix on v4.2.0.

[PR#3021](https://github.com/weseek/growi/pull/3021)
