### ISSUE TITLE
Improvement: option to disable "List" footer

### ISSUE THREAD

**Issue by mgmorcos** [weseek/growi#3008]
Allow to disable "List" (list of document paths) at the bottom of View Document screen. This functionality exists for "Timeline" already - it would be great to have the option to disable "List" as well.

**Comment by yuki-takei** [comment]
In the next minor version release v4.2.0, we are going to put some features in a modal window.
It might be good news for the users who have been thought page list at the bottom of page was not necessary.

![image](https://user-images.githubusercontent.com/1638767/98121661-ee11e080-1ef2-11eb-9a78-695562efa346.png)

![image](https://user-images.githubusercontent.com/1638767/98121966-5496fe80-1ef3-11eb-959f-ebb060b4c094.png)

v4.2.0-RC will be released by the end of this week.
Please try it and send feedback to us!
