### ISSUE TITLE
インデントされたCode Blockの各行の高さがインデントされていない物よりも高くなる

### ISSUE THREAD

**Issue by AstroTaka** [weseek/growi#3056]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.0.4|
|GROWI     |4.1.10|
|node.js   |14.15.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 Pro 64bit|
|browser   |Google Chrome 86.0.4240.183|

How to reproduce? (再現手順)
---------------------------

ページ作成で以下を入力する。（githubにmarkdownとして認識されないように全角スペースと全角の「＊｀」を使用しています）

＊　 TEST　　
　　｀｀｀
　　TEST1
　　TEST2
　　｀｀｀
｀｀｀
TEST3
TEST4
｀｀｀

What happens? (症状)
---------------------

プレビュー結果、および表示画面で「TEST1,TEST2」の行の高さが「TEST3,TEST4」の行の高さよりも高くなります。

![growi](https://user-images.githubusercontent.com/53452427/98453410-f2acf200-219b-11eb-837b-cb63e351e418.PNG)

What is the expected result? (期待される動作)
-------------------------------------------

- 表示させるコードの行数が多くなると間延びしてしまうのでインデントに関わらず「TEST3,TEST4」の様に行の高さは詰めて表示されるべきと思います。以下は[https://stackedit.io/](https://stackedit.io/)に同じ物を入力した場合の結果です。
 
![image](https://user-images.githubusercontent.com/53452427/98453451-749d1b00-219c-11eb-9b21-6934c6960905.png)

**Comment by yuki-takei** [comment]
@AstroTaka ご報告ありがとうございます。修正しました。

v4.1.12 or v4.2.0 のリリースをお待ちください。

**Comment by AstroTaka** [comment]
ありがとうございます！
