### ISSUE TITLE
Enhancement: バックアップ / リストア 機能の追加

### ISSUE THREAD

**Issue by Angola** [weseek/growi#308]
現状はmongodump などで自前で行うしかないので、crowi-plus の wikiデータのバックアップ / リストア を管理画面上の機能として実装してほしいです。
下記は理想案です。

### バックアップ機能
- バックアップ先にはs3 を利用。
- スケジュールを入力し、指定時間によりバックアップ開始。
- S3指定バケットに自動保存。

### リストア機能
- S3バケット上にある任意のバックアップデータを選択し、リストア

上記が機能として実装されれば、サーバー間のデータ移行もかなり楽になるため、是非実装してもらいたいです。

**Comment by yuki-takei** [comment]
@Angola 

docker-compose での解決策なら進行中で…
https://github.com/weseek/mongodb-awesome-backup

現状これは cli で一発バックアップ・リストアは可能な shell script。
これを docker-compose の example を参考にして定期的に実行できるようにしようという施策はこれから進めようという話になりました。

一方アプリ側での実装は考えたことなかったが、リストアのオプション何種類か用意しないといけないと思う。

* ページだけリストアきれば良しとする
    * 誰に作られたかとかは存在しないユーザーになる
* ユーザーごとリストア対象にする
    * 既存の同名 ユーザーとかどうする？
* 特定の既存ユーザーを author にするよう書き換える
    * 工数が…

**Comment by you-at4** [comment]
Growi.Cloudがオープンベータになったので、
オンプレのGrowiからGrowi.Cloudに移行しようと考えたのですが、
Pageの一括移行方法がわからなくて保留しています。

やはりGrowiの管理画面等からWiki全体のExport/Importできるような機能がほしいです。
また、全体だけでなくページ単位でもExport/Importできるとありがたいです。

**Comment by yuki-takei** [comment]
@you-at4 ご意見ありがとうございます。
弊社も GROWI.cloud の利用者拡大を考えた時に管理画面からのバックアップ/リストアは優先順が高くなるなという認識はありました。
とりあえずまだ GROWI.cloud のオープンβ版にバグが多くてプレスリリースを打てていないので、そちらを一段落させてからとりかかるつもりです。

**Comment by yuki-takei** [comment]
@Angola @you-at4 
大変長らくお待たせ致しました。v3.5.14 でページデータのみ、エクスポート・インポートが可能になりました。
添付ファイルやユーザー情報は未対応なので完全な移行には不十分ですが、今後その辺りも埋めていきます。お時間あるときにご試用いただければ幸いです。

**Comment by you-at4** [comment]
ありがとうございます。
試してみます。
