### ISSUE TITLE
Feature: Display icon around the cursor if the function to reform markdown table will action after the enter key is hit

### ISSUE THREAD

**Issue by ryu-sato** [weseek/growi#310]
refs: #299 

# TODO

Display icon around the cursor if the function to reform markdown table will action after the enter key is hit.

# Condition of the function which reform markdown table

- The enter key is hit 
    - when the end of line.
    - without shift key.
    - when editing markdown table. (like `| title col1 | title col2 |`)

**Comment by yuki-takei** [comment]
fixed by #374
