### ISSUE TITLE
Question: 特定の文字を含む検索ワードで検索に失敗する

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#3116]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04.1 LTS|
|GROWI     |4.1.11|
|node.js   |14.15.0|
|npm       |6.14.8|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.7|
|browser   |Chrome 86.0.4240.198|

How to reproduce? (再現手順)
---------------------------
1. 「口腔内」で検索する

What happens? (症状)
---------------------
- 「内」で検索した結果と同等になる

What is the expected result? (期待される動作)
-------------------------------------------

- 「口腔内」に完全一致したワードを含む記事のみ検索結果に表示される

Note
----

- 「口腔」での検索は問題なし
- 「腔」単体ではNo page found with "腔"になる
- 「腔内」で「内」と同じ結果になる。
- 「腔」の前にある文字列は無視され、後にある文字列で検索がされるようです。
  - 例えば「口腔アカウント」では「アカウント」で検索されます。
- 「腔」の他に「噂」「免」とかもありました。漢字コード周りで問題のある文字が絞り込めるかもしれません。
  - 「免」について追記
    - 「免税」というワードがある記事について「税」で検索すると出てこなかったので検索される側にも問題がありそうです。
    - 「税」で検索すると出てこないのに「免税」で検索すると出てくるので複雑です。

--

**Comment by yuki-takei** [comment]
日本語に関しては kuromoji tokenizer を使っているのと、デフォルトでは完全一致するかどうか(完全に含むかどうか)で引っかけているのではなく、`function_score` query を用いたスコアによる評価を行っています。

そのため、
>「口腔内」に完全一致したワードを含む記事のみ検索結果に表示される
は仕様ではありません。

ただし、ダブルクォーテーションで囲んだキーワードを使った検索はスコアによる評価ではなく、must, must_bot クエリを用いていますので、そちらの方が「期待される動作」には近いと思います。一度試してみていただけますでしょうか。

**Comment by hanapage** [comment]
遅くなりました。うまくいかなかった場合のみダブルクォーテーションで囲んで検索することで問題は解消できそうです。ありがとうございました。
