### ISSUE TITLE
Question: $lsx(/) (-> Network Error)が出る原因の切り分けを知りたい

### ISSUE THREAD

**Issue by panp2000** [weseek/growi#3167]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|GROWI     |4.1.3|
|node.js   |14.8.0|
|yarn       |1.22.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |Google Chrome 87.0.4280.67|

How to reproduce? (再現手順)
---------------------------

1. トップページを表示する

What happens? (症状)
---------------------

- `Contents`内の`All Pages`の表示が`$lsx(/) (-> Network Error)`となる
- `Contents`内の`/Sandbox`の表示が`$lsx(/Sandbox) (-> Network Error)`となる

What is the expected result? (期待される動作)
-------------------------------------------

- 以前は両方とも正常に表示されていたのですが、気がついたら上記のようになっていました
- `Dockerfile`は`FROM weseek/growi:latest`で時々`build`しているので、どこのタイミングで起こったのかよくわかりません
- ネットワーク構成はHOSTのLAN・Docker内共々使い始めから一切変更していません
- 問題の切り分けがしたいので、上記の`Network Error`表示の`Network`が何を指しているのかが知りたいです

Note
----

- 大変便利に使わせていただき感謝しております。
- 以前に`elasticsearch`が正常に動かなくなり、一時的に`mongo`を4.0にして復旧コマンドを実行させました。現在は`mongo:3.6`イメージを使用して正常に動いています

**Comment by yuki-takei** [comment]
@panp2000 

箇所としては以下の部分になります。

https://github.com/weseek/growi-plugin-lsx/blob/master/src/client/js/components/Lsx.jsx#L60

クライアントサイド(ブラウザ)からの API の実行で Network Error となっている、ということなので、まずは Chrome のデベロッパーツールを開き、Network タブで `/_api/plugins/lsx` へのリクエストとレスポンスがどうなっているかを確認してみてください。

**Comment by panp2000** [comment]
ありがとうございます。
調べたところヘッダが以下の様になっておりました。

```
Request Method: GET
Status Code: 304 Not Modified
Remote Address: [::1]:3030
Referrer Policy: strict-origin-when-cross-origin
```

`docker-compose.yml`では
    ports:
      - 3030:3000

としています。`アプリ設定`では`サイトURL設定`で`http://localhost:3030`を指定しています。

その後safari、FirefoxとOperaで試したところどれも正常に表示されました。

手元の環境だとMacのChromeでのみ表示されません。Chromeのバージョンは `87.0.4280.88（Official Build） （x86_64）`です。

**Comment by panp2000** [comment]
先日のバージョンアップでリビルドしたところ、元のように正常に表示されるようになりました。

**Comment by yuki-takei** [comment]
@panp2000 ご報告いただいた症状を顧みても今回の問題の原因はなお定かではないのですが、ひとまず正常動作するようになったということでなによりです。本 Issue は閉じます。
