### ISSUE TITLE
Bug: heroku: v4.x.x への upgrade に失敗する

### ISSUE THREAD

**Issue by ogiekako** [weseek/growi#3194]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | heroku |
|GROWI     |3.8.2|
|node.js   |12.20.0|
|npm       |6.14.9|
|Using Docker| ? |
|Using [growi-docker-compose][growi-docker-compose]| ? |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

It shouldn't matter, but

| item     | version |
| ---      | --- |
|OS        |Mac|
|browser   |Chrome 87.0.4280.67|

How to reproduce? (再現手順)
---------------------------

1. 現在，growi v3.8.2 を heroku 上で走らせています．これは，https://docs.growi.org/ja/admin-guide/getting-started/heroku.html#%E3%82%A2%E3%83%83%E3%83%97%E3%82%B0%E3%83%AC%E3%83%BC%E3%83%89 に従って，v3.5.25 から upgrade したものです．
1. これを，同ドキュメントに従って，v4.x.x に upgrade しようとしたところ失敗します．具体的には，v4.0.0 v4.0.11 v4.2.2 いずれも失敗します．v4.0.0 で試した場合を示します．
    ```bash
$ git co -b growi-v4.0.0 refs/tags/v4.0.0
$ git push heroku growi-v4.0.0:master --force
    ```

What happens? (症状)
---------------------

- Build に失敗し，git push が成功しません．

全体の Build Log は https://gist.github.com/ogiekako/52c52a59ba89ef21e59ed7115e84ab48 になります．

実際にエラーとなっているのは，以下の行かなと思います．
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-focus-lock/UI' in '/tmp/build_9f2b5429/node_modules/react-focus-on/dist/es2015'
```

What is the expected result? (期待される動作)
-------------------------------------------

- git push に成功する

**Comment by ryu-sato** [comment]
@ogiekako `app.json` で指定されている環境変数(env)が Heroku の Config Vars で指定されていないかもしれません。
https://github.com/weseek/growi/blob/7a588bcb041aae6aae98c2c0e95bcc422592be81/app.json#L28-L32

エラーメッセージはパッケージ不足のようですので、特に `ADDITIONAL_PACKAGES` を確認してから再度試してみるとよいと思います。

**Comment by yuki-takei** [comment]
続報なさそうですのでクローズします。
