### ISSUE TITLE
Question: README.md の "Deploy to Heroku" を行っても Deploy に失敗する

### ISSUE THREAD

**Issue by ryu8179** [weseek/growi#3202]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |heroku|
|GROWI     |4.2.2|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows10|
|browser   |Google Chrome: 87.0.4280.88|

How to reproduce? (再現手順)
---------------------------

1. heroku にログインする
1. https://github.com/weseek/growi にアクセスする
1. README.md の冒頭にある "Deploy to Heroku" ボタンを押下する
1. heroku ページ下部にある "Deploy app" ボタンを押下する

What happens? (症状)
---------------------

- `Configure environment` に下記メッセージが表示され、 Deploy app に失敗する
```
There was an issue setting up your app environment.
Couldn't find either the add-on service or the add-on plan of "mongolab".
```

What is the expected result? (期待される動作)
-------------------------------------------

- heroku への Deploy に成功し、ブラウザ上で growi の動作を確認出来る

**Comment by yuki-takei** [comment]
@ryu8179 
Heroku の mongolab アドオンは提供されなくなった模様です。

https://devcenter.heroku.com/changelog-items/1823
https://mikan.github.io/2020/07/11/migrate-heroku-mlab-to-mongodb-atlas/

そのため、Heroku で簡単に GROWI を起動できる手段はなくなってしまいました :cry:
代替手段を模索いただければと思います。オンプレであれば [weseek/growi-docker-compose](https://github.com/weseek/growi-docker-compose) の利用、SaaS もアリなのであれば https://GROWI.cloud が簡単です。

**Comment by ryu8179** [comment]
@yuki-takei 
返信ありがとうございます！
Heroku で簡単に起動出来なくなった事 & wontfix である事、了解致しました。

代替手段を検討致します。
ありがとうございます。  🙇
