### ISSUE TITLE
How to set up on the left Custom Sidebar

### ISSUE THREAD

**Issue by sevenjay** [weseek/growi#3215]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.1.11 on growi.cloud|

How to reproduce? (再現手順)
---------------------------
I use the method in https://genchan.net/it/server/28538/, but it does not work.
Is there a tutorial to implement it?
Could it be set a default index? not Recent Changes
And could it be implemented like `$lsx(../)`, just list the up level in Custom Sidebar?

**Comment by yuki-takei** [comment]
@sevenjay 
Thank you for your interest.

> I use the method in https://genchan.net/it/server/28538/, but it does not work.

The way of the page looks like a hack for GROWI v3.x.
It might not work on v4.x.

> Is there a tutorial to implement it?

If you are a user or an administrator, it does not exist.
If you are a developer and are going to implement it and send us a PR, refer [CustomSidebar.jsx](https://github.com/weseek/growi/blob/master/src/client/js/components/Sidebar/CustomSidebar.jsx).

> Could it be set a default index? not Recent Changes

Yes, but it is needed to implement the switchhing mechanism that the users choose what menu is set as a default.
See [NavigationContainer](https://github.com/weseek/growi/blob/master/src/client/js/services/NavigationContainer.js#L34).

> And could it be implemented like $lsx(../), just list the up level in Custom Sidebar?

Yes it is, maybe.

**Comment by yuki-takei** [comment]
@sevenjay 
Sorry I made you wait. Custom sidebar is now available since v4.2.12.
Try it and feedback to us if you notice anything.
