### ISSUE TITLE
PlantUMLを記述するときにXSS対策により<>で囲まれた部分が無視されてしまう

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#3225]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |20.04.1 LTS|
|GROWI     |4.2.2|
|node.js   |14.15.1|
|npm       |6.14.8|
|Using Docker| no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.7|
|browser   | Google Chrome 87.0.4280.88|

How to reproduce? (再現手順)
---------------------------

XSS対策をONにして <>を含むPlantUMLを記述する

```plantuml
@startuml
class Hoge {
    - fugas : List<T>
    --
    + getFugas() : List<T>
}
@enduml
````

What happens? (症状)
---------------------

- 本来List&lt;T&gt;とレンダリングされる箇所がListになる
- 改行時のカーソル初期値が行頭からずれて右にずれていく

What is the expected result? (期待される動作)
-------------------------------------------

- List&lt;T&gt;とレンダリングされる
- 改行時のカーソル初期値が行頭に来る

Note
----

- XSS対策をOFFにすると正常に表示されます。

**Comment by yuki-takei** [comment]
既知の問題になります。
#2557 での抜本対策をお待ちください。

その他の問題もいろいろ積み重なっているので、近々手を付けたいとは思っていますが、実装完了がいつになるかは今のところ未定です。

**Comment by yuki-takei** [comment]
アップデート : https://github.com/weseek/growi/pull/6604

2022年冬リリース予定の GROWI v6 をお待ちください

**Comment by yuki-takei** [comment]
@hanapage This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
