### ISSUE TITLE
Growi4.2.3でAPI経由のpages.createが出来ない

### ISSUE THREAD

**Issue by AnaTofuZ** [weseek/growi#3237]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.1.0|
|GROWI     |4.2.3|
|node.js   | growiのdocker イメージと同様|
|npm       |growiのdocker イメーと同様|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | mac OS Big Sure|
|browser   | httpie 2.3.0 |

How to reproduce? (再現手順)
---------------------------

1. 存在していないパスに対して`pages.createを発行
    ```bash
    $http POST https://growi.cr.ie.u-ryukyu.ac.jp/_api/pages.create  access_token='' path='/user/anatofuz/note/2020/12/14' body='#test' 
    ```
(`_api/v3/pages.create`にしても変わらず)

What happens? (症状)
---------------------

- jsonでなくエラーのHTMLが帰ってくる

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /_api/pages.create</pre>
</body>
</html>
```

What is the expected result? (期待される動作)
-------------------------------------------

- pages.createの成功及びjsonの返却

Note
----

- 既にページを作った場合、pages.updateは問題なく動作しました
-  4.2.2では動いていました

**Comment by itizawa** [comment]
Issue を立てていただきありがとうございます。

大変申し訳ございませんが該当の エンドポイントは
v4.2.3 より ` /_api/v3/pages/create` に移動しました。
こちらで再度お試しください。

v5.0.0 では、next化を行う予定です。それに伴って api も v3 に順次移行していくかと思われます。
ご不便をおかけしますが、何卒よろしくお願いいたします。

**Comment by AnaTofuZ** [comment]
ありがとうございます! エンドポイントの修正了解しました!

**Comment by AnaTofuZ** [comment]
すいません。`/_api/v3/pages/create`に変更しましたが、変わらずですね...

```
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /_api/v3/pages/create</pre>
</body>
</html>
```

**Comment by AnaTofuZ** [comment]
再openはできなさそうなのでログを残しておきます

**Comment by itizawa** [comment]
@AnaTofuZ
すいません、記述を間違えていました。

`http POST https://growi.cr.ie.u-ryukyu.ac.jp/_api/pages/`
こちらでお試しください。

**Comment by AnaTofuZ** [comment]
`/_api/pages`も同様にダメでした

```
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /_api/pages</pre>
</body>
</html>
, invalid character '<' looking for beginning of value: invalid character '<' looking for beginning of value
```

**Comment by AnaTofuZ** [comment]
`http POST https://growi.cr.ie.u-ryukyu.ac.jp/_api/v3/pages ` だといけました!!

**Comment by itizawa** [comment]
ご迷惑をおかけしました。 
Docs はこれから整備していきます...

今後とも GROWI をよろしくお願いいたします。

**Comment by AnaTofuZ** [comment]
ありがとうございます。何か協力できそうならお手伝い致しますのでよろしくお願いします!。issueは閉じさせていただきます。
