### ISSUE TITLE
Incorrect display of oldest changes

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#3238]
Environment
------------

### Host

GROWI on GROWI.cloud

| item     | version |
| ---      | --- |
|OS        |---|
|GROWI     |4.2.3|
|node.js   |~~x.y.z~~|
|npm       |~~x.y.z~~|
|Using Docker|~~yes/no~~|
|Using [growi-docker-compose][growi-docker-compose]|~~yes/no~~|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows 10|
|browser   |Google Chrome 86.0.4240.198|

How to reproduce? (再現手順)
---------------------------

1. Update a page over 20 times.
1. Display history view.
1. Scroll down to the page's oldest changes.

What happens? (症状)
---------------------

- In the oldest changes, the entire page content appears to have been added

What is the expected result? (期待される動作)
-------------------------------------------

- Diffs from the previous revision are displayed correctly.

Note
----

-

**Comment by itizawa** [comment]
Thank you for reporting the Issue.

The modified version will be released in v4.2.4.
Please wait for the next release
