### ISSUE TITLE
blockdiagが描画されない

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#3243]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |CentOS 7.8.2003|
|GROWI     |4.2.3|
|node.js   |14.15.1|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows10|
|browser   |87.0.4280.88|

How to reproduce? (再現手順)
---------------------------
```
::: blockdiag
  A -> B -> C;
  B -> D;
:::
```
のようなマークアップを使用する。

What happens? (症状)
---------------------
生のURLが表示され、描画されない。

What is the expected result? (期待される動作)
-------------------------------------------
図が描画される

Note
----
日々活用させていただいております。ありがとうございます。

先方の事情はわかりませんが、今月に入ったあたりから https://blockdiag-api.com にアクセスできなくなっているのが原因だと思われます。
https://github.com/kaishuu0123/blockdiag-api　
のソースから自前でapiサーバーを立てれば回避できるのかなと思いましたが、Growi側に外部変数などを経由してそのURLを指定する方法はありますでしょうか。

**Comment by hide-o-mvd** [comment]
表示されるようになっておりますので、取り下げます。

**Comment by kmet9** [comment]
[https://blockdiag-api.com] は証明書が切れたままであるため、いまだに上記の現象が発生しています。
上記URLにアクセスした際に、ブラウザで「警告を無視して表示する」等の選択をすると、
それ以降は、そのブラウザ上ではGrowiのblockdiagが表示されるようにはなりますが、根本解決になっておりません。

@hide-o-mvd さんのおっしゃるように、問い合わせ先を自前のAPIサーバに設定する方法はありますでしょうか？

**Comment by hide-o-mvd** [comment]
今アクセスすると証明書エラーが出ますね。
数日前は正常にアクセス出来たように思いクローズしましたが、記憶違いだったかもしれません。

**Comment by yuki-takei** [comment]
@hide-o-mvd 一旦 close します。再現条件確定しましたら reopen してください。
