### ISSUE TITLE
"pages.get" API can't get pages which are protected by group-based properly.

### ISSUE THREAD

**Issue by emadurandal** [weseek/growi#3245]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|Environment        | Growi.cloud|
|GROWI     |4.1.11|

### Client

| item     | version |
| ---      | --- |
|OS        | Window10 WSL2 Ubuntu|
|Client Program   | Python3 request package|

How to reproduce? (再現手順)
---------------------------

1. Make some pages on Growi.
2. Set group-based restrict access to the pages.
3. Try to get info by REST API "pages.get" with an administrator's access token as following:

    ```
    https://xxx.example.com/_api/pages.get?access_token=<urlencoded_access_token>&page_id=<id_of_the_page>
    ```

    The administrator account should belong to the group for this test.

What happens? (症状)
---------------------

- I fail to get the page info from "pages.get" API.
- The "pages.get" API returns this response: `{"ok":false,"error":"Error: Page \'<page_id>\' is not found or forbidden"}`

What is the expected result? (期待される動作)
-------------------------------------------

- The "pages.get" API returns a right infomation of the page.

**Comment by itizawa** [comment]
@emadurandal 
Thank you for reporting the Issue.

The modified version will be released in v4.2.4.
Please wait for the next release.
