### ISSUE TITLE
Question: GrowiでのMathJax数式が動作しない

### ISSUE THREAD

**Issue by YoshitakaMo** [weseek/growi#3259]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 8.1.1911|
|GROWI     |4.2.4|
|node.js   |14.15.0|
|npm       |6.14.8|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 11.1 or macOS 10.15.7|
|browser   |Google Chrome 87.0.4280.88 or Safari 14.0.2|

How to reproduce? (再現手順)
---------------------------

1. 4.2.4にアップデートした前後でMathJaxによる数式レンダリングが機能しなくなったように感じる。はじめは自前のサーバー上で運用している（上記Host参照）で動作しないことを確認したが、Growi の Versionを4.2.2や4.1.12に変更してみても変化がなかった。また、https://demo.growi.org/Sandbox/Math や https://growi.cr.ie.u-ryukyu.ac.jp/Sandbox#%00%20Math などGoogle検索で誰でも閲覧できるページでの数式レンダリングも動作していないようだった。当クライアントからは https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js にアクセスでき、スクリプトを正しく取得できていると思われる。

What happens? (症状)
---------------------------

数式レンダリングが動作しない

What is the expected result? (期待される動作)
---------------------------

数式が正しく表示される。

**Comment by yuki-takei** [comment]
まだ調べ切れていないけれどメモ

## 経緯
https://github.com/weseek/growi/commit/c6a817064185eddbfbc30a08862beedc18a42e28

## Upgrading from v2 to v3
http://docs.mathjax.org/en/latest/upgrading/v2.html#changes-in-the-mathjax-api

**Comment by yuki-takei** [comment]
@YoshitakaMo 
ご報告ありがとうございました。再現を確認し、修正を行いました。
v4.2 系は v4.2.5 リリース、
v4.1 系は v4.1.13 リリースをお待ちください。
