### ISSUE TITLE
Bug: iOSでログイン画面が崩れる

### ISSUE THREAD

**Issue by izmth** [weseek/growi#330]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7 |
|GROWI     | 3.0.2 |
|node.js   | 6.14.1 |
|npm       | 4.6.1 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | iOS 11.0.3 |
|browser   | Safari |

How to reproduce? (再現手順)
---------------------------
1. ログイン画面にアクセスする。

What happens? (症状)
---------------------
表示が崩れる。
![image uploaded from ios](https://user-images.githubusercontent.com/28652907/38455400-8221ee82-3ab2-11e8-8b5e-c1537b24deac.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 正常なログイン画面が表示される。

Note
----
- iOS9でも同じような症状が現れる
- Chromeなどを使用しても同じ

**Comment by yuki-takei** [comment]
@izmth 再現確認しました。修正まで今しばらくお待ちください。
