### ISSUE TITLE
Bug: ユーザー管理画面の「招待をメールで送信」にチェックを入れられない

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#331]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.0.2|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Google Chrome|
|browser   |65.0.3325.181|

How to reproduce? (再現手順)
---------------------------

1. ユーザー管理 (/admin/users) を開き「新規ユーザーの招待」をクリック

What happens? (症状)
---------------------

- 「招待をメールで送信」のチェックボックスにチェックが入らない
- 招待メールが送信されない

What is the expected result? (期待される動作)
-------------------------------------------

- 「招待をメールで送信」のチェックボックスのオンオフができる
- チェックがオンの場合に招待メールが送信される

Note
----

- Microsoft Edge 41.16299.248.0、Firefox 59.0.2でも同様の症状が発生している
- SMTPサーバー設定は正常に行われている

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。再現を確認しました。
修正してリリースしますので今しばらくお待ちください。
