### ISSUE TITLE
1M以上のサイズのファイルを添付できない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#3311]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04.1 LTS|
|GROWI     |4.2.5|
|node.js   |14.15.4|
|npm       |6.14.10|
|Using Docker|no|

### Client

| item     | version |
| ---      | --- |
| macOS        | 10.15.7 |
| Google Chrome   | 87.0.4280.141|

How to reproduce? (再現手順)
---------------------------
- 編集画面で1M以上の画像ファイル(png, gif等)を添付する

What happens? (症状)
---------------------
- 下記のようなエラーダイアログが表示され、添付ファイルのアップロードに失敗する

```
Error
Request failed with status code 413
```

What is the expected result? (期待される動作)
-------------------------------------------
- 添付ファイルのアップロードが成功する

Note
----
- 添付ファイルの保存先はローカルです
- 動画ファイル(mp4)など別の種類のファイルであれば成功するものもある
- pngやgifなど1Mあたりを超えるとエラーが表示されるようになります

**Comment by yuki-takei** [comment]
@hanapage 
GROWI のデフォルト設定では、アップロードの容量制限は設けていないです。(`MAX_FILE_SIZE`)

https://docs.growi.org/ja/admin-guide/admin-cookbook/env-vars.html

リバースプロキシを利用している場合、そちらの制限で 413 が返っていないかを調査してみてください。

**Comment by hanapage** [comment]
解決しました。

3000番ポートを80番でアクセスさせるために使用していたnginxのclient_max_body_sizeの設定がデフォルト値(1M)だったのが原因だったようです。お手数をお掛けいたしました。
