### ISSUE TITLE
Bug: 招待を受けたユーザーがアカウントの作成を完了できない

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#332]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.0.2|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Google Chrome|
|browser   |65.0.3325.181|

How to reproduce? (再現手順)
---------------------------

1. ユーザー管理 (/admin/users) を開き「新規ユーザーの招待」をクリック
1. メールアドレスを入力して「招待する」をクリックし、仮パスワードを発行
1. 上で入力したメールアドレスと発行されたパスワードでログイン
1. 必要事項を入力し「Create」をクリック

What happens? (症状)
---------------------

- /installer/activateInvited に転送されるが下記メッセージが表示され、アカウントの作成が完了できない
```
Cannot POST /installer/activateInvited
```

What is the expected result? (期待される動作)
-------------------------------------------

- 正常にアカウントの作成が行われる

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。

こちらは v3.0.0 でレイアウト変更に伴ってソースコードが意図しない形に書き換わっていたのを確認したので、元に戻しました。とりいそぎの変更なので再現確認していないのですが…もし直ってなかったらまた書き込みいただければと思います。

**Comment by k84rc** [comment]
@yuki-takei 修正版のリリースありがとうございます。v3.0.3 にて正常に動作することを確認いたしました。
