### ISSUE TITLE
mathjax の編集中に，rendering されていない状態が表示される

### ISSUE THREAD

**Issue by ryolate** [weseek/growi#3365]
Environment
------------

### Host

growi.cloud を使用

### Client

| item     | version |
| ---      | --- |
|OS        |Mac|
|browser   | Google Chrome 88.0.4324.96 (Official Build) (x86_64) |

How to reproduce? (再現手順)
---------------------------

1. ページを編集状態にする（画面の左に編集画面，右側にプレビューが表示されている状態）
2. MathJax rendering にチェックを入れる
3. $$\sum_{i=0}^{10} i$$ などと入力する（数式自体はなんでもよい）．右側に，rendering された数式が表示されている
4. x を入力し，$$\sum_{i=0}^{10} ix$$ とする（数式を変更するならば具体的な入力内容はなんでもよい）

What happens? (症状)
---------------------

- 右側に一瞬，rendering されていない数式（生のテキスト）が表示され，その後 rendering された数式が表示される

What is the expected result? (期待される動作)
-------------------------------------------

- rendering されていない状態の数式は表示されない

Note
----

- 数式を編集するたびに発生するため，数式を多用する文章を書いていると，この現象はかなりストレスフルに感じます．

**Comment by yuki-takei** [comment]
@ryolate 
ご相談いただいた症状ですが、現時点では仕様となります。
下部の歯車メニューにプレビューでのレンダリングを停止するためのオプションがありますので、そちらをご利用いただければと思います。

将来的には #2557 次第で挙動が変わることもあるかもしれません。

**Comment by yuki-takei** [comment]
@ryolate This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
