### ISSUE TITLE
特定グループのみ公開のページのリストアップについて

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/growi#339]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.4.1708 (Core)|
|GROWI     |3.0.3|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Vivaldi 1.14.1077.60 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1. グループ管理で新規グループ grp を作成する
1. 公開ページ「public_A」配下に、ページ「private_B」を作成する
1. 「private_B」の公開範囲を「特定グループのみ」とし、grp を指定して保存する
1. ポータルトップに lsx プラグインを用いて `$lsx(/public_A)` と記載し保存する

What happens? (症状)
---------------------

- grp に所属するユーザがポータルトップにアクセスした際、lsx プラグインでprivate_Bがリストアップされない
- grp に所属するユーザがpublic_Aのページを表示した際、画面最下部「List」にprivate_Bがリストアップされない

What is the expected result? (期待される動作)
-------------------------------------------

- grp に所属するユーザがポータルトップにアクセスした際、lsx プラグインでprivate_Bがリストアップされる
- grp に所属するユーザがpublic_Aのページを表示した際、画面最下部「List」にprivate_Bがリストアップされる

**Comment by TatsuyaIse** [comment]
どういう方針で行こうか要検討
1. Page の一覧を検索するときに、1つのクエリで一度に拾えるように改修を入れる
　・MongoDB でテーブル(コレクション)を結合等できるのか要調査(できればこちらがいい。。)
2. Page の閲覧権限範囲とUserを元に検索する現実装 + グループ関連の関連性を元に Page を検索する実装を追加 の2回に分けてDB検索を行うのか。
　・こっちだと、リスト表示されるときにソート順に不整合が発生するという問題が発生してしまう可能性がある(DBから取得したドキュメントの一覧を、一旦ひとつのリストにまとめてからソートするという手段を用いれば問題は解消できるが、できればその手は採用したくない。)

**Comment by yuki-takei** [comment]
@takuma-watanabe @TatsuyaIse 
こちらの要望ですが、「What is the expected result? (期待される動作)」通りの挙動は未実装ながら、「とりあえずリストアップされる」という挙動を v3.1.1-RC に追加しました。それにより、以下のような挙動になりました。

Before
-------
* 編集権限のあるグループに所属するユーザーの場合は、リスト表示はされないがURL直打ち等のアクセスで閲覧・編集が可能
* 上記グループに所属していないユーザーの場合は、リスト表示もされないし閲覧・編集も不可能

After
------
* 編集権限のあるグループに所属するユーザーの場合は、リスト表示され、かつ閲覧・編集が可能
* 上記グループに所属していないユーザーの場合は、リスト表示されるものの、閲覧・編集は不可能

これにより Group ACL 設定したページ群は隠蔽されることがなくなります。タイトルだけはグループ外にも出るという挙動になり賛否あるかとは思いますが、一旦こちらでユーザーさん達の反応を見ようと思います。

**Comment by kanayama-ACN** [comment]
こんにちは、Growiを社内で便利に利用させて頂いております。
この件、現状の挙動は直感的ではないため、ユーザーがちょっと混乱してしまいました。問い合わせ毎に事情説明するなど運用でカバーしてますが、できれば @takuma-watanabe さんがおっしゃる挙動が実現できればと思っており、要望としてコメントさせていただきます。

**Comment by yuki-takei** [comment]
@takuma-watanabe @kanayama-ACN ご意見ありがとうございます。
#535 で対応します。
