### ISSUE TITLE
Feature request: Markdownエディタのタブ幅をカスタマイズできるようにしてほしい (indentation width of Markdown editor should be adjustable)

### ISSUE THREAD

**Issue by tats-u** [weseek/growi#3439]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04 (Host)|
|GROWI | 4.2.8
|node.js|14.15.4|
|npm       |6.14.10|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Firefox|
|browser   |85.0.2|

How to reproduce? (再現手順)
---------------------------

1. Start to edit (create a new page or edit the existing one)
1. Add `- foo`
1. Press Enter key

What happens? (症状)
---------------------

- New line will starts with additional 4 spaces in any case (どんな場合も新しい行が4スペース付加されて始まってしまう)

```
- foo⌶
```

↓ Enter

```
- foo↵
□□□□⌶
````

(`⌶`: Current position / `↵`: U+00A0 / `□`: U+0020)

What is the expected result? (期待される動作)
-------------------------------------------

- The new line can start with additional 2 spaces.
- The width can be adjusted with surrounding lines, or global or editor settings.

Note
----

2 spaces is recommended by [markdownlint](https://github.com/DavidAnson/markdownlint).

- 参考 / Reference: <https://github.com/DavidAnson/markdownlint/blob/v0.22.0/doc/Rules.md#md007>

**Comment by tats-u** [comment]
おそらくここを変えればいけますね
https://github.com/weseek/growi/blob/f37fe2870e2c8b4b203478870fc95b4cc7970a8c/src/client/js/components/PageEditor/CodeMirrorEditor.jsx#L845-L846

**Comment by tats-u** [comment]
自動検出を利用する場合は https://www.npmjs.com/package/detect-indent などが必要です。
`yarn install (-D)`してもよろしいでしょうか。
また、インデント幅はどこで・どのように決定・管理するのかの仕様を決定していただく必要があります。
- 編集者にどこまで裁量を与えるか
  1. テーマやキーバインドのところで変更可能
  2. 1.のところに値だけ表示
  3. 現在通り不可視
- 初期値に管理者がどこまで介入できるか
  1. 完全にシステム・ユーザ任せ（管理オプションを作らない）
  2. インデントがなかったときのフォールバック値のみ設定
  3. 特定値に強制
  4. 2.・3.を選択可能
- 管理画面の「マークダウン設定」のどこにインデント設定を挿入するか
  1. 最上段
  2. 「Line Break設定」の直下
  2. 「プレゼンテーション設定」の直下
  3. 「XSS対策設定」の直下


ご意見無き場合は、順に1.・4.・2.の順として実装します。

**Comment by yuki-takei** [comment]
@tats-u ご提案ありがとうございます。
個人的な意見だけ書いときます！

> 編集者にどこまで裁量を与えるか
>     テーマやキーバインドのところで変更可能
>     1.のところに値だけ表示
>     現在通り不可視

不可視よりは可視がいいかなと思います。

> 初期値に管理者がどこまで介入できるか
>     完全にシステム・ユーザ任せ（管理オプションを作らない）
>     インデントがなかったときのフォールバック値のみ設定
>     特定値に強制
>     2.・3.を選択可能

ページ新規作成時のデフォルト値(フォールバック値)は管理画面から設定可能だといいですね。
実際のページ編集時は、個々のページごとに編集者がスペース x 2 でインデントするのか、x4 でインデントするのかを変えられていいと思います。
detect のために別途パッケージが必要であればインストールして構いません。

> 管理画面の「マークダウン設定」のどこにインデント設定を挿入するか
>     最上段
>     「Line Break設定」の直下
>     「プレゼンテーション設定」の直下
>     「XSS対策設定」の直下

これはこだわりは特にないですね。マージしたあとでこちらで位置を変えることもあるかもしれません。

> タブ文字によるインデントを許可するか
>     不許可
>     設定で許可

まあ不許可でいいのかなあと…
要望が出てきたら？

**Comment by tats-u** [comment]
@yuki-takei 
ありがとうございます。ご提案の内容の通りで実装を進めております。

**Comment by tats-u** [comment]
コメント入力欄でもインデント幅の変更ができるように、エディタオプションを表示するよう変更を加えてあります。
