### ISSUE TITLE
Bug: 編集中にページを離れると、戻っても編集内容が予告なく破棄される / Once you leave a page while editing, your edits will be discarded without notice even if you get back.

### ISSUE THREAD

**Issue by tats-u** [weseek/growi#3440]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04 (Host)|
|GROWI | 4.2.8
|node.js|14.15.4|
|npm       |6.14.10|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Firefox 85.0.2|

How to reproduce? (再現手順)
---------------------------

1. ページの編集画面に移行し、変更する（反映はしない）  
   Get into the edit window of a page and start editing. (do not save it)
1. 戻るボタンやリンクのクリックでページを離脱する
   Leave the page by clicking the back button or a link.
1. 戻る・進むボタンで元の編集画面に戻る
   Get back to the page by the back or forward button.

What happens? (症状)
---------------------

- 予告なく編集内容が消える
   The draft will be discarded without notice.

What is the expected result? (期待される動作)
-------------------------------------------

- 編集中で戻る・ウインドを閉じる・リンクを踏むなどする際に[onbeforeunload](https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onbeforeunload)イベントを発行し、「このページから移動しますか？入力されたデータは保存されません。」のようなダイアログを表示する。
  A dialog like "Do you want to leave this page?  The input data will be discarded." must show up by issuing an event [onbeforeunload](https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onbeforeunload) just after the back button or a link is clicked or the browser window is tried to be closed while edit is going on.
- または一旦ページを離脱しても編集内容が保持されるようにする。
   Or the draft must be retained even when leaving the page.

Note
----

-

**Comment by itizawa** [comment]
@tats-u 
ご報告いただきありがとうございます。

こちら firefox、safari で確認いたしました。
Google chrome では default でダイアログが表示されるようです。

修正いたしますので少々お待ちください

**Comment by tats-u** [comment]
Chromeではちゃんとダイアログが表示されるのですね。実装自体はされていてよかったです。
修正開始のご報告ありがとうございます。

**Comment by tats-u** [comment]
多分これですね。

https://github.com/weseek/growi/blob/9019381907446705d7994ba46153e2790e7c158e/src/client/js/services/EditorContainer.js#L156

https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onbeforeunload

Chrome以外では`preventDefault()`を呼ばないといけないので、それがないのが原因と思われます。

**Comment by itizawa** [comment]
@tats-u 
調査までしていただきありがとうございます！
先ほど修正完了しました。 

v4.2.9 にて修正されたバージョンがリリースされます。
