### ISSUE TITLE
数式が表示されない v4.2.7, v4.2.8

### ISSUE THREAD

**Issue by tom--bo** [weseek/growi#3448]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu server 20.04.2 LTS|
|GROWI     |4.2.7, 4.2.8|
|node.js   |14.15.4|
|npm       |6.14.10|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | OS X |
|browser   | Chrome 88.0.4324.182 |

How to reproduce? (再現手順)
---------------------------

1.  Write math expression like "$ a = b $"

What happens? (症状)
---------------------

$ a = b $のような数式を書いた場合に数式と判断されず、そのまま表示されてしまいます。

What is the expected result? (期待される動作)
-------------------------------------------

"$"や"$$"による数式表示が可能なこと

Note
----

- Nothing

**Comment by yuki-takei** [comment]
@tom--bo お問い合わせ内容ですが、ちょっとこちらでは再現しないです。

https://demo.growi.org/Sandbox/Math

上記ページでは数式表示されていないでしょうか？表示されていない場合、環境起因の場合もあるのでブラウザ側でなにかエラーが出ていないかご確認ください。
また、編集画面のプレビューで数式変換されるかどうかは、最下部歯車メニューの「MathJax Rendering」にチェックが入っているかどうかをご確認ください。

デモでは正常に表示されているがお手持ちの環境で表示されない場合は NOCDN モードではないかどうか等、もう少し情報をいただければと思います。こちらでもブラウザコンソールでエラーログが出ていないかどうかは有用な情報です。

よろしくお願いいたします。

**Comment by tom--bo** [comment]
そもそも最下部歯車メニューでMathJax Renderingの設定がありませんでした、これは別途設定が必要なものでしょうか？

![スクリーンショット 2021-03-03 21 47 46](https://user-images.githubusercontent.com/4121420/109808155-1d024e00-7c6a-11eb-9faa-5613aa6b8358.png)


[GROWI Docs](https://docs.growi.org/ja/guide/)で検索してみましたが、install以外に設定があるようには見えずなにか見落としていたら、すいません。
installは上記の環境で [growi-docker-compose](https://github.com/weseek/growi-docker-compose)のreadmeに従ってcloneとbuildをしました。
git statusで確認できる差分は以下だけです。
```sh
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,7 +6,7 @@ services:
       context: .
       dockerfile: ./Dockerfile
     ports:
-      - 127.0.0.1:3000:3000    # localhost only by default
+      - 3000:3000    # localhost only by default
     links:
       - mongo:mongo
       - elasticsearch:elasticsearch
@@ -48,7 +48,7 @@ services:
       dockerfile: ./Dockerfile
     environment:
       - bootstrap.memory_lock=true
-      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
+      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"  # increase amount if you have enough memory
     ulimits:
       memlock:
         soft: -1
```

**Comment by tom--bo** [comment]
chromeのdeveloper toolsを使ってconsoleを確認したところ以下の2つのwarningが出ていましたが、本件と関係があるかは調査できていません
```
content.js:4 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:4
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
```

**Comment by yuki-takei** [comment]
環境変数設定に `MATHJAX=1` を入れてみてください。

**Comment by tom--bo** [comment]
上記の設定で表示できました。
調査不足ですいませんでした。
