### ISSUE TITLE
Improvement: Disable group select-box when the user does not Choose the grant "Only inside the group”

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#346]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.0.x|

### Client

| item     | version |
| ---      | --- |
|        ||

How to reproduce? (再現手順)
---------------------------

1. Prepare user group from admin page.
    - グループを管理画面から用意
1. Add user to the group above.
    - 上記グループにユーザを追加
1. Create a new page(or edit an existing page).
    - ページ新規作成(または、既存ページの編集)画面を表示
1. Select a grant "Public".
    - ページの公開範囲に"公開"を選択
1. Select a grant group above.
    - 上記グループをグループの公開範囲に選択する。
1. Save the page.
    - ページを更新する

What happens? (症状)
---------------------

- It seems group selector can be selected, but it does not reflect when you do not choose the grant "Only inside the group".
    - グループが選択できるように見えるが、「特定グループのみ」を選択していない場合は、グループへの公開が反映されない。

What is the expected result? (期待される動作)
-------------------------------------------

- Group selector should be disabled if you did not select the grant "Only inside the group”.
    - グループの選択は、「特定グループのみ」を選択していない場合は選択できない。

Note
----

- see L49-64 of /lib/viws/_form.html

**Comment by sils-jk** [comment]
タイトル
Improvement: Disable group select-box when the user not Choose the grant "Only inside the group”
Improvement: Disable group select-box when the user does not Choose the grant "Only inside the group”

再現手順
1.Prepare user group in admin page.
1.Prepare user group from admin page.

2.Add user to the above group.
2.Add user to the group above.

3.Create a new page(or Edit a existing page).
3.Create a new page(or edit an existing page).

症状
It seems to group selector can select, but it not reflect when you not choose a grant "Only inside the group”.
It seems group selector can be selected, but it does not reflect when you do not choose the grant "Only inside the group".

期待される動作
Group selector should be disabled if you have not selected a grant "Only inside the group”.
Group selector should be disabled if you did not select the grant "Only inside the group”.
