### ISSUE TITLE
複数単語でフリーワード検索時にAND検索にならない

### ISSUE THREAD

**Issue by kalzit** [weseek/growi#3472]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04|
|GROWI     |4.2.5|
|node.js   |14.15.3|
|npm       |6.14.9|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.7|
|browser   |GoogleChrome 88.0.4324.192|

How to reproduce? (再現手順)
---------------------------

1. 下記の本文内容で、記事1, 記事2, 記事3 を投稿する。

```
記事1 本文: apple
記事2 本文: banana
記事3 本文: apple banana
```

2. フリーワード検索で「apple banana」を検索する。

3. 記事1, 記事2, 記事3 がHitする。

What happens? (症状)
---------------------

- スペースで区切られた複数の単語がAND検索にならず、OR検索になっている。
- 前述の例では、apple と banana を両方を含む記事ではなく、apple か banana のいずれかを含む記事がHitしている。

What is the expected result? (期待される動作)
-------------------------------------------

- apple と banana を両方を含む、記事3 のみがHitする。

**Comment by kalzit** [comment]
GROWI 4.2.9 でも同様でした。

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04|
|GROWI     |4.2.9|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

**Comment by yuki-takei** [comment]
@kalzit デフォルトでは厳密なAND検索ではなく、一定スコア以上の結果を出すようにしています。

ダブルクォートを使うことでお望みの挙動になるかと思います。

#2971 のコメントも参照してください。
