### ISSUE TITLE
Using a remote mongodb (e.g., Mongo DB atlas)

### ISSUE THREAD

**Issue by jinhojang6** [weseek/growi#3498]
Hey, thank you for maintaining this awesome open source project. 

I have 2 questions regarding making use of a remote SaaS mongodb instead of hosting the DB locally.

1. How can I connect to a remote MongoDB database(e.g., MongoDB atlas)?
    - I replaced `mongoUri` with `mongodb+srv://{ID}:{PASSWORD}@~~~~~~` in `config/migrate.js` but it didn't work. 

2. If I start launching growi with the [docker-compose repo](https://docs.growi.org/en/admin-guide/getting-started/docker-compose.html), how can I develop it? It just fetch docker image so I cannot find the code.

Looking forward to hearing from you soon,

**Comment by yuki-takei** [comment]
@jinhojang6 

> How can I connect to a remote MongoDB database(e.g., MongoDB atlas)?

Don't edit `config/migrate.js`, set the env var `MONGO_URI` instead.

refs: https://docs.growi.org/en/admin-guide/admin-cookbook/env-vars.html

> 2. If I start launching growi with the docker-compose repo, how can I develop it? It just fetch docker image so I cannot find the code.

Developers guide is [here](https://docs.growi.org/en/dev/).
If you would like to use custom docker image, build with [this Dockerfile](https://github.com/weseek/growi/tree/master/docker) and put it to your registry, and pull your image with weseek/growi-docker-compose.
