### ISSUE TITLE
Drwaioを日本語メニューで起動する方法は無いのでしょうか？

### ISSUE THREAD

**Issue by funakura** [weseek/growi#3507]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Alpine 3.11(weseek/growi:4) |
|GROWI     |4.2.10|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |chrome 89.0.4389.72|

How to reproduce? (再現手順)
---------------------------

1. 新規作成・編集から、Drawioを起動
2. Drawioが表示される。

What happens? (症状)
---------------------

常に英語メニューが表示される。

What is the expected result? (期待される動作)
-------------------------------------------

日本語メニューで表示してほしい。

Note
----

ソースを眺めると、DrawioModal.drawioURL()の中で、DRAWIO_URIからURLの作成でlangオプションで言語を指定している様に見えます。設定で日本語を指定する方法があるのでしょうか？

**Comment by yuki-takei** [comment]
@funakura 

> ソースを眺めると、DrawioModal.drawioURL()の中で、DRAWIO_URIからURLの作成でlangオプションで言語を指定している様に見えます。設定で日本語を指定する方法があるのでしょうか？

ご報告ありがとうございます。
こちら実装したつもりでしたがバグで働いていなかったようです。

修正を master にマージしましたので、次の版から言語選択が draw.io (diagrams.net) にも反映されます。
v4.2.12 リリースをお待ちください。
