### ISSUE TITLE
Improve: タイムライン表示で日本語をパーセントエンコーディングしないで欲しい。

### ISSUE THREAD

**Issue by izmth** [weseek/growi#351]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS7|
|GROWI     | 3.0.5-RC |
|node.js   | 8.11.1 |
|npm       | 5.8.0 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

### Client

| item     | version |
| ---      | --- |
|OS        | Ubuntu16.04|
|browser   | Chrome|

How to reproduce? (再現手順)
---------------------------
タイムライン表示を行う。

What happens? (症状)
---------------------
日本語がパーセントエンコーディングされて表示される。

What is the expected result? (期待される動作)
-------------------------------------------
日本語がそのまま表示される。

**Comment by yuki-takei** [comment]
@izmth ご報告ありがとうございます。v3.0.4 で発生したバグのようです。
近日中に修正しますので今しばらくお待ちください。
