### ISSUE TITLE
Question: Formatter Extension for VSCode

### ISSUE THREAD

**Issue by tats-u** [weseek/growi#3514]
Environment
------------

|item|version|
|----|----|
|OS|Windows 10|
|Editor|VSCode|

How to reproduce? (再現手順)
---------------------------

1. `yarn install`
1. Instal extension [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) in VSCode
1. Turn on `Eslint > Format: Enable` in settings
1. Configure formatter by `Format Document...`
1. Format
2. If chose Prettier in `Format Document...`, try `Alt+Shift+F` (Windows) or `Ctrl+Shift+I` (Linux) (Format Doucment) and format on save both

What happens? (症状)
---------------------

- Formatted code by ESLint and Prettier different

    ```javascript
    // ESLint
    const fooComponent = (props) => {
    //...
    }
    // Prettier
    const fooComponent = props => {
    //...
    }
    ```

- If chose Prettier, Prettier is used in `Format Document`, but ESLint is used in format on save

What is the expected result? (期待される動作)
-------------------------------------------

- ESLint and Prettier generates the same code
- Or either of them is the official formatter

Note
----

- If Prettier is not recommended, could you tell me why there is `.prettierrc`?

**Comment by yuki-takei** [comment]
> ESLint and Prettier generates the same code

This behavior is not possible, eslint is the recommended linter for JS.

https://github.com/weseek/growi/blob/e5a83d93a09ac184c8469561b62d04939d4a31ce/package.json#L41-L42

> If Prettier is not recommended, could you tell me why there is .prettierrc?

In this project, Prettier is setup only for stylelint.

**Comment by tats-u** [comment]
Thank you for your answer.  It seems that Prettier plugin for VSCode should be disabled as long as we do not touch SCSS.
