### ISSUE TITLE
docker 4-nocdn版でemojiが正しく表示されない

### ISSUE THREAD

**Issue by paichi81** [weseek/growi#3527]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.2.10|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

How to reproduce? (再現手順)
---------------------------

※非外部接続環境で、noCDN版のdockerイメージでgrowiを運用しています。

1. docker-hubにある `4-nocdn` をdocker-compose up -dし、起動する
1. Wikiの編集で、emojiを表示させる内容を記述する

What happens? (症状)
---------------------

- 絵文字左側にリンク切れ画像のイメージが表示される
- ソースをみるとcdn呼び出しがある

```
<img class="emojione" alt="☀️" title=":sunny:" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/2600.png">
```

What is the expected result? (期待される動作)
-------------------------------------------

- リンク切れせずに絵文字が表示される

Note
----

- emojioneを同梱すればよいと思うのですが、どうでしょうか。

**Comment by paichi81** [comment]
すいません、 #2472 , #2643 と同一の内容かもしれません。

**Comment by yuki-takei** [comment]
@paichi81 申し訳ありませんが現時点では仕様になります。
v5 系でレンダリングに関する大幅な改修を入れる予定で、もしかするとそちらで修正されるかもしれません。
