### ISSUE TITLE
Not to be able to login GROWI demo page as an admin user

### ISSUE THREAD

**Issue by kaoritokashiki** [weseek/growi#3537]
### Problem to Solve
Not to be able to login GROWI demo page as an admin user
- https://demo.growi.org/

How to reproduce? (再現手順)
---------------------------
- Try to login as an admin user refer to the following image.
<img width="1059" alt="Screen Shot 2021-03-18 at 18 09 56" src="https://user-images.githubusercontent.com/59536731/111600891-2ae0d300-8815-11eb-9091-57061af71dbe.png">

What happens? (症状)
---------------------
- Login failed
<img width="480" alt="Screen Shot 2021-03-18 at 17 46 19" src="https://user-images.githubusercontent.com/59536731/111601030-5237a000-8815-11eb-91fd-42d6bf1b330f.png">

What is the expected result? (期待される動作)
-------------------------------------------
- Be able to log in as an admin user

**Comment by itizawa** [comment]
解決したので close します
