### ISSUE TITLE
MathJax 利用時にバックスラッシュを重ねた際の表示がプレビューと結果で異なってしまう

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#3542]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8.2003|
|GROWI     |4.2.12|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 89.0.4389.90|

How to reproduce? (再現手順)
---------------------------

1. 任意のページの編集モードに入る
1. エディタ上にバックスラッシュ（半角￥）を重ねた文を書く（例：\\\\\\\\abc）
1. ページを更新し結果を確認する

What happens? (症状)
---------------------

-  例の場合（バックスラッシュ４個）ではプレビューではバックスラッシュ２つが表示されているが、更新すると１つしか表示されなくなっている。

| エディタ    | プレビュー | 結果 |
| --- | --- | --- |
| \\\\\\\abc  | \\\abc | \abc |

What is the expected result? (期待される動作)
-------------------------------------------

- プレビューと結果が一致する。
　

Note
----
- プレビューの状態が期待値なのかなと思います。

**Comment by yuki-takei** [comment]
@hide-o-mvd こちら調査したところ、MathJax の有効無効およびプレビュー画面での「MathJax Rendering」の有効無効が関係していることがわかりました。

## 再現手順補足

本事象が発生するのは、「MathJax が有効になっており、かつプレビュー画面で MathJax rendering が無効化されている場合」となります。
環境変数 `MATHJAX` を無効化して起動した場合は、入力 `\\\\abc` に対して、プレビュー、View 画面共に出力 `\\abc` となります。

## 期待される動作補足
下記のどちらか

- MathJax が有効になっており、かつプレビュー画面でも MathJax rendering 有効
- MathJax が無効になっている

の場合は、プレビューと View 画面での出力は一致します。ただし、残念ながらバックスラッシュの数は全てのケースで一定にはなりません。


## 取り扱い

MathJax を有効にする以上はバックスラッシュを含む文字列がそちらで処理されて消失するのは避けられないため、こちらは仕様という取り扱いにさせていただきます。

**Comment by hide-o-mvd** [comment]
調査いただき、ありがとうございました。現象について理解しました。
