### ISSUE TITLE
再帰的な移動/複製を行うとグループ権限を付与した子ページがスキップされる

### ISSUE THREAD

**Issue by rary21** [weseek/growi#3563]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |20.04.2 LTS (Focal Fossa) WSL2|
|GROWI     |4.2.12|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 89.0.4389.90|

How to reproduce? (再現手順)
---------------------------

1. 適当なグループを作成し、自身を割り当てる
2. 以下のようにページを作成する
```
a
 └b
  ├c
  └d
```
3. 以下のように権限を付与する
* グループ権限: `a/c`
* 公開: `b/d`

4. `a` を再帰的に複製する

What happens? (症状)
---------------------

- コピー先の構成が以下のようになり、グループ権限が付与されている `c` のみが複製されない
```
a
 └b
  └d
```

What is the expected result? (期待される動作)
-------------------------------------------

- 全てのページが複製される
```
a
 └b
  ├c
  └d
```

Note
----

- 権限を `自分のみ` に設定した場合は問題なく全て複製されました
- 親ページと子ページを全てグループ権限に設定すると、親ページのみ（例示している中の `a` のみ）が複製される
- 移動した場合も同様の症状が起きる。その場合、移動がスキップされたページは元の場所に残っておりアクセス可能。（例示している中の `c`）

**Comment by itizawa** [comment]
@rary21  
再度 issue を作成いただきありがとうございます。

https://github.com/weseek/growi/pull/3558 にて現在対応中です。 
Merge されましたら Close させていただきます。

**Comment by rary21** [comment]
ありがとうございます。

以下の手順を踏めば無駄な公開状態にならずに複製/移動可能でした。
1. ページ全てを `自分のみ` に権限変更
2. 複製/移動
3. グループ権限に変更
