### ISSUE TITLE
APIに関するドキュメントを作って欲しい

### ISSUE THREAD

**Issue by takuya-nakanishi** [weseek/growi#3579]
先程はインタビューありがとうございました。
早速 Issue を登録します。

---
API利用に関するドキュメントが欲しいです。
現状ソースコードから追跡して何とか利用できていますが、
それが正しいかの確証もありませんので、
正式に API 利用方法をまとめて頂いたものがほしいです。

**Comment by yuki-takei** [comment]
@takuya-nakanishi お返事遅くなり大変申し訳ないです。

整備途中のものになりますが、OpenAPI 化したものがこちらにございます。
https://docs.growi.org/en/api/rest-v3.html

ただこれも jsdoc から作っていますので、実装から乖離があることもあり…
こちらの文書で俯瞰しつつ、なにかおかしい場合はソースを見る他ないのが実情です。

いずれ Ts.ED 等を導入し、decorator から OpenAPI 化することも検討していますので、徐々に正確性を上げて行ければと考えております。

**Comment by takuya-nakanishi** [comment]
@yuki-takei 
ありがとうございます。
整備中とは言え、俯瞰しやすくて助かります。

> 徐々に正確性を上げて行ければと考えております。

是非、お待ちしてます。
