### ISSUE TITLE
非公開としたメールアドレスがLocalStorage内に含まれている

### ISSUE THREAD

**Issue by Archsted** [weseek/growi#358]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.0.7|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 65.0.3325.181|

How to reproduce? (再現手順)
---------------------------

1. メールアドレスを非公開に設定したユーザーを用意しておく。
1. GROWIの任意のページにアクセスする。
1. デベロッパーツールからLocal Storageの値を確認する。
1. 以下Keyから、最初に用意したユーザーの`email`を確認する。
  - users
  - userById
  - userByName

What happens? (症状)
---------------------

- メールアドレスを非公開としているユーザーでもemailの値が見えている。

What is the expected result? (期待される動作)
-------------------------------------------

- 非公開としているメールアドレスが外部に漏れないようにする。

以上、よろしくお願いいたします。

**Comment by yuki-takei** [comment]
@Archsted いただいたご要望について部分的に改修を行いましたが、ちょっと望まれている理想的な状態にはすぐには改修できなさそうです。

まずこのような実装となっている経緯ですが、GROWI のフォーク元の Crowi は元々クローズドな組織内での運用を主眼に作られていたようで、ユーザー間の情報の秘匿に関してはあまり頓着がありません。

GROWI(旧 crowi-plus)はフォーク後に後付けでメールアドレス非公開のオプションを付けましたが、現時点では飽くまでもユーザーの個人ページ( /user/hoge のような)で表示しないという効果があるのみです。

それ以外にも email 値を含むユーザー情報をクライアントとサーバーがやり取りする箇所は多く、例えばページリストを取得するような場合はその作成者の情報も受け取るため、ほぼ全ての通信で author の email 値はクライアントに渡されます。現時点で、それら全ての箇所でメールアドレスを隠匿するコードを挿入するのは現実的ではないと判断しました。いずれこの問題が多くのユーザーによって重要視される時が来たときに、大規模な改修を入れることになると思います。

ただ、今回 @Archsted さんが問題視した localStorage 内のデータに関してはより一層望ましくない動作であると考えましたので、 [32f1191] ではそちらに限って修正を行いました。

次回リリース後はメールアドレスを非公開としているユーザーの email 値は各クライアントの localStorage に保存されることはなくなりますが、名前や username は引き続き保存の対象であり、かつページ閲覧等のアクションによってやりとりされる JSON には引き続き email 値が入ってしまいます。

上記ご了承の上、ご利用いただければと思います。

満足のいく回答にはなっていないとは思いますが、ご容赦くださいm(_ _)m

**Comment by Archsted** [comment]
ご丁寧な説明ありがとうございました。経緯や状況は把握できました。
GROWIをオープンに公開して利用した時、非公開の設定があるからとプライベートなメールアドレスを登録する人がいた場合、後々もめる事になったら嫌だなという考えでした。

当面は、公開してはまずいメールアドレスは登録しないように注意書きをする運用で行こうと思います。
ご対応ありがとうございました。
