### ISSUE TITLE
通常の方法でアクセスできないページを作成できてしまう問題

### ISSUE THREAD

**Issue by mopisec** [weseek/growi#3582]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.2.13|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 91.0.4455.2|

How to reproduce? (再現手順)
---------------------------

GROWIは `http://192.168.XX.X:11729` 上で稼働しているものとする
1. `http://192.168.XX.X:11729/..%2f` のようなURLにアクセスする
2. ページを作成し、適当な内容を書き込み保存する

![image](https://user-images.githubusercontent.com/41460213/113261143-0e12c800-930a-11eb-9483-942b9c0f6a93.png)

What happens? (症状)
---------------------

- サイドバーやページリストから当該ページにアクセスしようとすると、一つ前の階層のページが開かれてしまい、ページ作成時と同じ手順を踏んでページにアクセスしないと削除・リネーム等の操作ができない

![image](https://user-images.githubusercontent.com/41460213/113259802-8082a880-9308-11eb-93c1-be0718a7a63e.png)

What is the expected result? (期待される動作)
-------------------------------------------

- このような (`..%2f` を含む) ページが作成できない
    - エラーが発生する
    - 特殊文字がエスケープされる

Note
----

- 脆弱性を探している過程で見つけた小さなグリッチで、悪用される可能性についても低いと感じたのでIssueを通してご報告させていただきました。

**Comment by yuki-takei** [comment]
@mopisec ご報告ありがとうございました。先ほど修正をコミットしました。
v4.2.15 リリースをお待ちください。
