### ISSUE TITLE
「メールアドレスの公開」のデフォルト設定を非公開にしたい

### ISSUE THREAD

**Issue by ntakahashi0505** [weseek/growi#3588]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.2.5|
|node.js   |14.15.3|
|npm       |6.14.9|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

What happens? (症状)
---------------------
現在、「メールアドレスの公開」設定はデフォルトで「公開」になっており、非公開にしたい場合は、ユーザーが個別に設定をする必要があります。

ただし、現在使用している用途でいうと、お互いのメールアドレスを非公開にできたほうが望ましいです。

What is the expected result? (期待される動作)
-------------------------------------------
管理者側で「メールアドレスの公開」をデフォルトで「非公開」に設定できるようにしていただければうれしいです。

Note
----
本件、問い合わせに連絡しましたが、こちらでissueを立てるようご案内いただきました。
ご対応ありがとうございます。

**Comment by zahmis** [comment]
ntakahashi0505 様
Issue 作成ありがとうございます。

修正にとりかかります！

**Comment by yuki-takei** [comment]
@ntakahashi0505 v4.2.14で実装されました。フィードバックございましたらコメントお願いします。
