### ISSUE TITLE
Bug: Don't show angle brackets link

### ISSUE THREAD

**Issue by girigiribauer** [weseek/growi#361]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |3.0.8-RC (Deploy to Heroku)|

### Client

| item     | version |
| ---      | --- |
|OS        | MacOS 10.12 |
|browser   | Chrome 65.0.3325.181 (Official Build) (64-bit) |

How to reproduce? (再現手順)
---------------------------

Write angle brackets link

```markdown
<http://example.com/path/to/link>
```

What happens? (症状)
---------------------

Don't show link

```markdown
(nothing)
```

Note
----

- No problem on crowi

<img width="1050" alt="on_crowi" src="https://user-images.githubusercontent.com/349184/39122721-be29c1d6-4730-11e8-8124-49c96c105987.png">
<img width="1049" alt="on_growi1" src="https://user-images.githubusercontent.com/349184/39122736-cbb28338-4730-11e8-8ddd-17556f3b9d73.png">
<img width="1050" alt="on_growi2" src="https://user-images.githubusercontent.com/349184/39122743-ce1dd50a-4730-11e8-85c9-4ec6132973c3.png">

**Comment by yuki-takei** [comment]
@girigiribauer 
This is not a bug.
GROWI uses [xss](https://www.npmjs.com/package/xss) package for security reason and it rejects some angle brackets expression.

Use following expressions instead:

- The standard Markdown link expression (`[text](url)`)
- Square brackets expression (`[/page1/page2]`)
- [weseek/growi-plugin-pukiwiki-like-linker](https://github.com/weseek/growi-plugin-pukiwiki-like-linker)

## Refs:

https://demo.growi.org/Sandbox#link

**Comment by girigiribauer** [comment]
OK, thanks.
