### ISSUE TITLE
Bug: 表編集ダイアログ表示中ダイアログ外をクリックすると確認なく編集がキャンセルされる

### ISSUE THREAD

**Issue by tats-u** [weseek/growi#3637]
Environment
------------

### Host

<https://demo.growi.org/> (2021/4/19 Version 4.2.14)

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Firefox 87.0|

How to reproduce? (再現手順)
---------------------------

1. Markdown編集画面に移行する
1. 表にキーボードカーソルを合わせてから表編集アイコンをクリック
1. ダイアログが出るので適当に編集してダイアログの外をクリック

What happens? (症状)
---------------------

確認なくダイアログ上の編集ログが破棄され、ダイアログが閉じられる

What is the expected result? (期待される動作)
-------------------------------------------

いずれか1つ

- 閉じられる前に確認が来る
- そもそも外をクリックした程度では閉じられない
- またはダイアログ外のクリックでは一旦反映されてから閉じられる

Note
----

- 表編集は手間がかかる場合が少なくなるので、本症状でキャンセルされてまた最初からやり直しとなると悲しいです。

**Comment by yuki-takei** [comment]
@tats-u 
> そもそも外をクリックした程度では閉じられない

で修正しました。また、ESCキーでも閉じられることのないように仕様を変更しました。
v4.2.15 のリリースをお待ちください。
