### ISSUE TITLE
Bug: 公開範囲を選択するとエラーが発生する

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#3655]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.9.2009|
|GROWI     |4.2.15|
|node.js   |14.16.1|
|npm       |6.14.12|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 89.0.4389.128|

How to reproduce? (再現手順)
---------------------------

1. 任意のページを新規作成、または編集する
1. 公開範囲で「特定のグループのみ」を選択する

What happens? (症状)
---------------------

1. 下記のエラーが発生します
```
Error occured in t
TypeError: this._mountContainer.removeChild is not a function
```

```
詳細
    in t
    in Ms
    in n
    in t
    in ForwardRef
    in withI18nextTranslation(Unknown)
    in div
    in div
    in Is
    in n
    in t
    in ForwardRef
    in withI18nextTranslation(Unknown)
    in form
    in div
    in div
    in Fs
    in n
    in t
    in ForwardRef
    in qs
    in n
    in t
    in ForwardRef
    in t
    in n
    in p
    in i
    in B
```

What is the expected result? (期待される動作)
-------------------------------------------

- 正常に指定できる

Note
----

- デモ版でも再現しました。

**Comment by yuki-takei** [comment]
@hide-o-mvd ご報告ありがとうございます。修正完了しました。v4.2.16 リリースをお待ちください。
