### ISSUE TITLE
Bug: 「全て他のグループに移譲する」に全てのグループが表示されない

### ISSUE THREAD

**Issue by hibikine** [weseek/growi#3724]
グループが11グループ以上存在する場合、グループ削除時に、「全て他のグループに移譲する」で全てのグループが表示されません。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |N/A (GROWI.cloud)|
|GROWI     |4.2.14|
|node.js   |14.16.1|
|npm       |6.14.12|
|Using Docker|N/A (GROWI.cloud)|
|Using [growi-docker-compose][growi-docker-compose]|N/A (GROWI.cloud)|

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Firefox 88.0.1|

How to reproduce? (再現手順)
---------------------------

1. グループ管理を開く (/admin/user_groups)
1. グループを11個以上作成する
1. グループを削除する
1. 「全て他のグループに移譲する」を選択
1. 「グループを選択してください」のプルダウンメニューに全てのグループが表示されない

What happens? (症状)
---------------------

- 移譲先のグループに、全グループが表示されません
  - 現在のページに表示されているものしか表示されません。
  - 例えば、3ページ目で削除する場合、3ページ目に表示されているグループしか選択肢に出てきません。

![image](https://user-images.githubusercontent.com/14365761/118107650-fefb5b80-b419-11eb-846d-0bea3238e4ac.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 移譲先のグループに、現在削除しようとしているグループを除く全グループが表示される

**Comment by yuki-takei** [comment]
@hibikine ご報告ありがとうございます。再現を確認いたしました。修正を行います。
次のバージョンリリースをお待ちください。
