### ISSUE TITLE
Improvement: 新規ページを保存する際に公開範囲の設定を反映させる

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#376]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.0.10|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.4|
|browser   |Firefox 59.0.2|

How to reproduce? (再現手順)
---------------------------

1. 新規ページを作成する
1. ファイルを1つアップロードする（文章の有無は問わない）
1. ⌘+S で保存する

What happens? (症状)
---------------------

- 画面右下の公開範囲の設定の選択を無視して「自分のみ」閲覧できる状態で保存される

What is the expected result? (期待される動作)
-------------------------------------------

- 画面右下の公開範囲の設定で保存される

Note
----

- 「更新」ボタンで保存した場合には正しく公開範囲が設定される

**Comment by yuki-takei** [comment]
@k84rc こちらは現状では画面右下部分の公開範囲設定のセレクトボックスと PageEditor Component で行っている ⌘+S の処理を連携できない仕組みになってしまっているので、仕様となります。

#346 の修正後に公開範囲設定のセレクトボックスが React Component になる予定ではあるので、そちらに続いて改修を行う事で望みの挙動にすることができるようになります。実装時期は未定なので、長い目で見ていただければと思います m(_ _)m
