### ISSUE TITLE
Bug: 新規ページを作成する際に2ファイル以上アップロードできない

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#377]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.0.10|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.4|
|browser   |Firefox 59.0.2|

How to reproduce? (再現手順)
---------------------------

1. 新規ページを作成する
1. ファイルを1つアップロードする
1. さらにファイルをアップロードしようとする

What happens? (症状)
---------------------

1. 「Error.」と表示され2ファイル目以降をアップロードすることができない

What is the expected result? (期待される動作)
-------------------------------------------

- 新規ページを作成する際に2ファイル以上アップロードすることができる

Note
----

- 一旦保存した後、**View に戻ってから**再度 Edit を開くとアップロードできる

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。再現確認しました。
近日中に修正版をリリースしますので今しばらくお待ちください。
