### ISSUE TITLE
Bug: 添付されたファイルの削除時に、Attachments リストが消える

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#378]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.0.10|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.4|
|browser   |Firefox 59.0.2|

How to reproduce? (再現手順)
---------------------------

1. 2ファイル以上添付されたページから添付されたファイルを削除する

What happens? (症状)
---------------------

1. Attachments リストが消える

What is the expected result? (期待される動作)
-------------------------------------------

- ページに添付されたファイルがあれば、その一覧を表示し続ける

Note
----

- リロードで再度表示される

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。再現を確認しました。
近日中に修正版をリリースしますので今しばらくお待ちください。
