### ISSUE TITLE
Request: expire login session

### ISSUE THREAD

**Issue by fmy** [weseek/growi#3794]
## Informations
**Is your feature request related to a problem? Please describe.**
ログインがずっと維持される

**Describe the solution you'd like**
ENVでログイン継続期間の指定ができ、ログインした時刻からその指定期間が過ぎると再ログインを要求する。

SAML管理していてIdPでアカウントを停止しても、ブラウザのセッションがあるのでずっと閲覧することができる。
Deprovisioningがあれば尚良いが、ログインセッションを1日などで切れるようにすれば、停止したユーザーがアクセスし続けることを防ぐことができる。

**Comment by yuki-takei** [comment]
@fmy

現状は、一応「ずっと」ではなく 30days 固定になっております。
https://github.com/weseek/growi/blob/v4.2.18/src/server/crowi/express-init.js#L85-L86

ただ利用者側での変更ができないのはその通りですので、改修を検討いたします。

**Comment by yuki-takei** [comment]
@fmy 
実装完了し、master にマージしました。環境変数 `SESSION_MAX_AGE` をセットするか、管理画面の Security Management から指定できます。(いずれも msec)

v4.2.19 リリースをお待ちください。

## 注意事項
既に管理されているセッションデータは MongoDB または Redis に保存されており、そのレコードが expire しない限りは v4.2.18 までのデフォルトであった「30日後」で有効期限を更新し続けます。
(https://github.com/expressjs/session#rolling 参照)

そのため、強制的に新しい値を全ユーザーに対して有効にしたい場合はは、MongoDB を操作し、セッションデータの削除を行ってください。具体的にはの sessions コレクションの全消去になります。

## 今後について
全セッションデータの削除操作に関しては、今後管理画面からの操作で行えるように機能を追加します。

**Comment by fmy** [comment]
ありがとうございます

> 現状は、一応「ずっと」ではなく 30days 固定になっております。
https://github.com/weseek/growi/blob/v4.2.18/src/server/crowi/index.js#L220

30days以内にアクセスを繰り返しているとずっとログインが維持されるようです
できれば最後にログインした日からX日後に再度ログインを必須になると嬉しいです
