### ISSUE TITLE
Bug: ERROR: growi:cli:SocketIoContainer: addLangAttrToHtmlTag/websocket error

### ISSUE THREAD

**Issue by ndr-thitinan** [weseek/growi#3799]
Environment
------------

### Host

| item     | version |
|OS        | CentOS Linux release 7.9.2009 (Core) Updated |
|GROWI     | 4.2.19-RC |
|node.js   | 14.17.0 |
|npm       | 6.14.13 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10 18363.1256 |
|browser   | Chrome 90.0.4430.93 |

How to reproduce? (再現手順)
---------------------------

https://docs.growi.org/ja/admin-guide/getting-started/centos.html#%E6%A6%82%E8%A6%81 に参照して、インストールした後、エラーが出てきます。

What happens? (症状)
---------------------

Web Browser のコンソールで下記のエラーになります。

```
Stack Trace
```

jquery.js:3841 jQuery.Deferred exception: addLangAttrToHtmlTag is not defined ReferenceError: addLangAttrToHtmlTag is not defined
    at HTMLDocument.<anonymous> (http://IP Address/admin:339:5)
    at e (https://cdn.jsdelivr.net/combine/npm/emojione@3.1.2,npm/jquery@3.4.0,npm/popper.js@1.15.0,npm/bootstrap@4.5.0/dist/js/bootstrap.min.js,npm/scrollpos-styler@0.7.1,npm/jquery-slimscroll@1.3.8/jquery.slimscroll.min.js:28:29453)
    at t (https://cdn.jsdelivr.net/combine/npm/emojione@3.1.2,npm/jquery@3.4.0,npm/popper.js@1.15.0,npm/bootstrap@4.5.0/dist/js/bootstrap.min.js,npm/scrollpos-styler@0.7.1,npm/jquery-slimscroll@1.3.8/jquery.slimscroll.min.js:28:29755) undefined
k.Deferred.exceptionHook @ jquery.js:3841
t @ jquery.js:3629
jquery.js:3850 Uncaught ReferenceError: addLangAttrToHtmlTag is not defined
    at HTMLDocument.<anonymous> (admin:339)
    at e (jquery.js:3557)
    at t (jquery.js:3625)
(anonymous) @ admin:339
e @ jquery.js:3557
t @ jquery.js:3625
vendors.08a823036a9798ad500e.chunk.js:2 WebSocket connection to 'ws://IP Address/socket.io/?EIO=3&transport=websocket' failed: 
f.doOpen @ vendors.08a823036a9798ad500e.chunk.js:2
i.open @ vendors.08a823036a9798ad500e.chunk.js:2
c.open @ vendors.08a823036a9798ad500e.chunk.js:2
c @ vendors.08a823036a9798ad500e.chunk.js:2
c @ vendors.08a823036a9798ad500e.chunk.js:2
h.open.h.connect @ vendors.08a823036a9798ad500e.chunk.js:2
h @ vendors.08a823036a9798ad500e.chunk.js:2
h @ vendors.08a823036a9798ad500e.chunk.js:2
l @ vendors.08a823036a9798ad500e.chunk.js:2
c @ commons.43f9e768127380219f73.chunk.js:1
./src/client/js/base.jsx @ commons.43f9e768127380219f73.chunk.js:1
i @ admin.3b1a6ebe7fade5431fde.bundle.js:1
./src/client/js/admin.jsx @ admin.3b1a6ebe7fade5431fde.bundle.js:1
i @ admin.3b1a6ebe7fade5431fde.bundle.js:1
a @ admin.3b1a6ebe7fade5431fde.bundle.js:1
(anonymous) @ admin.3b1a6ebe7fade5431fde.bundle.js:1
(anonymous) @ admin.3b1a6ebe7fade5431fde.bundle.js:1
vendors.08a823036a9798ad500e.chunk.js:2 [17:54:54:0311] ERROR: growi:cli:SocketIoContainer: websocket error  
 Error: websocket error
    at f.i.onError (http://IP Address/js/vendors.08a823036a9798ad500e.chunk.js:2:728087)
    at WebSocket.ws.onerror (http://IP Address/js/vendors.08a823036a9798ad500e.chunk.js:2:741401)
vendors.08a823036a9798ad500e.chunk.js:2 [17:54:54:0312] ERROR: growi:cli:SocketIoContainer: websocket error  
 Error: websocket error
    at f.i.onError (http://IP Address/js/vendors.08a823036a9798ad500e.chunk.js:2:728087)
    at WebSocket.ws.onerror (http://IP Address/js/vendors.08a823036a9798ad500e.chunk.js:2:741401)

What is the expected result? (期待される動作)
-------------------------------------------

エラーがないとの期待です。

Note
----

addLangAttrToHtmlTag は ws のコネクションに関係があるかどうかわかりません。

**Comment by yuki-takei** [comment]
@ndr-thitinan 
2つ問題があるようです。

## addLangAttrToHtmlTag について
GROWI 本体ではそのような文字列を使っておりません。検索したところ以下のサイトがヒットしましたが、カスタムスクリプトを設定しているなどの心当たりはないでしょうか？

https://qiita.com/k84rc/items/159a7399c11abd4e3587

## websocket error について
connection failed とあるます。
サーバー側、特にリバースプロキシの設定を見直してみてください。

**Comment by yuki-takei** [comment]
追記です。RC版ではなくリリースバージョン(タグ付けされているコミット)の利用をお勧めします。

**Comment by ndr-thitinan** [comment]
@yuki-takei 
ありがとうございます。

今、ディスクが壊れてしまいました。
両方のエラー、環境を設置直した後、確認します。

現在、本番には 4.2.9 バージョンでも、エラーが出てきます。

**Comment by yuki-takei** [comment]
続報がないので一度 close します。
