### ISSUE TITLE
Bug:動画が再生されない

### ISSUE THREAD

**Issue by mox-sumioka** [weseek/growi#3823]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu16.04.6|
|GROWI     |4.2.18|
|node.js   |14.17.0|
|npm       |6.14.13|
|Using Docker|yes|
|Using growi-docker-compose |yes|

### Client

| item     | version |
| ---      | --- |
|OS        |windows10|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. 動画(mp4)をホストにアップロードします。
1. iframeで動画を貼り付けます。
  

What happens? (症状)
---------------------

- 動画が再生されません。
- リンクをクリックしても再生されません。

What is the expected result? (期待される動作)
-------------------------------------------

動画を再生できるようにしたい。

Note
----
2021年1月に発覚しました。4.1.3から4.2.5にバージョンアップしたときに問題は発生しています。
レンタルVPSサーバーを用意し、そこにGrowiをインストールして使っています。
YoutubeやDropBoxの動画貼り付けは問題ないので、ホストにアップロードした場合の症状かと思われます。
詳細はメールにて報告済みですが、念の為こちらにも報告しておきます。

**Comment by yuki-takei** [comment]
@mox-sumioka 
再現手順についてですが、「動画(mp4)をホストにアップロードします。」の手順を詳しく教えていただけますでしょうか？
また、GROWI の添付機能を利用している場合は、アップロード先を何に設定しているかを教えてください。

https://docs.growi.org/ja/admin-guide/management-cookbook/app-settings.html

**Comment by mox-sumioka** [comment]
1. マウスを使ってWindowsエクスプローラーにある動画ファイルを、Chromeで表示しているGrowiのページの編集画面に、ドラッグアンドドロップします。
2. 動画はアップロードされ自動的にリンクのタグが挿入されます。この時点でリンクをクリックしても見れません。
3. iframeタグに書き換えます。やはり見れません。

GROWI の添付機能のアップロード先は　Local　です。

**Comment by yuki-takei** [comment]
@mox-sumioka v4.4.3 と FILE_UPLOAD=local の組み合わせで再現確認を行いましたが、再現しませんでした。

> 4.1.3から4.2.5にバージョンアップしたときに問題は発生しています。
に関しては Content-Security-Policy を疑いましたが、v4.4.3 の現状の指定で問題なく再生できるようです。


> 動画はアップロードされ自動的にリンクのタグが挿入されます。この時点でリンクをクリックしても見れません。

に関してはアップロード先が local (VPSサーバーのfs)ということですので、その経路でのアクセスでなにか別の設定が効いていないかを見直してみてください。

一旦 close しますので、もし最新版に於いてより確実に再現できる手順がありましたらお知らせください。
