### ISSUE TITLE
Improvement: Prevent XSS when move/redirect/duplicate page

### ISSUE THREAD

**Issue by YDKK** [weseek/growi#383]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.0.11|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|Windows 10|1709|
|Chrome|66.0.3359.139|

How to reproduce? (再現手順)
---------------------------

1. [https://demo.crowi-plus.org/?redirectFrom=<script>alert('xss')</script>](https://demo.crowi-plus.org/?redirectFrom=<script>alert('xss')</script>
)
にアクセス（ブラウザのXSSフィルタの無効化が必要です）

What happens? (症状)
---------------------

- アラートが表示される

What is the expected result? (期待される動作)
-------------------------------------------

- アラートが表示されない

**Comment by yuki-takei** [comment]
@YDKK ご報告ありがとうございます。再現確認しました。
次回リリースに反映させますので今しばらくお待ちください。
