### ISSUE TITLE
Bug: ユーザー登録でパスワードが短いときに invalid characters と表示される

### ISSUE THREAD

**Issue by yy0931** [weseek/growi#3856]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04 |
|GROWI     | 4.2.18 |
|node.js   | 14.17.0 |
|npm       | 6.14.13 |
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04 |
|browser   | Firefox |

How to reproduce? (再現手順)
---------------------------

1. ユーザー登録画面を開く
1. 短いパスワードで登録する
1. エラーメッセージが表示される

What happens? (症状)
---------------------

- ユーザー登録できない理由で、文字数が原因なのにもかかわらず文字種が正しくないと表示される

What is the expected result? (期待される動作)
-------------------------------------------
- 文字数が短いことを表すメッセージが表示される

PR: https://github.com/weseek/growi/pull/3850

**Comment by yuki-takei** [comment]
@yy0931 ご報告とPR、ありがとうございます！
次のバージョンに取り込みます。来週リリース予定ですので今しばらくお待ちください。
