### ISSUE TITLE
Question: ブラウザの戻るボタンで編集画面からプレビュー画面へ戻れない

### ISSUE THREAD

**Issue by yy0931** [weseek/growi#3870]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04 |
|GROWI     | 4.2.19 |
|node.js   | 14.17.0 |
|npm       | 6.14.13 |
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04 |
|browser   | Firefox 89.0, Chromium 91.0 |

How to reproduce? (再現手順)
---------------------------

1. 適当なページでEditボタンを押す
1. ブラウザの←ボタンを押す

What happens? (症状)
---------------------
- プレビュー画面に戻らない

What is the expected result? (期待される動作)
-------------------------------------------
- プレビュー画面に戻る

**Comment by yuki-takei** [comment]
@yy0931 起票と PR ありがとうございます。
申し訳ないのですがこちらは仕様となります。

v4.1.13 までは管理画面のオプションから切り替えができたのですが、v4.2 以降廃止されました。
ユーザーさんから元に戻してほしいという要望もそれ以降聞いておらず、今に至ります。

https://github.com/weseek/growi/compare/v4.1.13...v4.2.0#diff-9813d6df8d7a8830c5fb01ee3e1cb25953001aac5bd338ea5e81d61b8abb0aefL253-L289

## 今後について
dev/v5.0.x ブランチでは現在 Next.js 化が進んでいます。タブ周りも大幅に改修が入るので、v4.2 系ではこれ以上はタブ周りの新たな機能は入れないつもりでいます。

もしオプショナルな機能として追加するとしたら v5.0.x 以降ということになりますが、その場合も管理画面から(もしくは個々人で)の切り替え機能として PR が送られたら検討という感じになると思います。

せっかく PR 書いてくださったのにすみません。

**Comment by yuki-takei** [comment]
その辺りの仕様検討やいつリファクタや機能リリースが走るか、あるいは詳細設計としてどのようなコードだったら取り込みやすいかは slack で議論可能ですので、お気軽にご相談いただければと思います。
