### ISSUE TITLE
コメントを全文検索の検索対象に加えてほしいです

### ISSUE THREAD

**Issue by KesuidaF** [weseek/growi#3909]
コメントに価値のある情報が含まれていることもあるため、コメントの内容も全文検索の対象に加えていただきたいです。

**Comment by kaoritokashiki** [comment]
@KesuidaF 様

改めましてこの度はissueを起票していただき誠にありがとうございます。
修正がマスターにマージされました。

次回リリース(v4.4.13)をお待ちください！
引き続き、GROWIをよろしくお願いいたします。
