### ISSUE TITLE
Bug: サイドバーを開いたまま編集するとレイアウトが崩れる。

### ISSUE THREAD

**Issue by izmth** [weseek/growi#394]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.0.12|
|node.js   |8.11.1|
|npm | 5.6.0|
|Using Docker|yes?|
|Using [growi-docker-compose][growi-docker-compose]|yes?|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

https://demo.growi.org で確認

### Client

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04 |
|browser   | Chrome 66.0.3359.170, Firefox 60.0 |

How to reproduce? (再現手順)
---------------------------

1. サイドバーを開く
1. 編集を開始する。

What happens? (症状)
---------------------

## chromeの場合  
- サイドバーの表示分ページの右側が埋まる。
- サイドバーを閉じることが出来ない。
![screenshot from 2018-05-13 13-14-18](https://user-images.githubusercontent.com/28652907/39963758-b666c33e-56af-11e8-9590-9c8bbbb5690c.png)

## firefoxの場合
- ページ幅は調整されるがViewボタンが押せなくなる。
![screenshot from 2018-05-13 13-14-48](https://user-images.githubusercontent.com/28652907/39963761-b98621ea-56af-11e8-963d-e6b22bb6bed0.png)

What is the expected result? (期待される動作)
-------------------------------------------

- ページの幅が調整されすべてが正常に表示される。
- またはサイドバーが閉じられ、開くことが出来ないようにする。

**Comment by yuki-takei** [comment]
@izmth ご報告ありがとうございます。再現確認しました。
調査ののち修正を入れようと思います。

**Comment by yuki-takei** [comment]
@izmth 修正完了しました。v3.0.13 リリースまで今しばらくお待ちください。
