### ISSUE TITLE
Request:  I want order list to be displayed with line breaks

### ISSUE THREAD

**Issue by itizawa** [weseek/growi#3986]
## Informations

- Describe the following markdown
```
1. hogehoge
    2. hugahuga
```
- In the preview, it will be displayed as follows
- <img width="1099" alt="スクリーンショット 2021-07-05 16 12 53" src="https://user-images.githubusercontent.com/48426654/124431823-dce3e100-ddab-11eb-94b5-854f8417204b.png">

**Describe the solution you'd like**
- I want it to be displayed with line breaks instead of one line
- If all are 1, it works

**Comment by yuki-takei** [comment]
## 代替案メモ

- increment しない

## 手段
- https://github.com/codemirror/CodeMirror/blob/17634c2205d987366dedbb763fbf7b4d4ecf1326/addon/edit/continuelist.js のカスタム版を作る
    - incrementRemainingMarkdownListNumbers で increment しない
