### ISSUE TITLE
Bug: 4.3.0 で yarn run build:prod が失敗する

### ISSUE THREAD

**Issue by mzch** [weseek/growi#4025]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |`Debian 10.10`|
|GROWI     |`4.3.0`|
|node.js   |`v12.22.1`|
|npm       |`6.14.12`|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1. run `yarn install`
1. run `yarn run build:prod`

What happens? (症状)
---------------------
fails to run `run build:prod`

```
growi@n19:~/growi$ yarn prestart
yarn run v1.22.5
$ npm run build:prod
npm ERR! missing script: build:prod
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     build:poll
npm ERR!     build:dev
npm ERR!     build:slack

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/growi/.npm/_logs/2021-07-15T04_10_32_247Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What is the expected result? (期待される動作)
-------------------------------------------
run `yarn run build:prod` successfully.

**Comment by yuki-takei** [comment]
@mzch ご報告ありがとうございます。自前ビルド民のことがすっかり頭から抜けていました…
直します。

**Comment by yuki-takei** [comment]
修正完了しました。v4.3.1 リリースをお待ちください。
