### ISSUE TITLE
Bug:`pages/recent`に正しいアクセストークンを指定しても`/login`へのリダイレクトが返される

### ISSUE THREAD

**Issue by KosukeMizuno** [weseek/growi#4050]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|client        |curl 7.68.0|

How to reproduce? (再現手順)
---------------------------

1. セキュリティ設定→ページの閲覧・削除権限→ゲストユーザーのアクセス「拒否」 に設定
1. `curl -v "http://localhost:3000/_api/v3/pages/recent?access_token=<url_encoded_token>"`
    1. `/login`へのリダイレクトが返される
1. （比較用：期待通りに動作する例）`curl -v "http://localhost:3000/_api/v3/pages/list?path=%2F&access_token=<url_encoded_token>"`
    1. jsonで返される

What happens? (症状)
---------------------

`pages/recent`に正しいアクセストークンを指定しても`/login`へのリダイレクトが返される

原因
------------

<https://github.com/weseek/growi/blob/22d7937681adcf542910fe6510011ed5f7783e43/src/server/routes/apiv3/pages.js#L286>

`apiv3/pages.js`286行目（recentのハンドラのmiddleware）に`accessTokenParser`が抜けているため、認証されていないのが原因だと思われます。

**Comment by kaoritokashiki** [comment]
@KosukeMizuno 様

GROWIをご愛顧いただき誠にありがとうございます

また、issueを起票してくださりありがとうございます。
修正完了いたしましたので、次回のバージョンリリースまでお待ちください。

引き続きよろしくお願いいたします。
