### ISSUE TITLE
Bug: <> in codeblock is treated as html tag even if XSS security option is off

### ISSUE THREAD

**Issue by KosukeMizuno** [weseek/growi#4056]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.2.21|
|node|14.17.1|
|npm|6.14.13|
|yan|1.22.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |win10|
|browser   |chrome |

What happens? (症状)
---------------------

コードブロック内の`<`,`>`がエスケープされません。これはXSS対策による既知のバグかと思いますが、XSS抑制をoffにしても以下の現象が起きたので報告します。

- I. コードブロック内で`<?`を含むと`<`以降のレンダリングが崩れる
- II. 編集中の右側プレビューと実際の表示が異なる

python, tqdmの出力結果を貼ったときに発見しました。こちらは意図通りに表示される例です。
![image](https://user-images.githubusercontent.com/43668684/126923193-042dcd47-f90f-48a7-b04f-8700036309c1.png)
![image](https://user-images.githubusercontent.com/43668684/126923207-4ca67ba0-a172-45c1-95a0-d5f1793c2d90.png)

おかしくなる例です。
![image](https://user-images.githubusercontent.com/43668684/126923290-4afd5393-b425-4efc-ac44-954b0e1542d2.png)
![image](https://user-images.githubusercontent.com/43668684/126923315-0739d481-03f4-4a48-8277-ec5cd09d956d.png)

また(II)について、
上のスクリーンショットは編集画面のプレビューに表示されているものです。
1. ここでおかしくなっている箇所`<`にバックスラッシュを入れると右側プレビューの表示が期待通りのものになります。このとき、ページ内に別のコードブロック（内容はほぼ同じで`<?`を含む）があってもすべての表示が期待通りのものになります。
    ![image](https://user-images.githubusercontent.com/43668684/126923566-d5cfaf5b-b0a9-4271-9008-abdd9ae6d42f.png)
    ![image](https://user-images.githubusercontent.com/43668684/126923636-0fc861d1-be12-47ce-8fd4-3ee7e3dfc325.png)
2. エスケープを除去しても意図通りのレンダリングのままです。
3. 保存して編集を抜け、ページにもどるとレンダリングが乱れています。

**Comment by KosukeMizuno** [comment]
同じ原因によるものだと推測しますのでもう一つ気づいたことを追記します。
コードブロック内の`=`があると崩れるようです。

````html
<details open>


```
(<Figure size 576x288 with 2 Axes>,
 array([<AxesSubplot:xlabel='XXX', ylabel='yyy'>,
        <AxesSubplot:title={'center':'WWW'}, xlabel='xxx'>],
       dtype=object))
```


</details>
    
    
aaa
````

としたとき以下のようになります。


![image](https://user-images.githubusercontent.com/43668684/126924602-ae9e7706-1847-40df-bc6e-bcf3651bb8e3.png)

**Comment by yuki-takei** [comment]
@KosukeMizuno v6 で修正されました。v6.0.0 はまだ不安定ですが、次回アップデートでもう少し安定してくるはずです。お時間あるときにご確認ください。
