### ISSUE TITLE
Sandboxの右のサイドバーの下のほうが切れている

### ISSUE THREAD

**Issue by mizozobu** [weseek/growi#408]
How to reproduce? (再現手順)
---------------------------

1. /Sandboxにアクセス

What happens? (症状)
---------------------

- 右のサイドバーの下のほうが切れている
![bug](https://user-images.githubusercontent.com/27652080/40173036-7e889870-5a0b-11e8-8fa3-48cb5c85f241.PNG)

What is the expected result? (期待される動作)
-------------------------------------------

- 右のサイドバーにも独自のスクロールバーが欲しい

**Comment by yuki-takei** [comment]
jQuery slimscroll を使いたい

**Comment by yuki-takei** [comment]
fixed by #443
