### ISSUE TITLE
Request: 更新履歴のURLにパーマリンクを追加する

### ISSUE THREAD

**Issue by kaoritokashiki** [weseek/growi#4080]

**Comment by kaoritokashiki** [comment]
<img width="1202" alt="Screen Shot 2021-07-30 at 14 55 36" src="https://user-images.githubusercontent.com/59536731/127607429-db81f413-2a56-4272-86e7-19bdd7e8f180.png">

**Comment by Shunm634-source** [comment]
Resolved the issue and successfully added the permanent link in the history

**Comment by Shunm634-source** [comment]
The feature is added in the 5.0.6 version.
