### ISSUE TITLE
Bug: タイトルに半角スペースを含むwiki内ページへのリンクがレンダリングされない

### ISSUE THREAD

**Issue by KosukeMizuno** [weseek/growi#4096]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     | 4.2.21 |
|node.js   |14.17.1|
|npm       |6.14.13|
|yarn| 1.22.5 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Edge 91.0.864.67|

How to reproduce? (再現手順)
---------------------------

1. タイトルに半角スペースを含むページを作成しておく
2. 別のページとしてedit画面を開く
3. エディタ上部のボタンからリンクを作成する
  - use relative path にチェックを入れる

What happens? (症状)
---------------------

use relative pathを選択（デフォルト）すると、リンクとして描画されない。use permanent linkを選択しておくと期待される動作をする。

What is the expected result? (期待される動作)
-------------------------------------------

リンクURLに含まれる半角スペースがエスケープされるべきですが、なっていないようです。

修正ご検討お願い致します。

**Comment by yuki-takei** [comment]
@KosukeMizuno ご報告ありがとうございます。修正しますので少々お待ちください。

**Comment by yuki-takei** [comment]
修正完了しました。次回リリースをお待ちください。
