### ISSUE TITLE
Request: システム情報をコピーできると便利

### ISSUE THREAD

**Issue by KosukeMizuno** [weseek/growi#4097]
バグ報告のテンプレートにシステム情報を書く部分があります。
https://{GROWI_HOST}/admin にアクセスするとその情報が見れるようになっていると思いますが、テンプレートの表の並びとシステム情報の表示の並びが異なっているため確認しながら手入力が必要です。
また、システム情報画面をコピー＆ペーストするとHTMLタグが含まれる形でコピーされてしまいます。

バグ報告に記載するべき情報をまとめてクリップボードにコピーするボタンがあると便利かと思いますので、提案させて頂きます。

**Comment by yuki-takei** [comment]
# Motivation 

It will be useful to add a button to copy system information to create issue.

# TODO
- Add a button to `AdminHome.jsx`
- Click behavior
    - Collect system information and client information
    - Generate markdown
    - Copy to clipboard (refs: `CopyDropdown.jsx`)


## Target page to implement
![image](https://user-images.githubusercontent.com/1638767/130049910-863f1f45-b9bf-416d-8e13-e014c60d2aba.png)

## Markdown style to report

![image](https://user-images.githubusercontent.com/1638767/130050001-28dc26e6-833c-479f-889d-e12cb773bf4f.png)
