### ISSUE TITLE
Bug: 公開範囲「特定グループのみ」でグループ指定できない

### ISSUE THREAD

**Issue by kakkojc** [weseek/growi#410]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Mac OSX High Sierra|
|GROWI     |3.0.7|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Mac OSX High Sierra|
|browser   |Firefox 59.0.2|

How to reproduce? (再現手順) / What happens? (症状)
-------------------------------------------------------

1. ユーザグループを作成
1. ユーザグループにユーザ追加
1. 新規ページを作成 
    1. 公開範囲「特定グループのみ」が選択不可
    1. 上記設定したグループ名のプルダウンメニューが表示されていない状態
1. コンテンツを適当に埋めた状態で公開範囲を「公開」として保存
1. 上記保存したページを編集し、公開範囲「特定グループのみ」を指定して保存
    1. この時点では公開範囲「特定グループのみ」を選択可能
    1. グループ名のプルダウンの表示あり
1. 上記保存したページを編集・保存
    1. 公開範囲は「特定グループのみ」になっているがグループ名のプルダウンが非表示
    1. 保存すると、保存されたページの上部に`undefined (Browsing of this page is restricted) `と表示される。
    1. この状態のページはグループ外のメンバでもアクセス可能

What is the expected result? (期待される動作)
-------------------------------------------

- 新規ページ作成時にグループを指定した上で「特定グループのみ」を公開範囲として設定可能
- 「特定グループのみ」を指定したページにグループ外メンバはアクセス不可

Note
----

- growi-docker-compose をそのまま利用（改変無し）
- [Demo Site](https://demo.growi.org/) では再現しない（期待通りの動作になっている）

**Comment by yuki-takei** [comment]
@kakkojc いただいた内容で動作確認をしてみたのですが、全く同じようには再現しませんでした。

新しく GROWI v3.0.7 を立ててみたところ、6-i までは同じなのですが、6-ii ではデモサイト同様、指定した通りのユーザーグループに限る動作をしています(期待される動作通り)。

1 と 2 で設定しているユーザーグループとグループに追加したユーザー、それから当該ページ編集中のユーザーはどのような関係になっているでしょうか。

因みにこの辺りの UI/UX が非常にいけてないのはチームでも把握しているので、現在改修を入れている最中です。新しいバージョンではもう少しグループ選択周りが直感的になるはずです。

**Comment by kakkojc** [comment]
@yuki-takei 確認ありがとうございます。ユーザやグループは以下のように設定しております。

- ユーザについて
    - test_admin：Growi構築時に最初に作成したユーザ（admin）
    - test1：ログイン画面より作成したユーザ（非admin）
- グループについて
    - secret：メンバはtest_adminのみ。test_adminユーザがグループ作成・メンバ設定実施。
- 該当ページ
    - test_adminユーザで作成・編集

**Comment by yuki-takei** [comment]
Heroku で同様の実験を行ってみたのですが再現せず。

https://growi-307.herokuapp.com

ID: test_admin
Pass: test_admin

ID: test1
Pass: test1test1

でログインできると思います。対象のページは https://growi-307.herokuapp.com/secret です。
他のページでもいいので当該事象を再現できれば原因追及できるとおもうのですが。

**Comment by kakkojc** [comment]
@yuki-takei Herokuの環境でも再現しました。

1. `Only inside the group (Browsing of this page is restricted) `の状態で`test_admin`で https://growi-307.herokuapp.com/secret を編集
    - 編集画面の右下は「特定のグループのみ」のまま更新
    - この時、グループ選択のプルダウンは非表示の状態
2. 上記編集ページが`undefined (Browsing of this page is restricted) `と表示
3. この状態で上記編集ページにアクセスするとtest1ユーザも参照可能

**Comment by kakkojc** [comment]
スクリーンショットとしてはこんな感じになります。

↓の画面で「編集」を押下。

<img width="1153" alt="2018-05-20 19 00 51" src="https://user-images.githubusercontent.com/12195595/40277812-471ee9aa-5c60-11e8-8281-768a806fb9a9.png">
↓の画面で「更新」を押下。

<img width="1149" alt="2018-05-20 19 01 05" src="https://user-images.githubusercontent.com/12195595/40277819-4d377316-5c60-11e8-8c01-1519982279b8.png">

↓がundefinedの状態

<img width="1152" alt="2018-05-20 19 01 21" src="https://user-images.githubusercontent.com/12195595/40277820-4ffcac92-5c60-11e8-81c6-e4de5f526e66.png">

**Comment by kakkojc** [comment]
ブラウザについて、Firefox以外にSafariでも試してみましたが、同様の事象が発生しました。

**Comment by yuki-takei** [comment]
@kakkojc ありがとうございます。なるほど、再現確認できました。
近日中に修正しますので少々お待ちください。

**Comment by TatsuyaIse** [comment]
@kakkojc こちら、改修時の人為的なミスによるバグでした。
実際のところ、グループ指定でのページ公開範囲指定ができていないように見えておりましたが、
本件は、公開範囲の表示用文字列の定義をグループACLのUI改善(現在進行中)時に誤って削除してしまっていたため、 Undefined との表示になっておりました。
#419 こちらにて修正しておりますので、次回リリースにて反映される予定です。

**Comment by kakkojc** [comment]
@TatsuyaIse ご対応いただきありがとうございました。PRを拝見したところ`lib/models/page.js`のコメントアウト箇所を修正されていたように見受けられます。当該箇所のコメントアウトが行われてしまったのは4/23かと思いますが、今回バグの報告をさせていただいたのv3.0.7は4/16にリリースされたバージョンのようなので、コメントアウトが原因では無いような気がしております。

また、現在の最新版であるv3.0.13ではそもそも当該箇所はコメントアウトされておりませんが、https://github.com/weseek/growi/issues/410#issuecomment-390470186 に報告させていただいたのと同じ事象が発生します。直っているのであればよいのですが、もしかしたら修正できていないのではないかと思い連絡させていただきました。
試しに、v3.0.13で修正いただいた箇所をコメントアウトしてみましたが、ここのコメントアウトを行うと編集時に「特定グループのみ」での保存ができなくなるようでした。

誤りがあれば申し訳ありません。

**Comment by TatsuyaIse** [comment]
@kakkojc コメント頂きありがとうございます。
大変申し訳ございません。私の認識不足で本 Issue に上げていただいた問題を、別の問題と認識齟齬をしてしまい誤った対応を行なったPRをもって Issue をクローズしておりました。
再度コメントを頂けなければ気づかずに誤った対応でクローズされたままだった可能性もあります。ありがとうございました。
本 Issue を Reopen し、再度対応させていただきますので、今後ともよろしくお願いいたします。
