### ISSUE TITLE
Bug: Editor is broken on IE11

### ISSUE THREAD

**Issue by otas8070** [weseek/growi#426]
Environment
------------
OS:　Windows7
Browser: IE11

How to reproduce? (再現手順)
---------------------------

1.  既に存在するページに行き、編集をクリック
2. edit-formページに飛ぶ

What happens? (症状)
---------------------

- 下部のメニュー(ThemeやKeymapや更新ボタンの)が上に現れる
- 「更新」ボタンが消失し、ページを更新することができない

What is the expected result? (期待される動作)
-------------------------------------------

- 下部メニューが正しく表示される
- 「更新」ボタンが表示され、ページ更新できるようになる

Note
----

- 新規にページを作成する場合のedit-formでは、問題ない。既にあるページを編集する場合のみ問題が発生する。

**Comment by yuki-takei** [comment]
@otas8070 ご報告ありがとうございます。
たった今再現を確認し、修正を反映させました。v3.1.0 リリースをお待ちください。

※なお、今回はちょっとコード追加したら直ったのでよかったのですが、基本的に IE11 は正常動作させるための対象環境としてみていないので、今後利用できなくなる可能性もあります。予めご了承ください。
