### ISSUE TITLE
Bug: Keyword highlights disappear when searching pages

### ISSUE THREAD

**Issue by kaoritokashiki** [weseek/growi#4292]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |MacOS|
|GROWI     |4.4.2|
|node.js   |6.14.15|
|yarn       |1.22.5|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

searching pages with keyword

What happens? (症状)
---------------------
Keyword highlights disappear when searching pages

What is the expected result? (期待される動作)
-------------------------------------------
Keyword highlights remain when searching pages

**Comment by yuki-takei** [comment]
fixed by #4312
