### ISSUE TITLE
[3.1.0-RC2] Has been displayed unknown bootstrap's alert. affected by GroupACL?

### ISSUE THREAD

**Issue by kouki-o** [weseek/growi#431]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | unknown |
|GROWI     |3.1.0-RC2|
|node.js   | (snip use docker image) |
|npm       | (snip use docker image) |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10|
|browser   |Google Chrome 66.0.3359.181|

How to reproduce? (再現手順)
---------------------------

1. login
1. enable GroupACL in admin page.
1. create page in personal space ( /user/<account name>/memo/YYYY/MM/dd )
    * Page setting
        * [GroupACL] set *public*

What happens? (症状)
---------------------

![image 3](https://user-images.githubusercontent.com/13145344/40636646-0c8cd446-633b-11e8-81b7-46cc2b9a45dd.png)

* has been displayed unknown bootstrap's alert.

What is the expected result? (期待される動作)
-------------------------------------------

* not to display it, if there is nothing.

Note
----

- 
-

**Comment by kouki-o** [comment]
same issue: #432

**Comment by yuki-takei** [comment]
@kouki-o This would be resolved at v3.1.0 and I can't reproduce.
Please write the procedure to reproduce 100%.

**Comment by yuki-takei** [comment]
OK, now I confirmed to reproduce, but not 100%...

**Comment by yuki-takei** [comment]
This might be reproduced only when using Group ACL.
This doesn't occured when 'Public' grant.
