### ISSUE TITLE
Bug: VIMモードのとき3文字以上消せない

### ISSUE THREAD

**Issue by 3265** [weseek/growi#4328]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04|
|GROWI     |4.2.20|
|node.js   |14.17.6|
|npm       |6.14.15|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Manjaro Linux|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. process 1
  Editorを開く (VIMモード)
1. process 2
  複数行入力して、最後の行にいく
1. process 3
  InsertモードでBackspaceで文字を消すが3文字以上消せない

What happens? (症状)
---------------------

- symptom 1
  - 三文字以上消せない

What is the expected result? (期待される動作)
-------------------------------------------

- 任意の文字を消せる

**Comment by yuki-takei** [comment]
@mgoldchild 
ご報告ありがとうございます。再現しました。
react-codemirror2 での 以下の問題と同様でした。

https://github.com/scniro/react-codemirror2/issues/37

修正しますので次のバージョンのリリースをお待ちください。

**Comment by yuki-takei** [comment]
@mgoldchild すみません、この問題を直すために #4347 で入れた `detatch` オプションの影響で v4.4.4 では様々な機能が使えなくなってしまいました。問題を修正するため、一旦 #4347 の変更は revert します。そのため、この症状はしばらく回避できないままになる見込みです。

以上ご報告です。

**Comment by yuki-takei** [comment]
今 v6.1.0 で試してみたところ、この症状は起きなくなっているようです。(いつ直ったのかは定かではありませんが)

この Issue はクローズします。
