### ISSUE TITLE
IE11にて文字の入力ができない

### ISSUE THREAD

**Issue by otas8070** [weseek/growi#433]
v3.1リリースお疲れ様です。いつも利用させて頂き感謝しております。
導入を検討しておりますが、社内でIE11しか使えないという状況があり、
I動作対象外ということは重々承知しておりますが、
気長に待ちますので、どうぞよろしくお願い致します。

Environment
------------
- ＩＥ１１
- win７

How to reproduce? (再現手順)
---------------------------

- / (index) のページにて、検索バーや新しいページ作成時のinputタグの部分をクリックする。
 - ＊他の記事ページであれば再現する。

What happens? (症状)
---------------------

- inputタグ部分に入力しようと、クリックするが入力ができない。
- IE11のアドレスバー(urlのところ)も入力が不可になる。

＊検索結果のページやログイン画面では、再現しない。

What is the expected result? (期待される動作)
-------------------------------------------

inputタグ部に入力ができる。

**Comment by yuki-takei** [comment]
@otas8070 ご報告ありがとうございます。こちらでも再現は確認できましたが、既にブラウザの開発者コンソールで多くのエラーが出ていますので、やはりIE11では動かない、ということになりそうです。

ワークアラウンド的なもので恐縮ですが、一度任意のページで「Edit」タブに切り替えてから「View」に戻ると検索バーやページ作成モーダルの input でも入力可能になるようです。

**Comment by yuki-takei** [comment]
@otas8070 一応 #489 でコンソールのエラーが出ないようにはしてみたのですが、初回アクセス時はやはり入力できない症状が出るようです。

元々動作対象外のブラウザのため、申し訳ないのですがこの issue は close します。
