### ISSUE TITLE
Bug: グループ管理ページ内のページ一覧に不必要な項目が表示される

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#434]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.1.0|
|node.js   |8.11.2|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.4|
|browser   |Firefox 60.0.1|

How to reproduce? (再現手順)
---------------------------

1. 編集からページの公開範囲を特定のグループのみに設定する
1. ページを完全削除する

What happens? (症状)
---------------------

- `/admin/user-group-detail/<group name>` のページ一覧に、削除したページと思われる項目が名称なしの状態でリストに表示される

    | 削除前 | 削除後 |
    |:---:|:---:|
    | <img width="252" alt="before_deletion" src="https://user-images.githubusercontent.com/34315080/40646163-6568e1d6-6363-11e8-999b-f33ffcfa84a9.png"> | <img width="255" alt="after_deletion" src="https://user-images.githubusercontent.com/34315080/40646191-73836534-6363-11e8-8edb-3e279a08fc5e.png"> |

What is the expected result? (期待される動作)
-------------------------------------------

- 不必要な項目（空行）をリストに表示させない

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。再現確認し、先ほど修正を push しました。
ただ、当該事象が新たに起こることはないようになったのですが、現在運用中の環境に存在するゴミデータを一括削除するコードを入れるのは危険なので、そのままになってしまいます。

残っていて悪さをするものではありませんが、気になるようでしたら一度グループを削除してください。
