### ISSUE TITLE
Request: 編集モード開始時にサーバの最新情報を元に編集を開始するようにしてほしい

### ISSUE THREAD

**Issue by gimKondo** [weseek/growi#4341]
## Informations
**Is your feature request related to a problem? Please describe.**

現在、4.3.2を使っており、以下の現象が起こっています。
([Security Policy](https://github.com/weseek/growi/security/policy)のサポート外ですが機能面の話ですのでポストさせていただきました)

1. AさんがWikiページを開いておく
2. Bさんがそのページを更新する
3. Aさんが編集ボタンを押すと、1時点の情報で編集が開始される
4. Aさんが保存しようとすると、保存エラーになる

**Describe the solution you'd like**

3で編集を開始する時点で、(ローカルの情報ではなく)2の更新を取り込んだ最新バージョンを元に編集が開始されれば、この減少は軽減されるのではないかと考えています。
具体的には以下のような動作を想定しています。

1. AさんがWikiページを開いておく
2. Bさんがそのページを更新する
3. Aさんが編集ボタンを押すと、2で更新されたバージョンに対して編集を開始する

これだと編集モードを開始後にBさんが更新した場合にAさんが更新できなくなる問題は防げませんが、現実としてよくあるパターンは、

1. AさんがWikiページを長時間開きっぱなしにしている
2. Bさんがそのページを更新する
3. Aさんが編集を開始する

というケースでのエラーなので、多くを救えるのではないかと考えています。

**Comment by yuki-takei** [comment]
websocket が正常に作用していればページ下部に以下のようなアラートが出るのですが、これでは不足でしょうか？

![image](https://user-images.githubusercontent.com/1638767/134152650-5e026e71-e6c6-4923-9e5b-98d8860c7ac8.png)

「AさんがWikiページを長時間開きっぱなしにしている」状況下では websocket の通信はもしかすると切れているかもしれないのと、その辺の同期を完全に自動でやってほしいという要求に対してはたしかに現状の実装では不足していると思います。

**Comment by gimKondo** [comment]
回答ありがとうございます。
確認しましたところ、利用中のシステム構成の問題でwebsocketが上手く動いていないようだということが分かりました。
お騒がせしました。
構成を修正して、上手く動くようになったら、情報共有のため問題点と修正方法をレポートさせていただこうと思います。

> 「AさんがWikiページを長時間開きっぱなしにしている」状況下では websocket の通信はもしかすると切れているかもしれない

なるほど。
「編集」を押したタイミングで明示的にリクエストを飛ばさない分、websocket方式だと発生しうるのですね。
こちらはwebsocketが正常に動くように環境を修正してからも現実問題として発生するようであれば、また報告させていただこうと思います。

> その辺の同期を完全に自動でやってほしい

最新を取らずに編集することはないと思いますので、同期も自動だとより良さそうですね！
ただ、今回上げさせてもらったのは、(システム構築の際の問題があり)提示していただいた警告ポップアップが出てない認識の元でのものですので、今回のissueの対象外とさせてください。

**Comment by yuki-takei** [comment]
了解です、ご報告お待ちしております。

**Comment by gimKondo** [comment]
アラートが出ないのは、リバースプロキシに使用しているnginxがwebsocketの通信を許可していないことが問題でした。
下記設定を入れてwebsocketを通すことで、無事アラートが出るようになりました。
http://nginx.org/en/docs/http/websocket.html

以上、お騒がせしましたが、このレポートを持ってissueをクローズさせていただきます。
