### ISSUE TITLE
Bug: HTML escaped characters in markdown are unexpectedly unescaped after saved

### ISSUE THREAD

**Issue by dfukagaw28** [weseek/growi#448]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | [demo site](https://demo.crowi-plus.org/) |
|GROWI     |3.1.1|
|node.js   |8.11.2|
|npm       |5.6.0|
|yarn       |1.6.0|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 1709|
|browser   |Chrome 67.0.3396.62 (64 bit)|

How to reproduce? (再現手順)
---------------------------

1. 新しいページを作成する
1. 編集画面で以下の通り入力して（実際は，すべて半角文字）保存し，再度編集をおこなう
```
＆ａｍｐ；ａｍｐ；ａｍｐ；ａｍｐ；
```
「‘」は back quote U+0060

What happens? (症状)
---------------------

- 再編集時，編集用テキストエリアに以下のように表示される（実際はすべて半角）
```
＆ａｍｐ；ａｍｐ；ａｍｐ；
```
- つまり，HTML エスケープした文字がアンエスケープされてしまう
- 保存のたびに「ａｍｐ；」が１つずつ減り，最終的に「＆」となる

What is the expected result? (期待される動作)
-------------------------------------------

- 保存した文字列が，再編集後も変化しない

**Comment by yuki-takei** [comment]
@dfukagaw28 ご報告ありがとうございます。再現を確認しました。
また、先ほど対策を施した版を `fix/448-do-not-decodeHTML` ブランチにコミットしました。

ぱっと見よさそうなんですが、ちょっとどれくらい影響がでるかわからないので、弊社内でテストした後、然るべきタイミングでリリースしようと思います。次回リリース v3.1.2 へのマージは見送り、v3.1.3 以降になる予定です。今しばらくお待ちください。

**Comment by dfukagaw28** [comment]
3.1.3-RC で修正されていることを確認しました．ありがとうございました！
