### ISSUE TITLE
Discussion: FILE_UPLOAD=local 環境下での Attachment 保存場所の予期しない変更(bug 含む)への対処について

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#4528]
## Informations
**Is your feature request related to a problem? Please describe.**
- ローカルでビルド/添付ファイルを保存しているユーザ向けのリクエストです。
- GROWIのファイルアップロード先をLocalに指定している時、仕様変更でpublicの場所が変わってしまうと別の場所に新規にpublicディレクトリが作成され、過去に作られたpublicディレクトリは参照されなくなってしまう。そのため、添付ファイルへのリンクが切れてしまい画像などが表示されなくなる。
- この問題自体は過去のpublicの内容を新しいpublicにコピーすることで解決できるが、そもそもpublicが移動したことに気が付けなければ問題を自己解決することができない。(実際Twitterで数人のユーザがこの問題にぶつかっていたのを確認しています)
- おそらく過去2回はattachmentの場所が変更されていると思います。今後も変更があるのであれば教えてほしいです。

**Describe the solution you'd like**
- Localの添付ファイルの保存先が仕様変更された時にアップグレードガイド又はリリースノートで対応方法を告知してほしい。

**Describe alternatives you've considered**
- 過去のpublicにある添付ファイルも参照するようにしてほしい。
- もしくはpublicの場所を環境変数などで指定できるようにしてほしい。

いつも便利に使わせていただいてます。よろしくお願いします。

**Comment by yamatomo717** [comment]
横から失礼致します。

私の方でも
`/opt/growi/public` から `/opt/growi/packages/app/public` に
変わった際にトラブルがございましたので情報提供致します。

1. from version と to version

from version: 4.3.3 `/opt/growi/public`
to verstion: 4.4.0 `/opt/growi/packages/app/public`

2. 症状

> GROWIのファイルアップロード先をLocalに指定している時、仕様変更でpublicの場所が変わってしまうと別の場所に新規にpublicディレクトリが作成され、過去に作られたpublicディレクトリは参照されなくなってしまう。そのため、添付ファイルへのリンクが切れてしまい画像などが表示されなくなる。

こちらの通りです。
4.3.3 以前でローカルに保存した画像( /opt/growi/public/uploads に保存した画像)が表示されなくなります。

3. ワークアラウンド

私の環境では、
`/opt/growi/public/uploads` を `/opt/growi/packages/app/public/uploads` に移動することで解決しました。
