### ISSUE TITLE
Bug: 「マークダウン形式でページをエクスポート」がエラーとなる

### ISSUE THREAD

**Issue by t-tsuzuki-skgrp** [weseek/growi#4565]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian GNU/Linux 9|
|GROWI     |4.4.9|
|node.js   |14.18.1|
|npm       |6.14.15|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Professional(64bit)|
|browser   |Chrome 95.0.4638.69|

How to reproduce? (再現手順)
---------------------------

1. 任意のユーザーでログイン
1. 任意のページで3点リーダーをクリックして「マークダウン形式でページをエクスポート」をクリック

What happens? (症状)
---------------------

- 以下のエラーJSONが返されます

```json
{"errors":[{"message":"Cannot read property 'liker' of null","code":null}]}
```

What is the expected result? (期待される動作)
-------------------------------------------

- 指定したページのMarkdownファイルが表示orダウンロードされる

Note
----

- [デモサイト](https://demo.growi.org/)でも同様の症状でした
- Firefox 93.0でも同様でした。

**Comment by miya** [comment]
@t-tsuzuki-skgrp 様

issue の起票ありがとうございます！
こちらのバグの再現を確認致しました。これから改修に入らせて頂きますのでリリースまで今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@t-tsuzuki-skgrp 修正完了しました。次回リリースをお待ちください。
