### ISSUE TITLE
Bug: Put requests fail CSRF verification

### ISSUE THREAD

**Issue by stevenfukase** [weseek/growi#4575]
Environment
-----------

### Host
| item     | version |
| ---      | --- |
| OS        | Windows 10 Home ver. 21H1 |
| GROWI     | 4.4.10-RC.0 |
| node.js   | 14.18.1 |
| npm       | 6.14.15 |
| yarn      | 1.22.15 |
| Using Docker | yes |
| Using growi-docker-compose | yes |

### Client
| item     | version |
| ---      | --- |
| OS        | Windows 10 Home ver.21H1 |
| browser   | Google Chrome |

How to reproduce?
-----------------
1. Go to any edit page
1. Press Update

What happens?
-------------
- Updating page fails
![Capture](https://user-images.githubusercontent.com/66785624/139644031-877191ed-7f29-4238-8046-2157d780e06a.PNG)
![Capture](https://user-images.githubusercontent.com/66785624/139644098-0b60e7b5-fc4f-4e9c-81c9-165af551a1db.PNG)

What is the expected result?
----------------------------
- Update succeeds

Note
----
- Also happens when updating Site URL from admin page
![Capture](https://user-images.githubusercontent.com/66785624/139644234-5135a0e6-2cd7-4020-afed-7f85ca4baf1a.PNG)

**Comment by yuki-takei** [comment]
fixed by #4577
