### ISSUE TITLE
Bug: draw.io編集ダイアログ表示中ダイアログ外をクリックすると確認なく編集がキャンセルされる

### ISSUE THREAD

**Issue by nakashimaki** [weseek/growi#4586]
#3637 の類似課題です。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04 |
|GROWI     |4.4.5|
|node.js   |16.13.0|
|npm       |8.1.0|
|yarn      |1.22.15|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows |
|browser   | Microsoft Edge |

How to reproduce? (再現手順)
---------------------------

1. Markdown編集画面に移行する
2. 表にキーボードカーソルを合わせてから表編集アイコンをクリック
3. ダイアログが出るので適当に編集してダイアログの外をクリック

What happens? (症状)
---------------------

- 確認なくダイアログ上の編集ログが破棄され、ダイアログが閉じられる

What is the expected result? (期待される動作)
-------------------------------------------

- そもそも外をクリックした程度では閉じられない
   -  現状の表編集ダイアログと同じ挙動が望ましい

Note
----

- 所属組織内のユーザーから要望がありましたので起票いたしました

**Comment by yuki-takei** [comment]
fixed by #4587
