### ISSUE TITLE
コメントに、スレッド形式でコメントしたい

### ISSUE THREAD

**Issue by mizorin** [weseek/growi#466]
## Why

現状のコメントだと、ひたすら下に連なっていきカオスな状態になってしまう。
SlackやGitのコメントみたいに階層ができると見やすくて嬉しい！

![2018-06-09 11 17 14](https://user-images.githubusercontent.com/23519083/41186750-d7afd346-6bd6-11e8-8f05-36eed4c85dd4.png)

Note
----

- 
-

**Comment by yuki-takei** [comment]
@mizorin ご意見ありがとうございます。
ちょっと実装イメージつかなくて、もうちょっと掘り下げたいです。

Slack はチャットツールなので、そもそも参考にするのが難しいです。Reply と Thread がありますが、Reply 相当ならなんとなくわかります。
Thread 相当は既存の「Comments for Older Revision」「Comments for Newer Revision」機能との兼ね合いを考えると、実際問題表示方法が難しいですね…。


> Git のコメント

というのは具体的にどういう機能なんでしょうか…

**Comment by mizorin** [comment]
@yuki-takei 

雑に渡してしまってすみません・・・！
簡単にイメージ作ってみたので確認してみてください。

![2018-06-16 13 09 53](https://user-images.githubusercontent.com/23519083/41495634-98a92a36-7166-11e8-99b6-558ee0c93d53.png)


>Comments for Older Revision」「Comments for Newer Revision」機能との兼ね合いを考えると、実際問題表示方法が難しいですね…。

なるほどです。。これは弊社ではあんまり必要ではない機能だったので意識してなかったです。
Older Revision と Newer Revision を色分けすれば兼ね合いつつも実現できそうな気がします！

**Comment by yuki-takei** [comment]
実装されました。
v3.4.8 リリースまで今しばらくお待ちください。

(お手隙の方がいらっしゃいましたら master ブランチで動作確認・バグ報告等いただけると助かります)
