### ISSUE TITLE
Herokuでデプロイすると古いバージョンのGrowiが展開される

### ISSUE THREAD

**Issue by 0x0c** [weseek/growi#473]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.1.3 RC|
|node.js   |8.11.2|
|npm       |5.10.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.13.5 High Sierra|
|browser   | Safari 11.1.1|

How to reproduce? (再現手順)
---------------------------

1. https://github.com/weseek/growi のREADMEに表示されている「Deplyo to Heroku」ボタンを押し、Herokuにデプロイする

What happens? (症状)
---------------------

- 2018-06-13時点でGrowi 3.1.3 RCがインストールされる

What is the expected result? (期待される動作)
-------------------------------------------

- 2018-06-13時点で最新バージョンであるGrowi 3.1.5がインストールされる

Note
----

- Herokuからデプロイした場合にupgradeする方法がある場合、教えていただきたいです。

**Comment by 0x0c** [comment]
@inductor いま自分も手元でトライしたら3.1.6が入りました...。
1つ記載に誤りがありました。
デプロイしたタイミングは2018/6/5でした。3.1.5のリリースが6/8ですので、私の勘違いでした。
混乱させてしまい申し訳ありません...

このissueはcloseします。
もし、Noteに記載した「Herokuにデプロイしたときにupgradeする方法」をご存知でしたら教えていただけると幸いです。
よろしくお願いいたします。

**Comment by ozasuke** [comment]
@0x0c 
Noteに記載されていた「Herokuにデプロイしたときにupgradeする方法」についてですが、私も困っておりまして、herokuで
