### ISSUE TITLE
Bug:左サイドバーで<details>を使い折りたたまれた項目を開くと表示がされない

### ISSUE THREAD

**Issue by okqi** [weseek/growi#4810]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |AWS Linux?|
|GROWI     |4.4.13|
|Using Docker|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 96.0.4664.45|

How to reproduce? (再現手順)
---------------------------

1. サイドバーメニューに<details>$lsx()</details>のように記述
2. サイドバーメニューを開き項目を開く

What happens? (症状)
---------------------

- 表示エリアが小さいのか、項目が見切れて表示されない
-スクロールさせると表示されることがある

What is the expected result? (期待される動作)
-------------------------------------------

- 折りたたまれた項目が表示される

**Comment by yuki-takei** [comment]
@okqi 修正しました。v4.5.3 リリースをお待ちください。
