### ISSUE TITLE
Imprv: コメント記入があったことがわかるようにして欲しい

### ISSUE THREAD

**Issue by motoisto** [weseek/growi#486]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Centos7|
|GROWI     |3.1.7|
|Using Docker|yes|
Using [growi-docker-compose][growi-docker-compose]|yes|
### Client

| item     | version |
| ---      | --- |
|OS        |windows7|
|browser   |Chrome|

What is the expected result? (期待される動作)
-------------------------------------------

- コメント書き込みがあったことを見つけにくいので、本文書き込みと同様に、コメント書き込みでリストの上位にあげるようにしていただけないでしょうか
- 他の手段でも結構です

**Comment by yuki-takei** [comment]
@motoisto 要望ありがとうございます。検討します。

**Comment by yuki-takei** [comment]
@motoisto 改修を行いました。次回リリース(v3.1.8)で反映される予定です。
