### ISSUE TITLE
LDAP 連携したユーザのメールアドレスも LDAP から取得して欲しい

### ISSUE THREAD

**Issue by aviscaerulea** [weseek/growi#490]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.5|
|GROWI     |3.1.6|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

What happens? (症状)
---------------------

LDAP 上のユーザアカウントでログインしたが、メールアドレスは `change-it-og7axSCGkAv0@example.com` のようになっていた。

What is the expected result? (期待される動作)
-------------------------------------------

LDAP 上の mail 属性にあるメールアドレスを取得して設定すること。

**Comment by yuki-takei** [comment]
@aviscaerulea ご要望ありがとうございます。こちら結構問い合わせ多いので、実装検討します。
メールアドレスは DB 上で unique 制約があるため必ず入れられるとは限りませんが、重複していない場合は自動でセットするようにしようと思います。

**Comment by yuki-takei** [comment]
@aviscaerulea 実装完了しました。既にDB内に同じメールアドレスを持つユーザーがいない場合に限り設定します。重複している場合は今まで通り、`ランダムな文字列@example.com` を入れます。

次回リリース(v3.1.13)で利用可能になる予定です。

**Comment by aviscaerulea** [comment]
ご対応ありがとうございます！
これでだいぶ手間が省けるので助かります。
