### ISSUE TITLE
Bug: User trigger notifacationでデフォルトパターン設定後も記事作成時にInput channelsが自動入力されない

### ISSUE THREAD

**Issue by dashwood8691** [weseek/growi#4928]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.6 LTS|
|GROWI     |4.4.8 (Production) / 4.5.2 (Staging)|
|node.js   |14.18.0 (Production) / 14.18.2 (Staging)|
|npm       |6.14.15|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 21H1|
|browser   |Firefox 95.0 (64-bit) / Chrome 96.0.4664.93|

How to reproduce? (再現手順)
---------------------------

1. Slack連携でCustom bot (without proxy)を設定
1. 外部ツールへの通知でUser trigger notificationにデフォルトパターンを指定（Global notificationは未指定）
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30547/146468004-8d66b8c2-c730-410d-89c9-0d016175b880.png">
1. User trigger notificationに指定したパス以下に新規記事を作成

What happens? (症状)
---------------------

- User trigger notificationのデフォルトパターンに指定したSlack channelが自動入力されない
<img width="500" alt="image" src="https://user-images.githubusercontent.com/30547/146468112-d3aec7e7-b902-4ebe-94e5-1837f9d6ebb6.png">

What is the expected result? (期待される動作)
-------------------------------------------

- 指定したパスで記事を作成した場合はSlack channelが自動入力される

  参考：[User Trigger Notification 設定](https://docs.growi.org/ja/admin-guide/management-cookbook/external-notification.html#user-trigger-notification-%E8%A8%AD%E5%AE%9A)

**Comment by kaoritokashiki** [comment]
Issueの起票ありがとうございます！
再現確認をしたところ、再現条件に補足がありますので訂正させていただきます。

> How to reproduce? (再現手順)
Slack連携(新: GROWI Bot / 旧: IncomingWebhooks 設定)に関わらず、記事作成時にInput channelsが自動入力されない 
ですね。

修正対応を進めてまいりますので、しばらくお待ちいただければと思います。

**Comment by kaoritokashiki** [comment]
@dashwood8691

お待たせいたしました、バグの修正が完了しましたのでご報告させていただきます。

修正版のリリースバージョンは
５系では 👉🏻 v5.0.8
４系では 👉🏻 v4.5.22
になります。

次回リリースをお待ちください。
引き続き GROWI をよろしくお願い致します!
