### ISSUE TITLE
パーマネントリンクでコピーした URL について

### ISSUE THREAD

**Issue by aviscaerulea** [weseek/growi#493]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.5|
|GROWI     |3.1.6|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro|
|browser   |Chrome 67, Firefox 60.0.2|

What happens? (症状)
---------------------

例えば、`/xxx/yyy/zzz` という階層のページを作る。
画面上のパーマネントリンクが `http://somedomain:3000/5b28bc5e208986001ed47bf4` のように表示されていて、それをボタンからクリップボードコピーすると `/xxx/yyy/zzzhttp://somedomain:3000/5b28bc5e208986001ed47bf4` がコピーされてしまう。

HTML 的には以下のようになっていた。

``` html
<button type="button" class="btn btn-default btn-copy-link" style="padding: 0px 2px; vertical-align: text-top; font-size: 1em;" data-clipboard-text="/xxx/yyy/zzz
http://somedomain:3000/5b28bc5e208986001ed47bf4" id="btnCopyRevisionUrl" data-toggle="tooltip" data-container="body" title="" data-placement="bottom" data-trigger="manual" data-original-title="copied!"><i class="ti-clipboard"></i></button>
```

What is the expected result? (期待される動作)
-------------------------------------------
表示されているパーマネントリンクと同じ内容がクリップボードにコピーされること。

**Comment by yuki-takei** [comment]
@aviscaerulea こちらは一応仕様になります。

当該ボタンは、ページパス+改行コード付きで
```
/xxx/yyy/zzz
http://somedomain:3000/5b28bc5e208986001ed47bf4
```
という内容のテキストをコピーすることを目的としています。

「じゃあパーマリンク文字列のみコピーするボタンはどこにあるんだ」と言われると今ありませんという状態なのですが…

**Comment by k84rc** [comment]
`/admin/customize` のカスタムスクリプトで以下のように設定することで、期待される動作が実現できるかと思います。

```javascript
$(() => {
  // URL をコピーする際にページパスをコピーしないようにする
  var rt = $('#btnCopyRevisionUrl').attr('data-clipboard-text');
  var r = rt.split('\n')[1];
  $('#btnCopyRevisionUrl').attr('data-clipboard-text', r);
});
```

**Comment by aviscaerulea** [comment]
なるほど、そうだったんですね。
クリップボードコピーのアイコン位置から URL のみコピーするものだと勝手に思い込んでいました。
ちなみに、そのコピー内容は Markdown リンクでもないのには何か理由があるのでしょうか？

上記で教えていただいたカスタムスクリプトはありがたく使わせていただこうと思います。

**Comment by yuki-takei** [comment]
> そのコピー内容は Markdown リンクでもないのには何か理由があるのでしょうか？

この「Markdown リンク」が何を指すのかよく分かっていませんが、
```
[/xxx/yyy/zzz](http://somedomain:3000/5b28bc5e208986001ed47bf4)
```
という文字列を意図していますか？

今の実装になった理由としてはその当時に「ページタイトル(パス)とパーマリンクを一緒にコピーして Slack に貼り付けたい」という要求があったからですね。

ともあれ k84rc さんのカスタムスクリプトの助言もありますので、この Issue は close しようと思います。

**Comment by aviscaerulea** [comment]
すみません、Markdown リンクという言葉は意味不明になっていましたね。
はい、ご認識の通りの Markdown 上でリンクとして扱える書式のことでした。
