### ISSUE TITLE
Bug: Attachments not showing up when uploaded to a new page

### ISSUE THREAD

**Issue by stevenfukase** [weseek/growi#4985]
Environment
------------

### Host
Tested with two instances of GROWI:
| Item  | Version |
| --- | --- |
| Dev Wiki | 4.5.3 |

| Item     | Version |
| --- | --- |
| OS | MacOS Monterey |
| GROWI | 4.5.4-RC.0 |
| node.js | 14.18.2 |
| NPM | 6.14.15 |
| Using Docker | Yes |
| Using growi-docker-compose | Yes |

### Client
| Item | Version |
| --- | --- |
| OS | MacOS Monterey|
| Browser | Google Chrome v.96.0.4664.110 (Official Build) (arm64) |

How to reproduce?
---------------------------
1. Create a new wiki page and wait for the edit screen to show up (Don't press Create)
1. Upload an attachment to the new page

What happens?
---------------------
1. The attachment will not show up on the edit page
1. The page contents will be replaced by an H1 text with the path of the page
1. The page is saved with the "Only Me" grant
<img width="628" alt="Screen Shot 2021-12-22 at 4 35 09 PM" src="https://user-images.githubusercontent.com/66785624/147054519-d5eb1cb9-5a0a-4de4-a4e8-c0b40d5601fb.png">

What is the expected result?
-------------------------------------------
- The attachment will show up on the edit page, just like how it works when updating an existing page.
- The page will be saved with the currently selected grant settings

Note
----
- Has nothing to do with PR #4957 (The bug is present before merging the branch)
- Works fine when adding an attachment to an existing page
- The upload itself seems to be successful as it shows up on the Attachment Data tab on the View page.
<img width="1401" alt="Screen Shot 2021-12-22 at 4 44 06 PM" src="https://user-images.githubusercontent.com/66785624/147054775-82e18291-47fc-4d5d-be2d-4ec9a037f888.png">

**Comment by yuki-takei** [comment]
@nakashimaki 検証ありがとうございました。再現しないと言うことで close します。
