### ISSUE TITLE
Bug: 「テンプレートページの作成/編集」のダイアログでボタンが正しく表示されていない

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#499]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.1.7|
|node.js   |8.11.3|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 67.0.3396.87<br>Firefox 60.0.2|

How to reproduce? (再現手順)
---------------------------

- 任意のページで「テンプレートページの作成/編集」ダイアログを開く

What happens? (症状)
---------------------

- 編集画面に移動するためのボタンが正しく表示されていない

![image](https://user-images.githubusercontent.com/34315080/41735795-9d86d2d4-75c5-11e8-8d92-f7e70a588083.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 「作成」や「編集」の文字がボタンに表示される

**Comment by mizozobu** [comment]
@k84rc ご指摘ありがとうございます。各ページにテンプレートの有無をAPIで確認して「作成」「編集」を切り替えていたのですが、ファイルを読み込む順番の関係でうまく作動していませんでした。
予想以上に複雑だったため、今回は、APIを使わずに、「編集」で統一するようにして対応しました。最新のmasterでは修正されています。

**Comment by yuki-takei** [comment]
fixed by #506
