### ISSUE TITLE
Request: vendors.*.chunk.js is too large

### ISSUE THREAD

**Issue by yy0931** [weseek/growi#5022]
## Informations
It takes 20-40 secs to download vendors.*.chunk.js on my environment when there is no local cache, which is unbearable. It takes more when I access the site from mobile phones.
![image](https://user-images.githubusercontent.com/54441600/148025196-56350175-c217-4435-97a0-079353f3bc1a.png)

We should remove unnecessary files bundled in vendors.*.chunk.js. It is 6.82MB at v4.5.2 and 7.2MB at current master branch (0b77d0).

The following screenshot is the output of `ANALYZE_BUNDLE_SIZE=1 yarn build:prod` (packages/app/report/bundle-analyzer.html). Can mongoose, jshint, `codemirror/src`, elliptic, etc. be removed from  the client JavaScript code?

> 

![image](https://user-images.githubusercontent.com/54441600/148030416-bf56137a-eca0-44f8-b82f-551bcec596aa.png)

In addition, the JavaScript files doesn't seem to be gzipped.

![image](https://user-images.githubusercontent.com/54441600/148031923-8b8d4c2e-00fa-44ad-b42e-da4aa36e3fb7.png)

**Comment by yuki-takei** [comment]
@yy0931 
You're right, and we are aware of this issue as well. 

## 1. "Can mongoose, jshint, codemirror/src, elliptic, etc. be removed from the client JavaScript code?"

It might be possible and we really want to do so, but we don't have enough time to investigate at the moment.

## 2. Apply Next.js plan

There is a plan to apply Next.js to GROWI and we expect that it will help to optimize the size of bundle automatically.

Now we are working hard to release v5.0.0 at mid of Febrary that includes implementation for page tree feature, Next.js plan will be launched after that. We had planned to optimize bundles at the same time.


So we would like you to wait untill that schedule has done.

You can also investigate the cause of increasing bundle and send us Pull Requests if you want.

Thank you.
