### ISSUE TITLE
Bug: Error: The specified instance couldn't register because same id has already been registered

### ISSUE THREAD

**Issue by YoshitakaMo** [weseek/growi#5031]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 8.1.1911|
|GROWI     |4.5.4|
|node.js   |14.15.0|
|npm       |6.14.8|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 12.1|
|browser   |Google Chrome 96.0.4664.110|

How to reproduce? (再現手順)
---------------------------

Growiの任意のページ内見出しへの直リンクをブラウザのURLに入力する。または、Growi内で、あるページに埋め込まれている別のページの見出しへのリンクをクリックして移動しようとする。ただし、同一ページ内で見出し目次のリンクを用いたジャンプ（ページ内遷移）では発生しない。
例：https://growi.page/#Startup のようなURLへの直リンクでStartupという見出しに飛ぼうとする

v4.5.4で確認、v4.4.8では発生しなかった。

What happens? (症状)
---------------------

以下のようなエラーメッセージが現れ、目的とするページの見出しに直接移動することができない。

![ScreenShot 2022-01-05 14 10 32](https://user-images.githubusercontent.com/16487484/148165205-170207c4-9e4e-45d9-806b-99b09f10982a.png)

What is the expected result? (期待される動作)
-------------------------------------------

- ページ内リンクが正しく機能する。

Note
----

**Comment by yuki-takei** [comment]
@YoshitakaMo 
ご報告ありがとうございます。その事象はこちらでも確認していますが、たぶん master ブランチでは直っているはずで、v4.5.5 リリースで修正されるはずです(あとで確認します)

**Comment by yuki-takei** [comment]
こちらの変更で直っていることを確認しました。まもなくリリースしますのでもう少々お待ちください。

https://github.com/weseek/growi/commit/573216cc98a509424f50a32427702e0c50a2fe97#diff-a01c8fd14689752468debeddc10170fa69e95fe056cf8ecf18901ba6215d4b68

**Comment by YoshitakaMo** [comment]
@yuki-takei v4.5.5のリリースありがとうございます。
しかしながら当方の環境で4.5.5にアップデートし、動作を確かめてみましたのですが、同様のエラーながら少し異なる詳細が得られました。画像を添付いたします。
<img width="1397" alt="Screenshot 2022-01-06 0 10 44" src="https://user-images.githubusercontent.com/16487484/148240791-953973e1-c4be-4541-ae39-1337e0e16202.png">

**Comment by yuki-takei** [comment]
@YoshitakaMo 

https://github.com/weseek/growi/pull/5043
こちらの PR、別件の修正でしたが副作用で本件も修正されたようです。

上記を含む v4.5.6 をリリースしましたのでそちらで再度確認いただけますでしょうか。

**Comment by YoshitakaMo** [comment]
@yuki-takei 当方でv4.5.6にアップデートしたところ、期待の動作をするようになりました。どうもありがとうございました。
