### ISSUE TITLE
Bug: Production ビルドで /admin/customize のコードエディタが崩れている

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#511]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.1.9|
|node.js   |8.11.3|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 67.0.3396.87 / Firefox 60.0.2|

How to reproduce? (再現手順)
---------------------------

- `/admin/customize` にアクセス

What happens? (症状)
---------------------

- カスタムヘッダーHTML、カスタム CSS および カスタムスクリプトのコードエディタが崩れている
- これに伴い、編集ができない

![image](https://user-images.githubusercontent.com/34315080/41862363-9af4ba56-78de-11e8-9f3b-50bce18003e2.png)

What is the expected result? (期待される動作)
-------------------------------------------

- コードエディタが正しく表示される
- 編集ができる

**Comment by yuki-takei** [comment]
[mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) のせいでした。。
webpack 4 化で地雷を踏み抜いた…

[extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin)@next に戻すことで修正できました。
