### ISSUE TITLE
Bug: 公開ページをログインせずに開くとInternal Server Errorになる

### ISSUE THREAD

**Issue by h-kotou** [weseek/growi#5151]
# Environment
## Host
| item     | version |
| ---      | --- |
|OS        |BusyBox v1.24.1|
|GROWI     |4.5.9|
|node.js   |14.18.3|
|npm       |6.14.15|
|yarn      |1.22.15|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

## Client1
|item|version|
| ---      | --- |
|OS|Windows 11|
|browser|Chrome 97.0.4692.99（Official Build） （64 ビット）|

## Client2
|item|version|
| ---      | --- |
|OS|iPad OS 15.2.1|
|browser|Mobile Safari 15.2 iOS 15.2.1|

## How to reproduce? (再現手順)
1. git cloneする。
2. docker-compose up -dを実行する。
3. ユーザーを作成してログインする。
4. 設定→セキュリティ設定の項目を開き、ゲストユーザーのアクセスを許可(ゲストユーザーも閲覧のみ可能)に設定する。
5. ログインしていない状態で「公開」設定になっているページを開く（トップページなど）。

## What happens? (症状)
Internal Server Errorが表示される。
※ 非公開のページを開いた場合はページが存在しないという表示になる。

## What is the expected result? (期待される動作)
開きたい公開ページが表示される。

**Comment by yuki-takei** [comment]
@h-kotou ご報告ありがとうございます。

再現条件としては、管理画面のセキュリティ設定で「Restrict complete deletion of pages (ページの完全削除)」オプションを「Admin and author (管理者とページ作者が可能)」に設定している状態が必要であることを補足しておきます。

この問題を修正し、v4.5.11 としてリリースしました。ご確認ください。
https://github.com/weseek/growi/releases/tag/v4.5.11
