### ISSUE TITLE
Bug: 検索結果で相対パスのリンクがおかしい

### ISSUE THREAD

**Issue by ryohi15** [weseek/growi#5180]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.5.11|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

How to reproduce? (再現手順)
---------------------------

1. 「/テスト/ページ」のようなページを作成し以下を入力
` [子ページ](子ページ)`　←リンク先は、「/テスト/子ページ」。
1. 「/テスト/ページ」が検索結果に入るような検索をする
1. 検索結果の右ペインのページ本文にあるリンク先をクリック

What happens? (症状)
---------------------

「/子ページ」にリンクしてしまう

What is the expected result? (期待される動作)
-------------------------------------------

「/テスト/子ページ」にリンクされる

**Comment by yuki-takei** [comment]
@ryohi15 現状、markdown のリンク生成は markdown-it に任せているので仕様になります。
