### ISSUE TITLE
Bug: スタイルシートの記述で href が undefined となっている箇所がある

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#519]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.1.11|
|node.js   |8.11.3|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Google Chrome 67.0.3396.99 / Firefox 61.0|

How to reproduce? (再現手順)
---------------------------

- 任意のページにアクセスする

What happens? (症状)
---------------------

- ソース中のスタイルシートの記述で `<link rel="stylesheet" href="undefined">` となっている箇所がある

What is the expected result? (期待される動作)
-------------------------------------------

- 当該箇所が省略されるか正しいスタイルシートへの URI が指定されている

Note
----

（Web サーバーの設定によっては？）ログイン時に、開発者ツールのコンソールに
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://{hostname}/undefined".
```
と表示され、`/undefined` にリダイレクトされる

**Comment by yuki-takei** [comment]
@k84rc ご報告ありがとうございます。
#511 の修正対応の結果、吐き出される CSS の構成が変わってしまったようです。
次回リリースで対応します。
