### ISSUE TITLE
Bug: Disable password-recovery function when localStrategy is disabled

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#5223]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian GNU/Linux 9 (stretch) 9.13|
|GROWI     |4.5.12|
|node.js   |14.18.3|
|npm       |6.14.15|
|Using Docker|yes (K8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 Version 21H2 (Build 22000.434)|
|browser   |Google Chrome	97.0.4692.71 (Official Build) （64 ビット） (cohort: Stable)|

How to reproduce? (再現手順)
---------------------------

1. Upgrade from v4.3.x or older (or enable self-password recovery function)
1. Disable ID/Password auth (localStrategy)
1. Log out and visit login page

What happens? (症状)
---------------------

- Password-recovery link and API is active while ID/Password auth is not available.

What is the expected result? (期待される動作)
-------------------------------------------

- Password-recovery function is enabled when ID/Password auth is enabled

**Comment by shield-9** [comment]
It is better to also disable password setting tab at user settings page.

**Comment by yuki-takei** [comment]
Fixed.
Please wait v4.5.15.
