### ISSUE TITLE
\\\\で\\が表示されない

### ISSUE THREAD

**Issue by hkato312** [weseek/growi#5239]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |4.4.13|
|node.js   |14.18.1|
|npm       |6.14.15|
|yarn      |1.22.15|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 98.0.4758.81|

How to reproduce? (再現手順)
---------------------------

1. \\\\\\\\ を入力

What happens? (症状)
---------------------

- previewでは\\\\が表示されるが、viewでは\\が表示される

What is the expected result? (期待される動作)
-------------------------------------------

- \\\\が表示される

Note
----

- \\\\\\\\\\\\\\\\を入力すると、viewで\\\\が表示される

**Comment by yuki-takei** [comment]
@hkato312 既知の修正を予定していない問題になります。
#3542 参照

検索用キーワード:
バックスラッシュ プレビュー
