### ISSUE TITLE
Bug: 招待メールが送信されないときのエラーメッセージが出ない

### ISSUE THREAD

**Issue by yusuketk** [weseek/growi#524]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.1.12-RC|
|node.js   |8.11.1|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser|Firefox/Chrome|

How to reproduce? (再現手順)
---------------------------

メール設定が未設定のまま
 管理者ページのユーザー管理にて、新規ユーザーの招待で
- メールアドレスを一つだけ入力
- 「招待メールで送信」にチェック

の状態で招待する。

What happens? (症状)
---------------------

指定したメールアドレスにメールが送信されないが、その旨のエラーメッセージが表示されない。

What is the expected result? (期待される動作)
-------------------------------------------

メールの設定がされてないことをエラーメッセージとして表示する。

**Comment by yuki-takei** [comment]
Fixed by #531 .
This will be released as v3.1.12
