### ISSUE TITLE
Bug: cursor position on built-in editor page

### ISSUE THREAD

**Issue by yuto-oweseek** [weseek/growi#5288]
Environment
------------

### Host

| Item     | Version |
| --- | --- |
| OS | MacOS Big Sur and Windows 10 Home |
| GROWI | 4.5.9-RC.0 |
| node.js | 14.18.3 |
| NPM | 6.14.15 |
| Using Docker | Yes |
| Using growi-docker-compose | Yes |

### Client
| Item | Version |
| --- | --- |
| OS | MacOS Big Sur and Windows 10 Home|
| Browser | Google Chrome v98.0.4758.80 (Official Build) (arm64) and v.97.0.4692.99（Official Build）(64 bit)|

How to reproduce?
---------------------------
1. Create a new wiki page and write the following markdown and add many new lines at the end of lines
1. Enter keyboard input

```
| col1 | col2 | col3 |
| ---- | ---- | ---- |
|  a    |   f   | f    |


| col1 | col2 | col3 |
| ---- | ---- | ---- |
|      | ff   |      |
|      |      |      |

![aaaaaa](https://github.com/weseek/growi/issues/5060)

[https://github.com/weseek/growi/issues/5060](aaa)

[aaa](https://github.com/weseek/growi/issues/5060)

**aaa**a

*bbb
ff
~~ccc~~

# ddd
f
> eee
> ff
> ggg

f
1. ffs
1. aaf
1. as

- hoga
- fuga
- piya

-[ x]a

- s[x]sss
- a
- [x] a
- [x] a
- [x] a
- [x ] a
- [x] a
- [x] a
- [ ]     

aaf
あ
a

- [ x] a
- [x] a
- [x] a
- [ aa] 

aaaaa
aaa

-aaaaa[x]
```

What happens?
---------------------
- cursor on edit page moves to bottom or top when Input by keyboard runs

What is the expected result?
-------------------------------------------
- cursor on edit page isn't moved

Note
----
-  some space or character before and after `- [x]` must cause this bug
- I investigated commit 6e576d6bfa (before CodeMirror codes are changed) and 0a0a4f005f (after CodeMirror codes are changed)

**Comment by yuki-takei** [comment]
We couldn't reproduced.
