### ISSUE TITLE
Improvement: Edgeからドラッグ&ドロップで画像をアップロードできるように修正する

### ISSUE THREAD

**Issue by tremblerscreed** [weseek/growi#533]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI   |3.1.11|
|node.js |8.11.3|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Microsoft Edge 41.16299.522.0|

How to reproduce? (再現手順)
---------------------------
EdgeでWikiにアクセスし、編集画面で画像ファイルをドラッグアンドドロップする

What happens? (症状)
---------------------
画像がアップロードされない

Note
----
Firefoxでは通常通りアップロードできました

**Comment by yuki-takei** [comment]
@tremblerscreed ご報告ありがとうございます。
一応 Firefox, Chrome で正常動作することを目安にしていますので多少優先度は落ちますが、余裕のあるときに対応しようと思います。

**Comment by yuki-takei** [comment]
#1087 の調査・修正の過程でこちらの症状は修正されました。v3.5.2 以降をご利用ください。
