### ISSUE TITLE
Bug: Error occurs in PlantUML

### ISSUE THREAD

**Issue by satosisotas** [weseek/growi#537]
Environment
------------

### Host

https://demo.crowi-plus.org
(GROWI: 3.1.11)

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Chrome 67.0.3396.99|

How to reproduce? (再現手順)
---------------------------

See following post.
https://demo.crowi-plus.org/Sandbox/plantuml_error

What happens? (症状)
---------------------

Growi outputs a syntax error while it is correct PlantUML code.

What is the expected result? (期待される動作)
-------------------------------------------

Output a correct UML diagram image.

Note
----

- Looks like same issue as #278

**Comment by yuki-takei** [comment]
@satosisotas Thank you for your report. We reserched #278 at the past, the solution has not been found.
