### ISSUE TITLE
Bug: page can be deleted even if user is not administrator or page creator.

### ISSUE THREAD

**Issue by yuto-oweseek** [weseek/growi#5419]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |mac and windows|
|GROWI     |4.5.15|
|node.js   |16.13.2|
|npm       |8.1.2|
|yarn      |1.22.17|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        ||
|google chrome   |98.0.4758.102（Official Build） （64 bit）|

How to reproduce? (再現手順)
---------------------------
1. Go to Security Settings page as an admin.
2. Set "Restrict complete deletion of pages" to "Admin and author".
<img width="1150" alt="Screen Shot 2022-02-25 at 0 39 28" src="https://user-images.githubusercontent.com/59536731/155558168-c6b63117-2fa9-4f32-a77c-0974e30a8ff4.png">

3. Login as a normal user(not admin)
4. Go to any page the user has not created.
5. Delete page completely from top right button in view mode

![button_delete](https://user-images.githubusercontent.com/83065937/155522038-479dc307-f072-40fa-aab0-4ece9187df78.PNG)

What happens? (症状)
---------------------
Can delete page completely by any user

What is the expected result? (期待される動作)
-------------------------------------------
Cannot delete page completely if user is not administrator or page creator like the following image

<img width="679" alt="Screen Shot 2022-02-25 at 0 55 28" src="https://user-images.githubusercontent.com/59536731/155559748-c79accce-8b08-4e74-81d7-19817e8f5729.png">

**Comment by yuki-takei** [comment]
## related PR
#5102 (released in v4.5.9)

**Comment by kaoritokashiki** [comment]
v4.5.9より前からGROWIをお使いの場合、上記の #5102のバグの影響が残っており、ドロップダウンラベルの見た目の部分とDBに保存している値に誤差があったようです。

## How to fix
1.「ページの完全削除の権限」にて「誰でも可能」もしくは「管理者のみ可能」を選択して更新ボタンを押す
1. 「ページの完全削除の権限」にて「管理者とページ作者が可能」を選択して更新ボタンを押す

既に修正済みのためクローズします。
