### ISSUE TITLE
Feature: Support SAML providers

### ISSUE THREAD

**Issue by sahya** [weseek/growi#542]
I want to implement SSO on keycloak
So please support SAML on growi.

Maybe many people of organization wants to use SSO on growi.

I do not have much programming knowledge, but it's not implemented with this URL
proposal: Simple SAML Identity Provider (IdP) for Node
https://github.com/mcguinness/saml-idp
or
https://github.com/mcguinness/saml-sp

**Comment by yuki-takei** [comment]
@sahya and everyone:
Thank you for your request. We'll consider implementation.

**Comment by yuki-takei** [comment]
*TODO*

GROWI uses [Passport.js](http://www.passportjs.org/), it will be a short cut to impl with these:

- https://github.com/bergie/passport-saml
- https://github.com/jaredhanson/passport-openidconnect

**Comment by yuki-takei** [comment]
@sahya We've done to implement SAML Authentication with bergie/passport-saml at v3.2.2!
In my team, it was confirmed to work with Keycloak but other SAML provider has not been tested.

Please try it and send us a feedback if you could point out anything.

**Comment by sahya** [comment]
I'm so happy ,thank you verry much.

I will test in this month.
If I try it, I will send feedback you

**Comment by sahya** [comment]
(I write in English to able to  read for global everyone. )
I tried  feature of SAML authentication but it was not worked.
because maybe  relation of passport-saml not good.

I heard  from @yuki-takei , SAML authentication fix until september 3 times week.

**Comment by sahya** [comment]
I think item of SAML settings, with
