### ISSUE TITLE
Bug: Trackpad gestures are disabled

### ISSUE THREAD

**Issue by kota65535** [weseek/growi#5425]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Amazon Linux 2 |
|GROWI     |4.5.15|
|node.js   |14.19.0|
|npm       |6.14.16|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Catalina|
|browser   |Chrome 98.0.4758.109（Official Build） （x86_64）|

How to reproduce? (再現手順)
---------------------------

1. Swipe the trackpad with two fingers left or right

What happens? (症状)
---------------------

- Nothing happens

What is the expected result? (期待される動作)
-------------------------------------------

- Goes back to the previous page if swiped left
- Goes forward to the next page if swiped right

Note
----

- This is because of `overscroll-behavior-x: none` in CSS 
- Is this intended behavior? If so, is there a way to enable trackpad gestures?

**Comment by kota65535** [comment]
I've ended up with setting custom CSS.

```
body {
  overscroll-behavior: auto;
}
```

**Comment by hakumizuki** [comment]
This issue was fixed in GROWI version 5.x. Please wait until we to fix it in version 4.5.15 as well.
