### ISSUE TITLE
Feature: Endpoint for health check

### ISSUE THREAD

**Issue by skomma** [weseek/growi#544]
I'm trying to run Growi on a kubernetes cluster.
But currently, it seems that the endpoint suitable for health check are not implemented.

I would like to use this endpoint for livenessProbe/readinessProbe in k8s Pod yaml.
(I tried to use `/login` for *Probe url, but **IN INITIAL STATE** this URL returns 302 response that redirects to `/installer`)

So I hope the endpoint with the following specification.

* can be done regardless of the installation status
* (optionally) can monitor the state of connection to the underlying middleware

**Comment by yuki-takei** [comment]
How about these route?

- GET `/_api/v3/healthcheck` -> return 200 if express server alive
- GET `/_api/v3/healthcheck?connectMongoDB` -> return 200 if express server can read data from MongoDB
