### ISSUE TITLE
Request: Not increment index of ordered lists on auto complementation feature

### ISSUE THREAD

**Issue by fezzlk** [weseek/growi#5544]
## Informations
Current page editor automatically complements incremented index when push enter key on ordered lists.  I hope it always complements "1. " to make management index simple.

#### Current
```
1. hoge
2. fuga
3.           // <- incremented index
```

#### I hope
```
1. hoge
1. fuga
1.           // <- always "1. "
```

**Comment by kaoritokashiki** [comment]
I close this issue because the same issue has already been created [#3986](https://github.com/weseek/growi/issues/3986)
