### ISSUE TITLE
Bug:TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by yuuya137s** [weseek/growi#5599]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |AlmaLinux 8.5|
|GROWI     |4.5.15|
|node.js   |14.19.0|
|npm       |6.14.16|
|yarn      |1.22.17|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 Pro 22579.100|
|browser   |Edge  101.0.1202.0|

How to reproduce? (再現手順)
---------------------------

1. 何もせずに放置
1. タブ移動を行い、Growiに戻ってくるとエラー発生

What happens? (症状)
---------------------
- 高頻度でGrowiのどこかをクリックすると下図エラー発生  その後ログイン画面へ戻される
![image](https://user-images.githubusercontent.com/46161596/159838894-9bc78375-f412-4ce9-b558-74fbc80fe469.png)

```
TypeError: Cannot read properties of undefined (reading 'length')
    at app.033aa5900872a9b24647.bundle.js:1:403272
    at Zo (vendors.6b8235fba330e725cb45.chunk.js:2:5440197)
    at Bs (vendors.6b8235fba330e725cb45.chunk.js:2:5449054)
    at ba (vendors.6b8235fba330e725cb45.chunk.js:2:5487663)
    at pu (vendors.6b8235fba330e725cb45.chunk.js:2:5478992)
    at hu (vendors.6b8235fba330e725cb45.chunk.js:2:5478917)
    at iu (vendors.6b8235fba330e725cb45.chunk.js:2:5475947)
    at vendors.6b8235fba330e725cb45.chunk.js:2:5427585
    at t.unstable_runWithPriority (vendors.6b8235fba330e725cb45.chunk.js:2:5924820)
    at $i (vendors.6b8235fba330e725cb45.chunk.js:2:5427294)
ra @ vendors.6b8235fba330e725cb45.chunk.js:2
```

What is the expected result? (期待される動作)
-------------------------------------------

- エラーが発生せずに利用できるようになること
- 

Note
----

- Growi v5.0.0 RC9にアップグレードするも同様
- 別環境を構築しデータインポートするも同様

**Comment by yuki-takei** [comment]
GROWI (nocdn 版ではない) v4.5.15
Windows 11 Home 22000.556
Microsoft Edge 99.0.1150.46 (公式ビルド) (64 ビット)

の組み合わせで正常動作を確認しました。

- Proxy など環境による影響はないか
- Edge を GA バージョンまで落としても同じ症状が起こるか

あたりを確認いただけますでしょうか。

**Comment by yuuya137s** [comment]
ご確認いただきあありがとうございます。
- Proxy など環境による影響はないか
　 Proxyは私用しておりません。 
- Edge を GA バージョンまで落としても同じ症状が起こるか
　 下記確認いたしました。

```
Growi v4.5.15
Windows 11 22000.566
Edge 99.0.1150.46
Chrome 93.04577.82

Windows 11 22581.1
Edge 99.0.1150.46
Edge 101.0.1202.0

Windows 10 19041.1415
Chrome 93.04577.82
Edge  99.0.1150.46

```
こちらでお間違いないでしょうか。

**Comment by yuki-takei** [comment]
なるほど…
おそらくデータの問題なのでしょうね。何か「あるはずのデータがない」部分があって、そこの `length` を読みに行ってエラーになっていると。

該当箇所が分かればデバッグできるのですが、現時点ではちょっと原因を特定できないです。

**Comment by yuki-takei** [comment]
同環境で、クリーンインストールした GROWI v4.5.15 を起動できないでしょうか？
そちらで正常動作するならとりあえず何かしらのデータの問題と切り分けることができる気がします。

因みにデータをいただくことって不可能でしょうか？

**Comment by yuuya137s** [comment]
同じdocker-compose.ymlを使用して別環境での起動してみましたが、データが入っていない場合は症状は現れませんでしたが、データインポートを行うと同様の症状が発生したり、特に何も表示がなくログイン画面に戻されたりしました。  

また、V5.0.0へアップグレードした際は同様の症状の確認はできませんでしたが、突然ログイン画面に戻されてしまいました。  
様々な情報が入っているためデータはかなり難しいです。

**Comment by yuki-takei** [comment]
> データインポートを行うと同様の症状が発生したり、特に何も表示がなくログイン画面に戻されたりしました。

なるほど。
こちらでも試してみます。ありがとうございます。

**Comment by yuuya137s** [comment]
ありがとうございます。お手数をおかけします。
因みにMongoDBの中身を私のほうでも確認してみようと思いますが、確認したほうが良いテーブルがどこかございますでしょうか。

**Comment by yuki-takei** [comment]
今は全く確証はなく、、
たｄさ「高頻度でGrowiのどこかをクリックすると」という情報から SWR というツールで頻繁に API を叩いて情報取得するデータが対象かなと思います。pages collection とか users collection あたりのデータが壊れてるのかな…という推測をしています。

**Comment by yuuya137s** [comment]
ありがとうございます。少し調べてみます。
また、別の事象かもしれませんが、V5.0.0 RC9/10 ではエラー画面は出ないんですが、一定期間放置してからリンクをクリックするとログイン画面に戻されるのですがそちらも同様にデータ破損によるものでしょうか。

**Comment by yuuya137s** [comment]
ログイン画面に戻される症状についてはこちらの設定ミスが原因だったようです。  
セッション有効期間が`86400`で設定されていました。  
ただ該当の設定をデフォルト値に戻して、Growiを再起動したところエラーメッセージが現れなくなりました。
