### ISSUE TITLE
Bug: File title label not be fixed in a wide code block

### ISSUE THREAD

**Issue by fezzlk** [weseek/growi#5602]
Environment
------------

### Host

growi.cloud

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Big Sur v11.6.4|
|GROWI     |4.4.13|
|node.js   |14.18.1|
|npm       |6.14.15|
|yarn      |1.22.15|

How to reproduce? (再現手順)
---------------------------

1. Write the follow script in code block with file title.

```
''':hoge
A very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long script.
''' // replaced [`] to [']
```

What happens? (症状)
---------------------

- When scroll code block, file title label `hoge` not be fixed

![layout](https://user-images.githubusercontent.com/38426468/159946083-dc6087a0-53b2-4a71-b6f4-3fd08fe9d0b5.gif)

What is the expected result? (期待される動作)
-------------------------------------------

- File title label be fixed

Note
----

- It occurs on windows client.

**Comment by jam411** [comment]
Assignee declined.

I wanted to split the container, but when I split it within GrowiRenderer.js, pre and code tags were automatically generated.
The VScode extension extensionHostProcess.js seems to have affected this.
The extensionHostProcess.js was confirmed in vscode, WSL ubuntu LTS, windows11 environment.
