### ISSUE TITLE
Bug: Password reset gives "Error update-password-failed" when submitting a new password

### ISSUE THREAD

**Issue by dashwood8691** [weseek/growi#5653]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.6 LTS|
|GROWI     |4.5.15|
|node.js   |14.19.0|
|npm       |6.14.16|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 20H2|
|browser   |Chrome 100.0.4896.60 (Official Build) (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. Restart app container to workaround #5652 
   ```
   $ docker-compose restart app
   ```
1. Logout and go to the sign-in page.
1. Click "Forget Password?"
1. Enter your email address and click "Send"
1. Click the URL sent via email.
1. Enter a new password twice and click "Reset Password"
1. UI shows `Error update-password-failed`, but the password is successfully reset. Logging in using the new password is possible.

What happens? (症状)
---------------------

- The following error occurs.

   ![update-password-failed_masked](https://user-images.githubusercontent.com/30547/161477069-2f5bf472-a508-4d06-9388-4012d482351a.jpg)

- `docker-compose logs app` had the following message.

   ```
   app_1            | {"name":"growi:routes:apiv3:forgotPassword","hostname":"06ada90bc5b6","pid":17,"level":50,"err":{"message":"ENOENT: no such file or directory, open '/opt/growi/packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt'","name":"Error","stack":"Error: ENOENT: no such file or directory, open '/opt/growi/packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt'\n    at Object.openSync (fs.js:497:3)\n    at Object.readFileSync (fs.js:393:35)\n    at Object.ret.load (/opt/growi/node_modules/swig-templates/lib/loaders/filesystem.js:55:15)\n    at exports.Swig.compileFile (/opt/growi/node_modules/swig-templates/lib/swig.js:694:31)\n    at Object.renderFile (/opt/growi/node_modules/swig-templates/lib/swig.js:569:17)\n    at MailService.send (/opt/growi/packages/app/dist/server/service/mail.js:138:55)\n    at sendPasswordResetEmail (/opt/growi/packages/app/dist/server/routes/apiv3/forgot-password.js:41:28)\n    at /opt/growi/packages/app/dist/server/routes/apiv3/forgot-password.js:92:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","code":"ENOENT"},"msg":"ENOENT: no such file or directory, open '/opt/growi/packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt'","time":"2022-04-04T01:07:54.597Z","v":0}
   ```

- The file name is `PasswordResetSuccessful.txt` instead of `passwordResetSuccessful.txt`.

   ```bash
   $ docker exec -it growi_app_1 ls -l /opt/growi/packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt
   ls: cannot access '/opt/growi/packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt': No such file or directory
   $ docker exec -it growi_app_1 ls -l /opt/growi/packages/app/resource/locales/en_US/notifications/PasswordResetSuccessful.txt
   -rw-r--r-- 1 node node 136 Feb 17 16:05 /opt/growi/packages/app/resource/locales/en_US/notifications/PasswordResetSuccessful.txt
   ```

What is the expected result? (期待される動作)
-------------------------------------------

- Password reset does not give an error on UI.

Note
----

- Need to be careful about another issue #5652 when reproducing the issue.

**Comment by kaoritokashiki** [comment]
Hi, thanks for reporting the issue.
We'll try to reproduce this bug. please wait for a while.

**Comment by kaoritokashiki** [comment]
I could not reproduce the issue you reported but the file name fixes has been done.
Please check again after v5.0.1 release and if you have any problems, please tell us anytime. Thank you :)
