### ISSUE TITLE
Bug: 足跡アイコンの数値が一致しない場合がある

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#5659]
Environment
------------
### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.9.2009|
|GROWI     |4.5.15|
|node.js   |14.19.0|
|npm       |6.14.16|
|yarn      |1.22.17|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 99.0.4844.84|

How to reproduce? (再現手順)
---------------------------
明確な期間は不明ですが、古くに作成し閲覧数が多いページに発生する傾向が多いように思います。

What happens? (症状)
---------------------
ページ右上の足跡アイコンの数値と、画面左メニューの「最近の更新」で表示される足跡アイコンの数値が異なる場合があります。

What is the expected result? (期待される動作)
-------------------------------------------
閲覧数を示す正しい数値になること

Note
----

- 
-

**Comment by nakashimaki** [comment]
情報提供です。
私の環境でもv4.5.15でこの現象が再現していたのですが、v5.0.0では再現しませんでした。
現象の傾向を見ていると足跡アイコンの数値が一定数（15？）で頭打ちになるようになっており、それは足跡として表示されるユーザーアイコン数と一致しているようでした。

**Comment by miya** [comment]
nakashimak さんに情報提供していただいたバグの再現が確認できましたので修正して v4.5.18 でリリースいたしました。
issue の起票ありがとうございます、こちらはクローズさせていただきます。
