### ISSUE TITLE
Bug: New user notification email is also sent TO: deleted_at_<epoch_time>@deleted

### ISSUE THREAD

**Issue by dashwood8691** [weseek/growi#5669]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.6 LTS|
|GROWI     |4.5.15|
|node.js   |14.19.0|
|npm       |6.14.16|
|yarn      |1.22.17|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 21H1|
|browser   |Chrome 100.0.4896.60 (Official Build) (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. E-mail settings have `From e-mail address` set to existing email of admin.
1. A user with `admin` access is deactivated and then removed.
1. A new user creates an account.
1. Notification e-mail is sent to admins as well as **deleted_at_1649230493586@deleted**
1. Email server complains the email to **deleted_at_1649230493586@deleted** is undeliverable.

What happens? (症状)
---------------------

- Email server is unable to forward the email to @deleted address.
- Sample email message is below.

```
Subject: Undeliverable Message

The following message to <deleted_at_1649230493586@deleted> was undeliverable.
The reason for the problem:
5.1.1 - Bad destination email address 'invalid domain "deleted": no dot found'=
```

What is the expected result? (期待される動作)
-------------------------------------------

- Email notification is not sent to **deleted_at_1649230493586@deleted**

Note
----

- It seems like GROWI sends notifications to @deleted email addresses when "admin" is true.
- When using "Export Archive Data" feature to export "Users" collection, I see the following data.

```json
    {
        "_id": "6233e8f4baaceb00107a0bda",
        "isGravatarEnabled": false,
        "isEmailPublished": true,
        "lang": "en_US",
        "status": 4,
        "admin": true,
        "isInvitationEmailSended": false,
        "createdAt": "2022-03-18T02:05:40.654Z",
        "username": "deleted_at_1649230493586",
        "email": "deleted_at_1649230493586@deleted",
        "password": "",
        "__v": 0,
        "lastLoginAt": "2022-04-04T00:18:47.814Z",
        "imageUrlCached": "/images/icons/user.svg",
        "name": "",
        "googleId": null,
        "image": null
    },
```

**Comment by yuki-takei** [comment]
## Note

grep with `mailService.send`

**Comment by yuki-takei** [comment]
This issue is fixed in master branch.
Please use v5.0.3 or above. Thanks.
