### ISSUE TITLE
Improvement: Re-index ElasticSearch when the server boot

### ISSUE THREAD

**Issue by mizozobu** [weseek/growi#571]
How to reproduce? (再現手順)
---------------------------

1. Growiを介さずにMongoDBからPageを削除する
1. 削除したページ名ををキーワードに検索する

What happens? (症状)
---------------------

- 検索結果の数と検索結果リストが合致しない
- docker-composeとサーバーを再起動しても直らない

What is the expected result? (期待される動作)
-------------------------------------------

- 最低でもdocker-composeとサーバーを再起動したら直って欲しい

Note
----
`/hoge`を作成し削除し、`hoge`で検索をかけたとき
![issue](https://user-images.githubusercontent.com/27652080/43242654-5023ab7e-90dd-11e8-968c-29b107a43a58.PNG)

**Comment by yuki-takei** [comment]
@mizozobu データ量に依ってインデックス化ってすごく時間かかる、明示的に起動時インデックス化するための環境変数を追加するといいかな

**Comment by yuki-takei** [comment]
Taken over by #996
