### ISSUE TITLE
Bug: 「レイアウト」を「コンテンツ幅 100%」にしていると検索結果画面右側のスクロールに連動して左側もスクロールする

### ISSUE THREAD

**Issue by nakashimaki** [weseek/growi#5754]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04|
|GROWI     |5.0.3|
|node.js   |16.14.2|
|npm       |8.5.0|
|yarn      |1.22.18|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 21H2 |
|browser   | Microsoft Edge 100.0.1185.44 |

How to reproduce? (再現手順)
---------------------------

1. 「カスタマイズ」→「レイアウト」を「コンテンツ幅 100%」にする
1. 検索バーに任意のキーワードを入力し、Enterを押下して検索結果画面を開く
1. 右側の検索結果プレビュー（`search-result-content`）でスクロールを行う

What happens? (症状)
---------------------

- 左側の検索結果リスト（`search-result-list`）側が連動してスクロールする

What is the expected result? (期待される動作)
-------------------------------------------

- 右側の検索結果プレビューだけがスクロールする

Note
----

- 「デフォルトのコンテンツ幅」の場合発生しない

**Comment by jam411** [comment]
@nakashimaki

本Issueの修正が完了いたしました。

修正版のリリースは、
v5.0.7 になります。

引き続きGROWIをよろしくお願いしたします!
