### ISSUE TITLE
Request: パスワードの制限文字数の変更機能

### ISSUE THREAD

**Issue by kazuma-minoura** [weseek/growi#5757]
チーム内での情報共有に活用させていただいています。ありがとうございます。

#5116 でパスワードの最短文字数を8文字に制限されたと思うのですが、
この制限文字数を、環境変数などで変更できるようにしていただくことは出来ないでしょうか？
また、もし何かしら本制限を回避する手段があるようでしたら、教えていただけると助かります。

小規模チーム内限定での利用なので苗字ベースの簡単なパスワードを決め打ちで割り当てて使っているのですが、
苗字が短い人だと本制限に引っかかって設定できないので、このような機能があると助かります。
(それパスワードの意味ないじゃん、というご指摘もあるかとは思いますが)

**Comment by Shunm634-source** [comment]
The request has been merged and will be released in the next version.
