### ISSUE TITLE
Bug: Googleアカウント認証の際にgmailアドレスが既存ユーザーの登録したアドレスと一致しているのに新規ユーザーとして作成されてしまう

### ISSUE THREAD

**Issue by kyusuke-10** [weseek/growi#5769]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|　
|GROWI     | 5.0.1 |
|node.js   |16.14.2|
|npm       |8.5.0 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes| 

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 12.2.1|
|browser   |Safari 15.3|

How to reproduce? (再現手順)
---------------------------
これまでID/passwordによるログイン認証にて管理していたのですが、googleによるログイン認証に変更すると症状を確認しました。

What happens? (症状)
---------------------
`Automatically bind external accounts newly logged in to local accounts when email match` にチェックが入っているにも関わらず、
既存ユーザーがgoogleアカウント認証によるログインを行なった場合、growiに登録したemailアドレスと同じgmailアドレスなのに、新規ユーザーとして作成されてしまうケースがあります。
私が確認したところ、usernameとgmailアドレスの@より前が一致しない場合にこのような挙動になっているようです。そうでない場合は既存ユーザーとしてログインできます。

What is the expected result? (期待される動作)
-------------------------------------------
- `Automatically bind external accounts newly logged in to local accounts when email match` の通りemailアドレスが一致するユーザーであれば同一ユーザーとしてログインできるようにしてほしいです。
- 

Note
----

- 
-

**Comment by kaoritokashiki** [comment]
@kyusuke-10 
この度はIssueを起票していただきありがとうございます！
こちらのバグ、再現いたしましたので原因調査 & 修正対応を行います。
修正までしばらくお待ちください。

**Comment by kaoritokashiki** [comment]
@kyusuke-10 
この度はIssueを起票していただきありがとうございます！
こちらでも再現確認できましたので、原因調査 & 修正対応 を進めてまいります。
修正までしばらくお待ちください。

**Comment by kaoritokashiki** [comment]
### 調査 4.5.x

**Comment by kaoritokashiki** [comment]
5系での修正は完了したが、4系の修正が残っているのでReopenしました。

**Comment by kaoritokashiki** [comment]
@kyusuke-10

本Issueの修正が完了いたしました。

修正版のリリースは、
5系ではv5.0.7
4系ではv4.5.22 になります。

次回リリースをお待ちください。
引き続きGROWIをよろしくお願いしたします!

**Comment by kyusuke-10** [comment]
@kaoritokashiki ご対応ありがとうございました！V5.0.7のリリースを楽しみにしております。こちらこそ引き続きどうぞよろしくお願いいたします。
