### ISSUE TITLE
Request: 信頼するリバースプロキシを設定可能にする

### ISSUE THREAD

**Issue by hrko** [weseek/growi#5796]
## Informations
GROWIをリバースプロキシ下で動作させている場合、現状では、APIレート制限の判断に使われるソースIPアドレスはリバースプロキシのものになってしまいます。例えば、レート制限が10リクエスト/15分の場合は、15分以内に11人以上がリバースプロキシ経由でログインしようとするとレート制限に引っかかってしまいます。

Expressの設定で `trust proxy` を設定すると、リバースプロキシから渡された `X-Forwarded-*` ヘッダーからソースIPを取得するようになり、この問題を回避できるかと思います。

### 参考
- https://www.npmjs.com/package/express-rate-limit#user-content-troubleshooting-proxy-issues
- https://expressjs.com/ja/guide/behind-proxies.html

**Comment by yuki-takei** [comment]
@hrko PR ありがとうございます。こちらも v5.1.0 までに取り込む予定です。デフォルト値だけどうしようか思案中です。
