### ISSUE TITLE
Bug:コード内で<>で囲まれた文字列時々消えてしまう

### ISSUE THREAD

**Issue by soushi** [weseek/growi#5840]
初めまして、GROWI使わせて頂いております。ページ内にapacheの設定ファイルをメモしようとしたときに<>で囲まれた文字列が時々消えてしまう現象に当たったのでIssueを上げされてもらいました。
詳細は以下をご覧ください。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |5.0.4|
|node.js   |16.14.2|
|npm       |8.5.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Microsoft Edge 101.0.1210.39/Firefox 100.0|

How to reproduce? (再現手順)
---------------------------

1. コード内に次のような文字列を入力する

```
<VirtualHost *:80> aabb
    DocumentRoot "/var/www/localhost/html"
    ServerName localhost

    <Directory "/var/www/localhost">
        Options FollowSymLinks
        AllowOverride All

        <RequireAll>
            Require method GET POST HEAD
            Require all granted
        </RequireAll>
    </Directory>
</VirtualHost>
```

2. 保存後、Viewで内容を表示する

What happens? (症状)
---------------------

- <VirtualHost *:80>等、<>で囲まれた文字列が欠けた状態で表示される

![growi_view](https://user-images.githubusercontent.com/374107/168240446-350961da-9586-48a0-b8c0-56b235db1310.png)

- 正常に表示される事もあるが、viewの画面をリロードすると時々かけた状態になる

What is the expected result? (期待される動作)
-------------------------------------------

- <>で囲まれた文字列が欠けないで表示される

Note
----

- DevToolで確認すると欠けるときは"<"、欠けないときは"&amp;lt;" のようにエスケープされている
- ページを作成後、別ブラウザでリロードを繰り返すと時折欠ける事がある
- 「XSSを抑制する」設定のON/OFFどちらでも発生

**Comment by hakumizuki** [comment]
GROWI をお使いいただきありがとうございます。

[同等の issue](https://github.com/weseek/growi/issues/2508) が存在しますので、こちらはクローズさせていただきます。
改修をお待ちください。

**Comment by soushi** [comment]
早速の返信ありがとうございます。

案内頂いたissueに関しては「XSSを抑制する」の設定が影響し、タグをカットする挙動のように理解していたので別件だと思ってました(こちらはカットというより記号をエスケープしたり、しなかったりでしたので…)。

現象としては同じとの事ですのでそちらのissueの方をウォッチさせていただきます。
