### ISSUE TITLE
Request: when NO_CDN=true, How to implement Code highlight Theme?

### ISSUE THREAD

**Issue by sevenjay** [weseek/growi#5905]
How to implement Code highlight Theme?
This function is disabled when the environment variable NO_CDN=true.
Could someone help me?
In Custom script session I can add some script from Code highlight Theme,
but I don't know how to apply it to my code block.

thanks

**Comment by yuki-takei** [comment]
## Sequece

1. Building NO_CDN image
    - https://github.com/weseek/growi/blob/v5.0.6/packages/app/package.json#L12
    - https://github.com/weseek/growi/blob/v5.0.6/packages/app/package.json#L51
    - https://github.com/weseek/growi/blob/v5.0.6/packages/app/bin/download-cdn-resources.ts#L26
    - https://github.com/weseek/growi/blob/v5.0.6/packages/app/src/services/cdn-resources-service.js#L53
        - [CodeMirror themes in `cdn-manifests.js`](https://github.com/weseek/growi/blob/v5.0.6/packages/app/resource/cdn-manifests.js#L171-L226) will be downloaded into `/static/styles/cdn`
1. When an user select theme
    - https://github.com/weseek/growi/blob/v5.0.6/packages/app/src/components/PageEditor/CodeMirrorEditor.jsx#L416
        - Load CSS on demand from `/static/styles/cdn`

**Comment by yuki-takei** [comment]
@sevenjay So currentry, GROWI with NO_CDN=true couldn't load theme styles from Custom script URL even if you added.

**Comment by yuki-takei** [comment]
GROWI v6 is no longer supported to change the code highlight theme.
