### ISSUE TITLE
Bug:v5.0.6でReferenceError: emojione is not defined

### ISSUE THREAD

**Issue by soushi** [weseek/growi#5925]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |5.0.6|
|node.js   |16.14.2|
|npm       |8.5.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. Growiをv5.0.5→v5.0.6へアップデート
1. トップページへアクセス

What happens? (症状)
---------------------

- ReferenceError: emojione is not defined が表示される

What is the expected result? (期待される動作)
-------------------------------------------

- GROWIトップページが表示される

Note
----

- トップページ以外のページもすべて同様にエラーが表示される
- 管理画面(/admin)へは問題なくアクセスが可能

対応としてカスタマイズ→カスタム HTML Headerから下記emojioneのライブラリを読み込むようにしたらエラーが解消しました。

https://cdnjs.com/libraries/emojione/4.5.0

GROWIのアップデートはgitから最新版を取得後、yarnを実行しています。

**Comment by soushi** [comment]
すいません、編集前にPOSTしてしまったので、内容を再編集しています。

**Comment by yuki-takei** [comment]
v5.0.6 以降では emojione を要求するコードは削除されているはずなので、なにかおかしいですね…
クライアントのビルドし直し(`/packages/app` ディレクトリ下で `yarn build:client`)等を行っても状況に変わりはないでしょうか？

**Comment by soushi** [comment]
返信ありがとうございます。

> v5.0.6 以降では emojione を要求するコードは削除されているはずなので、なにかおかしいですね…
> クライアントのビルドし直し(`/packages/app` ディレクトリ下で `yarn build:client`)等を行っても状況に変わりはないでしょうか？

`yarn build:client`のみを行うとGROWIのview画面が真っ白になりました。
特にエラーメッセージが表示されてはおりません。

その後、下記ソフトのバージョンを上げて今度は`yarn build`を実行しました。

- node.js 16.14.2 → 16.15.0
- npm 8.5.0 → 8.11.0
- yarn 1.22.18 → 1.22.19

するとGROWIのview画面も表示されるようになり、カスタムヘッダーからemojioneのJSを削除してもエラーが表示されなくなりました。

これで問題が解決したと思ったのですが、今度は共有リンクを使うとページの中身が表示されていない事に気づきました。
(GROWI v5.0.5の時は表示されており、今回のv5.0.6のバージョンアップ時もしくはyarn build以降に発生したと思われます)
画面上には特にエラーは表示されていませんが、DevToolsでHTTPリクエストを確認すると一部HTTP403が発生していました。

```
・HTTP403となっているリクエスト
/_api/v3/page/is-grant-normalized?pageId=xxxx
/_api/v3/page/applicable-grant?pageId=xxxx
/_api/v3/page?path=/xxx/xxx
```

またコンソールログには `ERROR: growi:cli:SocketIoContainer: Login is required to connect.`というエラーメッセージも表示されています。

以下、補足事項です。

- ログイン状態で共有リンクのページを見ると問題なく表示される
- 新しく共有リンクを作成しても現象は変わらず
- Firefox/Edge等ブラウザを変更しても同じ現象

別の事象の話になり申し訳ございませんが、再度ご確認いただけますと幸いです。
