### ISSUE TITLE
Bug: 新規で作成したページの作成日時の表示がおかしい。

### ISSUE THREAD

**Issue by kyusuke-10** [weseek/growi#5966]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04|
|GROWI     |5.0.7|
|node.js   |16.15.0|
|npm       |8.5.5|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 12.4|
|browser   |Safari 15.5|

How to reproduce? (再現手順)
---------------------------
新しいページを作成した際に症状を確認しました。

What happens? (症状)
---------------------
新規ページを作成した際に、右上の作成日時の表示が正しい作成日時ではなく異なった日時が表示される。
更新日時は正しく表示されています。
作成日時に表示される日時はおそらくgrowiの起動日時となっていると思われます。
lsxで作成日時でsortする際に正しくsortされないので困っています。

What is the expected result? (期待される動作)
-------------------------------------------
- 正しい日時で保存・表示されるようにしてほしいです。

Note
----

- 
-

**Comment by yuki-takei** [comment]
@kyusuke-10 ご報告ありがとうございます。修正します。

**Comment by yuki-takei** [comment]
修正完了しました。次回リリースをお待ちください。

**Comment by kyusuke-10** [comment]
@yuki-takei 早速のご対応ありがとうございました。リリースを楽しみにしております。
