### ISSUE TITLE
Bug: "Error: cannnot get grant label" when using `$lsx()`

### ISSUE THREAD

**Issue by tminai** [weseek/growi#6005]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | AlmaLinux 8.6|
|GROWI     |5.0.8|
|node.js   |16.15.1|
|npm       |8.11.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10|
|browser   |Chrome 102.0.5005.63|

How to reproduce? (再現手順)
---------------------------

Use `$lsx()`
I have not pursued this in detail, but I suspect that the error message is probably due to the authorization settings of the child page.

What happens? (症状)
---------------------

The following error is printed at the top of the page using $lsx() and the page tree is only displayed halfway down.
![image](https://user-images.githubusercontent.com/56664277/172501208-0a3c46f2-bc72-4044-8648-662b5d5e63fb.png)

```
Error: cannnot get grant label
詳細

    in fi
    in vi
    in Unknown
    in t
    in n
    in p
    in Unknown
    in r
    in q
```

What is the expected result? (期待される動作)
-------------------------------------------

- No Error, Show full page tree.
- 

Note
----

- 
-

**Comment by yuki-takei** [comment]
@tminai Hi. Thank you for your report.

I would like to get more detail conditions about it.

1. Does the problem reproduce in GROWI v5.0.9?
2. Could you show us the state of the page (and children pages) concretely?
    - Public / Only me / Only inside the group ...

**Comment by tminai** [comment]
@yuki-takei 
Thanks for the confirmation.
I have updated to V5.0.9 but the same situation...

The error messages have changed a bit.
![image](https://user-images.githubusercontent.com/56664277/173707829-576a87a4-a3fe-42bc-b73d-bb63296996c0.png)

The following error was output on the chrome console.
```
vendors.e7ab0c96349db59bfa4f.chunk.js:2 Error: cannnot get grant label
    at app.09b589864ddd9c028cac.bundle.js:1:292588
    at app.09b589864ddd9c028cac.bundle.js:1:292718
    at ci (app.09b589864ddd9c028cac.bundle.js:1:293541)
    at Zo (vendors.e7ab0c96349db59bfa4f.chunk.js:2:6682659)
    at bs (vendors.e7ab0c96349db59bfa4f.chunk.js:2:6728906)
    at pu (vendors.e7ab0c96349db59bfa4f.chunk.js:2:6721454)
    at fu (vendors.e7ab0c96349db59bfa4f.chunk.js:2:6721379)
    at iu (vendors.e7ab0c96349db59bfa4f.chunk.js:2:6718409)
    at vendors.e7ab0c96349db59bfa4f.chunk.js:2:6670047
    at t.unstable_runWithPriority (vendors.e7ab0c96349db59bfa4f.chunk.js:2:7154667)
rs @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
o.componentDidCatch.n.callback @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
mo @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
us @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
yu @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
t.unstable_runWithPriority @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
$i @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
_u @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
iu @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
t.unstable_runWithPriority @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
$i @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Yi @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Ki @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Qs @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
ya @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
g @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
a @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Promise.then（非同期）
u @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
i @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
ss @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
us @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
yu @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
t.unstable_runWithPriority @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
$i @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
_u @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
iu @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
（匿名） @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
t.unstable_runWithPriority @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
$i @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Yi @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Ki @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
au @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
Gu @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
t.render @ vendors.e7ab0c96349db59bfa4f.chunk.js:2
./src/client/app.jsx @ app.09b589864ddd9c028cac.bundle.js:1
l @ app.09b589864ddd9c028cac.bundle.js:1
a @ app.09b589864ddd9c028cac.bundle.js:1
（匿名） @ app.09b589864ddd9c028cac.bundle.js:1
（匿名） @ app.09b589864ddd9c028cac.bundle.js:1
```


The permission of the page on which the error is displayed is `Public`.
There is a mix of `Public` and `Only Inside Group` pages under this page.
The maximum page depth is 2, for a total of 68 pages.

Additionally, when I tried to edit and save this page (Public), I got the following error
![image](https://user-images.githubusercontent.com/56664277/173709136-b7d75010-2047-421b-af12-1dbb26368a83.png)

**Comment by tminai** [comment]
@yuki-takei 
I found the cause.
It seems that the error is displayed when the page executing '$lsx()' is "Public" and the parent is "Only inside group".

My problem is solved, but it would be nice to be able to easily understand this kind of error in setting page permissions.
Occasionally, other pages show a yellow warning message with a suggestion to review permissions, but not this time.

**Comment by yukendev** [comment]
@tminai 
Thanks for the info.
We are in the process of investigating and correcting this issue, so please wait a moment.
