### ISSUE TITLE
Imprv:samlのX.509 証明書対応

### ISSUE THREAD

**Issue by ushiyasan** [weseek/growi#603]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |3.2.3-RC|
|node.js   |5.6.0|
|yarn       |1.9.2|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

What happens? (症状)
---------------------

- G Suite等の、X.509 証明書が必要なSAML認証が利用できない

What is the expected result? (期待される動作)
-------------------------------------------

- Passport認証機構設定のSAMLの項目にCertificateの入力欄があり、鍵をコピペできる
- src/server/service/passport.js 433行目 `passport.use(new SamlStrategy({`に
`cert: config.crowi['security:passport-saml:cert'] || process.env.SAML_CERT`
などが追加され、証明書を使ったSAML認証ができるようになる

**Comment by yuki-takei** [comment]
@ushiyasan こちらもご提案ありがとうございます。しかも改修箇所まで…助かります！
近日中に実装してリリースします。

**Comment by sahya** [comment]
すぐに完璧である必要はないですが、添付のファイル程度項目があると良いのではないでしょうか。
網羅性という意味合いで大事かなと思いました。
wordpress | onelogin saml plugin

**Comment by yuki-takei** [comment]
v3.2.4 で搭載しました。その他のオプション群は #615 に持ち越し。
