### ISSUE TITLE
Bug: Authentication settings with OpenID Connect fails

### ISSUE THREAD

**Issue by penguin2716** [weseek/growi#6030]
Abstract
--------
Some OpenID Providers such as Keycloak support multi-tenant use cases by introducing a realm name to their endpoint URLs. Growi supports authentication integration to external identity providers by OpenID Connect, and it checks their OpenID discovery endpoint (`/.well-known/openid-configuration`) at the first step of the settings procedure. However, since v4.5.12 and v5.0.0, Growi uses a generated discovery endpoint URL according to the user input (`Issuer Host` value from user input or `OAUTH_OIDC_ISSUER_HOST` environment variable) instead of the raw input value. For example, keycloak provides the issuer host URL `https://keycloak.example.com/auth/realms/<theNameOfRealm>` and its discovery endpoint should be `https://keycloak.example.com/auth/realms/<theNameOfRealm>/.well-known/openid-configuration`. When Growi starts OpenID integration, it generates a discovery endpoint URL `https://keycloak.example.com/.well-known/openid-configuration` (instead of `https://keycloak.example.com/auth/realms/<theNameOfRealm>/.well-known/openid-configuration`) and checks its reachability. However, since the generated URL is invalid in Keycloak, the reachable test fails (keycloak returns 404 Not found). As a result, the OpenID integration procedure fails.

Environment
------------

### Host

| item                                               | version             |
| -------------------------------------------------- | ------------------- |
| OS                                                 | Ubuntu 20.04.02 LTS |
| GROWI                                              | 5.0.8               |
| node.js                                            | 16.15.1             |
| npm                                                | 8.11.0              |
| Using Docker                                       | yes                 |
| Using growi-docker-compose | no                  |

### Client

| item    | version                                 |
| ------- | --------------------------------------- |
| OS      | Linux                                   |
| browser | 102.0.5005.61 (Official Build) (64-bit) |

How to reproduce? (再現手順)
---------------------------

1. Setup Growi (>=v4.5.12 or >=5.0.0) and Keycloak deployments
2. Login to Keycloak, register a client id (growi), and generate a client secret
3. Login to Growi as admin, and go to Settings > Security settings > Authentication Mechanism Settings > OIDC tab
4. Input following information and press "Update" button
    - OpenID Connect
        - Enable OIDC: yes
        - Callback URL: (not editable)
    - Configuration
        - Provider Name: keycloak
        - Issuer Host: `https://keycloak.example.com/auth/realms/<theNameOfRealm>`
        - Client ID: growi
        - Client Secret: (generated client secret value on Keycloak)
    - Attribute Mapping
        - Identifier: sub
        - Username: preferred_username
        - Name: name
        - Email: email

What happens? (症状)
---------------------

Growi emits following logs (OidcStrategy: issuer host unreachable: undefined) and fails to integrate with the OpenID provider.

```
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"5adaf693-0f3b-4d70-8402-e447d280e969","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/in-app-notification/list?limit=6 HTTP/1.1 200 160 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 13.467589 ms","time":"2022-06-09T22:30:46.688Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"a1e69155-c99e-41d4-a3bb-cc1a0e41b4f2","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/in-app-notification/status HTTP/1.1 200 11 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 7.162421 ms","time":"2022-06-09T22:30:46.689Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":20,"msg":"OidcStrategy: reset","time":"2022-06-09T22:30:47.977Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":20,"msg":"OidcStrategy: setting up..","time":"2022-06-09T22:30:47.977Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"0b0e8ab7-c148-444b-92a2-9d6fa96aa246","level":30,"msg":"::ffff:10.6.6.2 <-- PUT /_api/v3/security-setting/oidc HTTP/1.1 200 645 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 63.805533 ms","time":"2022-06-09T22:30:47.981Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":50,"msg":"OidcStrategy: issuer host unreachable: undefined","time":"2022-06-09T22:30:47.985Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":50,"msg":"OidcStrategy: setup failed","time":"2022-06-09T22:30:47.985Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"32cc8ab7-be87-44f6-aad6-36ed4a0d29f1","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/security-setting/authentication HTTP/1.1 200 29 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 1.492068 ms","time":"2022-06-09T22:30:48.028Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

OpenID Connect integration settings successfully configured.

Note
----

The problem was injected by the commit 2813835. Related issues are #5201 (for >=v5.0.0), #5220 (for >=4.5.12), and [GW-7681](https://youtrack.weseek.co.jp/issue/GW-7681).

Originally, the change seems to be intended for accepting ambiguous input for the Issuer Host value (e.g. `https://auth.example.com` and `https://auth.example.com/.well-kn# Authentication settings with OpenID Connect fails

Abstract
--------
Some OpenID Providers such as Keycloak support multi-tenant use cases by introducing a realm name to their endpoint URLs. Growi supports authentication integration to external identity providers by OpenID Connect, and it checks their OpenID discovery endpoint (/.well-known/openid-configuration) at the first step of the settings procedure. However, since v4.5.12 and v5.0.0, Growi uses a generated discovery endpoint URL according to the user input (`Issuer Host` value from user input or `OAUTH_OIDC_ISSUER_HOST` environment variable) instead of the raw input value. For example, keycloak provides the issuer host URL `https://keycloak.example.com/auth/realms/<theNameOfRealm>` and its discovery endpoint should be `https://keycloak.example.com/auth/realms/<theNameOfRealm>/.well-known/openid-configuration`. When Growi starts OpenID integration, it generates a discovery endpoint URL `https://keycloak.example.com/.well-known/openid-configuration` (instead of `https://keycloak.example.com/auth/realms/<theNameOfRealm>/.well-known/openid-configuration`) and checks its reachability. However, since the generated URL is invalid in Keycloak, the reachable test fails (keycloak returns 404 Not found). As a result, the OpenID integration procedure fails.

Environment
------------

### Host

| item                                               | version             |
| -------------------------------------------------- | ------------------- |
| OS                                                 | Ubuntu 20.04.02 LTS |
| GROWI                                              | 5.0.8               |
| node.js                                            | 16.15.1             |
| npm                                                | 8.11.0              |
| Using Docker                                       | yes                 |
| Using [growi-docker-compose][growi-docker-compose] | no                  |

### Client

| item    | version                                 |
| ------- | --------------------------------------- |
| OS      | Linux                                   |
| browser | 102.0.5005.61 (Official Build) (64-bit) |

How to reproduce? (再現手順)
---------------------------

1. Setup Growi (>=v4.5.12 or >=5.0.0) and Keycloak deployments
2. Login to Keycloak, register a client id (growi), and generate a client secret
3. Login to Growi as admin, and go to Settings > Security settings > Authentication Mechanism Settings > OIDC tab
4. Input following information and press "Update" button
    - OpenID Connect
        - Enable OIDC: yes
        - Callback URL: (not editable)
    - Configuration
        - Provider Name: keycloak
        - Issuer Host: `https://keycloak.example.com/auth/realms/<theNameOfRealm>`
        - Client ID: growi
        - Client Secret: (generated client secret value on Keycloak)
    - Attribute Mapping
        - Identifier: sub
        - Username: preferred_username
        - Name: name
        - Email: email

What happens? (症状)
---------------------

Growi emits following logs (OidcStrategy: issuer host unreachable: undefined) and fails to integrate with the OpenID provider.

```
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"5adaf693-0f3b-4d70-8402-e447d280e969","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/in-app-notification/list?limit=6 HTTP/1.1 200 160 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 13.467589 ms","time":"2022-06-09T22:30:46.688Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"a1e69155-c99e-41d4-a3bb-cc1a0e41b4f2","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/in-app-notification/status HTTP/1.1 200 11 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 7.162421 ms","time":"2022-06-09T22:30:46.689Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":20,"msg":"OidcStrategy: reset","time":"2022-06-09T22:30:47.977Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":20,"msg":"OidcStrategy: setting up..","time":"2022-06-09T22:30:47.977Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"0b0e8ab7-c148-444b-92a2-9d6fa96aa246","level":30,"msg":"::ffff:10.6.6.2 <-- PUT /_api/v3/security-setting/oidc HTTP/1.1 200 645 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 63.805533 ms","time":"2022-06-09T22:30:47.981Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":50,"msg":"OidcStrategy: issuer host unreachable: undefined","time":"2022-06-09T22:30:47.985Z","v":0}
{"name":"growi:service:PassportService","hostname":"6f736638b495","pid":1,"level":50,"msg":"OidcStrategy: setup failed","time":"2022-06-09T22:30:47.985Z","v":0}
{"name":"express","hostname":"6f736638b495","pid":1,"req_id":"32cc8ab7-be87-44f6-aad6-36ed4a0d29f1","level":30,"msg":"::ffff:10.6.6.2 <-- GET /_api/v3/security-setting/authentication HTTP/1.1 200 29 http://192.168.86.250:3000/admin/security Chrome 102.0 Linux 0.0.0 1.492068 ms","time":"2022-06-09T22:30:48.028Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

OpenID Connect integration settings succeeds.

Note
----

The problem was injected by the commit 2813835. Related issues are #5201 (for >=v5.0.0), #5220 (for >=4.5.12), and [GW-7681](https://youtrack.weseek.co.jp/issue/GW-7681).

Originally, the change seems to be intended for accepting ambiguous input for the Issuer Host value (e.g. `https://auth.example.com` and `https://auth.example.com/.well-known/openid-configuration`). However, its logic extracts the URL scheme and the hostname, ommiting the trailing path.

Solution 1

It could be solved by changing the logic of `getOIDCIssuerHostName` from extracting the hostname to ommiting the trailing string `/.well-known/openid-configuration`.

Solution 2

It could be solved by changing the label of `Issuer Host` to `Discovery endpoint` or `Configuration endpoint`, and setting its input placeholder to `https://auth.example.com/.well-known/openid-configuration`.

**Comment by yuki-takei** [comment]
Please wait the next release.
