### ISSUE TITLE
Bug: Error on typing emoji

### ISSUE THREAD

**Issue by SIY1121** [weseek/growi#6036]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |centos7|
|GROWI     |5.0.0|
|node.js   |16.14.2|
|npm       |8.5.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |windows11 21H2|
|browser   |chrome 102.0.5005.63（Official Build）|

How to reproduce? (再現手順)
---------------------------

Unknown(cannnot reproduce)

content at the time of occurrence
- There is a drawio diagram
- There is a table
- There is a decoration using bootstrap

What happens? (症状)
---------------------
After typing : to enter a emoji, an error occurred and the article disappeared 😢

> Error occured in ms
TypeError: Cannot read properties of undefined (reading 'map')

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/17082836/173243117-bbfee1ff-cd28-4a44-9506-46e0ea19553e.png">

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at nr (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:685748)
    at br (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:690006)
    at $r (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:697271)
    at qr (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:697208)
    at ol.prepareSelection (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:813327)
    at Oi (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:711548)
    at Si (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:710567)
    at vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:710436
    at Tn (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:679185)
    at Ei (vendors.c18fdd0d2de2eb7a13fb.chunk.js:2:710364)
```

<img width="454" alt="image" src="https://user-images.githubusercontent.com/17082836/173243507-46f95dee-c394-47a8-9be4-ca994f24676c.png">

What is the expected result? (期待される動作)
-------------------------------------------
No errors occur

I'm very sad that an hour was wasted.
It would be nice to have an auto save feature.

**Comment by yuki-takei** [comment]
@SIY1121 v6.0.0 or above solve this.
