### ISSUE TITLE
GROWIの検索について

### ISSUE THREAD

**Issue by Genki-Kobayashi** [weseek/growi#6066]
GROWIご担当者様
いつもお世話になっております。HEROZの小林と申します。

GROWIの検索が、過去の記事にあるキーワードを入力しても
ヒットしなくなっています。
最近の記事だけヒットするようです。
キーワードで調べたいときがあるので、修正することは可能でしょうか？

宜しくお願い致します。

**Comment by yuki-takei** [comment]
@Genki-Kobayashi ご利用中の状況がバグにあたるのかどうかを切り分けたいです。以下をご確認いただけますでしょうか。

- GROWI のバージョンが v5 以降か
    - その場合、[GROWI v5.0.x へのアップグレード](https://docs.growi.org/ja/admin-guide/upgrading/50x.html) の「新しい v5 互換形式へのアップグレード操作」を行っているか
    - プライベート設定のページに関しても同様に「新しい v5 互換形式への変換」操作を行っているか
- 管理画面の全文検索管理から、インデックスの再作成を行っても同様の症状のままか

上記の対処を行っても解決しない場合は、ご利用中の環境についてもう少し詳しい情報をください。具体的には、

https://github.com/weseek/growi/issues/new?assignees=&labels=bug&template=bug-report.md&title=Bug%3A

のフォーマットに則って記載いただければと思います。
よろしくお願いいたします。

**Comment by Genki-Kobayashi** [comment]
GROWIご担当者様
いつもお世話になっております。HEROZの小林です。

ご連絡ありがとうございます。
インデックスの再作成で事象解決しました。
一応ですが、弊社で利用しているGROWIは
クラウド版で、バージョンは4.5.21でした。

ご対応いただきありがとうございました。
本件、クローズとしていただいて構いません。

以上です。宜しくお願い致します。

2022年7月5日(火) 2:59 Yuki Takei ***@***.***>:
>
> @Genki-Kobayashi ご利用中の状況がバグにあたるのかどうかを切り分けたいです。以下をご確認いただけますでしょうか。
>
> GROWI のバージョンが v5 以降か
>
> その場合、GROWI v5.0.x へのアップグレード の「新しい v5 互換形式へのアップグレード操作」を行っているか
> プライベート設定のページに関しても同様に「新しい v5 互換形式への変換」操作を行っているか
>
> 管理画面の全文検索管理から、インデックスの再作成を行っても同様の症状のままか
>
> 上記の対処を行っても解決しない場合は、ご利用中の環境についてもう少し詳しい情報をください。具体的には、
>
> https://github.com/weseek/growi/issues/new?assignees=&labels=bug&template=bug-report.md&title=Bug%3A
>
> のフォーマットに則って記載いただければと思います。
> よろしくお願いいたします。
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
HEROZ株式会社 小林 弦生
KOBAYASHI Genki ***@***.***>
HEROZ, Inc.

**Comment by kaoritokashiki** [comment]
解決したとのことなので、Isuue closeします。
引き続きGROWIをよろしくお願いいたします!
