### ISSUE TITLE
Request: 言語pumlのコードブロックをPlantUMLで出力したい

### ISSUE THREAD

**Issue by fujitalon** [weseek/growi#6074]
## Informations
growiでPlantUML用の記述を含むドキュメントを作成しmarkdownでexportした後、VSCodeでそのmarkdownを開くとPlantUMLの部分がUMLとして出力されない

VSCodeでUML出力されるように@startuml～@endumlを コードブロックにし言語としてpumlを指定すると、groiwでUMLとして出力されない

**Describe the solution you'd like**
growiで言語pumlのコードブロックをPlantUMLの出力対象として評価してほしい

**Comment by sevenjay** [comment]
it's related to
https://github.com/weseek/growi/issues/5680

**Comment by yuki-takei** [comment]
@fujitalon #5680 を discussion に移しました。こちらはクローズします。
