### ISSUE TITLE
Bug: Slack integrationのtest connectionのtestボタンが反応しない

### ISSUE THREAD

**Issue by kyusuke-10** [weseek/growi#6099]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |5.0.9|
|node.js   |16.15.1|
|npm       |8.11.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 12.4|
|browser   |Safari 15.5|

How to reproduce? (再現手順)
---------------------------
Slack Integration -> Custom bot with proxy -> Test Connection
で実在するパブリックチャンネルを入力し、テストボタンを押しても反応しない。(Logsのところに何の表示も出ない)

What happens? (症状)
---------------------
上記のようにテストボタンを押しても反応しない。

What is the expected result? (期待される動作)
-------------------------------------------
Testボタンを押すと何かしらの反応があること。（失敗したとしても何かしらの反応があった様な気がしています。）

Note
----

- Proxy server上部にIntegration successfulの表示は出ています。
- 以前のバージョン(5.0.1)のときにはTestは成功していました。

**Comment by yukendev** [comment]
issueの報告ありがとうございます。バグがこちらの手元でも再現しましたので、修正対応します。

**Comment by yukendev** [comment]
こちらの不具合を修正いたしました。報告ありがとうございます

**Comment by kyusuke-10** [comment]
ありがとうございます。次のリリースを楽しみにしています

**Comment by yukendev** [comment]
バージョン5.0.12で修正されます。これからもGROWIをよろしくお願いいたします
