### ISSUE TITLE
Bug: ページツリー上でリネームしたページの配下に別ページをD&D移動すると古いページパスに移動してしまう

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#6117]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |5.0.9|

### Client

| item     | version |
| ---      | --- |
|OS        | Windows11 (64bit) |
|browser   | Google Chrome  103.0.5060.53（Official Build） |

How to reproduce? (再現手順)
---------------------------

1. PageTree を開く
1. 任意の1ページ (子ページ無し) を、ページツリー上でリネーム
1. ブラウザリロード等をせず、ページツリー上で続けざまに別の任意の1ページ (子ページ無し) を、`2.` でリネームしたページの配下に D & D で移動させる
1. ブラウザをリロードする

What happens? (症状)
---------------------

- 手順 `3.` で、D & D で移動させたページが、手順 `2.` でリネームする前のパスの配下に移動してしまう
  - ページツリーからリネームした旧名のパスには、空ページが生成される

What is the expected result? (期待される動作)
-------------------------------------------

- リネーム後のページ名配下に正しく移動される
![GROWI_issue_pagetree-rename](https://user-images.githubusercontent.com/8895367/175354841-527fb5dd-6ba0-49b0-8640-d680aac0656f.gif)

**Comment by jam411** [comment]
@TatsuyaIse This issue was fixed by v6.0.15.
この問題は v6.0.15 で修正されました。
