### ISSUE TITLE
Bug: 「ID&Password」有効状態で管理者が「新規ユーザーの仮発行」を使用したユーザーがログインボタンを押下時にユーザー新規登録画面に遷移しない

### ISSUE THREAD

**Issue by eyelly** [weseek/growi#6134]
Environment
------------
growi.cloud freeplan
### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |5.0.9|
|node.js   |16.15.1|
|npm       |8.11.0|
|yarn      |1.22.19|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

### Client

| item     | version |
| ---      | --- |
|OS        |windows 11|
|browser   |Microsoft Edge 103.0.1264.37 & Chrome102.0.5005.115 |

How to reproduce? (再現手順)
---------------------------

1. 管理画面>ユーザー管理ページの「新規ユーザーの仮発行」から招待したいユーザーのemailアドレスを入力し、「発行」ボタンを押す(仮パスワードを取得)
1. 該当するユーザーがログイン画面にいき、emailアドレスと、上記で取得したパスワードを用いてログインする

What happens? (症状)
---------------------

- ログイン後、エラーが画面左上に表示
- 画面上部navバー上のユーザー情報が表示されない
![image](https://user-images.githubusercontent.com/14306698/175802262-5a3563c6-32b3-4893-82e3-24797cb96346.png)
- 編集画面へのアクセスができてしまう（編集はできない）

What is the expected result? (期待される動作)
-------------------------------------------

- 仮発行ユーザーによる登録を可能とする

Note
----

- ユーザーが自身で新登録画面で情報を入力しログインすることで新規登録は可能。
- 仮発行した場合はログインできても、閲覧だけ可能。

**Comment by kaoritokashiki** [comment]
@eyelly 
Issueの報告ありがとうございます。
GROWI Demo (v5.0.9) にて再現確認できましたので、修正対応に入ります。
しばらくお待ちください。

**Comment by kaoritokashiki** [comment]
@eyelly
追加で確認させてください。
## Q1. ゲストユーザーのアクセスについて
管理画面 > セキュリティ設定にて、「ゲストユーザーのアクセス」を許可にしていますか?

## Q2. email & 仮パスワードでのログイン時の挙動について
 ユーザーが自身で新登録画面で情報(email & 仮password)を入力し「ログイン」ボタンを押した時の挙動について
1. ユーザー新規登録画面(email, name, username, password の登録画面)に遷移せず、トップページなどのページに遷移してしまいますか?
2. URL で('/me') などのページに遷移しようとすると、新規登録画面に遷移しますか?
┗新規登録の必要事項を入力し、登録ボタンを押してログインすると、ナビバーのエラーはなくなりますか?

**Comment by eyelly** [comment]
> 管理画面 > セキュリティ設定にて、「ゲストユーザーのアクセス」を許可にしていますか?
⇒許可しています。
![image](https://user-images.githubusercontent.com/14306698/175811856-216a887e-9281-40d1-9ad4-ca18c044fb1a.png)

> ユーザー新規登録画面(email, name, username, password の登録画面)に遷移せず、トップページなどのページに遷移してしまいますか?
⇒はい

> URL で('/me') などのページに遷移しようとすると、新規登録画面に遷移しますか?
⇒/meに遷移しようとするとlogin/invitedへリダイレクトされ、新規登録が可能です。エラーは無くなりました。

**Comment by kaoritokashiki** [comment]
## Memo
仮発行されたユーザーは、初回ログイン時にユーザー新規登録ページに遷移して欲しいが、現状だと、遷移せずトップページなどのページが表示されてしまうことが原因。

>仮発行した場合はログインできても、閲覧だけ可能。

これは「ゲストユーザー」のアクセスを許可していたので、ログインしているように見えただけで、ゲストユーザーとしてページの閲覧ができているということになる

## バグが修正されるまでの対策
仮ユーザーでログインボタンを押した後、`/me`などページにいくことで新規登録画面に遷移可能なので、そこから本登録する

**Comment by kaoritokashiki** [comment]
@eyelly 
今回 Issueを起票していただきありがとうございました。

修正が完了致しましたのでご連絡です。
次回リリース v5.0.11 をお待ちください。

引き続きGROWIをよろしくお願いします 😊

**Comment by kaoritokashiki** [comment]
4系での修正

**Comment by kaoritokashiki** [comment]
4系では [v4.5.24](https://github.com/weseek/growi/releases/tag/v4.5.24) にて修正版のリリースが済んでいます。
よって、issueをクローズします。
