### ISSUE TITLE
新規ページで更新(Create)ボタンが出てこない

### ISSUE THREAD

**Issue by gaku-h** [weseek/growi#614]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |windows7|
|GROWI     |3.2.3-RC|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome,Edge,IE11|

How to reproduce? (再現手順)
---------------------------

1. process 1
ログインユーザー配下に記事を作成しようと右上の作成ボタンを押下
ページを以下に作成でページ名を入力、作成を押下

What happens? (症状)
---------------------
ページ作成画面にて右下の更新ボタンがない
　※下側が見切れている
　※一度[List]を選択し、[Create]を選択しなおすと問題なく表示される
　※Chrome、Edge、IE11でも事象が発生する
　※編集(Edit)は問題なく表示される
![error](https://user-images.githubusercontent.com/43461621/45860602-8f5f6c00-bd57-11e8-8450-357c1c9b41e1.jpg)

Stack Trace
```



What is the expected result? (期待される動作)
-------------------------------------------
表示される
- 
- 



Note
----
切り分けとして、Growiのバージョンを3.1.6-RC以下にすると
問題なく表示されたが、IE11でテキスト入力ができなくなった

- 
-

**Comment by yuki-takei** [comment]
@gaku-h ご報告ありがとうございます。

開発環境でたまにこの事象が発生することは確認しているのですが、production 環境では再現を確認できていません。3.2.3-RC をご利用とのことですが、GROWI をどのように起動しているかを教えていただけますでしょうか。

また、再現確率がどれくらいかも併せて教えていただけると助かります。

**Comment by gaku-h** [comment]
yuki-takai様ご連絡ありがとうございます。
Growiの起動についてですが
MongoDBはサービスで起動しています。
　※同時にElasticsearchもサービス起動しています。
Growiはコマンドプロンプトでnpm startで起動しています。

再現確率ですが,100%になっています。

宜しくお願いします。

**Comment by yuki-takei** [comment]
起動方法が `npm start` なのは手順としては合っていますね。起動時のコマンドプロンプトのログを貼ることはできますか？

あとは気になる箇所は npm のバージョンが 6 系なところ…こちらを 5 系にするとどうなるでしょうか。

**Comment by gaku-h** [comment]
@yuki-takei 
検証が遅くなりました。
バージョンをいろいろ試したところ
以下のバージョンで今のところ正常に[Create]ボタンが出るようになりました。
Growi 3.2.4-RC
node.js 8.11.4
npm 5.6.0
yarn 1.9.4
しばらくこれで様子を見ようと思います。
有難う御座いました。
