### ISSUE TITLE
 Feature: Support mostly setting items of SAML provider

### ISSUE THREAD

**Issue by sahya** [weseek/growi#615]
## Environment

|item|version|
|:---:|:---:|
|OS||
|GROWI|3.2.2|
|node.js|5.6.0|
|yarn|1.9.2|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1.  no trouble(this is request)

What happens? (症状)
---------------------

1.  no trouble(this is request)

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------

- for examle
    - able to choose  the signatureAlgorithm of SAML provider on growi. (e.g. sha256)
    - Able to choose the identifierFormat of of SAML provider on growi.(e.g. undefined[username])

Note
----
- I think the item of SAML authentication can set few item when I compare the Growi and wordpress that SAML settings of word press used [onelogin SAML plug-in.](https://ja.wordpress.org/plugins/onelogin-saml-sso/)
- It is not a hurry (e.g. 2-mounth), but The item of SAML authentication need comprehensiveness.
#603 x.503 certificate is a part of the item of SAML settings.

**Comment by sahya** [comment]
related issue : #542

**Comment by yuki-takei** [comment]
@sahya Thank you for your suggestion.

SAML related settings are too many, we had discussed which settings we should support.
In conclusion, we raise it to shelve and released v3.2.1 for the time being.

I think OneLogin's implementation is a nice job, too.
We’ll consider it.

**Comment by sahya** [comment]
OK, I wait to  release feature include this issue.
About how long impremets feature include this issue?
but I dont rush things.

**Comment by yuki-takei** [comment]
Sorry, we can't promise it at the moment. But it is in progress since we need it for [GROWI.cloud](https://growi.cloud).

**Comment by yuki-takei** [comment]
## Refs 1

https://qiita.com/katakura__pro/items/1e65e0bde7fda75332a1

## Refs 2

![screenshot-wp fiarysky net-2018-09-15-21-12-31-590](https://user-images.githubusercontent.com/1638767/46344200-59858600-c67b-11e8-832b-63f226941d67.png)

**Comment by sahya** [comment]
hello, 
Long time no see.

I was sorry to request beggest this feature request.
I guess this issue may better than to close.
And if you need, I will try to divide this issue for easy to close.

Do you think about the dividing issue?

**Comment by sahya** [comment]
I heard you the issue has a better divide than this state by Growi slack.
So I  will create the related issue,
