### ISSUE TITLE
Improvement: ファイル添付時にダウンロードリンクが挿入されてほしい

### ISSUE THREAD

**Issue by dalance** [weseek/growi#616]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.5|
|GROWI     |3.2.3|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome/Vivaldi/Edge|

How to reproduce? (再現手順)
---------------------------

1. 編集画面でファイルをドラッグ＆ドロップする

What happens? (症状)
---------------------

1. 以下の記述が挿入される

    ```
    [ファイル名](/uploads/attachment/xxxx/yyyy.ext)
    ```

2. このリンクをクリックするとyyyy.extというファイル名でダウンロードされる

What is the expected result? (期待される動作)
-------------------------------------------

- 以下のようにダウンロードリンクが挿入されてほしい

    ```
    [ファイル名](/download/xxxx)
    ```

- こちらは元のファイル名でダウンロードされる

**Comment by yuki-takei** [comment]
@dalance 現状、フッター部にそのページ添付のファイル一覧とそのダウンロードリンクが表示されますが、それでは不足でしょうか？

仕様変更は悩ましいですね。ダウンロードリンクは GROWI が用意しているダウンロード用のリンクなので、

`[ファイル名](ファイルの実体参照URL)`

を載せるのが筋だとは思いますが…管理画面からどちらにするかを選べるというのがいいんでしょうか。

**Comment by dalance** [comment]
了解しました。
ダウンロードリンクが追加機能であれば
それに依存する機能を本体に入れるのは
あまりよくないように思います。
運用で回避可能なので本件は取り下げます。
ありがとうございました。
