### ISSUE TITLE
Bug: Comment, preview と write を切り替えた時の表記のずれ, 行数が多い(Sandboxと同内容など)場合に表示されない. 

### ISSUE THREAD

**Issue by jam411** [weseek/growi#6229]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |5.0.11|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11 (64-bit)|
|browser   |Firefox 102.0 (64-bit)|

How to reproduce? (再現手順)
---------------------------
- Bug 1
1-1. 任意のページ下部の Comments から Add Comment をクリックする
1-2. Write と Preview を切り替える
- Bug 2
2-1. 任意のページ下部の Comments から Add Comment をクリックする
2-2. Sandboxの内容などを張り付ける
2-3. Preview へ切り替える, もしくは保存する

What happens? (症状)
---------------------

- Bug 1 & 2
![Comments](https://user-images.githubusercontent.com/68407388/177960856-5ea9ac3c-461e-4155-980d-d3c2fa90a037.gif)

What is the expected result? (期待される動作)
-------------------------------------------

- Write, Preview を切り替えても表記がずれないこと.
- 上限がある場合は, 記載もしくはエラー表記するなどしてCommentの上限を示す.

Note
----

**Comment by yuki-takei** [comment]
This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
