### ISSUE TITLE
Bug: diagrams.netの図が描画されない場合がある

### ISSUE THREAD

**Issue by CMS-yokota** [weseek/growi#6253]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        Amazon Linux |2|
|GROWI     |5.0.11|
|node.js   |16.15.1|
|npm       |8.11.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10 pro|
|browser   |chrome 103.0.5060.114|

How to reproduce? (再現手順)
---------------------------

1. Diagrams.netの図が組み込まれたページ(例:Sandbox/Diagrams)を開く

What happens? (症状)
---------------------

- diagrams.netの図が描画されない場合がある (添付画像参照)
- アクセス時によって再現する場合としない場合がある (再現率: 11/20)

![draw io_err](https://user-images.githubusercontent.com/108501533/178630620-7e5d1bb4-49a9-4d8c-b87a-36a70040d3ef.PNG)

What is the expected result? (期待される動作)
-------------------------------------------

- Diagrams.netの図が必ず描画されること

Note
----

-

**Comment by hakumizuki** [comment]
Issue 起票ありがとうございました。https://github.com/weseek/growi/pull/6275 にて修正いたしました。
次回の 5.1.0 リリースで修正が反映される予定です。
