### ISSUE TITLE
Request: ユーザごとのブックマークを常に表示したい

### ISSUE THREAD

**Issue by uniocto** [weseek/growi#6255]
## Informations
自分のブックマークから各ページにアクセスする時、常にHOMEページを経由する必要がある。　　
そのため、常にブックマークが表示されていて、ブックマークの各ページにアクセスできるようにして欲しい。

**Describe the solution you'd like**
ログインしているユーザのブックマーク表示を、ページツリーやカスタムサイドバーの並びに追加する。

**Describe alternatives you've considered**
個々人のカスタムサイドバーを表示できるようにする。

**Comment by kaoritokashiki** [comment]
@uniocto
Issueの起票ありがとうございます。
サイドバーにブックマークを表示する施策は既にデザイン検討から走り出しておりますので、今しばらくお待ちいただければと思います。

**Comment by yuki-takei** [comment]
@uniocto v6.1 で実装されました
