### ISSUE TITLE
特定の条件を満たすタイトルの記事の作成に失敗する

### ISSUE THREAD

**Issue by tubo28** [weseek/growi#631]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04 (Growi は下記の通り Docker で動いています)|
|GROWI     |3.2.3|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Firefox 62.0.3 (64 bit), Chrome 69.0.3497.100 (Official Build) (64 bit)|

How to reproduce? (再現手順)
---------------------------

1. `/++` に新規ページを作る
1. `/++/a` に新規ページを作ろうとする

What happens? (症状)
---------------------

- 長時間レスポンスが帰ってこず、待つと Nginx が `504 Gateway Time-out` を返す

What is the expected result? (期待される動作)
-------------------------------------------

- ページの作成に成功する

Note
----

軽く試すと

- `/c++`, `/+/+/+` は成功
- `/c++/a`, `/a/++/a` は失敗

**Comment by utsushiiro** [comment]
@tubo28 ご報告ありがとうございます、再現を確認しました。
近日中に対処しますので今しばらくお待ちください。
