### ISSUE TITLE
Improvement: A pasted table is broken

### ISSUE THREAD

**Issue by cgwr** [weseek/growi#639]
Environment
------------

### Host
Demo site  (v3.2.4)

### Client

| item     | version |
| ---      | --- |
|Windows  |10 pro|
|Chrome   ||
|Excel | 2016|

How to reproduce? (再現手順)
---------------------------

1. Copy some cells on Excel
1. Open "Edit Table" dialog on Growi
1. Paste
1. Click "Done"
 

What happens? (症状)
---------------------

![image](https://user-images.githubusercontent.com/39648501/46813628-08c80880-cdb2-11e8-9927-db5e8ccd5e97.png)

What is the expected result? (期待される動作)
-------------------------------------------

![image](https://user-images.githubusercontent.com/39648501/46813569-eafaa380-cdb1-11e8-81e0-1689d21b64b6.png)

Note
----
* There is no problem with macOS and Google Spreadsheet.

This new feature is really great. I wish that it would be fixed. Thanks.

**Comment by yuki-takei** [comment]
@cgwr Thank you for your report.

Features to paste data that is copied from other tools will be implemented in near future.

That includes:

1. Paste HTML/CSV and convert to Markdown
1. Paste from Excel/Googlespreadsheet

And this phenomenon you reported will be fixed at that time.

**Comment by cgwr** [comment]
It sounds great!  I'm looking forward to it.

**Comment by yuki-takei** [comment]
refs https://github.com/handsontable/handsontable/issues/5330

**Comment by yuki-takei** [comment]
Test Environment (Heroku)
https://growi-639.herokuapp.com/Sandbox/TableTest

**Comment by cgwr** [comment]
@yuki-takei @utsushiiro 
Thanks for the fix!
I checked it on the demo site 3.2.7 .
