### ISSUE TITLE
Bug: Recent Createdに当該ユーザの記事が表示されるよう修正して欲しい

### ISSUE THREAD

**Issue by motoisto** [weseek/growi#640]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |CentOS|
|GROWI     |3.2|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client
| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   |Chrome|

### 期待される動作
-------------------------------------------

- ユーザHomeのRecent Createdに自分の（ログインユーザの）記事だけが表示されてしまいます。
　元の仕様通り、選択している当該ユーザの記事が表示されるよう修正をお願いします。

### 用途
-------------------------------------------
- N氏が作成したコンテンツを一覧して、興味深いコンテンツを探したい
- 以前に見たN氏の記事を探したい

**Comment by motoisto** [comment]
growi3.2.4です。

**Comment by TsuyoshiSuzukief** [comment]
ご指摘ありがとうございます。ご報告いただいた通り、処理の追加により動作が変わっており、不具合でした。

/user/foo
/user/bar

上記のユーザー名階層の画面にて、各ユーザー毎の RecentCreated 表示があります。

ログインユーザーが foo でも、
/user/bar 画面では bar ユーザーの作成した RecentCreated ページが表示されていましたが、
今回の修正対応により、fooがログイン者だと
/user/bar 画面でも foo ユーザーが作成した RecentCreated リストが表示されています。

こちらの不具合については、元の仕様通りの動作へ修正する予定です。
取り急ぎご報告させていただきます。
