### ISSUE TITLE
Bug:mathjaxの数式が表示されない

### ISSUE THREAD

**Issue by tnagai-github** [weseek/growi#6407]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS       |ubuntu22.04 |
|GROWI     | 5|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows|
|browser   |firefox/google chrome|

How to reproduce? (再現手順)
---------------------------
docker-compose.yml でバージョン5.x.xのgrowiをインストールすると、Mathjaxの数式が見られない。
デモの<https://demo.growi.org/5ed46e05df07e700484389f4>でも数式が変換されておらず、
\[ などがそのまま見えている。

一方で、 docker-compose.v45x-es6.ymlをベースに利用してインストールした際は、数式が変換されて正しく見られる。

What happens? (症状)
---------------------

5系で数式が見られない。
（firefoxでもgoogle chromeでも生じる）

What is the expected result? (期待される動作)
-------------------------------------------
5系でも数式が正しく変換される。

Note
----

**Comment by yuki-takei** [comment]
@tnagai-github ご報告ありがとうございます。既知のバグです。
https://github.com/weseek/growi/pull/6396

修正された v5.1.2 がリリースされましたのでそちらをご利用ください。
