### ISSUE TITLE
Feature: サイドバーの編集機能を実装してほしい

### ISSUE THREAD

**Issue by yusuke-kishi** [weseek/growi#642]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Linux mint 19(tara) |
|GROWI     | 3.2.4 |
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]| yes |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | windows10 |
|browser   | google chorme |

What is the expected result? (期待される動作)
-------------------------------------------

- markdownでの編集／更新
- サイドバーの横幅を調整／固定
- サイドバーの横幅を超える文字幅は自動的に折り返し
- サイドバーの縦幅を超える文字幅はスクロールバーの付与

Note
----

nullと申します。
サイドバーの編集機能が欲しいと思い、リクエストさせていただきました。
現バージョンではサイドバー自体はあるものの、編集機能がないためとても惜しいと思いました。
運用としてはPukiWikiのサイドメニューに近い事ができると良いと考えています。
Sidebar imageに現行と実装後のイメージ図を添付しております。

もし現バージョンで私が希望している機能と同等の事が出来るならば、
そのやり方を提示していただけると非常に助かります。

Sidebar image
----

| current | future | future_scrollbar_true |
| ---  | --- | --- |
| <img src="https://user-images.githubusercontent.com/12610584/46877774-96702a80-ce7c-11e8-9c11-de15dc7caad0.png" width="200px"> | <img src="https://user-images.githubusercontent.com/12610584/46877802-a556dd00-ce7c-11e8-8eaa-51d0f5acd1c4.png" width="200px"> | <img src="https://user-images.githubusercontent.com/12610584/46877829-b869ad00-ce7c-11e8-93a2-419c6355cb65.png" width="200px"> |

Related issues
----

#175

**Comment by yuki-takei** [comment]
@null-void-dev ご意見ありがとうございます。
我々も元 PukiWiki ユーザーでしたので、実装後に想定している使い方としては今回挙げていただいたような形を考えていました。

ただ愚直に実装すると lsx プラグインが使えてしまって、そちらノーキャッシュなのであまりよくないなあというのと、PukiWiki におけるページヒストリーのようなものもプラグイン提供したいなあとかいろいろ考えていて実装が先送りになっている状況です。

現状チームの優先順位としては ACL 周りの改修と GROWI.cloud 関連機能が上位になっている状況で、それらを片付けてから改めて優先順位を見直して着手、ということになると思います。

開発者増えて欲しい～～

**Comment by null-void-dev** [comment]
ご回答ありがとうございます！

> PukiWikiにおけるページヒストリーのようなものもプラグイン提供

確かに編集履歴（最新の○○件）的なものを表示するアドオンはあったらいいなとは思っていました。
やはり検討はされていて、現状のタスクと比較して優先度が低い状態でしたか…

GROWI.cloudもビジネス視点で考えると会社の利益に直結するものなので優先度が高いのも頷けます。
プロジェクトを維持するにもお金が掛かりますし…

実装される見通しがあるとわかっただけでも収穫ですので気長に待ちたいと思います。

**Comment by yuki-takei** [comment]
優先順は単純に自分達＆利用者コミュニティの需要が高い物からやってて、サイドバーはたまたま今まであまり声が聞こえてこなかったから、という感じですね。

GROWI.cloud は、今のところそれで収益上げようとは考えてなくて、インフラ実費回収できたらいいなくらいの感覚です。安価に情報共有ツールを提供できたら満足。

OSS 版も cloud 版も合わせて不具合報告や提案の投稿お待ちしてます 😃

**Comment by yuki-takei** [comment]
みなさまお待たせしております。サイドバーは support/apply-bootstrap4 ブランチで実装が進んでいます。
次のメジャーバージョン、v4.0.0 から利用可能になります。

しかしながら、bootstrap v3 -> v4 の作業がとてもとても苦しく、GROWI 村総出でやっていますが、結構キリがない感じ。そんなわけで猫の手でも借りたいところでございます。もしお手隙の方いましたらお手伝いいただけると助かります。

**Comment by yuki-takei** [comment]
thumbs up 付けてくださったのべ30名の方々、大変お待たせ致しました。
`/Sidebar` ページを作成することで中身を自由に入力できるカスタムサイドバーが v4.2.12 から利用可能になりました。

![Evzj0BBUYAQyqVm](https://user-images.githubusercontent.com/1638767/110213506-b4bea100-7ee3-11eb-8c3c-46c7b9a28b5a.jpg)

使用感などございましたら slack でコメントいただけると嬉しいです。

こちらの issue はクローズいたします。
