### ISSUE TITLE
Improvement: Revision history shows empty diffs

### ISSUE THREAD

**Issue by almereyda** [weseek/growi#645]
Environment
------------

### Host

demo.growi.org

### Client

Fedora 28, Firefox 62

How to reproduce? (再現手順)
---------------------------

Visit https://demo.growi.org/#revision-history and check out some of the diffs of certain versions in the history.

What happens? (症状)
---------------------

Some versions will not have any diff associated

What is the expected result? (期待される動作)
-------------------------------------------

Each version should have a diff displayed, else it is omitted from version history.

Note
----

Empty diffs only clutter the version history with information that is not useful to the user.

**Comment by yuki-takei** [comment]
@almereyda Certainly that's right. We'll consider it.

**Comment by yuki-takei** [comment]
![image](https://user-images.githubusercontent.com/1638767/47530601-0a331e00-d8e6-11e8-8c9b-f0e1887ac92f.png)

No diff rows are shrinked.
However, this affects only the revisions which are generated by GROWI v3.2.6.

Please wait a while until next release.
