### ISSUE TITLE
`/_api/v3/user-groups`にアクセストークンを指定しても`/login`へのリダイレクトが返される (dup of #4050?)

### ISSUE THREAD

**Issue by dashwood8691** [weseek/growi#6457]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.5 LTS|
|GROWI     |4.5.22|
|node.js   |14.19.3|
|npm       |6.14.17|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.5 LTS|
|browser   |curl 7.58./0|

How to reproduce? (再現手順)
---------------------------

1. セキュリティ設定→ページの閲覧・削除権限→ゲストユーザーのアクセス「拒否」 に設定
1. `curl -k --location --request GET 'https://localhost/_api/v3/user-groups?access-token=<url_encoded_token>' -I --max-redirs 0`
    i. `/login`へのリダイレクトが返される

    ```
    HTTP/2 302 
    ...snip...
    content-type: text/plain; charset=utf-8
    content-length: 28
    ...snip...
    content-language: en_US
    location: /login
    ```

1. `curl -k --location --request GET 'https://localhost/_api/v3/pages/list?path=/&access_token=<url_encoded_token>' -I`
    i. JSONで返される

What happens? (症状)
---------------------

`/_api/v3/user-groups`に正しいアクセストークンを指定しても`/login`へのリダイレクトが返される

What is the expected result? (期待される動作)
-------------------------------------------

JSONが返される

Note
----

https://github.com/weseek/growi/blob/884a6d1ba46f88544262e40b7a6a313314ec57b2/packages/app/src/server/routes/apiv3/user-group.js#L64

#4050 と同じように`apiv3/user-group.js`64行目含む`router.get()`に`accessTokenParser`が見当たりませんでした。他の`apiv3/`以下のファイルでも`loginRequiredStrictly`が指定されている箇所では`accessTokenParser`が無いように見受けられます。

**Comment by yuki-takei** [comment]
@dashwood8691 バグではなく仕様になります。

現状の access token は機能的に洗練されていないため、全てのエンドポイントで受け付けるようにするとシステムが脆弱になりかねません。そのため主に管理者権限を利用する API では意図的に付けていないものがあります。

根本解決は https://github.com/weseek/growi/issues/4848 にある高度な access token 機構の開発をお待ちいただくことになりますが、こちらは WIP になっているものの開発はそれほど進んでおらず、また現時点でそこまで優先度が高くありません。([Priority C](https://github.com/weseek/growi/discussions/6332))
