### ISSUE TITLE
Internationalisation (I18N)

### ISSUE THREAD

**Issue by almereyda** [weseek/growi#646]
Currently the settings screen of a user allows to switch between English and Japanese.

When selecting English, still some Japanese artifacts remain in the user interface.

It would be nice to have internationalisation configurable from the admin settings, where one could choose standard languages for all users, choose if language switching is available. Also preparing a Transifex/Weblate project can help in translating user interface strings into other languages.

I am taking the effort to write this issue, since Growi is the most feature-complete Markdown Wiki that I found during the last years searching for one, and I wish it receives wide adoption.

Internationalisation will help in allowing users and developers outside of Japan to interact more easily.

**Comment by yuki-takei** [comment]
@almereyda Thank you for your post.

> I am taking the effort to write this issue, since Growi is the most feature-complete Markdown Wiki that I found during the last years searching for one, and I wish it receives wide adoption.

We are really encouredged your message.

I agree with the importance of internationalization.
Since I recognized that GROWI users are only Japanese people, I have not paid attention before.

> Also preparing a Transifex/Weblate project can help in translating user interface strings into other languages.

I didn't know about Transifex/Weblate. We consider it. Thanks.

**Comment by almereyda** [comment]
For convenience, you can find both tools at

- https://www.transifex.com/ (commercial)
- https://weblate.org/ (FLOSS)

If you wish to try out the latter, we're running an instance at https://weblate.allmende.io/

**Comment by yuki-takei** [comment]
It looks like Transifex provides a free license for open source projects.
I inquired about it.

**Comment by yuki-takei** [comment]
I created Transifex Project for the time being.
https://www.transifex.com/weseek-inc/growi
