### ISSUE TITLE
5.0.11 でページリストが20件までしか表示できない

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#6470]
### Discussed in https://github.com/weseek/growi/discussions/6465

<div type='discussions-op-text'>

<sup>Originally posted by **TatsuyaIse** August 19, 2022</sup>
GROWI のバージョン 5.0.11 以降で確認できましたが、ページリストの機能を使って表示するとページの一覧が20件までしか表示されません。
これは意図した仕様でしょうか？
また `$lsx()` をページに記載する以外に、配下のページ一覧を画面から閲覧する方法はありますか？
→ 元の質問は Slack の #help チャンネルにて: https://wsgrowi.slack.com/archives/C4V5ZG4UC/p1660880403918179</div>

確認した結果、バグとのことなので Issue に切り替える。

### 再現条件
1. 上記のバージョンの GROWI で、任意のページの配下に任意の子ページを21ページ以上作成する
2. ページリストのモーダルを表示する

### 症状
- ページリストに 20 件までしか表示されない

### 期待される動作
- 配下の全てのページを表示できる
  - ページャなどにより、全て閲覧できるようになる

**Comment by miya** [comment]
以下の PR で 20件以上ある場合はページャーを表示するように修正しました。
https://github.com/weseek/growi/pull/6468
