### ISSUE TITLE
Bug: SAMLでログインしているユーザーが登録したブックマークが/meページ上に表示されない

### ISSUE THREAD

**Issue by eyelly** [weseek/growi#6503]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04|
| item     | version |
|GROWI     |5.1.3 or 5.1.1|
|node.js   |16.16.0|
|npm       |8.11.0|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

How to reproduce? (再現手順)
---------------------------

1. ページをブックマークする
1. 自身のホームに移動する

What happens? (症状)
---------------------

- ブックマークに表示されていない 

What is the expected result? (期待される動作)
-------------------------------------------
- ブックマークが表示されること

Note
----

- ID&Passwordでログインしているユーザーはブックマーク登録後、/meページでブックマークが表示される

**Comment by kaoritokashiki** [comment]
以下の設定で確かめてみたけど、再現しないですね 🤔
https://dev.growi.org/632bf6fd4a0e56cdd8c249c0

<img width="1556" alt="Screen Shot 2022-09-22 at 16 47 58" src="https://user-images.githubusercontent.com/59536731/191688914-5424ee8f-bacd-4cc9-974c-844d27bf85ce.png">

**Comment by yuki-takei** [comment]
@eyelly 調査してみましたが再現しなかったので、もしかするとその症状が起こるには追加の条件などがあるのかもしれないです。もし他に情報があればお願いします。

**Comment by eyelly** [comment]
@yuki-takei 
調査いただきありがとうございます。
同じ環境で、/me配下のRecently Createdが動作していないこともわかりました。
疑われる点は、Growi導入後すぐはID&Password認証で、その後SAMLに変更していることが挙げられます。
その際、Attribute Mapping OptionsでSAML認証後は既存のユーザープロファイルとマッピングさせていて、SAML認証変更前のプロファイルをそのまま使っている状態です。
引き続きご確認いただけますと幸いです。

**Comment by jam411** [comment]
@eyelly 
こちらでも回答いたします。
ログイン方法によらず、削除された username (User ID) と同じ username で再度ユーザ作成すると、
新規作成ユーザの /user/{username} ページが削除済みユーザのものとなっているようです。
/user/{username} ページは、ユーザを削除しても配下のwikiページを残す意味でそのまま残す仕様でしたので、現在こちらの対応について開発チームで仕様検討しています。今しばらくお待ちください。

**Comment by jam411** [comment]
@eyelly @kota65535
ご報告・検証ありがとうございます。
こちらの issue の正式な修正は[開発ロードマップ](https://github.com/weseek/growi/discussions/6332)にある"ユーザページ改善"のリリース時になりそうです。

現状ワークアラウンドとして、DB操作が可能であれば以下が考えられました。
Bookmarks と Recently Created 表示機能はページの `creator._id` を参照しているため、
ホームページの作成者を変更すれば情報を更新できます。

具体的には
1. `users` コレクションから表示させたいユーザの `_id` キーの値 を取得.
1. `pages` コレクションから該当ユーザホームページのドキュメントの `creator` キーの値 を、先ほど取得した表示させたいユーザの `_id` キーの値 に変更する.

ただし、以前のユーザのデータが更新されてしまうこと、
手元の開発環境で確認したところ特に問題なかったですが構築環境や、中・長期でなんらかの影響可能性があること御了承ください。

また、特定の username を使用したい場合は、ユーザ作成前にユーザページを削除することでユーザホームページを新規作成できました。
1. DB操作で, `pages` コレクションから該当ユーザホームページのドキュメントを削除
1. ユーザを新規に作成。-> 新しいユーザページが作られる。

DB操作せず最も安全でおすすめなのは、
"ユーザページ改善" リリースまでお待ちいただくか、
そのままですが、

1. 異なる username でユーザを新規作成する

となりそうです。

**Comment by jam411** [comment]
- [v6.2.0](https://github.com/weseek/growi/tree/v6.2.0) でユーザー新規登録時に同じ username のユーザーホームページがある場合はそれを一度削除して作り変えるように仕様変更されました。
また、ユーザー削除時にユーザーホームページも一緒に削除する設定ができるようになりました。
詳しくはアップグレードガイドをご覧ください。
https://docs.growi.org/ja/admin-guide/upgrading/62x.html#growi-v6-2-x-%E3%81%B8%E3%81%AE%E3%82%A2%E3%83%83%E3%83%95%E3%82%9A%E3%82%AF%E3%82%99%E3%83%AC%E3%83%BC%E3%83%88%E3%82%99

- SAML によるログインが関係するか確定しませんが、一旦クローズします。
