### ISSUE TITLE
Bug: 既存グループの説明を更新しようとするとエラーになる

### ISSUE THREAD

**Issue by kometchtech** [weseek/growi#6515]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Amazon Linux release 2 (Karoo)|
|GROWI     |5.1.3|
|node.js   |16.17.0|
|npm       |8.15.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using growi-docker-compose|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Winodws11 21H2|
|browser   |Microsoft Edge 104.0.1293.70|

How to reproduce? (再現手順)
---------------------------

グループ管理から、既存グループの説明の内容を更新し、[更新]をクリックする。

What happens? (症状)
---------------------

[更新]をクリックすると”Error Something went wrong. Please try again.” と表示され、説明を更新できない。

What is the expected result? (期待される動作)
-------------------------------------------

グループの説明が更新される。

**Comment by kaoritokashiki** [comment]
@kometchtech
Isuueの起票ありがとうございます。

こちら再現することを確認できましたので、修正対応に入ります。
しばらくお待ちください。
