### ISSUE TITLE
コメントを追加してもブラウザを更新するまで追加されない

### ISSUE THREAD

**Issue by gaku-h** [weseek/growi#654]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows7|
|GROWI     |3.2.4-RC|
|node.js   |8.11.4|
|npm       |5.6.0|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7,10|
|browser   |IE11|

How to reproduce? (再現手順)
---------------------------

1.IE11で記事に対してコメントを書く
2.[Comment]ボタンをクリック

    ```bash
    
    ```

1. process 4
    ```bash
    
    ```

What happens? (症状)
---------------------
[Comment]ボタンをクリックしてコメントを追加しても
画面に反映されない。
画面の更新「F5」とかで更新すると反映される

```
Stack Trace
```

What is the expected result? (期待される動作)
-------------------------------------------

-リアルタイムに反映される 
- 

Note
----

- 
-

**Comment by yuki-takei** [comment]
@gaku-h 申し訳ないのですが IE11 は動作対象のブラウザに入っていないので…

すみません、close します。
