### ISSUE TITLE
drawioの数式組版が表示されない

### ISSUE THREAD

**Issue by tthogehoge** [weseek/growi#6545]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 10|
|GROWI     |5.1.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows 10|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. drawioの拡張→数式組版をチェック
1. drawioでtextを配置、```$$e=mc^2$$```等の数式を書く

What happens? (症状)
---------------------

- growi上で見ると数式にならず```$$e=mc^2$$```がそのまま表示される
- growi上でdrawioをクリックして拡大した表示でも数式にならない

What is the expected result? (期待される動作)
-------------------------------------------

- ```$$e=mc^2$$```が数式として表示されること

Note
----

**Comment by yuki-takei** [comment]
@tthogehoge demo.growi.org で試してみましたが、正常に動作しているように見えます。確認お願いします。

https://demo.growi.org/63189b3c5a4a0b3a50d595d4

![image](https://user-images.githubusercontent.com/1638767/188889452-fd7e8629-9c4f-4022-86a4-c8174b0bf260.png)

**Comment by tthogehoge** [comment]
https://demo.growi.org/63189b3c5a4a0b3a50d595d4
をリロードしてみると、2回に1回くらい表示されないようです。
プロキシを経由しているせいかもしれません。

**Comment by yuki-takei** [comment]
こちらでは再現しないので、再現確立があまり高くない(もしくは確かな再現条件が確立できない)と言える事象かと思います。
一旦「バグではない」という取り扱いで close しますので、もし再現条件を整えられそうな情報がありましたら reopen の依頼をお願いします。

**Comment by tthogehoge** [comment]
v7だと表示されなくなってないでしょうか？
https://demo.growi.org/63189b3c5a4a0b3a50d595d4

drawioのviewer.min.jsが2回呼ばれていて、2回目はinitMathの中身が実行されない(1回目でwindow.MathJaxが定義済みであるため初期化処理がスキップされる)のではないかと思います。
