### ISSUE TITLE
BugFix: Login Form rejects weak password

### ISSUE THREAD

**Issue by sztakeshi** [weseek/growi#662]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |3.2.5|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. ユーザー新規登録画面、もしくはユーザー設定 -> パスワード設定 からパスワードを入力する
1. 「test」や「a」など非常に弱いパスワードを入力する
1. 「*** has invalid characters」とエラーが表示されて、パスワード設定に失敗する

What is the expected result? (期待される動作)
-------------------------------------------

- パスワード強度を変更することは可能でしょうか？
login.js, password.jsなどで以下のように強度をコントロールしているように見えるのですが、
これを外部から再設定できるのでしょうか。
```
required().is(/^[\x20-\x7F]{6,}$/)
```

- もしくはLDAP連携のときはこれを無視できないでしょうか？

LDAP連携での運用を考えてて、Active Directoryでゆるいパスワードが設定されている状態です。
GrowiもLDAPで運用したいと考えてます。

**Comment by yuki-takei** [comment]
@sztakeshi ご意見ありがとうございます。

## パスワード強度の変更オプションについて
まずパスワード強度の変更は、後方互換を考えると管理画面から無効化する(とか、さらに強くするとか？)オプションを選べるようにする実装が必要になります。こちらは今後検討していきます。

## LDAP 連携時のパスワード強度について
ただ LDAP と連携するシチュエーションに限って言えば、必ずしも GROWI で ID/Pass でログインできるユーザーを作成する必要はないです。How to reproduce? で書いていただいた、

> ユーザー新規登録画面、もしくはユーザー設定 -> パスワード設定 からパスワードを入力する

の手順です。
LDAP 連携を設定後、GROWI にはユーザーアカウントが存在しない状態で LDAP の ID/Pass を入力してログインすることで、GROWI 側では自動的にパスワード未設定のユーザーアカウントが作成されます
。そのユーザーは、GROWI のパスワード強度設定とは切り離された存在として運用できます。

**Comment by yuki-takei** [comment]
@sztakeshi ご意見ありがとうございます。

## パスワード強度の変更オプションについて
まずパスワード強度の変更は、後方互換を考えると管理画面から無効化する(とか、さらに強くするとか？)オプションを選べるようにする実装が必要になります。こちらは今後検討していきます。

## LDAP 連携時のパスワード強度について
(先ほど投稿したコメントから書き換えました)

```
required().is(/^[\x20-\x7F]{6,}$/)
```

こちら、フォームの機能として働いてしまいますね…

- `src/server/form/invited.js`
- `src/server/form/login.js`
- `src/server/form/password.js`
- `src/server/form/register.js`

で同じ正規表現の利用を確認しましたが、login.js からは外した方がよさそうです。
次期バージョンで反映させますので今しばらくお待ちください。

**Comment by yuki-takei** [comment]
修正を master に取り込みました。
v3.2.6 リリースをお待ちください。

**Comment by sztakeshi** [comment]
対応ありがとうございました。
