### ISSUE TITLE
Bug: Can not create page correctly by API v3 (pages) with grantUserGroupId

### ISSUE THREAD

**Issue by tminai** [weseek/growi#6647]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Redhat 8|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1. Create new page with API
- POST: `https://{hostname}/_api/v3/pages`
- data: 
  ```
   body: "New page test"
   path: "/APITest"
   grant: 5
   grantUserGroupId: "ObjectId("6317e1aa4eb6221d29b16f8b")"
  ```

I can't understand what is "grantUserGroupId" by official doc page.
So, I use the id which found at db (usergroup collection, _id).
In addition, `access_token` user belong to specified group.

What happens? (症状)
---------------------

Page create is OK.
But the grant is something wrong.

I check the mongo db record.
`db.pages.find({path: "/APITest"})`

Result:
```
{ "_id" : ObjectId("6330e8f990084a2f13f836fc"), "parent" : ObjectId("6330e89690084a2f13f834e0"), "descendantCount" : 0, "isEmpty" : false, "status" : "published", "grant" : 5, "graentCount" : 0, "updatedAt" : ISODate("2022-09-25T23:49:13.998Z"), "path" : "/APITest", "creator" : ObjectId("5e9016f922193a00445950e2"), "lastUpdateUser" : ObjectId("5e9016f92219h" : true, "createdAt" : ISODate("2022-09-25T23:49:13.993Z"), "__v" : 0, "revision" : ObjectId("6330e8f990084a2f13f83700") } 
```

`"grant": 5` maybe OK.
However this record doesn't have "grantedGroup".

this is manually set granted group page's record.
this record has ` "grantedGroup" : ObjectId("6317e1aa4eb6221d29b16f8b")`
```
{ "_id" : ObjectId("6330e89690084a2f13f834dc"), "parent" : ObjectId("6330e89690084a2f13f834e0"), "descendantCount" : 0, "isEmpty" : false, "status" : "published", "grant" : 5, "grantedUsers" : [ ], "liker" : [ ], "seenUsers" : [ ObjectId("5e9016f922193a00445950e2") ], "commentCount" : 0, "updatedAt" : ISODate("2022-09-25T23:47:53.144Z"), "path" : "/APITest/1", "creator" : ObjectId("5e9016f922193a00445950e2"), "lastUpdateUser" : ObjectId("5e9016f922193a00445950e2"), "grantedGroup" : ObjectId("6317e1aa4eb6221d29b16f8b"), "expandContentWidth" : true, "createdAt" : ISODate("2022-09-25T23:47:34.530Z"), "__v" : 1, "revision" : ObjectId("6330e8a990084a2f13f83657") }
```
Rightly, this page work correctly.

**Comment by yuki-takei** [comment]
@tminai 
Please try to post with `grantUserGroupId` as a string.

Like the following: 
```
{
  ...
  "grant":5,
  "grantUserGroupId":"5b5092ff60200d00218d7d9a",
  ...
}
```

**Comment by yuki-takei** [comment]
v7.0.0 should not cause this problem while that version respects the grant of the parent page.
