### ISSUE TITLE
Bug: LDAPでログインしているユーザーが登録したブックマークがホーム画面に表示されない

### ISSUE THREAD

**Issue by kota65535** [weseek/growi#6693]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Monterey|
|browser   |Chrome 105.0.5195.125（Official Build） （x86_64）|

How to reproduce? (再現手順)
---------------------------

1. 任意のページをブックマークする
![image](https://user-images.githubusercontent.com/10975834/193386093-ea97d5c2-23ed-44ff-9796-c8323070174d.png)

1. ホーム画面を開く
![image](https://user-images.githubusercontent.com/10975834/193386135-55cdce16-fdb9-42d5-8d6b-0177ec2f8c6d.png)

What happens? (症状)
---------------------

- ブックマークが表示されていない

What is the expected result? (期待される動作)
-------------------------------------------

- ブックマークが表示される

こちらのIssueと関係がありそう
https://github.com/weseek/growi/issues/6503

**Comment by jam411** [comment]
@kota65535 
ログイン方法によらず、削除された username (User ID) と同じ username で再度ユーザ作成すると、
新規作成ユーザの /user/{username} ページが削除済みユーザのものとなっています。

お手数ですが事象が発生しているユーザについて、以下ご確認いただけませんでしょうか？

### 確認事項1
1. 事象が発生しているユーザでログインし、ホーム画面を開く
2. 以下写真のように、ホーム画面最下部に表示されるアイコンにマウスオーバーして、表示されるIDを確認する

![image](https://user-images.githubusercontent.com/68407388/195535846-af50c7db-4bb8-4237-b2fa-f56f184b6a54.png)

### 確認事項2
1. 表示されたIDが `@deleted_*` となっていた場合、どこかのタイミングで同じ username (User ID) のユーザが削除されていることが予想されます。削除した、もしくは意図せず削除されたタイミングに心当たりがある場合はそちらを教えていただけますでしょうか。

**Comment by kota65535** [comment]
@jam411 うおっ、確かに調べてみたところ `@deleted_*` と表示されていますね。
![image](https://user-images.githubusercontent.com/10975834/195648539-00012a61-e63a-4c23-a835-b7189c30ceed.png)

最近追加したユーザーは問題ないので、記憶が定かではありませんがLDAP移行時とかバージョン上げた時に削除したことになっているのかも。
DBを直接いじる方法でも構いませんので、修正方法を教えていただけると幸いです。

**Comment by jam411** [comment]
Duplicate of #6503

**Comment by misafortune** [comment]
同じ症状に遭遇しました。
LDAP連携前に作ったユーザーページのブックマーク機能が使えないという問題は
mongodbのuserコレクションで該当ユーザーのpasswordフィールドを削除する事で正常化しました。

LDAP連携後に作成されたユーザーはpasswordフィールドを持っていませんが
LDAP連携前に作成されたユーザーはpasswordフィールドを持っております。

これが原因でLDAP連携後では、passwordを持っているユーザーがブックマーク機能を使えなくなっているようです。

**Comment by jam411** [comment]
- [v6.2.0](https://github.com/weseek/growi/tree/v6.2.0) でユーザー新規登録時に同じ username のユーザーホームページがある場合はそれを一度削除して作り変えるように仕様変更されました。
また、ユーザー削除時にユーザーホームページも一緒に削除する設定ができるようになりました。
詳しくはアップグレードガイドをご覧ください。
https://docs.growi.org/ja/admin-guide/upgrading/62x.html#growi-v6-2-x-%E3%81%B8%E3%81%AE%E3%82%A2%E3%83%83%E3%83%95%E3%82%9A%E3%82%AF%E3%82%99%E3%83%AC%E3%83%BC%E3%83%88%E3%82%99

- LDAP によるログインもしくは password フィールドが関係するか確定しませんが一旦クローズします。
