### ISSUE TITLE
Bug: Draw.io の図を含んだページを編集している際にエディタのスクロール位置が暴れる

### ISSUE THREAD

**Issue by kota65535** [weseek/growi#6716]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Monterey|
|browser   |Chrome 105.0.5195.125（Official Build） （x86_64）|

How to reproduce? (再現手順)
---------------------------

1. Draw.io の図を挿入する
1. ページ末尾に画面をスクロールさせる
1. 文字を入力、または削除する

What happens? (症状)
---------------------

- 時々スクロール位置が最上部に移動することがある
- 元の位置に戻ってくることもあれば戻ってこないこともある
- 特に文字を削除した際に顕著

https://user-images.githubusercontent.com/10975834/194263166-6bf1124f-1156-40d9-9268-59c16adb4f99.mov

What is the expected result? (期待される動作)
-------------------------------------------

- 編集中の行のスクロール位置が変わらないこと

Note
----

- 文字を打つたびに View画面の Draw.io の図が再描画されてちらつくのも気になります。以前からこのような挙動でしたっけ？

**Comment by yuki-takei** [comment]
@kota65535 This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
