### ISSUE TITLE
コンフリクト解消モーダルから3つの選択肢のどれを選んでも「解消し保存する」ボタンを押すと「r.getCurrentOptionsToSave is not a function」エラーが出て保存できない。

### ISSUE THREAD

**Issue by moeohtani** [weseek/growi#6724]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |5.1.2|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11|
|browser   |Chrome 105.0.5195.127|

How to reproduce? (再現手順)
---------------------------

1. page bodyが `hoge` のページ `/A`を作成する
2. ユーザーAでログインし、/Aのページにアクセス
3. `hoge` を `fuga`に編集(更新はせず、編集中のままにしておく)
4. プライベートタブを開き、ユーザーBでログインする
5. /Aのページにアクセスし、編集モードで `hoge` を `piyo` に変更し、更新する
6. ユーザーAの画面下部にアラートが表示されるので、「衝突を解消」ボタンをクリック
7. 3つの選択肢のどれかを選択し、「解消し保存する」ボタンをクリック

  
What happens? (症状)
---------------------
- 「r.getCurrentOptionsToSave is not a function」のトーストエラーが出て保存できない。

![image (4)](https://user-images.githubusercontent.com/115530503/195037415-14b362f7-3593-4af2-bdfb-bc2ea3b4ea98.png)

What is the expected result? (期待される動作)
-------------------------------------------

- 選択した通りにコンフリクトの解消 & ページの保存ができる

**Comment by kaoritokashiki** [comment]
再現確認済み、調査/修正中 です。

**Comment by kaoritokashiki** [comment]
This bug has been fixed v 4.1.6. Please upgrade your GROWI version.
