### ISSUE TITLE
Bug: 3 times line break doesn't work for page break when next page is header.

### ISSUE THREAD

**Issue by sztakeshi** [weseek/growi#675]
Environment
------------

GROWI デモサイト

### Client

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|browser   |Chrome|

What happens? (症状)
---------------------

1. GROWI デモサイトの [このページ(/Sandbox/test-presentation)](https://demo.growi.org/Sandbox/test-presentation) をプレゼンテーションで確認する
1. 空白改行3回があるのに1ページ目が改ページされない

空白改行3回後が # のような見出しだとうまく改ページされないようです。
ちょうど見出しのところで改ページしたいので、修正していただけると助かります。

改ページのセパレーターをハイフン5個に変更すれば、ハイフン5個でちゃんと動作することを確認していますが、空白改行3回を使って、できるだけHTML表示をキープしたままプレゼンテーションを行いたいと思ってます。

**Comment by yuki-takei** [comment]
@sztakeshi ご報告ありがとうございます。再現確認しました。
近日中に修正してリリースしますので少々お待ちください。

**Comment by sztakeshi** [comment]
返信遅くなりました。いつもすばやい対応ありがとうございます・
