### ISSUE TITLE
Improvement: CDN を使わずに動作するモードを用意する

### ISSUE THREAD

**Issue by shuji-nakayama** [weseek/growi#676]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |RHEL7|
|GROWI     |3.2.6|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        ||
|browser   |x.y.z|

What is the expected result? (期待される動作)
-------------------------------------------

- 非インターネット環境でGrowiが動作できる

Note
----
中山と申します。
インターネットに出られない環境でGrowiを使用したいと思いリクエストさせていただきました。
セキュリティ要件が高く設けられている様な環境で、いかに情報共有するかは課題となっており
グループ単位でのアクセス制御機能などを持っているGrowiは非常に良い面を持っていますが
インターネット接続が前提となっているため、js、cssなどを取得できない環境では、
改修する、ネットワークで解決するなどが必要となります。

その点を標準機能（設定など）で解決できると非常に助かります。

**Comment by yuki-takei** [comment]
@shuji-nakayama Issue 作成ありがとうございます。

「CDN を使う・使わないをユーザーが選べるようにしたい」
一方で、
「CDN を使わない場合は docker image の容量をなるべく抑えたい」
という要求もあって(これ自己満足なだけという結論もあるかもしれないけど)、どういう手段を使って実現するか悩みどころです…

需要、結構多いんでしょうか。
(欲しいよ、という人は、この issue に thumb up とかリアクションいただけると嬉しいです)

**Comment by yuki-takei** [comment]
# 前提

- npm のライブラリをダウンロードしてくるフェーズは避けられないので、「少なくともインストール時だけはインターネットに出られるはず」という前提は合ってるはず？

# 案1

- クライアントを webpack で build する時に CDN を使うかどうかを選ぶ
- CDN でリンクしているものを build 時に同じ物をダウンロードしてきてローカル fs に保存する
- 起動時は `NO_CDN=true` とかの環境変数を入れる

## pros
- ライブラリの扱い方はそのままでいいはず

## cons
- 仕組みがなんとなくわかりにくい
    - CDN リストを json とか yml で用意しとかないといけない
    - 上記をダウンロードするスクリプトを書かないといけない
- highlight.js のテーマへの対応が難しい
    - CDN を使わない場合はテーマ変更不可っていう選択肢もあり？



# 案2
- 最初から npm install したライブラリを使えるようにして、インストール後も選択できるようにする

## pros
- 仕組み(考え方)が単純

## cons
- CDN 版と勝手が違うこともあるだろうから工数増

# 共通の悩み
- highlight.js のテーマへの対応が難しい
    - CDN を使わない場合はテーマ変更不可っていう選択肢もあり？
    - それか、インストール時にダウンロードするテーマリストを何らかの形でインプットするとか…
    - ユーザーがファイルを自分で入れればいいという説も…
        - カスタムCSSもあるし？

**Comment by inductor** [comment]
SRI対応は自分もやりたいです（一回やろうとしたけど上手くいかずそのままやってない）
Dockerfileの場合、WebpackのビルドだけMulti Stage Buildにして出力結果を吐き出すのが妥当かなとは思ってます

**Comment by yuki-takei** [comment]
integlity に関しては [この辺](https://github.com/weseek/growi/pull/742/files#diff-3c541b8af5072a96eb8b850d3e585736R8) に入れようかなとは思ったのですが、今そこそこ多くのリソースを jsdelivr の

https://www.jsdelivr.com/using-sri-with-dynamic-files

の combined files で参照しています。(HTTP req 数を減らしてパフォーマンスを上げようという意図から)

ここを妥協して 1 tag - 1 resource にするかどうか…
HTTP/2 標準になったらそれでいいじゃんみたいな話はあるかもしれません。

**Comment by yuki-takei** [comment]
実装完了。なんか思ったより早く終わったけどちゃんと動くか不安であります…
v3.3.0 リリースまで今しばらくお待ちください。(master ブランチでの動作報告歓迎)

**Comment by zsh2fish** [comment]
素早いご対応、ありがとうございます。
動作確認して、問題があれば報告致します。

**Comment by shuji-nakayama** [comment]
早速の対応ありがとうございます。
リリースされましたら弊社環境でも動作確認させていただきます。

**Comment by shisyamo** [comment]
お世話になっております、shisyamです。

うちの社内プロジェクトでも、メンバ間の情報共有の目的で、Glowを採用したいと検討させて頂いております、うちの社内プロジェクトもインターネットに繋がらない環境化でGlowを利用したいと思っております。

そこで、DockerCompose.ymlを利用し最新バージョンで、「NO_CDN」を指定しコンテナをビルドし動作させてみたのですが、ログイン画面で、ログインすると、「Page is not found　Thera are no pages under /styles/cdn/highlight-theme-github.css」と出力されCSSが見つけられないようでした。

ブラウザの開発ツールを表示させてみると、basis.jsやhighlight.jsやhighlight-addons.jsやmathjax.jsが見つけられないようです。

DockerCompose.ymlを利用して動作させる場合、何か環境設定的なものが別途必要になるのでしょうか？

ちなみに、「NO_CDN」をfalse（未指定時）に指定してDockerCompose.ymlでビルド・動作させると思ったとおりに動作してくれます。

**Comment by inductor** [comment]
@shisyamo

GlowではなくGrowiのことですかね・・・？

**Comment by shisyamo** [comment]
@inductor 

はい、そのとおりです、Glowではなく、Growiです、すいません。

**Comment by yuki-takei** [comment]
NO_CDN  を指定してコンテナをビルドした時に、なにかエラーが出ていないかを確認してください。docker を動かしているマシンのホストから外部への疎通ができていないと、ビルド時に highlight.js 等を取得・保存できていない可能性があります。

**Comment by shisyamo** [comment]
確かに、何かのDL時にワーニングが出ておりました、それを解消してみたのですが
状況は変わらずでした。

オフィシャルのnocdnサフィックス付きイメージでは問題ありませんでした、
このイメージを利用させて頂くことにします。

ご回答ありがとうございました。
