### ISSUE TITLE
Improvement: Express のログフォーマットを変更できるようにする

### ISSUE THREAD

**Issue by y-ogino** [weseek/growi#681]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7|
|GROWI     |3.2.4|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

How to reproduce? (再現手順)
---------------------------
1. docker-composeでgrowiを導入する
1. [このページ](https://github.com/weseek/growi-docker-compose/tree/master/examples/https-portal)の通りにHTTPS proxy serverを設定する

What happens? (症状)
---------------------
expressのログを見ると、proxy経由アクセスの接続元が全てproxyのIPアドレスになっている。
```
app_1 | [2018-11-05T02:22:54.824Z]  INFO: express/70 on 61b07bf039a3: ::ffff:172.18.0.5 <-- GET / HTTP/1.1 200 61263 - Vivaldi 2.1 Windows 10.0.0 55.763413 ms (req_id=2446b1fb-de6f-473b-9756-27df5adfa324)
app_1 | [2018-11-05T03:38:49.126Z]  INFO: express/70 on 61b07bf039a3: ::ffff:172.18.0.5 <-- GET /5b178130cfc054002bc0b47c HTTP/1.1 302 56 android-app://com.Slack Chrome Mobile 67.0 Android 7.0.0 7.021892 ms (req_id=e5c71e7d-0727-421e-a047-48e413d5f53a)
app_1 | [2018-11-05T03:38:49.298Z]  INFO: express/70 on 61b07bf039a3: ::ffff:172.18.0.5 <-- GET /login HTTP/1.1 200 15694 android-app://com.Slack Chrome Mobile 67.0 Android 7.0.0 17.487647 ms (req_id=72ec059b-5738-4159-917c-3d0069237b0c)
app_1 | [2018-11-05T03:39:00.105Z]  INFO: express/70 on 61b07bf039a3: ::ffff:172.18.0.5 <-- GET /login HTTP/1.1 200 15694 - Chrome Mobile 67.0 Android 7.0.0 4.772367 ms (req_id=46949a3e-519c-4ade-b234-ab4ffd1c4345)
```

What is the expected result? (期待される動作)
-------------------------------------------

- HTTPヘッダに`X-Forwarded-For`フィールドが含まれる場合は、それを接続元IPアドレスとしてログに表示する。
- proxyのIPアドレスを環境変数などで設定し、それ以外からのアクセスに対しては`X-Forwarded-For`を無視する。（偽装対策）

**Comment by yuki-takei** [comment]
@y-ogino Issue 立てていただいたのに反応が遅くてすみません。

まずログに関してですが、express-bunyan-logger を使っているので現状これがデフォルトです。
https://github.com/villadora/express-bunyan-logger/blob/master/index.js#L33

こちらですが、僕が HTTP ヘッダとミドルウェアの責務について知識が浅いので、一旦 Slack で議論を投げかけています。(もし興味をお持ちでしたらご参加いただければ)

対応方針が固まったらまたこちらに投稿するか、修正するかしますので今しばらくお待ちください。

**Comment by kainosuke** [comment]
@y-ogino slackで議論した上で現在の方針をお伝えいたします。

> What is the expected result? (期待される動作)
> -------------------------------------------
> 
> - HTTPヘッダに`X-Forwarded-For`フィールドが含まれる場合は、それを接続元IPアドレスとしてログに表示する。

上記の要望は、(1)「ログの出力内容を管理者が必要に応じて express-bunyan-logger の default フォーマットの代わりに任意のフォーマットを指定できる」ように改修を加えることで、 X-Forwarded-For header の内容も出力できるように対応したいと考えています。

> - proxyのIPアドレスを環境変数などで設定し、それ以外からのアクセスに対しては`X-Forwarded-For`を無視する。（偽装対策）

上記は、growi管理者が構築したネットワークにおいて、必ず特定のreverse proxyを経由するよう設計された場合は、(1)の機能を使ってログに X-Forwarded-For header の内容が出力されるように設定していただき、reverse proxyを特に経由しない設計であれば default のログ出力のまま利用していただくことで偽装を防ぐ形になると考えております。よって、proxyのIPアドレスを設定するような機能は実装しない予定です。

また、バグということで報告をいただいていますが、現時点では想定された仕様であると考えております。一方で @y-ogino さんの本質的な要求である、「proxyを挟んだ構成にした場合でも、 X-Forwarded-For header に記録された本来のクライアントIPを記録できてほしい」という件に関しては、改善要望として前述の通り引き続き対応をしたいと考えております。

ご意見ありましたら、その旨コメントください。

**Comment by y-ogino** [comment]
@yuki-takei @kainosuke 早速のご対応どうもありがとうございます。

> 必ず特定のreverse proxyを経由するよう設計された場合は、(1)の機能を使ってログに X-Forwarded-For header の内容が出力されるように設定していただき、reverse proxyを特に経由しない設計であれば default のログ出力のまま利用していただくことで偽装を防ぐ形になると考えております。よって、proxyのIPアドレスを設定するような機能は実装しない予定です。

[expressのtrust proxy設定](http://expressjs.com/en/guide/behind-proxies.html)を変更することで対応できるかと曖昧に想定していたので、その影響で「proxyのIPアドレスを設定する」という表現をしておりました。しかし改めて考えますとproxyの有無だけが本質的ですので、@kainosukeさんの仰る通りの対応が最適かと思います。

**Comment by yuki-takei** [comment]
では有識者会議の結果、このストーリーはタイトルを変えて実装待ちとします！

**Comment by yuki-takei** [comment]
#962 を起票し IssueHunt に公開しました。こちらは close します。
