### ISSUE TITLE
Bug: Inconsistent update of "grant" results in an inaccessible page

### ISSUE THREAD

**Issue by nandnor93** [weseek/growi#6822]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 20.04 LTS |
|GROWI     |5.1.6|
|node.js   |16.18.0|
|npm       |8.19.2|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Monterey 12.5 |
|browser   | Google Chrome 106.0.5249.119  |
|Python | 3.10.4 |
|Python `requests` | 2.28.1 |

How to reproduce? (再現手順)
---------------------------

1. Create a page manually as a public page
2. Access the page via the API `/_api/pages.update` with an incorrect (inconsistent) `grant` parameter
    ```Python
    import requests
    
    # Get page_id, revision_id, and body
    # At this time, the page's `grant` is `1`

    params={
        'access_token': "API_TOKEN",
        'page_id': page_id,
        'revision_id': revision_id,
        'body': body,
        'grant': 5    # <------ !!!!!!
    }
    res = requests.post(req_url, data=params)
    ```

What happens? (症状)
---------------------

- The response is `200` and contains the "updated" page (body is also updated in the response JSON).
```Python
{'page': {'_id': '635671ad62ae8e0bb68138bd',
  'parent': '6356629162ae8e0bb68119a6',
  'descendantCount': 0,
  'isEmpty': False,
  'status': 'published',
  'grant': 5,
  'grantedUsers': [],
  'liker': [],
  'seenUsers': ['6356629162ae8e0bb68119b6'],
  'commentCount': 0,
  'updatedAt': '2022-10-24T11:06:58.329Z',
  'path': '/test04',
  'creator': {'_id': '6356629162ae8e0bb68119b6',
   'isGravatarEnabled': False,
   'isEmailPublished': True,
   'lang': 'en_US',
   'status': 2,
   'admin': True,
   'name': 'admin',
   'username': 'admin',
   'email': 'admin@example.com',
   'createdAt': '2022-10-24T10:01:53.257Z',
   'imageUrlCached': '/images/icons/user.svg'},
  'lastUpdateUser': {'_id': '6356629162ae8e0bb68119b6',
   'isGravatarEnabled': False,
   'isEmailPublished': True,
   'lang': 'en_US',
   'status': 2,
   'admin': True,
   'name': 'admin',
   'username': 'admin',
   'email': 'admin@example.com',
   'createdAt': '2022-10-24T10:01:53.257Z',
   'imageUrlCached': '/images/icons/user.svg'},
  'grantedGroup': None,
  'expandContentWidth': False,
  'createdAt': '2022-10-24T11:06:21.877Z',
  '__v': 1,
  'revision': '635671d262ae8e0bb6813a92',
  'id': '635671ad62ae8e0bb68138bd'},
 'revision': {'_id': '635671d262ae8e0bb6813a92',
  'format': 'markdown',
  'pageId': '635671ad62ae8e0bb68138bd',
  'body': 'Hello!!!!\n\nHello!!!!\n\nHello!!!!\n\nHello!!!!\n\n',
  'author': {'imageUrlCached': '/images/icons/user.svg',
   'isGravatarEnabled': False,
   'isEmailPublished': True,
   'name': 'admin',
   'username': 'admin',
   'email': 'admin@example.com',
   'lang': 'en_US',
   'status': 2,
   'admin': True,
   'isInvitationEmailSended': False,
   '_id': '6356629162ae8e0bb68119b6',
   'createdAt': '2022-10-24T10:01:53.257Z'},
  'hasDiffToPrev': True,
  'createdAt': '2022-10-24T11:06:58.327Z',
  '__v': 0},
 'ok': True}
```

- When accessed from a browser, it results in a "Forbidden" page
    - ![image](https://user-images.githubusercontent.com/67882711/197513953-4481f4c6-e567-4993-9692-eb38bdf00c3b.png)

- When accessed from the API again, it results in the response `404`

```Python
req_url = '{}{}'.format(base_url, '/_api/v3/page')
queries = {
    'access_token': api_token,
    'path': page_path,
}
res = requests.get(req_url, params=queries)

res
# --->  <Response [404]>

res.content
# --->  b'{"errors":[{"message":"Page is not found"}]}'
```

What is the expected result? (期待される動作)
-------------------------------------------

- This "irregular" and "inconsistent" update operation should be rejected.

Notes
------

The full Jupyter result is attached:

[inaccessible_page.pdf](https://github.com/weseek/growi/files/9851236/inaccessible_page.pdf)

**Comment by yuki-takei** [comment]
The API endpoint `/_api/pages.update` has been removed in v7.0.0.
New updating API `PUT /_api/v3/page` denies requests with an incorrect (inconsistent) grant parameter.
