### ISSUE TITLE
Improvement: 新規ページで画像をアップロード後、作成ボタンを submit できるようにする

### ISSUE THREAD

**Issue by gaku-h** [weseek/growi#687]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows7|
|GROWI     |3.2.7|
|node.js   |8.11.4|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome,Edge|

How to reproduce? (再現手順)
---------------------------

1. 新規ページ作成
2. 画像をアップロード
　　※D&D
3. [作成]ボタン押下

What happens? (症状)
---------------------

1. Error: Page Exists

What is the expected result? (期待される動作)
-------------------------------------------

問題なくページが作成される

Note
----

Growi3.2.4で同事象だったため、3.2.7に上げたが変わらず。
#663 　で　「PageEditor.js」を確認したが問題なかった
デモサイトでも同事象を確認

**Comment by yuki-takei** [comment]
@gaku-h ご報告ありがとうございます。

GROWI と Crowi は、元々の仕様的に、未保存のページに対するファイル添付は「ページを一旦 Just me 状態で保存してからファイル添付まで完了」という動作を行います。

## #663 について
#663 の「Bug: An error occured by uploading attachment file when the page is not exists」に言及すると、こちらは

1. 新規ページ作成
1. 画像をアップロード
    - ※D&D

の手順を行うと、保存までは正常に終わるものの、アップロード後の振る舞いに余計なコードが入っていて、クライアント・サーバー側共にエラーが発生する、というバグでした。(現在修正済み)

## この Issue について
一応、「What is the expected result? (期待される動作)」に書いていただいた「問題なくページが作成される」は満たしており、ページ保存後にページ更新を行う事が回避手段になります。

強いて言えば、本来期待される動作は「問題なくページが**更新**できる」なのかもしれないです。

**Comment by gaku-h** [comment]
@yuki-takei  ご連絡ありがとうございます。

このような手順で画像を添付する仕様でしょうか。

1. 新規ページ作成
2. 文字のみ入力で[作成]ボタン押下
3. [編集]
4. 画像D&D
5. [更新]ボタン押下

**Comment by yuki-takei** [comment]
現状を書くと、

## うまくいくはず1

1. 新規ページ作成(not found ページ表示)
1. 文字のみ入力で[作成]ボタン押下(ページ遷移して通常ページ表示)
1. [編集]
1. 画像D&D
1. [更新]ボタン押下

## うまくいくはず2

1. 新規ページ作成(not found ページ表示)
1. 画像D&D(アプリ的には not found ページのまま、サーバー側はページが作成されている)
1. ブラウザのページリロード(通常ページ表示)
1. [編集]
1. [更新]ボタン押下

## うまくいかないはず(今のところ「仕様」)

1. 新規ページ作成(not found ページ表示)
1. 画像D&D(アプリ的には not found ページのまま、サーバー側はページが作成されている)
1. [更新]ボタン押下

です。

**Comment by gaku-h** [comment]
@yuki-takei 
有難う御座います。
仕様ということであれば問題ないです。
そのうち直るといいなーって気持ちでいます。

**Comment by yuki-takei** [comment]
@gaku-h 

This issue has fixed on v3.5.0. Please wait the next release.
直りました！v3.5.0 リリースをお待ちください。
