### ISSUE TITLE
Bug: #614が発生（新規ページで更新ボタンが表示されない）

### ISSUE THREAD

**Issue by ymatsush** [weseek/growi#690]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7|
|GROWI     |3.2.8-RC|
|node.js   |8.11.3|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Mac OS|
|browser   |Chrome|

What happens? (症状)
---------------------
#614 が発生しています。
HTMLをInspectorモードで確認すると、下の図のように高さが1ピクセルになっているようです。

![image](https://user-images.githubusercontent.com/33915966/48297538-7325b300-e4ee-11e8-920d-6f2c75c8cfb0.png)

100%で再現しますので、追加で必要な情報があれば添付いたします。

**Comment by yuki-takei** [comment]
@ymatsush ご報告ありがとうございます。

どうも発生条件について、「結構発生する」という声と「たまに見ることはあるけど、いざやってみると発生しない」という声と両方あって、僕は後者なので是非 100% の再現条件を知りたいです。

因みに #691 を出してくれている @utsushiiro は「結構発生する」と言っています。


## こちらでやったこと

1. ユーザーのホームに行く( `/user/yuki` 等)
1. ヘッダの「New」リンクをクリックし、新規ページ作成モーダルを開く
1. `Create page under below:」に適当な存在しないページ名を入れる
    ![image](https://user-images.githubusercontent.com/1638767/48315069-2f799900-e615-11e8-98a9-886b71a09bb3.png)
1. 「Create」ボタンをクリック

上記フローで、僕の環境ではご報告いただいているような症状は全く発生しないです。
(not found ページに正常に遷移し、正常にエディタが全画面で表示されているような状態)

ただ、開発中の development build ではたまに発生するのは見ています(再現条件は不明)

また、production 環境でも、not found ページを放置して PC がスリープ→復旧 をやったりするとたまに発生しています(こちらも100%の再現条件は不明)

**Comment by utsushiiro** [comment]
@yuki-takei 
#614のバグはevent handlerの処理順序の問題であり, 再現条件を記述するのは難しいと思われます.
しいて言えば, document の DOMContentLoaded event と window の load event の発生間隔が小さくなるような環境でしょうか.

私は docker-compose.dev.yml + npm run build:prod && npm run server:prod でローカルにGROWIを立ち上げ macOS + FireFox でアクセスし, ページを作成すると再現できました.

@ymatsush 
#691 にてバグの修正を行い, master branchにmergeしました.
お手数ですがymatsush様の環境においても修正されているか確認いただくことは可能でしょうか？

**Comment by ymatsush** [comment]
@utsushiiro 修正ありがとうございます。こちらの環境で適用後に事象が解消されていることを確認しました。

**Comment by utsushiiro** [comment]
@ymatsush 確認ありがとうございます.
