### ISSUE TITLE
Bug: LSX list is not displayed on Editor Preview

### ISSUE THREAD

**Issue by ryohi15** [weseek/growi#6959]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |5.1.8|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Win 10 Home|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------
1. Edit a page that has child page 
1. Input `$lsx()` in Editor 

What happens? (症状)
---------------------

-  Although there is child page, `$lsx() has no contents` is displayed in Preview.

What is the expected result? (期待される動作)
-------------------------------------------
- Displaying child page by using $lsx()

Note
----
- It is displayed correctly in View mode.

**Comment by kaoritokashiki** [comment]
This bug will be fixed on v6.0.0.
Please wait for the v6 release and update.


## Memo
- View mode では、LsxContext instance の `fromPagePath` が パス(例: `/parent`)で取得できている
- Editor mode では　LsxContext instance の `fromPagePath` が `id` になってしまっており, pagepath がnull になっている。

<img width="1345" alt="Screen Shot 2022-11-22 at 18 40 53" src="https://user-images.githubusercontent.com/59536731/203289325-806c5e0c-cfa0-4a14-a870-8dcc511ef441.png">

<img width="1508" alt="Screen Shot 2022-11-22 at 18 40 11" src="https://user-images.githubusercontent.com/59536731/203289314-aa0e5804-e194-464e-8a96-254fa3563812.png">

## 原因
context.pagePath がnull の場合、`currentPathname` を代入しているのが原因
context.pagePath を代入している場所を洗い出して修正する必要がある

https://github.com/weseek/growi/blob/v5.1.8/packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js#L42
