### ISSUE TITLE
Bug: コードブロック内で正規表現のPOSIX文字クラスが正常に表示されない

### ISSUE THREAD

**Issue by kota65535** [weseek/growi#6965]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Monterey|
|browser   |Chrome 107.0.5304.110（Official Build） （x86_64）|

How to reproduce? (再現手順)
---------------------------

1. 正規表現のPOSIX文字クラスをコードブロック内で入力
```
[[:space:]]
```

What happens? (症状)
---------------------

- View画面で以下のように表示される
```
<a href="/61d2fe8ae2ae2300518b62a9/:space:">:space:</a>
```

What is the expected result? (期待される動作)
-------------------------------------------

- 入力したままに表示されること

**Comment by yuki-takei** [comment]
@kota65535 
related to https://github.com/weseek/growi/issues/2557

レンダリング周りを根本から見直す必要があるため、大変申し訳ありませんが v5 系では修正を見送ります。
現在 master ブランチが v6 系になっているのですが、報告いただいた事象が発生しないことを確認しています。
年内を目処にリリースを予定しています。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@kota65535 This issue was fixed by [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0).
この問題は [v6.0.0](https://github.com/weseek/growi/releases/tag/v6.0.0) で修正されました。
