### ISSUE TITLE
Bug: 絵文字のオートコンプリートの場所がずれる

### ISSUE THREAD

**Issue by ktat** [weseek/growi#703]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Chrome 70.0.3538.102 |

How to reproduce? (再現手順)
---------------------------

1. 編集可能行を10行程度まで狭める
1. 以下のように入力する
   ```
   # start (空行でも可)
   
   
   (40行目まで空行を続ける)
   ```
1. その下で絵文字を書くために":"を入力する

What happens? (症状)
---------------------

- オートコンプリートが":"が表示されない(おそらく、下の方に表示されており、見切れている)。

What is the expected result? (期待される動作)
-------------------------------------------

- オートコンプリートが":"を入力した場所に出る

**Comment by ktat** [comment]
アクティビティ図は関係なかったようです。再現手順を更新しました。
例は極端ですが、おそらく、長めの文章を書いた場合に、絵文字のオートコンプリートが表示されなくなることがある、ということだと思われます。

**Comment by yuki-takei** [comment]
@ktat ご報告ありがとうございます。
こちらでも再現を確認しました。

ただ修正方法がわからなくて途方に暮れています。
影響するのは文章の長さと言うより「スクロール位置」で、

https://github.com/codemirror/CodeMirror/blob/master/addon/hint/show-hint.js#L220

ここで `cursorCoords` を呼んで返って来る位置情報オブジェクトの値が実際の cursor の位置とずれていくのが原因なのですが、どういう計算をしているのかは理解しきれず…深い沼のようです。

引き続き調査 or どなたかの調査報告待ちというステータスになります。

**Comment by yuki-takei** [comment]
CodeMirror からコードを移植して `cm.display.viewOffset` を hint 表示前に強制アップデートするように改修。
