### ISSUE TITLE
Improvement: プレゼンテーションモードでの Markdown レンダリング処理前後で、コードブロックを退避させる

### ISSUE THREAD

**Issue by ktat** [weseek/growi#704]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Chrome 70.0.3538.102 |

How to reproduce? (再現手順)
---------------------------

1. ````言語` の書式でコードを書く(中に # を含む)
   ```bash
   while true; do
     echo 1
   done
   # aaaa
   echo 1
   ```
1. プレゼンテーションモードで見る

What happens? (症状)
---------------------

- コードがMarkdownのまま表示される

What is the expected result? (期待される動作)
-------------------------------------------

- コードが整形された状態で表示される

**Comment by yuki-takei** [comment]
@ktat 改善提案ありがとうございます。

こちらは実装を考えるのは難しいですね…
そもそもプレゼンテーション以外の Markdown レンダリング時(markdown-it による処理)もコードブロック内を raw なまま扱うというのは考慮されておらず、GROWI が独自にコードブロックを退避させて Markdown 処理前後でコードブロック部分だけ退避させるという処理を行っています。

同様の退避処理を、プレゼンテーションモードでの Reveal + marked でもやらないといけないので…悩ましいですね。

**Comment by ktat** [comment]
@yuki-takei HackMDだと実現できているので、その当たりの実装は参考になるかもしれませんね。
HackMDだとシーケンス図なども問題ないのですが、Growiとはそのあたりの書式が異なるので、悩ましいところですね。

**Comment by yuki-takei** [comment]
ほぼ独自実装で markdown-it を使うようにしてますね…ううむ…

https://github.com/hackmdio/codimd/blob/2a8b56e14b482faa38e9661ad0aa8d208085c50e/public/js/reveal-markdown.js#L324

**Comment by yuki-takei** [comment]
fixed by #841
