### ISSUE TITLE
Bug:Cannot update Grant if public wiki only

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#7045]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |5.1.8|
| Service | GROWI.cloud |

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 |
|browser   | Google Chrome |

How to reproduce? (再現手順)
---------------------------

1. Create a GROWI as public.  
  GROWI を公開 wiki モードで作成
    - I created a GROWI with FREE plan on GROWI.cloud (SaaS).  
      (SaaS 版) GROWI.cloud サービスのフリープランで作成
2. Log in to the GROWI.  
  GROWI にログイン
3. Open an editor to create a new page.  
  新規ページ作成で編集画面を開く
4. Attach files to the page.  
  ファイルを添付
5. Save the page.  
  ページを作成 (保存)

What happens? (症状)
---------------------

- page grant becomes "only me".  
  公開 wiki モードなのに、ページの閲覧権限が「自分のみ」になってしまう
    - Can't change grant because GROWI is public only.  
      また、公開 wiki なので、ページの閲覧権限が変更できなくて詰む

What is the expected result? (期待される動作)
-------------------------------------------

- If GROWI is public, page grant must also be public only.
  GROWI が公開 wiki の場合には、ページの閲覧権限は常に公開 (誰でも閲覧可) になるべき

Note
----

- Slack GROWI work space [#help channel](https://wsgrowi.slack.com/archives/C4V5ZG4UC)
- Message(thread) https://wsgrowi.slack.com/archives/C4V5ZG4UC/p1670295865571119

**Comment by miya** [comment]
ページを新規作成してファイルアップロードする場合は、ファイルアップロード時に page document が生成されます。UI 的には明示的に保存していないので意図せず grant public でページが保存されないように grant restricted で保存されます。

こちらの PR (https://github.com/weseek/growi/pull/7481) で 環境変数: FORCE_WIKI_MODE=public が指定されている場合は grant public で保存できるように修正しました。
