### ISSUE TITLE
Improvement: aws, local モード時の画像の閲覧権限をログインユーザーに限る

### ISSUE THREAD

**Issue by ktat** [weseek/growi#705]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Chrome 70.0.3538.102 |

How to reproduce? (再現手順)
---------------------------

1. 編集画面で画像をアップロード
1. 自分のみ閲覧可能な状態で保存する
1. アップロードした画像のリンクを取得して、ブラウザをプライバシーモードにして、URLを表示する

What happens? (症状)
---------------------

- プライバシーモードでも画像が閲覧可能

What is the expected result? (期待される動作)
-------------------------------------------

- プライバシーモードでは画像が閲覧できない

**Comment by yuki-takei** [comment]
@ktat 改善提案ありがとうございます。

利用できるかどうか限定的ですが、一応回避策があります

## v3.2.9 以降

v3.2.9 から、 `FILE_UPLOAD=mongodb` を指定できるようになりました。こちらはデータ取得時は GROWI がプロキシする URL を提供しており、そちらのアクセスはユーザーがログインしているかどうかを見ます。

なので、もしこれから GROWI をクリーンインストールするような場合(つまり、これまでのアップロード済みファイルが閲覧できなくなっても構わない場合)とか、AWS S3 やローカルFSに拘らない場合はこちらの方法を選択することで期待される動作を満たします。

※因みに v3.2.9 は近日リリース予定です

## 以前のデータ
S3 に関して言えば、後方互換の問題をどうすればいいかというのが決着付いていなくて。
現在と同じように直アクセスで

`FILE_UPLOAD=aws` , `FILE_UPLOAD=local`
の他に、
`FILE_UPLOAD=aws-proxied` `FILE_UPLOAD=local-proxied` 
というのを用意すればいいのかもしれませんが…どうしましょうね。

**Comment by yuki-takei** [comment]
## その他の議論

あるページに添付されたファイルは、そのページの閲覧権限がある人のみに限られるべき…
という要望もそのうち出てくるような気がしていて、抜本的な対策が必要なのかも。

**Comment by yuki-takei** [comment]
以下の仕様で実装を進める事にしました。

* `FILE_UPLOAD` 環境変数は増やさない
* バージョンアップ後に新たにアップロードされたファイルは、全て GROWI バックエンドがプロキシする
    * URL 形式はファイルアップロード方式に依らず `/attachment/${attachmentId}` に統一
    * **参照/削除操作時に、関連付けられているページの閲覧権限を考慮する**
* 以前のデータ(Wiki ページ内に貼られたリンクは引き続き閲覧可能であるようにする
    * MongoDB GridFS の `/attachment/${pageId}/${filaHash}.${ext}` 形式のリンクはそのまま閲覧可能となるような route を新設する
    * AWS は S3 Bucket への直リンクなので問題ないはず
    * local FS も public dir 下への直リンクなので問題ないはず

**Comment by yuki-takei** [comment]
@ktat 実装されました。v3.4.0 のリリースをお待ちください

**Comment by ktat** [comment]
@yuki-takei ありがとうございます!リリース待ってます。
