### ISSUE TITLE
Improvement: プレゼンテーションモードでPlantUML, Blockdiag 等を処理できるようにする

### ISSUE THREAD

**Issue by ktat** [weseek/growi#707]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Chrome 70.0.3538.102 |

How to reproduce? (再現手順)
---------------------------

1. 編集画面でUMLを書く
1. 保存して、プレゼンテーションモードで表示する

What happens? (症状)
---------------------

- UML部分がMarkdownのまま表示される

What is the expected result? (期待される動作)
-------------------------------------------

- 画像として表示されて欲しい

**Comment by yuki-takei** [comment]
fixed by #841
