### ISSUE TITLE
S3に非公開でオブジェクトを格納したい

### ISSUE THREAD

**Issue by ma-chisuke** [weseek/growi#708]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |debian 8.7|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. FILE_UPLOADをAWS(s3)使用モードで構築
2. Growi管理画面からS3のバケット、アクセスキー等を設定する。 
3. ファイルをアップロードする。

What happens? (症状)
---------------------

- アップロードしたファイルが公開オブジェクト(public-read)としてS3に登録される。

What is the expected result? (期待される動作)
-------------------------------------------

- 現状仕様となるかとは思いますが意図しない公開となってしまっていたので、アップロードしたオブジェクトを非公開と出来る等、機密保持の為の仕組みが出来ると嬉しいです。

**Comment by yuki-takei** [comment]
@ma-chisuke 改善提案ありがとうございます。

こちらの要望、#705 とゴールとしては重複しているため、close した上で #705 の方で引き続き仕様を議論いたします。

**Comment by yuki-takei** [comment]
#705 は根本解決になっていない。詳細は以下を参照。

[Dev Wiki: /資料/内部仕様/S3-ACL設定](https://dev.growi.org/5d091f611fe336003eec5bfd)
