### ISSUE TITLE
Bug: PlantUMLが2つ書けない場合がある

### ISSUE THREAD

**Issue by ktat** [weseek/growi#709]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Chrome 70.0.3538.102 |

How to reproduce? (再現手順)
---------------------------

1. 下記を記述する
   ```
   @startuml
   
   actor Promoter
   actor Entrant
   
   Promoter --> (Create Event)
   Promoter -> (Attend Event)
   
   Entrant --> (Find Event)
   (Attend Event) <- Entrant
   
   @enduml
   ```
1. 同様のものをもう一度記述する

What happens? (症状)
---------------------

- 下記が表示され、両方とも表示されない
  ```
  [From string(line 9)]
  ... (skipping 5 lines) ...
  Promoter -> (Attend Event)
  
  Entrant --> (Find Event)
  (Attend Event) (Create Event)
  Syntax Error?
  ```

What is the expected result? (期待される動作)
-------------------------------------------

- 両方とも正しく表示される。

**Comment by ktat** [comment]
こちらでもダメでした。下記に関しては、左向き矢印を右向きに変えれば、大丈夫です。
```
@startuml
B -> A
B <- A
@enduml
@startuml
B -> A
B <- A
@enduml
```

**Comment by yuki-takei** [comment]
#278 と同じような症状のようですね…
正直こちらはまだ時間をかけられていなくて、現在も原因不明のままです。

**Comment by tak-ngs** [comment]
#278 でも似た言及がありますが`<` `>`の間がhtmlタグと認識され、
XSS対策のタグに引っかかって除外されてるているような気がします。


`管理ページ > マークダウン設定 > XSS対策設定`でXSS抑制をOFFにするか、
カスタムホワイトリストに`-`を追加すればとりあえず回避できました。

**Comment by yuki-takei** [comment]
@tak-ngs おお、原因特定していただけるとは。ありがとうございます。

Recommended Setting にハイフンを入れて次期バージョンリリースすることにします！
