### ISSUE TITLE
Improvement: ページを削除できるユーザーを限定したい

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#714]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Chrome 70.0.3538.110|

What is the expected result? (期待される動作)
-------------------------------------------

- ページの削除を管理者およびページを作成したユーザーのみが行える

Note
----

現状、ページの削除は登録ユーザーであれば任意に行うことができると思いますが、これを管理者およびページを作成したユーザーのみに限定するオプションがあるとよいと感じたため、リクエストさせていただきました。ご検討よろしくお願いいたします。

**Comment by yuki-takei** [comment]
@k84rc ご提案ありがとうございます。

確かに、Wiki への参加が自由に行える状態で誰でも完全削除できるのは権限として強すぎるかもしれませんね。

* ページの完全削除を行えるユーザーを以下から選択
  * 誰でも可能 (default)
  * 管理者とページの作者のみ可能
  * 管理者のみ可能

というオプションを管理画面に付けようかなと思います。
こちらで要求満たせそうでしょうか？

**Comment by yuki-takei** [comment]
因みに実装時期ですが、現在 Access Control List 周りの大幅なリファクタを imprv/refactor-acl ブランチで行っている最中なので、こちらの着手はそれが終わってからになると思います。すみません。

**Comment by yuki-takei** [comment]
fixed by #1020, #1075
