### ISSUE TITLE
Bug: /trash配下のページを編集すると削除出来なくなる

### ISSUE THREAD

**Issue by ma-chisuke** [weseek/growi#719]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |debian 8.7|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |mac|
|browser   |chrome|

How to reproduce? (再現手順)
---------------------------

1. ページを削除する(not 完全削除)

2. /trashの中間パスのページを「作成」タブから編集して(編集出来てしまう)保存。
(/trash/foo/hoge　だとしたら/trash/foo)

What happens? (症状)
---------------------
編集したページが削除できなくなってしまう
 
What is the expected result? (期待される動作)
-------------------------------------------
- /trash配下で編集したページも削除出来る。
or
- /trashの中間パスは編集できないようにする。

困っている事象としては削除出来ないという点ですが、本質的には/trash配下は編集出来ない状態が望ましいかと思量致します。

**Comment by yuki-takei** [comment]
@ma-chisuke ご報告ありがとうございます。

> /trashの中間パスは編集できないようにする

こちらがよさそうですね。
修正して v3.2.10 としてリリースします。今しばらくお待ちください。
