### ISSUE TITLE
Bug: PortalPageを作成できない

### ISSUE THREAD

**Issue by you-at4** [weseek/growi#721]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 1804|
|GROWI     |3.2.8|
|node.js   |8.12.0|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10 1803|
|browser   |chrome 70|

How to reproduce? (再現手順)
---------------------------

1. 挙動設定でCrowi Classic Behaviorを選択する
2. 適当なページ(/Test/Test1)を作成
3. 親ページ(/Test/)を表示しCreatePortalボタンをクリックする

What happens? (症状)
---------------------
 Error occured  HackmdEditor component has not initialized と表示されポータル化できない

What is the expected result? (期待される動作)
-------------------------------------------
ポータルページを作成できる

Hackmdは必須なのでしょうか？

**Comment by yuki-takei** [comment]
@you-at4 ご報告ありがとうございます。

Hackmd はオプショナルなので、この挙動はバグですね。
修正して v3.2.10 としてリリースします。今しばらくお待ちください。
