### ISSUE TITLE
Bug: $lsx()の引数で2バイト文字を含む相対パスが機能していない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#7234]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04.5 LTS|
|GROWI     |6.0.2|
|node.js   |14.21.1|
|npm       |6.14.17|
|yarn      |1.22.19|
|Using Docker| no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 21H2|
|browser   |Google Chrome 108.0.5359.125|

How to reproduce? (再現手順)
---------------------------

1. 漢字で階層構造のある記事を作成する
  - /甲/甲/甲甲
  - /甲/乙/甲乙
  - /甲/丙/甲丙
 
2. /甲で下記の様に$lsx()を呼び出す
  ```
  $lsx(./甲)
  $lsx(./乙)
  $lsx(./丙)
  ```

What happens? (症状)
---------------------

```
$lsx(%E7%94%B2/%E7%94%B2) has no contents
$lsx(%E7%94%B2/%E4%B9%99) has no contents
$lsx(%E7%94%B2/%E4%B8%99) has no contents
```
のように表示される

What is the expected result? (期待される動作)
-------------------------------------------

  - 甲甲
  - 甲乙
  - 甲丙

のように下位のページがリスト表示される

Note
----

下記の様な英字だけのリンクは問題ありませんでした。

- /foo/foo/foofoo
- /foo/bar/foobar
- /foo/baz/foobaz

**Comment by yuki-takei** [comment]
@hanapage ご連絡ありがとうございます。再現確認しました。修正します。
