### ISSUE TITLE
Bug: ISO8601形式で日付を入力するとページ内容が表示されない

### ISSUE THREAD

**Issue by mori-hiro** [weseek/growi#7262]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.1 LTS|
|GROWI     |6.0.2|
|node.js   |16.17.1|
|npm       |8.15.0|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item    | version                      |
| ------- | ---------------------------- |
| OS      | Windows10                    |
| browser | Google Chrome 108.0.5359.125 |

How to reproduce? (再現手順)
---------------------------

1. ページ編集にて```2023-01-01T00:00:00.000Z```を内容として表記する
1. ページViewにてページアクセス

What happens? (症状)
---------------------

- 本文が表示されない

What is the expected result? (期待される動作)
-------------------------------------------

- 内容が表示される

Note
----

- v5系では表示されるため、一旦v5.1.8に切戻して利用
- 表示時にブラウザのコンソールに出力
```
[react-markdown]Warning: please pass a string as children(not : Sat Jan 01 2022 00:00:00 GMT+0900（日本標準時）)
```

**Comment by yuki-takei** [comment]
@mori-hiro 情報ありがとうございます。

再現を確認し、https://github.com/weseek/growi/pull/7249 での改修が完了しています。
v6.0.3 リリースをお待ちください。
