### ISSUE TITLE
Bug: 丸括弧入りページをlsx指定するとページツリー表示されない

### ISSUE THREAD

**Issue by mori-hiro** [weseek/growi#7263]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.1 LTS|
|GROWI     |6.0.2|
|node.js   |16.17.1|
|npm       |8.15.0|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item    | version                      |
| ------- | ---------------------------- |
| OS      | Windows10                    |
| browser | Google Chrome 108.0.5359.125 |

How to reproduce? (再現手順)
---------------------------

1. 既存で丸括弧入りの```Index(TEST)```ページが存在
1. 別ページで```$lsx(/Index(TEST))``` でページツリー表示定義

What happens? (症状)
---------------------

- ページツリー表示されない

What is the expected result? (期待される動作)
-------------------------------------------

- ページツリー表示される

Note
----

- v5系ではページツリー表示されるため、一旦v5.1.8に切戻して利用

**Comment by yuki-takei** [comment]
@mori-hiro 情報ありがとうございます。再現を確認しました。
修正が結構大変なので、優先度は落ちると思います。

## ワークアラウンド

filter option 等で一応代用可能

`$lsx(/, filter=Index\(Test)`

**Comment by yuki-takei** [comment]
ワークアラウンドでの回避を解決策としてクローズします
