### ISSUE TITLE
Request: Support MongoDB Server 5.x/6.x

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#7273]
## Informations
**Is your feature request related to a problem? Please describe.**
* MongoDB 4.4 will reach its EOL on February 2024. (1 year left)
* Some providers already dropped support for 4.x (e.g. https://github.com/bitnami/containers/commit/92e06b062e934e8cb9d00b993af06f96e0299188)

**Describe the solution you'd like**
It's better to add support for MongoDB 5.x/6.x to GROWI.

**Comment by yuki-takei** [comment]
@shield-9 Now GROWI v6.1 support 5.x/6.x
