### ISSUE TITLE
Docker for windows にてElasticSearchの起動に失敗する

### ISSUE THREAD

**Issue by zerowindo9244o34** [weseek/growi#729]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows Server 2016|
|GROWI     |3.2.9-RC|
|node.js   |8.14.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. Azureに構築したWindowsServer2016にDocker for Windowsをインストールし、
　docker-compse up　を実行

What happens? (症状)
---------------------
**docker-compose up**実行時、コンソールに下記エラーが出力されます。

**elasticsearch_1  | Error: Could not create the Java Virtual Machine.
elasticsearch_1  | Error: A fatal exception has occurred. Program will exit.**

以下、コンソール出力内容です。
PS C:\Docker\growi> docker-compose up
Starting growi_mongo_1         ... done
Starting growi_elasticsearch_1 ... done
Starting growi_app_1           ... done
Attaching to growi_elasticsearch_1, growi_mongo_1, growi_app_1
mongo_1          | 2018-12-06T05:10:47.481+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=d1715c00ba42
mongo_1          | 2018-12-06T05:10:47.482+0000 I CONTROL  [initandlisten] db version v3.4.18
mongo_1          | 2018-12-06T05:10:47.482+0000 I CONTROL  [initandlisten] git version: 4410706bef6463369ea2f42399e9843903b31923
mongo_1          | 2018-12-06T05:10:47.483+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_1          | 2018-12-06T05:10:47.483+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1          | 2018-12-06T05:10:47.483+0000 I CONTROL  [initandlisten] modules: none
mongo_1          | 2018-12-06T05:10:47.484+0000 I CONTROL  [initandlisten] build environment:
mongo_1          | 2018-12-06T05:10:47.484+0000 I CONTROL  [initandlisten]     distmod: debian81
app_1            | 2018/12/06 05:10:50 Waiting for: tcp://mongo:27017
mongo_1          | 2018-12-06T05:10:47.485+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1          | 2018-12-06T05:10:47.485+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1          | 2018-12-06T05:10:47.486+0000 I CONTROL  [initandlisten] options: {}
mongo_1          | 2018-12-06T05:10:47.507+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1          | 2018-12-06T05:10:47.508+0000 I STORAGE  [initandlisten]
mongo_1          | 2018-12-06T05:10:47.509+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1          | 2018-12-06T05:10:47.510+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1          | 2018-12-06T05:10:47.516+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1452M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compresso
=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1          | 2018-12-06T05:10:48.606+0000 I STORAGE  [initandlisten] WiredTiger message [1544073048:606504][1:0x7f53771fdd40], txn-recover: Main recovery loop: starting at 34/4480
mongo_1          | 2018-12-06T05:10:48.991+0000 I STORAGE  [initandlisten] WiredTiger message [1544073048:991444][1:0x7f53771fdd40], txn-recover: Recovering log 34 through 35
mongo_1          | 2018-12-06T05:10:49.299+0000 I STORAGE  [initandlisten] WiredTiger message [1544073049:299099][1:0x7f53771fdd40], txn-recover: Recovering log 35 through 35
mongo_1          | 2018-12-06T05:10:50.256+0000 I CONTROL  [initandlisten]
mongo_1          | 2018-12-06T05:10:50.256+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1          | 2018-12-06T05:10:50.257+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1          | 2018-12-06T05:10:50.257+0000 I CONTROL  [initandlisten]
mongo_1          | 2018-12-06T05:10:50.301+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1          | 2018-12-06T05:10:50.302+0000 I NETWORK  [thread1] waiting for connections on port 27017
mongo_1          | 2018-12-06T05:10:50.600+0000 I NETWORK  [thread1] connection accepted from 172.18.0.4:59098 #1 (1 connection now open)
app_1            | 2018/12/06 05:10:50 Waiting for: tcp://elasticsearch:9200
app_1            | 2018/12/06 05:10:50 Problem with dial: dial tcp 172.18.0.3:9200: connect: connection refused. Sleeping 1s
app_1            | 2018/12/06 05:10:50 Connected to tcp://mongo:27017
app_1            | 2018/12/06 05:10:51 Problem with dial: dial tcp 172.18.0.3:9200: connect: connection refused. Sleeping 1s
app_1            | 2018/12/06 05:10:52 Problem with dial: dial tcp 172.18.0.3:9200: connect: connection refused. Sleeping 1s
**'lasticsearch_1  | Unrecognized VM option 'UseConcMarkSweepGC
elasticsearch_1  | Did you mean '(+/-)UseConcMarkSweepGC'?
elasticsearch_1  | Error: Could not create the Java Virtual Machine.
elasticsearch_1  | Error: A fatal exception has occurred. Program will exit.**
app_1            | 2018/12/06 05:10:53 Problem with dial: dial tcp 172.18.0.3:9200: connect: connection refused. Sleeping 1s
app_1            | 2018/12/06 05:10:54 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
growi_elasticsearch_1 exited with code 1
app_1            | 2018/12/06 05:10:55 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:10:56 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:10:57 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:10:58 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:10:59 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:11:00 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:11:01 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
app_1            | 2018/12/06 05:11:02 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
Gracefully stopping... (press Ctrl+C again to force)
Stopping growi_app_1           ... done
Stopping growi_mongo_1         ... done

Note
----
・docker-compse.ymlから、elasticsearch関連を削除することで、正常に起動することを確認しております。
・elasticsearch単体でdocker pullし、動作することをを確認しております。

**Comment by yuki-takei** [comment]
@zerowindo9244o34 うーん… Docker for Windows 特有なんですかね…
growi-docker-compose を使っているならホストOSが違っても同じ挙動になるはずですが。あいにくこちらで Docker for Windows 環境で開発やテストを行っている人間がいないため、再現確認ができないです。

因みにメモリ不足とかの線は薄いでしょうか？

**Comment by utsushiiro** [comment]
ElasticSearchの起動時に付与しているJVM Optionの指定の部分でコケてるようですが, [この部分](https://github.com/weseek/growi-docker-compose/blob/master/esconfig/jvm.options#L36)を変更したりしてはいないでしょうか？

**Comment by zerowindo9244o34** [comment]
回答が遅くなり、申し訳ありません。

@yuki-takei 
Dockerに割り当てるメモリ量や、AzureのVMのメモリ量を増やしてみましたが、
状況に変化はありませんでした。

@utsushiiro 
jvm.optionsの変更は行っておりません。
ただ、こちらのアドバイスをもとに確認したところ、
jvm.optionsの改行コードがCRLFになっておりました
gitインストール時にデフォルトでインストールされていたようで、
改行コードの自動変換が有効になっていたようです。
クローンし直すことで無事起動できました。
大変お騒がせして申し訳ありません。
