### ISSUE TITLE
Bug: ページツリーのページ数が閲覧不可のページも含んでいる

### ISSUE THREAD

**Issue by aviscaerulea** [weseek/growi#7297]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux2|
|GROWI     |5.0.4|
|node.js   |16.15.0|
|npm       |8.5.5|
|yarn      |1.22.18|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 Pro 22H2|
|browser   |Firefox 109.0|

How to reproduce? (再現手順)
---------------------------

1. 同じ階層に複数のノートを作成する
1. 作成したノートのいくつかを「自分のみ」にする
1. 他のユーザで上記ノートのある階層をページツリーで見る

What happens? (症状)
---------------------

以下のように見えているページ（ 1 件）に対して、赤枠のページ数が一致しない。
つまり閲覧中のユーザに見えない権限のページが存在することが分かる。

![20230126_113455](https://user-images.githubusercontent.com/1040522/214746229-78b494d0-4d74-4e12-802e-ebb65a1cafe6.png)

What is the expected result? (期待される動作)
-------------------------------------------

ツリーに表示されている内容と同じく権限が考慮されたページの数が表示されること。

**Comment by yuki-takei** [comment]
内部仕様として、子ページのページ数の合計を親ページのデータに永続化させています。
(閲覧者によって下層のページを全てカウントし直すのが現実的ではないため)
