### ISSUE TITLE
Bug: 動画が再生されない（#3823 と類似）

### ISSUE THREAD

**Issue by dashwood8691** [weseek/growi#7348]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.6 LTS|
|GROWI     |5.1.9|
|node.js   |16.19.0|
|npm       |8.19.3|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version | 問題発生有無 |
| ---      | --- | --- |
|OS        |Windows 10 22H2| - |
|browser   |Chrome 109.0.5414.120 (Official Build) (64-bit)| 発生 |
| |Microsoft Edge 109.0.1518.78 (Official build) (64-bit)|発生|
| |Firefox 109.0.1 (64-bit)|発生なし|

How to reproduce? (再現手順)
---------------------------

1. ページを作成して動画(mp4)をドラッグアンドドロップしてページへ添付する。`[__filename__](/attachment/__id__)` のリンクが挿入される。
1. ページを保存する。
1. Chrome若しくはMicrosoft Edgeでページ内の動画リンクをクリックして `/attachment/__id__` のページに移動する。
1. Firefoxでアクセスすると動画が再生される。

What happens? (症状)
---------------------

1. "/attachment/<id>" のページに移動しても動画を読み込まない。画像のように黒い背景に小さいプレイヤーは表示されるが、待っていてもこのまま進まない。

   <img width="273" alt="image" src="https://user-images.githubusercontent.com/30547/216769820-8d95ce8a-8b86-462c-aa86-d1f3f33fa0bb.png">
   
1. DevToolsのNetworkタブではType: documentとなっていてTime: Pendingのまま進まない。

   <img width="887" alt="image" src="https://user-images.githubusercontent.com/30547/216770431-b6d32c56-e269-4867-8bff-a0a6e4724572.png">
   
1. リクエストを選択すると "CAUTION: request is not finished yet!" と表示されている。

   <img width="568" alt="image" src="https://user-images.githubusercontent.com/30547/216770540-aa17ed94-98b1-4d3f-99de-d140eabf0b25.png">

What is the expected result? (期待される動作)
-------------------------------------------

- すぐに動画が再生される。

Note
----

- ファイルアップロード設定は本番環境ではLocal、テスト環境はMongoDB(GridFS)です。 
- 本番環境のGROWI 5.1.3にて事象確認後、テスト環境を5.1.9へアップデートして再現を確認しました。
- 通常はNGINXのproxyでSSL化しているので一旦IP:3000でアクセスを許可して確認しましたが、事象改善しませんでした。
- [GrowiでAudio/Videoを埋め込む](https://qiita.com/6gsn/items/192c033809afa4f84a14) の方法を使うと同じ動画を記事に埋め込んで再生できたのでチームメンバーにはこの方法をアナウンスしますが、単純に添付するだけでも再生できるようになると助かります。

**Comment by yuki-takei** [comment]
@dashwood8691 ご報告ありがとうございます。
別の方から PR をいただいたので、master 向けに取り込みました。来月リリースの v6.1.0 で反映される予定です。
