### ISSUE TITLE
Bug:未ログイン状態でページURLにアクセスしてログインすると指定ページではなくホームが表示される

### ISSUE THREAD

**Issue by nakashimaki** [weseek/growi#7351]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 22.04 (WSL2) |
|GROWI     |6.0.5|
|node.js   |16.19.0|
|npm       |8.19.3|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 22H2 |
|browser   | Microsoft Edge	109.0.1518.70 |

How to reproduce? (再現手順)
---------------------------

1. GROWIからログアウトしておく
1. ページURLをブラウザーのアドレスバーに入力してアクセスする
    * 例: `http://localhost:3000/63df9b863feae67200d4342e` （/Sandbox/Bootstrap4）
1. 開いたページからGROWIへログインする

What happens? (症状)
---------------------

- GROWIのホームページ（/）が表示される

What is the expected result? (期待される動作)
-------------------------------------------

- ページURLが示すページが表示される

Note
----

- v5.1.9では期待される動作となっています

**Comment by nakashimaki** [comment]
@miya ご対応いただきありがとうございます！
私の実環境ではSAML認証によるログインを使用しておりまして、ご対応の恩恵を受けられるのは少し先になりそうです。
SAML認証のXHR化対応についても今後ご検討いただければ幸いです🙇

**Comment by miya** [comment]
@nakashimaki 
issue の起票ありがとうございます！
先ほどの PR  では nakashimaki さんがおっしゃっている通り外部アカウントでの対応ができないものでしたので一旦クローズしました。全ての認証に対応するためにログイン周りの実装方法を再考中です。次回か次々回のリリースには含めたいと思っているので、それまでお待ちください 🙏

**Comment by nakashimaki** [comment]
ご対応いただきありがとうございました！  
アップグレードを導入する際の課題になっていたためとても助かりました🙏
