### ISSUE TITLE
Improvement: 新規ページ作成時に親ページの公開設定を引き継いでほしい

### ISSUE THREAD

**Issue by you-at4** [weseek/growi#741]
How to reproduce? (再現手順)
---------------------------
1. 特定の公開設定を設定したページを作成
2. 1.で作成したページの配下に新規ページを作成

What is the expected result? (期待される動作)
-------------------------------------------
デフォルトで親ページと同じ公開設定が選択されている

Note
----
新規ページを作成するたびに公開設定を変更するのは設定忘れの恐れがあるため、
公開設定で特定グループや自分のみに設定したページの配下は親と同じ設定になっているのが望ましいです。
アプリの設定でデフォルトで選択される公開設定を変更できればいいのかもしれません。

**Comment by yuki-takei** [comment]
@you-at4 ご提案ありがとうございます。
実は結構前に作られた Issue なんですが #423 に同じような話があって、その中での僕のコメントがご提案いただいた内容とほぼ同じ案になっています。

その辺りの改修を行っていくために次のバージョンの v3.3.0 のリリースを準備しているところですので、それ以降で検討・実装を行う予定です。(具体的にいつ着手というのはまだ未定ですすみません)

なお、この Issue は重複に当たるので close しますが、#423 からリンクを張るようにしておきます。

**Comment by you-at4** [comment]
すでにあった要望でしたか。すみません。
ユーザーから現状だとリスト表示から辿れてしまうと上記要望があったので
当面はリスト表示全体を非表示化して対応しようと思います。

**Comment by yuki-takei** [comment]
- 親ページの公開設定を GrantSelector の初期値とする
- https://github.com/weseek/growi/issues/924#issuecomment-486991149 も合わせて改修できるとよい
