### ISSUE TITLE
Bug: Error occurred in using $lsx() with except option

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#7434]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |6.0.7|

GROWI on GROWI.cloud

### Client

| item     | version |
| ---      | --- |
|OS        |windows 11|
|browser   |110.0.5481.105（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. Edit any page and enter the lsx code below.
    -  `$lsx(/Projects/GROWI/GROWI.cloud/マニュアル類,except=メンテ手順/\,depth=1)`
    - (It includes `except` option.)
1. Save the page.

What happens? (症状)
---------------------

- 500 Internal server error occurs
- Screenshot
![image](https://user-images.githubusercontent.com/68407388/222026493-307360d9-12e5-4220-a84b-555fe5afe3f4.png)

What is the expected result? (期待される動作)
-------------------------------------------

- The except option can be used normally

**Comment by miya** [comment]
Dupliicate of #7263

**Comment by jam411** [comment]
400 エラーが返るように修正されました。正規表現に合うように except に渡す値の書き方を修正してください。

Fixed to return a 400 status. 
Please modify the value passed to except to match the regular expression.
