### ISSUE TITLE
Bug:権限のないページを開けると、すべてのページが見れなくなる

### ISSUE THREAD

**Issue by misafortune** [weseek/growi#7445]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu20|
|GROWI     |6.0.5|
|node.js   |16.19.0|
|npm       |8.19.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |windows 10/11|
|browser   |Chrome 110.0.5481.178|

How to reproduce? (再現手順)
---------------------------

1. 特定グループにしか閲覧出来ないページを生成する。
1. カスタムサイドバーに上記ページのリンクを作る
1. 権限のないメンバーが上記リンクを踏む

What happens? (症状)
---------------------

![847e3ba9bfd03c10daadd8e13228288e](https://user-images.githubusercontent.com/33389270/222181190-4b19df5b-2ffe-42ad-8921-738b83bf8cb8.png)
画像の通り、Forbiddenになる。

ここまでは想定通りなので問題ないのですが

この状態から、他のページを閲覧しようとすると
すべての公開ページもForbiddenのままになります。
権限のあるページでF5を押して更新すれば治ります。

What is the expected result? (期待される動作)
-------------------------------------------
権限のないページのみForbiddenになり
権限のあるページは普通に見れる

Note
----
P.S.
グループ権限作成でかなり苦戦しております。別途投稿します。

**Comment by miya** [comment]
GROWI のご利用、issue の起票ありがとうございます。

v6.0.5 では確かにこのバグは再現いたしました。最新 version (v6.0.7) では修正されているので、お手数ですがこちらにアップデートしていただけると問題は解消されると思います。

**Comment by misafortune** [comment]
そうだったんですね、ありがとうございます！
