### ISSUE TITLE
Bug:段落中に2つ以上の$を含むと表示結果が崩れる

### ISSUE THREAD

**Issue by nakashimaki** [weseek/growi#7449]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04 (WSL2)|
|GROWI     |6.0.7|
|node.js   |16.19.1|
|npm       |8.19.3|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 22H2|
|browser   |Microsoft Edge 110.0.1587.57|

How to reproduce? (再現手順)
---------------------------

1. ページを作成する
1. 以下のテキストを入力する
    ```md
    chocolates are $3 and cookies are $5.
    ```

What happens? (症状)
---------------------

- 以下のような表示になる
   - chocolates are *3andcookiesare*5.

What is the expected result? (期待される動作)
-------------------------------------------

- 以下のように表示されること
   - chocolates are $3 and cookies are $5.

Note
----

- v5.1.10では再現しない
- v6.0.0では再現する

**Comment by miya** [comment]
@nakashimaki 
いつも Issue の起票をありがとうございます！
こちら再現を確認いたしましたので、開発チームで優先度を決定して着手させていただきます。

**Comment by arafubeatbox** [comment]
@nakashimaki 
こちらですが、v6.0.0 以降、`$` は LaTeX のように数式を記述する際に使用する記号となりました。
`$` をそのまま使用したい場合は、`\$` のようにエスケープしていただくようお願いいたします。

取り急ぎ、数式の記述法については[こちら](https://github.com/remarkjs/remark-math#example-katex)を参考にしてください。
ドキュメントには追って追記いたします。

改めて、issue の起票ありがとうございました。こちらは閉じさせていただきます。
