### ISSUE TITLE
Bug: Bug that prevents page creation if images are submitted before saving the page.

### ISSUE THREAD

**Issue by 3265** [weseek/growi#7469]
# Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04|
|GROWI     |6.0.7|
|node.js   |14.17.6|
|npm       |6.14.15|
|yarn      |1.22.18|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11|
|browser   | Google Chrome 110.0.5481.180 (Official Build) （64 ビット） (cohort: 110_Win_Cotrol) |

### How to reproduce? (再現手順)

1. Create a new page 
2. Upload an image by pasting a file into the editor area
3. save the page

Then i got following bellow error:

![image](https://user-images.githubusercontent.com/8959761/224584966-b052e2a7-61fa-483f-8a3e-48b296ec2546.png)

**Comment by miya** [comment]
@3265 
Thank you for taking the time to raise this issue!
This problem has been fixed in the latest version (v6.0.8). I believe updating will resolve this issue.
