### ISSUE TITLE
Bug: Page Tree does not close automatically on android

### ISSUE THREAD

**Issue by 3265** [weseek/growi#7470]
# Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 20.04|
|GROWI     |6.0.7|
|node.js   |14.17.6|
|npm       |6.14.15|
|yarn      |1.22.18|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Android 13|
|browser   | Brave |

### What happens? (症状)

Clicking on a page in the page tree to move from one page to another does not automatically close the page tree on android.

**Comment by yuki-takei** [comment]
In v7.0.0, the opening/closing behavior has changed. This issue is a problem with versions below v6.0.0 and will not be fixed.
