### ISSUE TITLE
Question: `$foo` 形式の文字列が表示されない

### ISSUE THREAD

**Issue by syuchan1005** [weseek/growi#7492]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu|
|GROWI     |6.0.9|
|node.js   |16.19.1|
|npm       |8.19.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Google chrome|

How to reproduce? (再現手順)
---------------------------

1. ページを作成する
2. ページに`$test`のような、`$`から始まり`[a-zA-Z]`が続く存在しないタグを記述する 

What happens? (症状)
---------------------

- 5.1.10ではタグがテキストして表示されるが、6.0.9ではなにも表示されない

#### 5.1.10
<img width="80%" src="https://user-images.githubusercontent.com/8733829/226147993-5aa6282b-31e5-40b3-a66b-ee4baba0c0c4.png">

#### 6.0.9
<img width="80%" src="https://user-images.githubusercontent.com/8733829/226148015-95e05f7f-2f75-4ab2-a31b-66812845f8fd.png">

What is the expected result? (期待される動作)
-------------------------------------------
- テキストとして正常に表示される

Note
----
- 
-

**Comment by yuki-takei** [comment]
@syuchan1005 報告ありがとうございます。
この挙動は修正は可能ですが、現時点では一旦仕様という着地でいいかなと思っています。(修正の手間の割に回避できるメリットはそれほど多くないので)

## ワークアラウンド(回避策)

`\$foo` のように頭にバックスラッシュを入れることでテキストとして表示できる

## memo
- 内部的には remark-growi-directive により remark ast に変わるが、その後 hast に変換する処理がない
    - hast にした上で、文字列をそのまま出すようにする rehype plugin を作れば期待される動作通りになる
    - この処理は remark-lsx 等の rehype plugins より後で処理する必要がある
