### ISSUE TITLE
Bug: draw.ioで作成したダイアグラムがInvalidCharacterErrorと表示される

### ISSUE THREAD

**Issue by kyoruni** [weseek/growi#7524]
Environment
------------

### Host
- デモサイト https://demo.growi.org/

| item     | version |
| ---      | --- |
|GROWI     |6.0.12|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Monterey |
|browser   | Google Chrome 111.0.5563.146（Official Build）, Safari 15.4 (17613.1.17.1.13)|

How to reproduce? (再現手順)
---------------------------

1. draw.ioでダイアグラムを作成し、保存

What happens? (症状)
---------------------

- ダイアグラムを表示している箇所に、以下が表示される（ [デモサイトで作成したページ](https://demo.growi.org/64262085eb8a1534ef0a6c15) ）

 `InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`

![スクリーンショット 2023-03-31 9 26 49](https://user-images.githubusercontent.com/40832190/228993082-bebd6da6-290d-4582-962e-a8e133942a36.png)

 - ページに保存されているダイアグラムのデータは以下になります。

```
    <mxGraphModel dx="922" dy="517" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="2" value="黄色の丸" style="ellipse;whiteSpace=wrap;html=1;fillColor=#fff2cc;strokeColor=#d6b656;" vertex="1" parent="1">
          <mxGeometry x="60" y="40" width="120" height="80" as="geometry"/>
        </mxCell>
        <mxCell id="3" value="赤の四角" style="rounded=0;whiteSpace=wrap;html=1;fillColor=#f8cecc;strokeColor=#b85450;" vertex="1" parent="1">
          <mxGeometry x="60" y="150" width="120" height="60" as="geometry"/>
        </mxCell>
      </root>
    </mxGraphModel>
  ```

What is the expected result? (期待される動作)
-------------------------------------------

- 作成したダイアグラムが正しく表示される

**Comment by tWatanabeCTC** [comment]
6.0.13でも同様の問題を確認しています。

**Comment by yuki-takei** [comment]
現在調査中です。
6.0.13 で全く問題が起きない環境もあれば、demo のようにこの症状が出る環境もあって難航しています。

**Comment by yuki-takei** [comment]
## 経緯と対策
https://github.com/weseek/growi/issues/7505#issuecomment-1488410666

## この Issue で報告されている問題について
結論から言うと、解消を諦めます。。(すみません)

報告されている症状については demo サイトで問題を確認してはいるものの、開発環境で再現せず原因を特定できませんでした。

加えて[本家の対応](https://github.com/jgraph/drawio/issues/3484) により compress して保存できるオプションが付いたため、 以前のバージョンと同じように再び compressed data で保存するようになりました。それによって「uncompressed data のレンダリング」という機能に対する状況が変わり、優先度も高くないと判断したため原因究明と問題の解消を見送ることにしました。

## ワークアラウンド(回避方法)
この症状は View やプレビューでレンダリングされないのが問題で、Drawio で編集するウィンドウを開くと図表は復元できます。そのまま何かしらの変更を加えて保存することで compressed data で保存することができ、結果的に View やプレビューでのレンダリングを正常化することができます。

**Comment by yuki-takei** [comment]
遅ればせながらこちらの問題の原因が判明しました。
管理画面の Markdown 設定で「Line Break 設定」を有効にしていると、uncompressed data に XML としては無効な文字列が入ってしまうようです。

本日リリースした v6.0.15 で Line Break 有効状態でも正常にレンダリングできるようにする修正を入れてあります。
