### ISSUE TITLE
Bug:1ページ内でdraw.ioを3~4つ以上配置できない

### ISSUE THREAD

**Issue by Akira-Demizu** [weseek/growi#7533]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |mac OS Ventura 13.3|
|browser   |Chrome バージョン: 111.0.5563.146（Official Build） （x86_64）|

How to reproduce? (再現手順)
---------------------------

1. ページを新規作成
1. draw.ioにて任意の図形を設置する
1. draw.ioにて任意の図形を設置する
1. draw.ioにて任意の図形を設置する
1. draw.ioにて任意の図形を設置する
1. `更新`をクリックする

What happens? (症状)
---------------------

- draw.ioの内容次第で3~4つ目の図形が表示されない

What is the expected result? (期待される動作)
-------------------------------------------

- 設置したすべてのdraw.ioが表示される

Note
----

- 技術的に不可であれば、エラーの表示または3つ目以降は追加できないようにしていただきたい

**Comment by yuki-takei** [comment]
@Akira-Demizu ご報告ありがとうございます。

少なくとも v6.0.13 で3つ以上の図表の表示を確認できていますので、まずは v6 系で再現するかどうかの確認をお願いします。
(別途、https://github.com/weseek/growi/issues/7524 という問題がありそちらは調査中です)

v5 系は今後セキュリティ関連のアップデート以外は行わない予定です。
もし v6 系で同様の症状がある場合は修正対象としますので、改めて Issue を作成していただけると助かります。
