### ISSUE TITLE
Bug: v4.2.17からv5.1.10に更新するとページの更新履歴が見れなくなる

### ISSUE THREAD

**Issue by rary21** [weseek/growi#7549]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |20.04.3 LTS (Focal Fossa)|
|GROWI     |5.1.10|
|node.js   |16.19.0|
|npm       |8.19.3|
|yarn      |1.22.19|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 Pro 22H2|
|browser   |Google Chrome 111.0.5563.147|

How to reproduce? (再現手順)
---------------------------

1. v4.2.17で起動中のサーバーから全てのデータをアーカイブする
1. ローカルマシンを用いてv4.2.17を立ち上げる  
    環境構築は下記のgrowi-docker-composeを用いる。
    `ports` と `PASSWORD_SEED`を変更する  
     `./Dockerfile` のバージョンをv4.2.17に変更する  
    https://github.com/weseek/growi-docker-compose/commit/27184e7c3aa68ec36205139d2cb67fe02486b132
1. 2で立ち上げたマシン上で1のアーカイブをインポートする  
    `Check All` を押して実行するだけで、インポートのモードは変更しない。  
    元々存在する `SandBox` と `/` の `Pages` のみインポートが失敗するが他は成功する。  
1. この時点では問題なく更新履歴が確認できる
1. ローカルマシンをv5の最新版に更新する  
    環境構築は下記のgrowi-docker-composeを用いる。  
    `ports` と `PASSWORD_SEED` のみ更新する。  
    https://github.com/weseek/growi-docker-compose/commit/68adada4a999e5e3214de013fba6c3b78f75e169
1. 更新履歴が `2022/04/12 13:44:52 (差分なし)` のように表示される。  
    また、v5形式へ全ページを変換しても症状は変わらない  
    ページ右上に表示されるページの作成日・更新日は正常に表示されている
    アップグレード後に変更したページの更新履歴は閲覧可能

What happens? (症状)
---------------------

- v4.2.17からv5.1.10に更新するとページの更新履歴が閲覧できなくなる
- MongoDB Compassからデータベースを確認すると `growi.revisions` にデータは存在している

What is the expected result? (期待される動作)
-------------------------------------------

- v5への更新後もページの更新履歴が閲覧できる

Note
----

- `/`, `/SandBox`, `/SideBar`, `/user` を除いて全てのページにグループ権限をつけて管理している

**Comment by rary21** [comment]
v4/v5では `growi.revisions` のデータに以下の違いがあるので
v4のデータから履歴を取得できなさそう

* v4ではページの `path` を持っている
* v5では `path` がなくなり `pageId` が追加されている

**Comment by rary21** [comment]
v6へのマイグレーション例を参考にして以下のスクリプトを作成した。
https://github.com/weseek/growi/discussions/7180

```javascript
var pagesCollection = db.getCollection('pages');
var revisionsCollection = db.getCollection('revisions');

// pagesCollectionのすべてのドキュメントを取得する
const pages = pagesCollection.find({});

// 各ページについて、revisionsCollectionを更新する
pages.forEach(page => {
  const path = page.path;
  const pageId = page._id;

  // pageIdが存在しない場合にのみ同一のpathを持つページIDをセット
  revisionsCollection.updateMany({ path: path, pageId: { $exists: false }}, { $set: { pageId: pageId } });
});

print('migration complete!');
```

v5形式への変換をadmin画面/PageTreeの両方から実行した後に上記を実行すると
変更履歴が閲覧できるようになった。
以上の変更が適切かどうか、開発グループの方の意見をいただきたいです。

**Comment by yuki-takei** [comment]
@rary21 ご報告ありがとうございます。

v4 から v5 になったタイミングで Revision のスキーマ変更があったのは正しいです。ご指摘の通り、path による参照から pageId による参照に変わっています。

ただその変更は DB migration script によってカバーされている範囲になります。
https://github.com/weseek/growi/blob/8f330e7692a298e5b27daf9accbf06c666630282/packages/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration.js

GROWI 本体を v5 以降のバージョンにアップグレードして起動したタイミングで、その時点の全ての Revision ドキュメントが更新されます。

## v5形式への変換との関連

Revision モデルのスキーマ変更は、v5形式への変換とは関係ないものと認識しています。
GROWI 本体を v5 にアップグレードし、v5互換形式に変換せず使い続けてた場合でも、新たに作られた Revision ドキュメントは pageId による参照を持つため、正常に紐付けがなされます。

## ご報告いただいた症状について

もしあるとすれば、

1. v4 で運用
2. v5 で一度起動、`20211227060705-revision-path-to-page-id-schema-migration.js` で変換
3. v4 にダウングレード
4. (この間、path による参照を持ったデータが作られる)
5. 再度 v5 にアップグレード
    - この時、`20211227060705-revision-path-to-page-id-schema-migration.js` は再度処理されない

というケースかなと思いますが…該当しますでしょうか？

[v5.0.x へのアップグレードガイド](https://docs.growi.org/ja/admin-guide/upgrading/50x.html#v4-5-%E7%B3%BB%E4%BB%A5%E4%B8%8B%E3%81%B8%E3%81%AE%E3%82%BF%E3%82%99%E3%82%A6%E3%83%B3%E3%82%AF%E3%82%99%E3%83%AC%E3%83%BC%E3%83%88%E3%82%99%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6) にも書いていますが、3. 時点で migration down を行わない限りは、5. で再度 `20211227060705-revision-path-to-page-id-schema-migration.js` が実行されません。

**Comment by rary21** [comment]
@yuki-takei 

他のmigrationは適用されているようです。
期待する変更が適用されていない `20211227060705-revision-path-to-page-id-schema-migration.js`  
を見ると以下のように記述されています。
このコードを見たところ `Page` が持つ `revision` (おそらく最新) のみに変更が適用されるように見えます。  
また以下の振る舞いからもこの挙動であることが推察されます。

* v5へアップデート後、変更履歴は最新のrevisionしか表示されない。
```js
  // path => pageId
  async up(db, client) {
    mongoose.connect(getMongoUri(), mongoOptions);
    const Page = getModelSafely('Page') || getPageModel();
    const Revision = getModelSafely('Revision') || require('~/server/models/revision')();

    const pagesStream = await Page.find({ revision: { $ne: null } }, { _id: 1, revision: 1 }).cursor({ batch_size: LIMIT });
    const batchStrem = createBatchStream(LIMIT);

    const migratePagesStream = new Writable({
      objectMode: true,
      async write(pages, encoding, callback) {
        const updateManyOperations = pages.map((page) => {
          return {
            updateMany: {
              filter: { _id: page.revision },
              update: [
                {
                  $unset: ['path'],
                },
                {
                  $set: { pageId: page._id },
                },
              ],
            },
          };
        });

        await Revision.bulkWrite(updateManyOperations);

        callback();
      },
      final(callback) {
        callback();
      },
    });

    pagesStream
      .pipe(batchStrem)
      .pipe(migratePagesStream);

    await streamToPromise(migratePagesStream);

    logger.info('Migration has successfully applied');
  },
```

**Comment by rary21** [comment]
@yuki-takei 
直前のコメントに書いてあるDB migration scriptに対する理解は合っていますか？
また合っている場合、この振る舞いは意図したものでしょうか？

**Comment by rary21** [comment]
特に悪影響がなさそうと判断したためv5へのアップグレード後に
以下のスクリプトを実行してすべてのRevisionを変更しました。
現状は想定通りに更新履歴が見えているのでクローズします。

```js

/* eslint-disable no-undef, no-var, vars-on-top, no-restricted-globals, regex/invalid, import/extensions */
// ignore lint error because this file is js as mongoshell

var pagesCollection = db.getCollection('pages');
var revisionsCollection = db.getCollection('revisions');

// pagesCollectionのすべてのドキュメントを取得する
const pages = pagesCollection.find({});

// 各ページについて、revisionsCollectionを更新する
pages.forEach(page => {
  const path = page.path;
  const pageId = page._id;

  // revision内にpageIdが存在しない場合にのみ同一のpathを持つpageIdをsetしpathをunsetする
  revisionsCollection.updateMany({ path: path, pageId: { $exists: false }}, { $set: { pageId: pageId }, $unset: { path } });
});

print('migration complete!');
```

**Comment by yuki-takei** [comment]
@rary21 昨日の close 処理で気付きました、返信が遅くなってすみません。

なるほど、確かに page.revision しか処理していないので過去のリビジョンを参照できないのですね。おそらく数が多すぎるために端折った結果で、History まで考慮できていないなかったのではないかと思います。

## TODO

1. 全ての revision について同様の処理を行う
1. 古い形式の Revision データ(path しか存在しない)でも引っ張ってくるように改修する

のどちらかをやればよさそうですね。1の方がクリーンですが、2の方が環境への負荷は少ない。

**Comment by yuki-takei** [comment]
v6.1.0 で対象データがあれば追加のマイグレーションを行うようにします。
運用中ページを移動させてしまって path が一致しなくなってしまったものは救えないと思いますが…
