### ISSUE TITLE
Bug: コードブロック内の <xxx> の表示が崩れる

### ISSUE THREAD

**Issue by eternity1984** [weseek/growi#7568]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | debian v10.13 |
|GROWI     |5.1.10|
|node.js   |16.19.0|
|npm       |16.19.0|
|Using Docker|yes (*k8s) |
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 |
|Microsoft Edge   |112.0.1722.39|

How to reproduce? (再現手順)
---------------------------

1. 記事を作成し、以下をコードブロックとして追加する。
    
    ```
    NAME             STATUS      ROLES           AGE    VERSION
    k8s-master-1     Ready       control-plane   321d   v1.27.0
    k8s-worker-001   Ready       <none>          173d   v1.27.0
    k8s-dgx-001      Ready       computing,gpu   283d   v1.27.0
    ```

1. （プレビュー画面）の要素が正しいことを確認する。`&lt;none&gt;`

    ```
    <pre class="hljs hljs-no-border">
        <code>
            ”NAME             STATUS      ROLES           AGE    VERSION
            k8s-master-1     Ready       control-plane   321d   v1.27.0
            k8s-worker-001   Ready       &lt;none&gt;          173d   v1.27.0
            k8s-dgx-001      Ready       computing,gpu   283d   v1.27.0
            "
        </code>
    </pre>
    ```

3. 保存し、記事を確認する。

What happens? (症状)
---------------------

- Edge では、内部の`<none>` がエスケープされていない。

```
<pre class="hljs hljs-no-border">
    <code>
        "NAME             STATUS      ROLES           AGE    VERSION
        k8s-master-1     Ready       control-plane   321d   v1.27.0
        k8s-worker-001   Ready       "
        <none>
            "          173d   v1.27.0
                k8s-dgx-001      Ready       computing,gpu   283d   v1.27.0
            "
        </none>
    </code>
</pre>
```

What is the expected result? (期待される動作)
-------------------------------------------

- 編集中のプレビュー画面と同様にコードブロック内の`<>`表現が維持される。

Note
----

XSS設定によって `none` は初期では許可されていないので非表示となる。
一応、ホワイトリストに登録すれば正常に表示されるが...タグではないので、可能ならば登録したくはないです。
 
Chrome 112.0.5615.86 では問題ありません。

**Comment by yuki-takei** [comment]
@eternity1984 v5 系までの制約になります。v6 以降をご利用ください。

関連する Issue: https://github.com/weseek/growi/issues/2557

**Comment by eternity1984** [comment]
@yuki-takei ありがとうございます。`6.0.15` にアップグレードして正常に表示されるようになりました。
