### ISSUE TITLE
Bug: Specified Group ACL is not persisted correctly on v3.3.1

### ISSUE THREAD

**Issue by gaku-h** [weseek/growi#764]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Windows 7 |
|GROWI     |3.3.1|
|node.js   |8.12.0|
|npm       |6.4.1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome,Edge|

How to reproduce? (再現手順)
---------------------------
0.グループ作成
　対象ユーザーをグループに追加

1. ページ作成
![1](https://user-images.githubusercontent.com/43461621/50200656-27421580-039a-11e9-822e-891668f26f52.jpg)

2. 記事作成
![2](https://user-images.githubusercontent.com/43461621/50200707-6cfede00-039a-11e9-8221-23ebc92fb467.jpg)

3.公開範囲を作成したグループに設定(作成者も所属しているグループ)
![3](https://user-images.githubusercontent.com/43461621/50200721-80aa4480-039a-11e9-9ae9-8dda3080c0c9.jpg)

![4](https://user-images.githubusercontent.com/43461621/50200750-a0416d00-039a-11e9-87f3-605304855f89.jpg)

4.閲覧権限がないと表示される
![5](https://user-images.githubusercontent.com/43461621/50200755-a8011180-039a-11e9-8129-6413e12edebc.jpg)

その後どのユーザーで入っても記事閲覧、編集ができなかった。

What happens? (症状)
---------------------
公開範囲を特定グループに設定したら、グループ所属のユーザーで見れなくなる

What is the expected result? (期待される動作)
-------------------------------------------
公開範囲を設定したグループに所属しているユーザーのみ閲覧、編集ができる

**Comment by yuki-takei** [comment]
@gaku-h ご報告ありがとうございます。再現確認しました。
早急に修正してリリースします。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@gaku-h 当該事象ですが、
「公開範囲を特定グループに設定したページが、当該グループ所属のユーザーでも閲覧できなくなる」
ではなく、
「公開範囲を特定グループに設定しても、そもそも当該グループの情報が保存されない」
というものなので、申し訳ないのですが上記操作を行ったページのデータはどうやっても閲覧不可になってしまいます。(例え fixed version にアップグレードしてもデータはそのまま)

どうしてもページの復旧が必要な場合は、恐れ入りますが直接 MongoDB のデータを書き換える等していただけますでしょうか。

`grant: 5` になっている部分を `grant: 1` に変えれば一旦 public になります。
