### ISSUE TITLE
Bug: v6.0.15, 6.1.0, 6.1.1：Growiページ内の見出しへのリンクが動作しない

### ISSUE THREAD

**Issue by YoshitakaMo** [weseek/growi#7696]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.2|
|GROWI     |6.0.15, 6.1.0, 6.1.1|
|node.js   |16.20.0|
|npm       |8.19.4|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Ventura 13.3|
|browser   |Microsoft Edge 113.0.1774.50, Google Chrome 113.0.5672.126のそれぞれで確認|

How to reproduce? (再現手順)
---------------------------

Growi内ページへのページ内リンクを以下のように記述しても動作しない状態が発生しています。
例えばGrowiのあるページAのMarkdownで

```
## 研究

- [学会活動](学会活動)
  - [出張申請の方法](学会活動#出張申請の方法)
```

とあり、「学会活動」のページで

```
## 出張申請の方法

foo
```

のように書いたとして、ページAにおいて「出張申請の方法」というところでのリンクを押しても「学会活動」ページの該当の見出し「出張申請の方法」にジャンプせず、「学会活動」ページの先頭が表示されます。

What is the expected result? (期待される動作)
-------------------------------------------

- ページ内での見出しリンクが以前のように動作するようになって欲しい

よろしくお願い致します。

**Comment by yuki-takei** [comment]
@YoshitakaMo ご報告ありがとうございます。以下で再現しました。
修正し次第リリースしますので今しばらくお待ちください。

## 再現条件 (厳密版)
1. 新規ページ作成
    1. クリーンインストールで作成される /Sandbox ページに対するリンクを本文に記述する
         ```markdown
         [anchor link test](/Sandbox#-typography)
         ```

## 症状
- リンク先が `/Sandbox` になり、アンカーが消える

## 期待される動作
- アンカー付きのリンクが生成される

**Comment by yuki-takei** [comment]
v6.1.2 リリースをお待ちください。
