### ISSUE TITLE
Improvement:  minio (aws s3 alternative) Support

### ISSUE THREAD

**Issue by ghost** [weseek/growi#770]
minio is alternative AWS s3.

we can use minio via aws-sdk(growi is using)
https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-javascript-with-minio.md

but some parameter design is not compatible with minio.
so I offer to support file upload function with minio.

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | ubuntu 16.04|
|GROWI     |3.2.4|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Chrome 71.0|

How to reproduce? (再現手順)
---------------------------

1. launch minio server
2. edit docker-compose.yml environment like minio page

What happens? (症状)
---------------------

- endpoint parameter not supported

What is the expected result? (期待される動作)
-------------------------------------------

- add endpoint parameter 
- remove region parameter

Note
----

- 
-

**Comment by yuki-takei** [comment]
@ktakeuchi Thank you for your suggestion.

We'll consider it, but I do not have much demand for it, the priority may be low.

**Comment by you-at4** [comment]
I would like to suggest Google Cloud Storage (GCS) support.

**Comment by e1en4** [comment]
I am hoping for an early response as I want to use Google Cloud Storage.

**Comment by yuki-takei** [comment]
fixed by #1138
