### ISSUE TITLE
Question:S3にアップロードしようとすると失敗する

### ISSUE THREAD

**Issue by tanakamac** [weseek/growi#774]
Question
------------
以前GROWIのファイルアップロード先をS3に指定して利用しておりましたが、
最近そのS3に対してバケットポリシー等を変更したところ、アップロードができなくなってしまいました。本件がAWS側の設定の問題か、もしくはGROWI側の問題か切り分けたいのですが、GROWI側で確認するべき事項等（デバッグモードにしてログを出力する方法や見るべきエラーログなど）ありますでしょうか？

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |amazon linux|
|GROWI     |3.2.2|
|node.js   |8.11.4|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows7|
|browser   |Google Chrome 71.0.3578.98|

### システム構成について
- growi/mongodb/elasticsearchのコンテナがVPC内のEC2インスタンスの中で動いています
- クライアントーGROWI(EC2)間はAWS DX経由でのアクセスとなっており、社内IPからしかアクセスできません。
- S3は社のプロキシ経由でのアクセスまたはS3アクセス用のIAM権限からのみアクセス可能なように、プリンシパルに該当ユーザーを指定した設定と、コンディションでソースＩＰを制限した設定を施しています。
- S3バケット自体はプライベートです。

How to reproduce? (再現手順)
---------------------------
S3の設定を実施し、アップロードできるか確認→ＯＫ
その後、Amazon S3のバケットポリシーを変更

What happens? (症状)
---------------------
画像をアップロードしようとしたところ、
記事エディタへのD&Dではずっとロード中（サークルが回り続ける）となり、
プロフィール画像をアップロードしようとするとエラーとなるようになる。

What is the expected result? (期待される動作)
-------------------------------------------
エディタおよびプロフィール等画像がアップロードできる。

Note
----
S3側の問題かと思い、試しにローカルの下記環境で同じバケットに対して
GROWI側のAWS設定を実施したところ、こちらの環境では正常にアップロードできました。
（こちらではS3の設定後、バケットポリシーの変更はしていない）

> 2018.12.26 edit: OSの種類をubuntuに訂正
> ‘ローカル‘と言いながらOSがamazonになっていました。訂正いたします。

### HOST
| item     | version |
| ---      | --- |
|OS        |ubuntu 18.04LTS|
|GROWI     |3.3.3|
|node.js   |8.14.1|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

クライアントは前述のものです。

**Comment by yuki-takei** [comment]
@tanakamac 

心当たり
----------

> 画像をアップロードしようとしたところ、
> 記事エディタへのD&Dではずっとロード中（サークルが回り続ける）となり、
> プロフィール画像をアップロードしようとするとエラーとなるようになる。

こちらですが、まず新規ページ作成画面(未保存の状態)でD&Dしているのか、
既に保存済みのページの編集画面でD&Dしているのかを確認してください。

前者の場合、v3.2.5 以前でバグがあります。(v3.2.6 で修正済み)
https://github.com/weseek/growi/releases/tag/v3.2.6


切り分け方法
----------------

上記の問題以外の場合は、サーバー側ログ(app コンテナログ)、ブラウザコンソールを確認してください。
サーバー側ログは、以下の環境変数を設定して起動することでログレベルが上がります。

```
DEBUG=growi:routes:attachment,growi:service:fileUploaderAws
```

出力されたログ中、該当部分を抜粋して貼っていただければこちらでももう少し切り分けできると思います。

**Comment by tanakamac** [comment]
早速のご対応、またログの出力方法などご教示いただきありがとうございます。
> 心当たり
新規記事でも発生していたように思いますが、あやふやなので確認いたします。

発生しているのが社内サーバでレスポンスが遅めになってしまうかと思います。
大変申し訳ありません。

ログのほうはわかり次第こちらに報告いたします。

以上、取り急ぎのご連絡まで。

**Comment by tanakamac** [comment]
掲題の件、まず新規記事・作成済み記事の編集において発生していることを確認いたしました。
また、ブラウザのコンソールでは、/_api/attachments.addにて{"ok":false,"error":"Error while uploading."}
が返っていました。
growiのアプリケーションサーバのログ(dockerコンテナのログ)は下記のようになっておりました。
> {"log":"      at IncomingMessage.onEnd (/opt/growi/node_modules/aws-sdk/lib/event_listeners.js:269:13)\n","stream":"stdout","time":"2018-12-29T12:10:31.895382266Z"}
{"log":"      at emitNone (events.js:111:20)\n","stream":"stdout","time":"2018-12-29T12:10:31.895385509Z"}
{"log":"      at IncomingMessage.emit (events.js:208:7)\n","stream":"stdout","time":"2018-12-29T12:10:31.895388625Z"}
{"log":"    message: 'Access Denied',\n","stream":"stdout","time":"2018-12-29T12:10:31.895404731Z"}
{"log":"    code: 'AccessDenied',\n","stream":"stdout","time":"2018-12-29T12:10:31.895408932Z"}
{"log":"    region: null,\n","stream":"stdout","time":"2018-12-29T12:10:31.895412134Z"}
{"log":"    time: 2018-12-29T12:10:31.894Z,\n","stream":"stdout","time":"2018-12-29T12:10:31.895415226Z"}
{"log":"    requestId: 'D834D20F30C03B1B',\n","stream":"stdout","time":"2018-12-29T12:10:31.895418453Z"}


上記からAWSのネットワーク周りの設定にてDenyされていると理解しております。

認識齟齬ございましたらご指摘ください。

**Comment by tanakamac** [comment]
クローズ前にもう一点だけ、事後報告いたします。

今回発生していた問題は上記の推測通りS3のバケットポリシーなどの問題でした。

GROWIではS3にアップロードすると現状必ず公開ステータスになるので、それを社外に見せたくないためにバケットポリシー等設定したのが発端です。
→バケットポリシーのPrincipal周りに関して、「"*"」としていたのをNotPrincipalでS3設定時に入力するIAMの情報を追加して解消いたしました。
（よくよく考えれば当たり前の話ですよね。。すみません。）

私の知識不足でこのたびはお手数をおかけしまして申し訳ありません。
OSSにも関わらずこのたびのご丁寧な対応、誠にありがとうございます。

**Comment by yuki-takei** [comment]
無事切り分けできてよかったです。お疲れさまでした。
