### ISSUE TITLE
Bug: Profile image not display

### ISSUE THREAD

**Issue by duyhotung** [weseek/growi#775]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |3.2.10-RC|
|node.js   |v8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Window 10|
|browser   |Chrome 71.0.3578.98|

How to reproduce? (再現手順)
---------------------------
1. upload file mode is:  FILE_UPLOAD: 'mongodb',
2. move /me
3. choose image file

What happens? (症状)
---------------------

The upload image cant display

What is the expected result? (期待される動作)
-------------------------------------------

The upload image can display

![image](https://user-images.githubusercontent.com/33145005/50419930-11cf5e80-0866-11e9-99ff-9b2ecc9ec969.png)

**Comment by yuki-takei** [comment]
@duyhotung Thank you for your report. I'll fix it.

**Comment by yuki-takei** [comment]
@duyhotung Fixed. Wait the next release v3.4.0
