### ISSUE TITLE
Improvement: 記事を複数のディレクトリに属せるように

### ISSUE THREAD

**Issue by ame0011** [weseek/growi#777]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Arch Linux|
|GROWI     |3.3.3|
|node.js   |8.14.1|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |CentBrowser 3.7.2.33|

What happens? (症状)
---------------------

- ディレクトリをカテゴライズのために使うと、複数のカテゴリに属する記事の扱いに困ってしまいます

What is the expected result? (期待される動作)
-------------------------------------------

- 記事の属するディレクトリを複数指定できる

Note
----

- 実装が困難になりそうならショートカットを作れるようにでも可

**Comment by yuki-takei** [comment]
@ame0011 提案ありがとうございます。

ページパスの仕様はもう変えられないので、esa のようにディレクトリとタグを両方使えるように機能追加することになると思います。
アンケートでも一定数需要があったので、追々実装するつもりですが、直近での着手予定は立っていないので、方針決定まで今しばらくお待ちいただければと思います。

**Comment by ame0011** [comment]
了解しました

**Comment by yuki-takei** [comment]
Released on v3.4.6.
