### ISSUE TITLE
Bug: slackChannels is always empty because /pages.updatePost is never called

### ISSUE THREAD

**Issue by asial-matagawa** [weseek/growi#7789]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Debian GNU/Linux 9 (stretch) |
|GROWI     | 6.0.15 |
|node.js   | 16.20.0 |
|npm       | 8.19.4 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Ventura 13.3.1 |
|browser   | Chrome 114 |

How to reproduce? (再現手順)
---------------------------

1. Register some page patterns and Slack channel names under `User trigger notification > Default notification settings`.
1. Open a target page in GROWI.
1. Proceed to the editing screen.
1. (optional) Click on the Slack logo toggle button at the bottom right of the page.

What happens? (症状)
---------------------

- I registered some page patterns and Slack channel names under `User trigger notification > Default notification settings`. However, the Slack channel names are not auto-filled when I open the editing screen for the target pages.
- Upon inspection with DevTools, I was able to confirm that `useSWRImmutable` inside `useSWRxSlackChannels` is being called with the key `["/pages.updatePost", "/sandbox"]`. However, `([endpoint, path]) => apiGet(endpoint, { path }).then((response: SlackChannels) => response.updatePost)` has never been called.
  - As a result, the value of `slackChannels` in `PageEditor/EditorNavbarBottom.jsx` is always empty.

https://github.com/weseek/growi/blob/6631a5a849e5deee6551bd6264787c9751dc0725/apps/app/src/stores/editor.tsx#L77-L86

### Screenshot 1
<img width="1275" alt="2023-06-09 0 53 42" src="https://github.com/weseek/growi/assets/19771915/798eff19-40a4-493b-9214-8cd44489ee2e">

### Screenshot 2
<img width="1169" alt="2023-06-09 1 07 39" src="https://github.com/weseek/growi/assets/19771915/6f149eab-9292-4ed2-842c-96b2e9b03383">

What is the expected result? (期待される動作)
-------------------------------------------

- The Slack channel name is correctly auto-filled when the editing screen is opened.

**Comment by yuki-takei** [comment]
@asial-matagawa Thanks for the very detailed report. We will investigate it.

**Comment by yuki-takei** [comment]
@asial-matagawa This issue has fixed. Please wait the next release v6.1.4.

**Comment by asial-matagawa** [comment]
@yuki-takei 
Awesome! I really appreciate your speedy fix to the issue I reported. Thank you!
