### ISSUE TITLE
Bug: lsx機能でprefix(ページパス)とdepthを同時に指定した際の動作に一貫性がない

### ISSUE THREAD

**Issue by tthogehoge** [weseek/growi#7805]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |debian11|
|GROWI     |6.1.4|
|node.js   |18.16.0|
|npm       |9.5.1|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows10|
|browser   |chrome 114.0.5735.110|

How to reproduce? (再現手順)
---------------------------

1. 最初のページを作成(例: /P)
1. 最初のページの下に何階層かページを作成(例: /P/A1/B1)
1. 最初のページの下に何階層かページを作成(例: /P/A2/B2)
1. 最初のページに以下を記述
    ```
    $lsx(.,depth=1)
    ```

What happens? (症状)
---------------------

- 一覧として1階層下が表示されず、2階層下が表示される(例ではA1, A2が表示されず、B1, B2が表示される)

What is the expected result? (期待される動作)
-------------------------------------------

- 一覧として1階層下が表示される

Note
----
カレントとして./や.を指定しなければ表示される。
またはdepthを指定しなければ表示される。
```
$lsx(depth=1)
$lsx(depth=2)
$lsx(.)
```

**Comment by yuki-takei** [comment]
@tthogehoge ご報告ありがとうございました。再現を確認し、修正しました。次のリリースをお待ちください。

エンバグしたバージョンについてはおそらく 6.0.0 ではなく 6.1.3 あたりだろうと思います(未検証)。
そのためタイトルを若干変更しました。もし症状が発現する境界となるバージョンについて確定的な情報をお持ちであれば教えてください。再度変更します。

**Comment by tthogehoge** [comment]
> もし症状が発現する境界となるバージョンについて確定的な情報をお持ちであれば教えてください。再度変更します。

6.1.4に変えてみて気づいたので、境界となるバージョンについてはちょっとわからないです。

修正ありがとうございました。
