### ISSUE TITLE
Autolink with angle brackets not shown

### ISSUE THREAD

**Issue by mandel59** [weseek/growi#781]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Linux|
|GROWI     |3.3.4-RC (master 7de051b8)|
|node.js   |8.15.0|
|npm       |6.5.0|
|yarn       |1.12.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Firefox 64.0|

How to reproduce? (再現手順)
---------------------------

1. Write an autolink in markdown:
    ```markdown
    Example: →<http://example.com/>←
    ```

What happens? (症状)
---------------------

- The autolink is removed and not displayed. オートリンクが除去され、表示されません。
![image](https://user-images.githubusercontent.com/1079715/50781306-5dfbb380-12e8-11e9-9b67-69207b6adc5d.png)

What is the expected result? (期待される動作)
-------------------------------------------

- The autolink should be rendered as same as a hyperlink to <http://example.com/>

Note
----

- Autolinks with angle brackets are removed by XssFilter in PreProcessor.

**Comment by yuki-takei** [comment]
@mandel59 This is expected behavior.

## Available Link Syntax
see https://demo.growi.org/Sandbox#%00%20Link

## When you want to render `<http://example.com>`
write as below:
```
Example: →&lt;http://example.com/&gt;←
```
