### ISSUE TITLE
Bug: Entity references are decoded in code blocks without info strings

### ISSUE THREAD

**Issue by mandel59** [weseek/growi#782]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Linux|
|GROWI     |3.3.4-RC (master 7de051b8)|
|node.js   |8.15.0|
|npm       |6.5.0|
|yarn       |1.12.3|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   |Firefox 64.0|

How to reproduce? (再現手順)
---------------------------

1. Write entity references (and/or numeric character references) in a fenced code block without info strings
    ````markdown
    ```
    &lt;-&gt;
    ```
    ````

What happens? (症状)
---------------------

- The references are shown as decoded characters. 実体参照・数値文字参照がデコードされた文字として表示される。
  - In contrast, references written in code blocks with info strings are rendered as same as the code correctly. 対照的に、info stringを持つコードブロック中の参照は正しく、コードと同様に表示される。 
![image](https://user-images.githubusercontent.com/1079715/50783332-d87b0200-12ed-11e9-88c9-59320f5e2c96.png)

What is the expected result? (期待される動作)
---------------------

- The block is rendered as `&lt;-&gt;`

**Comment by yuki-takei** [comment]
@mandel59 Thank you for your report. We'll fix it. Please wait a moment.

**Comment by yuki-takei** [comment]
Fixed on v3.3.4.
