### ISSUE TITLE
$lsxでexceptオプションを使用するとページ一覧が表示されない

### ISSUE THREAD

**Issue by eito-88** [weseek/growi#7835]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04|
|GROWI     |6.1.3|
|node.js   |18.16.0|
|npm       |9.5.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04|
|browser   |FireFox 112.0.1|

How to reproduce? (再現手順)
---------------------------

1. v6.1.3以降でexceptオプションを使用してlsxを記述する
```
$lsx(/, except=_template)
```

What happens? (症状)
---------------------

- ページ一覧が読み込まれず、ずっとロード中になる

What is the expected result? (期待される動作)
-------------------------------------------

- exceptしたページを除いて一覧が表示される

Note
----

以下のバージョンは正しい動作であることを確認しています。

- v6.0.15
- v6.1.2

**Comment by yuki-takei** [comment]
@eito-88 ご報告ありがとうございました。修正しましたので次回のリリースをお待ちください。
