### ISSUE TITLE
Improvement: グループの新規作成階層を設定できるようにしてほしい

### ISSUE THREAD

**Issue by rtakamura** [weseek/growi#788]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7.5|
|GROWI     |3.3.4RC|
|node.js   |8.15.0|
|npm       |6.4.1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |any|
|browser   |any|

What happens? (症状)
---------------------

/
/public  （全公開）
/team1  （特定グループのみ公開）
/team2  （特定グループのみ公開）

という運用を想定しています
ページの公開設定で /team1、/team2 階層はアクセス制限をかけることができますが
グループに所属するしないに関わらず、全てのユーザーが
あらゆる階層にページを新規作成することができます

What is the expected result? (期待される動作)
-------------------------------------------
管理設定のグループ設定で、グループに対して作成権限階層の設定項目があると
グループ毎のコンテンツ管理を明確にすることができると考えています

例えば、"team1" というグループがある場合、グループの作成階層として
"/team1" というパスを設定すると、"team1" グループに所属するユーザーは
「作成」ボタンで新規作成できるパスが ”/team1/" 以下に制限され
"/hoge" や "/team2/hoge" 等のパスには新規作成ができなくなるという感じです

階層を入れない場合や、グループに所属しないユーザーは現状通りで問題ないと思います。
ご検討いただければ幸いです

**Comment by yuki-takei** [comment]
@rtakamura ご提案ありがとうございます。
確かにそれは便利そうですね。ホワイトリスト、ブラックリスト両方設定できると尚良いかもしれません。
一旦工数検討してみます。

**Comment by yuki-takei** [comment]
@rtakamura 相当前の要望ですが、v5 系で期待される動作を満たす仕様になったためクローズします。

参考: https://docs.growi.org/ja/guide/features/authority.html#%E3%83%98%E3%82%9A%E3%83%BC%E3%82%B7%E3%82%99%E3%81%AB%E8%A8%AD%E5%AE%9A%E5%8F%AF%E8%83%BD%E3%81%AA%E9%96%B2%E8%A6%A7%E6%A8%A9%E9%99%90
