### ISSUE TITLE
crowi 互換の ```plantuml ... ``` も使えるようにして欲しい

### ISSUE THREAD

**Issue by liber-takano** [weseek/growi#789]
What is the expected result? (期待される動作)
-------------------------------------------

Crowiのplantumlと互換性が欲しいです。
データ移行したいですが、plantuml をすべての文書で修正するのは厳しいです。。。

* crowi
```
    ```plantuml
    (a) -> (b)
    ```
```

* growi
```
    @startuml
    (a) -> (b)
    @enduml
```

**Comment by yuki-takei** [comment]
@liber-takano 
こちらのご要望ですが、現時点で対応することが困難です。(GROWI 独自の内部仕様に依ります)

また将来の話をすると、Markdown の思想的にもフェンスブロックで囲われたコードブロックは pre または pre>code の出力に限定して使うべきだと思っています。なので、PlantUML のように「全く別のHTML」を吐くシンタックスは別で用意したいという感じです。

一括してデータマイグレーションするプログラムを書くのが最も工数少なく対応できる方法ですかね…

**Comment by masaki-takano** [comment]
ちょっとしょぼいコードですが、下記で置換できました。

```
function replaceOne(text) {
    return text.replace(/```plantuml([\s\S]*)/, function(match, p1, p2) {
        var v = p1.replace(/```([\s\S]*)/, function(match, p2) {
            return `@enduml${p2}`;
        });
        return `@startuml${v}`;
    });
}

function replaceAll(text) {
    var t1 = text;
    var t2;
    while(true) {
        t2 = replaceOne(t1);
        if (t2 == t1) {
            return t2;
        }
        t1 = t2;
    }
}

db.revisions.find({body: /```plantuml/}).forEach(
    function (e) {
        if (e.body != null) {
            var obj = {};
            obj.body = replaceAll(e.body);
            db.revisions.update({"_id":e._id}, { $set : obj } );
        }
});
```

**Comment by yuki-takei** [comment]
こちらは一旦クローズします。

**Comment by yuki-takei** [comment]
related discussion: https://github.com/weseek/growi/discussions/6324
