### ISSUE TITLE
Bug: 無編集のファイルを編集しようとすると「page_id, body and revision_id are required.」と出力され、更新できない。

### ISSUE THREAD

**Issue by kometchtech** [weseek/growi#7924]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |6.1.8|
|node.js   |18.17.0|
|npm       |9.6.7|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 22H2|
|browser   | Microsoft Edge  115.0.1901.183 (ChromeやFirefox 102 ESRでも同様)|

How to reproduce? (再現手順)
---------------------------

1. process 1
あらかじめ以下のような形でページが存在する
- /work/page1
- /work/page2
- /work/page3

2. process 2
「移動/名前変更」を使用し、以下のような形にする
- /work/tmp/page1
- /work/tmp/page2
- /work/tmp/page2

この時点で、自動的に無編集状態の`/work/tmp`が生成されている

3. process 3

例えば、`/work/tmp`配下のページ一覧を作成すべく、`/work/tmp`を編集する。
※`$lsx()`を挿入するとかなど。

4. process 4
「更新」をクリックすると「page_id, body and revision_id are required.」を表示され、更新できない。

What happens? (症状)
---------------------

- WebUI上では以下のメッセージが表示される
```
page_id, body and revision_id are required.
```
- docker compose logsは以下の出力
```
growi                                 | {"name":"express","hostname":"growi","pid":17,"req_id":"f67b9505-b1ce-4a1b-a75d-e24551794f46","level":30,"msg":"::ffff:172.20.0.1 <-- GET /_api/v3/pages/list?path=%2FTips%2FIPAM_DCIM&page=1 HTTP/1.1 304 - https://****.jp/Tips/IPAM_DCIM Chrome 115.0 Windows 10.0.0 12.427207 ms","time":"2023-07-27T09:54:55.412Z","v":0}
growi                                 | {"name":"express","hostname":"growi","pid":17,"req_id":"39f5121c-b993-4e29-a976-b0cad6305d2a","level":30,"msg":"::ffff:172.20.0.1 <-- GET /_api/pages.updatePost?path=%2FTips%2FIPAM_DCIM HTTP/1.1 200 27 https://****.jp/Tips/IPAM_DCIM Chrome 115.0 Windows 10.0.0 4.958241 ms","time":"2023-07-27T09:54:55.784Z","v":0}
growi                                 | {"name":"express","hostname":"growi","pid":17,"req_id":"e96b07a0-85c1-40fc-92c7-dad01c3f2fd1","level":30,"msg":"::ffff:172.20.0.1 <-- POST /_api/pages.update HTTP/1.1 200 66 https://****.jp/Tips/IPAM_DCIM Chrome 115.0 Windows 10.0.0 8.829129 ms","time":"2023-07-27T09:55:07.538Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

- ページの更新が可能になること
- 

Note
----

- 
-

**Comment by yuki-takei** [comment]
@kometchtech ご報告ありがとうございます。症状を確認しました。修正しますので少々お待ちください。

**Comment by yuki-takei** [comment]
## memo

- https://github.com/weseek/growi/pull/7877/files#diff-743fd750d799d9154a499b3c84849384b3e1dabb99e92f103fe19ed29f5c969cR115 によるデグレ
- revisionId に空文字列が入ることにより、`page-operation` で create ではなく update が走る

**Comment by yuki-takei** [comment]
v6.1.9 リリースをお待ちください。

**Comment by kometchtech** [comment]
ご対応ありがとうございます！
