### ISSUE TITLE
Bug: 差分を表示すると、表示されていた名前とアイコン画像が消える

### ISSUE THREAD

**Issue by k84rc** [weseek/growi#793]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.2|
|GROWI     |3.3.3|
|node.js   |8.14.1|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Google Chrome|
|browser   |71.0.3578.98|

How to reproduce? (再現手順)
---------------------------

1. 更新履歴を表示する
2. 「差分を表示」をクリックする

What happens? (症状)
---------------------

「差分を表示」をクリックした項目、およびその1つ下の項目の
- 名前が消える
- アイコンがデフォルトのものとなって表示される

What is the expected result? (期待される動作)
-------------------------------------------

- 名前、アイコンがそのまま正しく表示される

**Comment by yuki-takei** [comment]
@k84rc こちらは v3.3.0-v3.3.3 で確認できる症状で、v3.3.4 で修正済みだと思われます。
アップグレードしてまだ再現するかどうかご確認いただけますか？

**Comment by k84rc** [comment]
@yuki-takei 3.3.4 にて症状が出ていないことを確認しました。ありがとうございます。
この Issue はクローズいたします。
