### ISSUE TITLE
Bug: Backslash in code display as ￥ symbol

### ISSUE THREAD

**Issue by xuanddlftv** [weseek/growi#794]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |3.2.10-RC|
|node.js   |v8.12.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Window 10|
|browser   |Firefox Quantum 64.0 (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. Create new wiki
1. Add content with code block has backslash inside.

What happens? (症状)
---------------------

- Markdown side
![markdown_backslash_1](https://user-images.githubusercontent.com/35219552/51008829-08413880-1580-11e9-9a49-12a5716a4e16.PNG)
- View side
![markdown_backslash_2](https://user-images.githubusercontent.com/35219552/51008832-0ecfb000-1580-11e9-8e08-42602191b63b.PNG)

What is the expected result? (期待される動作)
-------------------------------------------

- Backslash inside code will display as backslash, not ￥ symbol.

**Comment by mandel59** [comment]
This is common problem called **yen sign probrem** (円記号問題) in Japan.

To render Japanese text in monospace font, by default Firefox choose _MS Gothic_, the most common Japanese monospace font. Unfortunately, most of Japanese fonts for Windows render the character code U+005C as yen sign, because 0x5C has been yen sign in [JIS X 0201](https://en.wikipedia.org/wiki/JIS_X_0201), which is one of Japanese legacy character set.

- Option 1: Change default fonts setting via browser preferences (about:preferences)
    You can change default fonts per font-style per language. See [Change the fonts and colors websites use](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use).
- Option 2: Change language setting to English via GROWI user settings.
    _Courier New_ is used for English monospace text by default. Of course it renders U+005C as backslash.
- Option 3: Set custom header HTML and custom CSS
    Customize style via `/admin/customize`.
    For example, set following custom header HTML and CSS, and you can use _[Inconsolata](https://fonts.google.com/specimen/Inconsolata)_ from [Google Fonts](https://fonts.google.com/) in editor view:
    ```html
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    ```

    ```css
    .CodeMirror {
      font-family: "M+ 1mn", monospace;
    }
    ```

**Comment by mandel59** [comment]
I had misunderstood that the problem is in editor view.
The style of code block also can be ammended with custom CSS.

**Comment by mandel59** [comment]
https://github.com/weseek/growi/blob/2f09d0308f3355484e37dcd0e66f45b33db9b44c/src/client/styles/scss/_override-bootstrap-variables.scss#L31
This line sets MS Gothic.

**Comment by xuanddlftv** [comment]
Sorry, but I do not clearly understand what the solution will be.
Can you explain more, please?

**Comment by yuki-takei** [comment]
#887 will fix this issue.
