### ISSUE TITLE
Bug: HackMD連携でiframeが404になる

### ISSUE THREAD

**Issue by mazrean** [weseek/growi#7955]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 22.04.2 LTS |
|GROWI     |6.1.10|
|node.js   |18.17.0|
|npm       |9.6.7|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11|
|browser   |Chrome 115.0.5790.110|

How to reproduce? (再現手順)
---------------------------

1. `http://example.com/_md`のような一段深いパスで動いているHackMDとGrowiを連携させる
1. 新しくページを作成し「HackMDを開始する」をしてHeckMDでの編集をしようとする
    ![image](https://github.com/weseek/growi/assets/50093633/c743753e-062d-4651-8f1d-76d27a6376df)

What happens? (症状)
---------------------

- iframeが404となり、HackMDで編集できない
    ![image](https://github.com/weseek/growi/assets/50093633/e003f8a5-4393-4182-aa28-a73e4c131ad8)
    - この際、iframeのURLが`http://example.com/_md/_md?both`のようになっている
        ![スクリーンショット 2023-08-05 200746](https://github.com/weseek/growi/assets/50093633/4568d61c-4ffd-4969-b252-67868dd8c7ef)

What is the expected result? (期待される動作)
-------------------------------------------

- HackMDの編集画面がiframeとして埋め込まれ、HackMDで編集できる

Note
----

- 以下の部分でHackMDとの連携でURLの解析に`HACKMD_URI`を利用できていないために、pageIdが誤った値となることが原因の可能性が高いhttps://github.com/weseek/growi/blob/a261a38e08d77e1c58e95d9082556625e7b729fa/apps/app/src/server/routes/hackmd.js#L196-L197
    ![image](https://github.com/weseek/growi/assets/50093633/e9c7b582-8390-450d-98d3-7cec02f31b28)

**Comment by miya** [comment]
GROWI v7.0.0 のリリースに伴い HackMD が廃止されたため、アップグレードしていただくとこちらの問題は再現しなくなると思います。
