### ISSUE TITLE
Bug: 「リンクを知っている人のみ」の閲覧権限が機能しない

### ISSUE THREAD

**Issue by fmy** [weseek/growi#796]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | heroku |
|GROWI     |3.3.3|
|node.js   |8.15.0|
|npm       |6.5.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |全て|
|browser   |全て|

How to reproduce? (再現手順)
---------------------------

1. 「リンクを知っている人のみ」の権限でページ作成
1. ページリンクを別のアカウントに共有
1. 別のアカウントでページを訪問

What happens? (症状)
---------------------

- 正しいリンクを訪問しても閲覧できない
- 「Browsing of this page is restricted」と表示される

What is the expected result? (期待される動作)
-------------------------------------------

- リンク知っている人は閲覧できる

Note
----

- 
-

**Comment by yuki-takei** [comment]
@fmy ご報告ありがとうございます。再現しました。

修正を入れて v3.3.5 としてリリースします。今しばらくお待ちください。
