### ISSUE TITLE
Bug: Minified React error #62 でページの内容が表示されないことがある

### ISSUE THREAD

**Issue by kyoruni** [weseek/growi#8091]
Environment
------------

### Host

- デモサイト https://demo.growi.org/

| item     | version |
| ---      | --- |
|GROWI     |6.2.0|

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Monterey |
|browser   | Google Chrome 116.0.5845.187（Official Build）|

How to reproduce? (再現手順)
---------------------------

1. ページに以下を記載して、保存

```
<img src="image_url" style="max-width: 100px"/>
```

What happens? (症状)
---------------------

- ページに以下が表示される（[デモサイトで作成したページ](https://demo.growi.org/647efdf707f841a79f745f3c)）

```
Something went wrong:
Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

What is the expected result? (期待される動作)
-------------------------------------------

- 記載したスタイルが正しく表示される

Note
----

- `style=""` の箇所を削除すると、正しく表示されるようです
- どのバージョンから発生したのかわからなくなってしまったのですが（すみません）、以前のバージョンではこの書き方でも表示されていました

**Comment by jam411** [comment]
fix https://github.com/weseek/growi/pull/8092

**Comment by jam411** [comment]
報告ありがとうございます！

v6.2.1 で修正版をリリース予定です。

**Comment by kyoruni** [comment]
@jam411 
さっそくのご対応ありがとうございます！
