### ISSUE TITLE
Basic認証を有効にするとユーザ登録できない

### ISSUE THREAD

**Issue by hikaen2** [weseek/growi#814]
Basic認証を有効にするとユーザ登録ができない現象が起きました。
ご報告まで。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 9.7|
|GROWI     |3.3.6|
|node.js   |8.15.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Debian 9.7|
|browser   |Chrome/71.0.3578.98|

How to reproduce? (再現手順)
---------------------------

1. セキュリティ設定 (http://localhost:3000/admin/security) -> Basic認証でID，パスワードを設定して更新ボタンを押す
1. Sign in画面 (http://localhost:3000/login) で，Sign upボタンを押し，User ID, Name, Email, Passwordを入力し，Sign upボタンを押す
1. Sign in画面 (http://localhost:3000/login) で，2.でSign upしたUser name, Passwordを入力し，Sign inボタンを押す

What happens? (症状)
---------------------
- symptom 1
Sign in failure.と表示されてログインできない

- symptom 2
Sign upしたユーザがユーザー一覧画面 (http://localhost:3000/admin/users) に現れない

What is the expected result? (期待される動作)
-------------------------------------------
- Sign upしたユーザでログインできる
- Sign upしたユーザがユーザー一覧画面 (http://localhost:3000/admin/users) に現れる

**Comment by yuki-takei** [comment]
@hikaen2 ご報告ありがとうございます。レスが遅くなってしまい申し訳ないです。

再現を確認しました。次バージョンで修正されるはずです。

ただ、現在サポートされている Basic 認証ですが、近い将来GROWI本体機能から削除しようと考えています。Basic 認証が必要な場合は別途リバースプロキシ等を準備いただくよう、お願いいたします。

**Comment by hikaen2** [comment]
ありがとうございます！
