### ISSUE TITLE
Bug: Move/Duplicate don't work on v3.3.7

### ISSUE THREAD

**Issue by motoisto** [weseek/growi#822]
Environment
------------
### Host
| item     | version |
| ---      | --- |
|OS        |CentOS|
|GROWI     |3.3.7|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   |Chrome|

### 期待される動作
-------------------------------------------
- ページの「移動」操作ができなくなりました。
- 「移動先のページ名」を編集すると「No matches found on title...」という吹き出しが出ます

**Comment by yuki-takei** [comment]
@motoisto ご報告ありがとうございます。再現確認しました。
修正してリリースしますので今しばらくお待ちください。

**Comment by yuki-takei** [comment]
修正完了しました。v3.3.8 リリースをお待ちください。

**Comment by yuki-takei** [comment]
fixed by #823
