### ISSUE TITLE
Bug: iOSで記事閲覧時のナビゲーションバーがスクロール時に開いたり閉じたりを繰り返す

### ISSUE THREAD

**Issue by nxsdev** [weseek/growi#8254]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|Ubuntu        |22.04.2 LTS|
|GROWI     |6.2.3|
|node.js   |18.18.2|
|npm       |9.8.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|iOS       |16.6.1|
|Google Chrome   |119.0.6045.169|

How to reproduce? (再現手順)
---------------------------

1. iPhoneにてChromeで記事を開きスクロールする [GROWI Demo](https://demo.growi.org/)でも再現可能

What happens? (症状)
---------------------

- サブナビゲーションバーが開いたり閉じたりを繰り返す
他バージョンや端末がバラバラのiPhone利用者3名に試してもらったが、全員同様の現象が発生
https://i.gyazo.com/f4c3f9fba1f4fef94191b5a6005fa7d3.mp4

What is the expected result? (期待される動作)
-------------------------------------------

iOSスクロール時の動作の改善
- スクロール時はバーが閉じ、停止時に開くのが本来の想定？と思いますが、判定が正しく行えていないように思います

**Comment by yuki-takei** [comment]
@nxsdev ご報告ありがとうございます。
今月から来月前半あたりでリリースされる v7 ではサブナビゲーションの実装方法が変更されており、この問題は起こらないことを確認しています。

v6 では引き続き同様の事象で煩わしい思いをさせてしまうかもしれませんが、そちらには手を入れない方針でいくつもりです。すみません。
