### ISSUE TITLE
The security-setting API of Growi cannot be invoked with the token.

### ISSUE THREAD

**Issue by kaiseimima** [weseek/growi#8298]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 11|
|GROWI     |6.2.1|
|node.js   |18.16.0|
|npm       |9.5.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Big Sur 11.6|
|browser   |Google Chrome 118.0.5993.117|

How to reproduce? (再現手順)
---------------------------

1. To prepare a workspace for development using devcontainer.
    ```sh 
    mkdir -p ~/Projects/GROWI
    cd ~/Projects/GROWI
    git clone https://github.com/weseek/growi.git
    git clone https://github.com/weseek/growi-docker-compose.git
    ```

1. Launch VSCode and open the weseek/growi repository using the command palette with devcontainer.\
Open the command palette with "Ctrl + Shift + P".\
Select the weseek/growi local repository from "Dev Containers: Open folder in Container..."

1. Launch GROWI using the following command.
    ```sh
    turbo run bootstrap
    cd apps/app
    turbo run dev
    ```

1. To utilize the API, acquire an API Token.\
Access the launched GROWI instance and use the obtained API Token from 'API Token を取得する' in the settings for username, user configuration, and API configuration within the 'setting.py' file.
1. Create a 'python-app' directory and within it, create files named 'setting.py' and 'growiSAML.json' with the following content:。
    ```sh
    mkdir python-app
    cd python-app
    vi setting.py
    vi growiSAML.json
    ```
    ```python
    import requests
    api_token = "from growi site"
    url = 'http://localhost:3000/_api/v3/security-setting/saml?access_token='+api_token
    
    with open('growiSAML.json', 'r') as file:
        data_to_saml = json.load(file)

    res = requests.put(url,json=data_to_saml)
    print(res)
    ```
    ```json
    {
        "entryPoint": "https://growisitename",
        "issuer": "growi",
        "cert": "-----BEGINCERTIFICATE-----\nwriteTheContentsOfTheCertificateHere\n-----END CERTIFICATE-----",
        "attrMapId": "id",
        "attrMapUsername": "username",
        "attrMapMail": "email",
        "attrMapFirstName": "firstName",
        "attrMapLastName": "lastName"
    }  
    ```
1. Send a PUT request to 'security-settings' using an API in Python with below command.
    ```sh
    python3 setting.py
    ```

What happens? (症状)
---------------------

- Requests for GET and PUT to the security-setting API, as documented in GROWI Docs, are not going through, and the following error message is being returned.

```
// When attempting to send a PUT request using Python
<Response [403]>
```

What is the expected result? (期待される動作)
-------------------------------------------

- A <Response [200]> is being returned.

Note
----

- I've identified the cause of the error and I'm prepared to submit a pull request with the fix.
```
apps/app/src/server/routes/apiv3/security-settings/index.js
```
- In the above code, the accessTokenParser is not being passed when sending the PUT request, resulting in a "forbidden" response.

**Comment by yuki-takei** [comment]
@kaiseimima Hi.

You noted:
> In the above code, the accessTokenParser is not being passed when sending the PUT request, resulting in a "forbidden" response.

That's correct, and currently the behavior is as designed.

GROWI has only a rough access control mechanism, so what you can accomplish with the accessTokens you can create in `/me` is intentionally limited.

The security-setting API is implemented to configure GROWI settings from the management screen, and is a restricted set of APIs.

We need to implement [Enhanced Access Token](https://github.com/weseek/growi/discussions/7722) to allow the users to control GROWI more convinient in the future.

**Comment by mit0223** [comment]
> The security-setting API is implemented to configure GROWI settings from the management screen, and is a restricted set of APIs.

The specifications are very disappointing. I think the recent trend is to automate construction with IaC using tools such as ansible. Being able to initialize services only from the web UI has a negative impact on the quality of system construction.
