### ISSUE TITLE
Bug: ページの移動が出来ない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#831]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 18.04.1 LTS|
|GROWI     |3.3.7|
|node.js   |8.15.0|
|npm       |6.4.1|
|yarn       |1.13.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

- Installed plugins:

| package name    | version |
| ------------------ | -------- |
| growi-plugin-lsx | ^2.1.1 |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.2|
|browser   | Chrome 71.0.3578.98 |

How to reproduce? (再現手順)
---------------------------

1.  適当なページ(ex : Test)を作成する。
 一行適当なメッセージ(hoge)等を追記して作成ボタンを押す。
1. ハンバーガーメニューから移動を選択する
（再帰的に移動/リダイレクトのチェックは入れても入れなくてもよい)
1. 元のページとは異なる移動先のページ名(ex: Test2)を指定してrenameボタンを押す。

What happens? (症状)
---------------------
- 何も処理が行われてないようにみえる。
- ダイアログはそのまま表示されている。

What is the expected result? (期待される動作)
-------------------------------------------
- 元のページ(Test)が新しい名前のページ(Test2)に移動する。

Note
----
- 公式のデモサイト(2019/2/8 15:00~16:00頃)でも同様の挙動をすることを確認しています。

**Comment by yuki-takei** [comment]
@hanapage ご報告ありがとうございます。
こちらの事象は #822 と同一で、v3.3.8 で修正されています。アップグレードをお願いします。

**Comment by hanapage** [comment]
Issue見落としてたようで申し訳ないです。
アップグレードありがとうございました。
