### ISSUE TITLE
Bug: /が重複登録される

### ISSUE THREAD

**Issue by 768** [weseek/growi#8337]
Environment
------------
[GROWI Demo](https://demo.growi.org/)

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |6.3.0|
|node.js   |18.19.0|
|npm       |10.2.3|
|yarn      |1.22.19|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows|
|browser   |Google Chrome 120.0.6099.72|

How to reproduce? (再現手順)
---------------------------
1. process 1
/下に「ThisIsATest」という名前で記事を作る。
1. process 2
名前変更で、記事名の初めに<をつける。

What happens? (症状)
---------------------
/として登録されてしまい削除もできない。

What is the expected result? (期待される動作)
-------------------------------------------
名前変更を拒否されるべきだと思います。
また、すでに出来てしまった記事を削除する方法も必要かもしれません。

**Comment by yuki-takei** [comment]
@768 ご報告ありがとうございました。`<>` を含むパスではページを作成できないようにするという修正は完了しました。
v6.3.1 リリースをお待ちください。

> また、すでに出来てしまった記事を削除する方法も必要かもしれません。
こちらに関しては継続協議します。

**Comment by miya** [comment]
次回リリースの v6.3.1 にアップデートしていただくことで既に作成済みの重複した root ページが、サーバー再起動時に `/obsolete-root-page-65b7774486601ab3fdf7de73` (/obsolete-root-page-${page._id}) に自動的にリネームされるようになります。
