### ISSUE TITLE
Bug: ページ移動ダイアログで移動先のページ名を入力するときにポップアップに入力を妨げられる

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#835]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 18.04.1 LTS|
|GROWI     |3.3.8|
|node.js   |8.15.0|
|npm       |6.4.1|
|yarn       |1.13.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

- Installed plugins:

| package name    | version |
| ------------------ | -------- |
| growi-plugin-lsx | ^2.1.1 |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.2|
|browser   | Chrome 72.0.3626.109 |

How to reproduce? (再現手順)
---------------------------

1. 任意のページを開き、右上のメニューから移動を選択する
1. 移動先のページ名フィールドをクリックする

What happens? (症状)
---------------------
- ポップアップが入力フィールドを覆うような位置にあり入力が妨げられる。

![growi_input](https://user-images.githubusercontent.com/2525461/52933156-ac937780-3395-11e9-80d5-fd8eb4b7e393.png)

What is the expected result? (期待される動作)
-------------------------------------------
- ポップアップの上端が入力フィールドの下端より少し下にある。

Note
----
- 複製の方も同様の症状がありました。
- ページ移動そのものはペーストなどでフィールドを書き換えることで可能でした。
- 入力中に一時的にポップアップが消えるタイミングがあるが、再度現れるとまた同じ位置に表示されてしまう。

**Comment by yuki-takei** [comment]
@hanapage ご報告ありがとうございます。再現を確認しました。
次のバージョンで修正しますので今しばらくお待ちください。

**Comment by yuki-takei** [comment]
v3.3.9 で修正される予定です。リリースまで今しばらくお待ちください。

**Comment by hanapage** [comment]
対応ありがとうございました。
