### ISSUE TITLE
Bug: Unportalize が働かない

### ISSUE THREAD

**Issue by sobanayn** [weseek/growi#839]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |RHEL 7.4|
|GROWI     |3.3.9|
|node.js   |8.11.2|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7 Professional 32bit  / Windows 10 Professional 64bit|
|browser   |Chrome  72.03626.109 / ie 11.09600.19266|

How to reproduce? (再現手順)
---------------------------

1. process 1
   記憶が曖昧ですが、
　既存PORTALを複製しRenameしたら
   複製先のページもPORTALとなり既存PORTALと2つのPORTALとなった。

What happens? (症状)
---------------------
- PORTALが2つになり
　片方のPORTALを解除しようとするがUnportalizeボタンを押しても
　PORTALが解除できない

What is the expected result? (期待される動作)
-------------------------------------------
- PORTALを1つにしたい(戻したい)

**Comment by yuki-takei** [comment]
@sobanayn ご報告ありがとうございます。
Unportalize が機能しない問題、手元で再現できました。

次回リリースで修正されるようにしますので、今しばらくお待ちください。

**Comment by yuki-takei** [comment]
ただ気になることとして、再現手順に書いていただいた「既存PORTALを複製」という操作はUI的にできないはずなので、どういう抜け道があるのかは気になるところです…
もし思い出すことができたら追記していただけると助かります。
