### ISSUE TITLE
Bug: 全文検索が働かない

### ISSUE THREAD

**Issue by motoisto** [weseek/growi#842]
Environment
------------
### Host
| item     | version |
| ---      | --- |
|OS        |CentOS|
|GROWI     |3.3.9|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose]|yes|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   |Chrome|

### 期待される動作
-------------------------------------------
- テキスト全文検索ができません
　→ヘッダには反映されています「/_search?q=あいうえお」
- 管理＞全文検索管理＞Build Now
 「Building request is successfully posted.」があっという間に表示されますが、
　状況は変わりません。
- 新規構築したgrowiでも同様です

**Comment by yuki-takei** [comment]
@motoisto ご報告ありがとうございます。

新規構築したGROWIで、インストール直後の状態で全文検索が働かない症状は確認できました。
ただ、管理画面からインデックスビルド後は正常動作しているように見えていて、ご報告いただいた賞状が手元で再現できません。「テキスト全文検索ができません」の部分をもう少し詳しくいただけますでしょうか。(サーバー側ログがあれば尚良し)

よろしくお願いいたします。

**Comment by motoisto** [comment]
再現しないとのことなので、環境依存かもしれません。
再度、確認しますので、本件は取り下げとさせて下さい。
お手数をおかけしました。
