### ISSUE TITLE
Bug: Slack連携ページで設定をリセットできない

### ISSUE THREAD

**Issue by gomagom** [weseek/growi#8429]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |22.04.2 LTS|
|GROWI     |6.2.6|
|node.js   |18.19.0
|npm       |10.2.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11|
|browser   |Google Chrome 121.0.6167.86|

How to reproduce? (再現手順)
---------------------------

1.  管理設定のSlack連携ページ(https://{GROWI_HOST}/admin/slack-integration)にアクセスする
1. `全ての設定をリセット`をクリック
1. モーダルウィンドウが出てくるので，何れかのボタンを押す

What happens? (症状)
---------------------

- モーダルウィンドウ上の全てのボタンが反応しない
- ボタン押下後，ページをリロードしても変更は反映されず
- マウスオーバーは反応するが，クリックイベントが動作していない？

What is the expected result? (期待される動作)
-------------------------------------------

- `リセット`を押下することでモーダルウィンドウが閉じ，全ての設定をリセットした旨を通知するトーストが表示される
- キャンセルやxボタンを押下することで，元のページに戻る

Note
----

- Growi version 6.2.4から6.2.6にアップデートしても同様の症状を確認しました

**Comment by miya** [comment]
v7.0.0 がリリースされたことによってこちらの問題は改善されていることを確認いたしましたので、こちらの issue は close させていただきます。
