### ISSUE TITLE
Imprv: 全文検索時に意図しないページがヒットする事象を改善する

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#845]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 18.04.1 LTS|
|GROWI     |3.3.10|
|node.js   |8.15.0|
|npm       |6.4.1|
|yarn       |1.13.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

- Installed plugins:

| package name    | version |
| ------------------ | -------- |
| growi-plugin-lsx | ^2.1.1 |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.2|
|browser   | Chrome  72.0.3626.119|

How to reproduce? (再現手順)
---------------------------

1. 管理 -> 全文検索管理 画面でBuild Nowボタンを押す (インデックスが作成されているのを確認するため)
1. 検索ワードをどのページのタイトルにも本文にも含まれないような単語、例えば「くぁwせdrftgyふじこlp」等で検索する。このとき検索ワードをダブルクォートで囲まないこと。

What happens? (症状)
---------------------

- 関係のないページが大量にヒットしている。

What is the expected result? (期待される動作)
-------------------------------------------

- 検索結果は[No page found with "くぁwせdrftgyふじこlp"]となる

Note
----

- ダブルクォートで囲んだ場合は、検索キーワードを本文に含んだページのみが表示され、正しい動作をしているように見えます。
- ヒットしないはずの検索ワード(例えばランダムなアルファベット等)を追加するとさらにヒット数が増えました。

**Comment by yuki-takei** [comment]
@hanapage 起票ありがとうございます。
こちらは「現時点では仕様だが改善した方がよいもの」ですね…

クエリ文字列を長めのランダムな文字列にすることで ngram での一致が多くなり、スコアが意図せず高くなってしまう事象となっています。

時間をみつけて調整を入れてみようと思います。

**Comment by yuki-takei** [comment]
v3.4.0-RC で、以下の対策を入れました

* tokenizer の変更によるノイズ除去
    * index 用: ngram -> edge_ngram
    * search 用: ngram -> standard
* クエリ文字列の長さに比例する「最小ヒットスコア(min_score)」を設定することによるノイズ除去

ここからはチューニングになりますが、一旦これで様子見といたします。

**Comment by yuki-takei** [comment]
> クエリ文字列の長さに比例する「最小ヒットスコア(min_score)」を設定することによるノイズ除去

いろいろ実験したが、これは本来ヒットすべきドキュメントまで除去する確率が上がってしまうので revert する…

refs: 7c6d8e13
