### ISSUE TITLE
Bug: Crowi Classic Layout でコメントが投稿できない

### ISSUE THREAD

**Issue by hide-o-mvd** [weseek/growi#847]
Crowiより移行し、日々活用させていただいております。

Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 4.9.110|
|GROWI     |3.3.8|
|node.js   |8.15.0|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 72.0.3626.119|

How to reproduce? (再現手順)
---------------------------

1. 「管理」→「カスタマイズ」→Crowi Classic Layoutを選択
1. 任意のページを開く
1. 右のサイドバーを開く
1. Comments欄に任意のコメントを記入し、「Comment」ボタンを押す

What happens? (症状)
---------------------

- 「Comment」ボタンを押しても反応せず、コメントが投稿されません。

What is the expected result? (期待される動作)
-------------------------------------------

- 「Comment」ボタンを押下することによりコメントが投稿される。

Note
----

-  Growi Enhanced Layoutに戻せば、Markdown有りでコメント機能が正常動作していることは確認済です。
- Classic LayoutではMarkdownは無しでもよいので、まずは互換性を維持していただけるとありがたいです。

**Comment by yuki-takei** [comment]
@hide-o-mvd ご報告ありがとうございます。再現確認しました。
これいつからできなくなっていたのか…結構前のような。

修正して次リリースに入れます。しばらくお待ちください。
