### ISSUE TITLE
Bug: 編集/削除できないポータルページが生成される

### ISSUE THREAD

**Issue by kurubushi** [weseek/growi#850]
Environment
------------

### Host

https://demo.growi.org/ 2月28日 21時現在

### Client

| item     | version |
| ---      | --- |
|OS        | Arch Linux |
|browser   |Firefox 65.0.1 (64 ビット)|

How to reproduce? (再現手順)
---------------------------

1. `/user/kurubushi/test2` を生成
1. `/user/kurubushi/test2` を `/user/kurubushi/test2/` に移動

What happens? (症状)
---------------------

- `/user/kurubushi/test2/` がポータルページとなる
- `/user/kurubushi/test2/` にはアクセスできず，編集および削除もできない (`/user/kurubushi/test2` に転送されてしまう)

What is the expected result? (期待される動作)
-------------------------------------------

-  GROWI Simplified Behavior のとき，ページの移動はその宛先の末尾 `/` をトル．
- ポータルページを作成したい場合には Crowi Classic Behavior を使う旨の Warning が出てくれると親切かもしれない．

Note
----

上記の方法で Demo のほうに，ポータルページを作成してしまったので，削除しておいてほしいです．お手数かけます．

- https://demo.growi.org/user/kurubushi/test/
- https://demo.growi.org/user/kurubushi/test2/

**Comment by yuki-takei** [comment]
@kurubushi ご報告ありがとうございます。再現確認しました。

今まで「GROWI Simplified Behavior でも誤ってポータルページを作ってしまう(そして消せない)」という報告がたまにあって、どういう操作をしているんだろうと長らく謎だったのですが、おかげさまで原因特定できました。Move/Duplicate で起こるんですね。

## 修正方針
ポータルはそもそも Move/Duplicate で作れなくていいものだと思うので、どちらの Behavior 設定でも末尾のスラッシュを削除したパスに Move/Duplicate するように修正しようと思います。
v3.4.0 に反映させる予定です。今しばらくお待ちください。

## Note
Demo のページ削除は、リリースしてから追々やっておきます。

**Comment by kurubushi** [comment]
早速の修正ありがとうございます．master を pull して手元で試してみましたが，まだ不具合があったので報告します．

1. `/test/test1` を生成する
1. `/test/test1//` に移動する
1. `/test/test1/` というポータルページが生成される．

移動先パスの末尾 `/` の数が
* 1 つの場合は「新しいページが既に存在しています」でエラー，
* 3 つ以上の場合は「Invalid path」でエラー
になりますが，ちょうど 2 つの場合が通ってしまっているようです．

**Comment by yuki-takei** [comment]
そうか、そういうケースが…考慮が足りてなかった。
対応します。動作確認ありがとうございます。

**Comment by kurubushi** [comment]
ページ作成時のパス整形のメソッドなどがあれば，それを再利用するのがよいかもですね．
現状，例えば `/test///test2` は作成できるけれど，`/test///test2` には Invalid Path で移動できないなどもちょっと気になるので．

**Comment by yuki-takei** [comment]
@kurubushi 

https://github.com/weseek/growi/issues/850#issuecomment-468581467 で報告いただいていたケースに対応しました。また、ページ作成時(not found ページへの遷移時)も同じロジックでパスのチェックを行い、invalid の場合は forbidden page に飛ばすようにしました。

もしお暇がありましたら master ブランチで動作を見ていただけると助かります。

**Comment by kurubushi** [comment]
修正ありがとうございます．気になっていたところが修正されたので嬉しいです．master の動作確認を思い付く限り試してみましたが，不具合等なく大丈夫だと思います :+1:
