### ISSUE TITLE
「ユーザー登録時のメール認証」を有効時に「Activation」画面で「作成」ボタンをクリックしても無反応

### ISSUE THREAD

**Issue by funakura** [weseek/growi#8510]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |6.3.1|
|node.js   |18.19.0|
|npm       |10.2.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome バージョン: 121.0.6167.185（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. ローカルPCにHostファイルで設定、ホスト名を設定
2. ローカルPCにNginxでを設置(HTTPS)
3. ローカルPCにDockerでGrowiをインストール
4. 管理者ユーザを作成
5. 「セキュリティ設定」-「ID/Pass」-「ユーザー登録時のメール認証」を有効化
6. [ホスト名]/login#registerにアクセス
7. メールアドレスを入力して「作成」ボタンを押す（管理者ユーザとは別ユーザ）
8. 「[GROWI] User Activation」受信
9. メール記載のURLにアクセスする
10. 必要事項を記入
11. 「作成」ボタンをクリックする。

What happens? (症状)
---------------------
「作成」ボタンをクリックしても無反応
（Dockerのコンソールを見ても、GrowiのLog出力に変化無し。）

What is the expected result? (期待される動作)
-------------------------------------------
「作成」ボタンをクリックしてユーザ登録が完了する。

以上、よろしくお願いします。

**Comment by hiromu-ta** [comment]
対応ストーリー：https://redmine.weseek.co.jp/issues/144137

**Comment by yuki-takei** [comment]
v7.0.3 以降で修正されました
