### ISSUE TITLE
[7.0.0] Authentik でOIDC ログインが動作しない

### ISSUE THREAD

**Issue by eternity1984** [weseek/growi#8644]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Synology DSM 7.2.1 |
|GROWI     |7.0.0|
|node.js   |20.11.1|
|npm       |10.2.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes (downgrade to MongoDB 4.4)|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 14.4.1 |
|browser   |Safari 17.4.1, Chrome 123.0.6312.59|

How to reproduce? (再現手順)
---------------------------
Authentik [2024.2.2](https://goauthentik.io/docs/releases/2024.2) でプロバイダおよびアプリケーション設定を行い、 ID/PASSログインでGrowiにもOIDC設定を行う。
その上で、ログアウト状態から [OIDC でログイン] を押下する。

### Authentik 構成 / OAuth2 Provider

| name| value |
|---|---|
|name| growi|
|Authorization flow|implicit|
|Client type|Confidential|
|Client ID|growi|
|Client Secret| {REDACTED}|
|Redirect URIs|https://growi.local/passport/oidc/callback|
|Advanced protocol settings|(default)|

### Growi 構成

| name| value |
|---|---|
|provider|authentik|
|Issuer host|https://authentik.local/application/o/growi|
|Client ID|growi|
|Client Secret| {REDACTED}|
| (attrmap) identifier |sub|
| (attrmap)username |preferred_username|
|(attrmap)name|name|
|(attrmap)email|email|

What happens? (症状)
---------------------
**7.0.0** では Authentik による OIDC ログインが機能しない。
Authentik の認証ページに飛ばず、Authentik にログイン状態であっても Growi にはログインできない。
（Authentik 側にはリクエストも来ていない）

同じ docker-compose.yml を用いて、イメージを **6.3.2** に変更すると、Authentik でログインできる。

What is the expected result? (期待される動作)
-------------------------------------------

- 7.0.0 でも Authentik による OIDC ログインができる。

もしかしたら、KeyCloak 以外はサポート対象外なのかもしれませんが、
よろしくお願いいたします。

**Comment by yuki-takei** [comment]
v7 のログイン画面のバグでした。ご報告ありがとうございます。すぐ修正に入ります。

**Comment by yuki-takei** [comment]
修正完了しました。v7.0.1 リリースをお待ちください。

**Comment by eternity1984** [comment]
@yuki-takei 
先日は、修正対応ありがとうございました。
v7.0.1 と入れ替えてみましたが、まだ OIDC ボタンからログインができません。
こちらで何か確認・協力できることがあれば、お申し付けください。

**Comment by eternity1984** [comment]
申し訳ありません！私の確認間違いのようで、使えるようになっておりました。ありがとうございます。
（今回は、内部DNSに切り替えた関係でした）
