### ISSUE TITLE
[7.0.0] Azure Entera ID SAMLでログインできない

### ISSUE THREAD

**Issue by funakura** [weseek/growi#8647]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |7.0.0|
|node.js   |20.11.1|
|npm       |10.2.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11|
|browser   |Google Chrome 123.0.6312.60|

How to reproduce? (再現手順)
---------------------------
docekr-compose.ymlでSAML設定を記述
同一設定・同一DBデータ

What happens? (症状)
---------------------
Growi v6.3.1はSAMLでログインできる。
Growi v7.0.0はSAMLでログインでできない。

DocekrでGrpowiのログを見ても、idpに接続している気配がない。
ログイン画面でSAMLボタンを押すと'/passport'に遷移する。

※Azure Entera ID側は未調査

What is the expected result? (期待される動作)
-------------------------------------------

Growi v7.0.0はSAMLでログインできる。

**Comment by yuki-takei** [comment]
v7 のログイン画面のバグでした。ご報告ありがとうございます。すぐ修正に入ります。

**Comment by yuki-takei** [comment]
修正完了しました。v7.0.1 リリースをお待ちください。

**Comment by funakura** [comment]
v7.0.1でSAMLログインできることを確認しました
