### ISSUE TITLE
Bug: Cannot create a new user when SAML and ABLC rule is enabled

### ISSUE THREAD

**Issue by skomma** [weseek/growi#8650]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |6.2.x ~|

How to reproduce? (再現手順)
---------------------------

1. Enable SAML and ABLC rule
1. Login with SAML
    * The login user to be used must not satisfy ABLC rules.

What happens? (症状)
---------------------

- `/passport/saml/callback` endpoint doesn't respond anything
    - When this situation occurs, no error message has been output

What is the expected result? (期待される動作)
-------------------------------------------

- `/passport/saml/callback` endpoint responds valid content.

**Comment by hiromu-ta** [comment]
対応ストーリー：https://redmine.weseek.co.jp/issues/144138
