### ISSUE TITLE
Bug: slide:trueのGROWIスライド表示で､drawioの図が文字の羅列になる

### ISSUE THREAD

**Issue by 768** [weseek/growi#8662]
Environment
------------

| item     | version |
| ---      | --- |
|OS        | Uubuntu23.04 |
|GROWI     |6.3.3-RC.0|
|node.js   |18.16.0|
|npm       |9.5.1|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

注: v7デモサイトでも再現します｡ https://demo.growi.org/6531ea27853125fc8831eb85

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu23.04|
|browser   |Chrome 123.0.6312.86（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. YAMLフロントマターで slide:trueを指定
2. drawioの図を記述
3. 保存

What happens? (症状)
---------------------
図が表示されず､生のdrawio文字列が表示される｡

What is the expected result? (期待される動作)
-------------------------------------------
図が表示される｡
(GROWI DOCSの [プレゼンテーション機能を使う](https://docs.growi.org/ja/guide/features/presentation.html#growi-%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%88%E3%82%99))の記述
｢GROWI で対応している Math、Mermaid、draw.io などが表示できます。｣ より

Note
----
mermaidは正常に図が表示される｡全画面プレゼンではdrawioは正しく表示される｡

**Comment by yuki-takei** [comment]
https://wsgrowi.slack.com/archives/C4V5ZG4UC/p1712736698294699

> Growi のプレゼンテーション・スライドにおいてViewに数式が表示されないといった事例が発生しました。
> プレゼンテーションモードにする or そもそもスライドじゃなくすると見えるのですが、作成しながら数式が確認できないのも不便かと感じております。原因、あるいは対処法についてご存知でしたらご教示いただけますと幸いです。
> 以下に導入ソフト、動作確認済みのバージョン、markdownを記載いたします。他に必要な情報あればご返信ください。
> 恐縮ですがよろしくお願いいたします。
> 
> ソフトウェア：動作確認済みのバージョン
> 　dockerize：dockerize-linux-amd64-v0.6.1.tar
> 　HackMD：hackmd_1.3.0-alpine.tar
>  　jetty：jetty_v1.2021.12.tar
> 　mariadb：mariadb_10.3.tar
> 　analysis-icu：analysis-icu-7.17.1.zip
> 　analysis-kuromoji：analysis-kuromoji-7.17.1.zip
> （例：markdownを表示します。）
> 
> ```
> ---
> slide : true
> ---
> 
> ## title
> 
> - text $y = x$ text
> 
> text
> 
> $$
> y = x
> $$
> 
> text
> ```

**Comment by hiromu-ta** [comment]
対応ストーリー：https://redmine.weseek.co.jp/issues/144087

**Comment by yuki-takei** [comment]
v7.0.4 で修正
