### ISSUE TITLE
3.3.x以前でAWS S3にアップロードしたattachmentが正しく表示されない

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#8674]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04|
|GROWI     |6.3.2|
|node.js   |18.20.0|
|npm       |10.5.0|
|Using Docker|yes (k8s)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11|
|browser   |Google Chrome 123.0.6312.86|

How to reproduce? (再現手順)
---------------------------

1. v3.3以前のGROWIでアップロード先をAWS S3に設定
1. attachmentをアップロード
1. GROWIを更新
1. ファイルの配信方法を「リダイレクト」に設定
1. attachmentを表示 (`/attachment/{ObjectId}` にアクセス)

What happens? (症状)
---------------------

- S3にてNoSuchKeyエラーが発生
  - 誤ったobject keyでS3の署名付きURLが発行される
  - MongoDB上の `temporaryUrlCached` が `https://{bucket-name}.s3.{region-name}.amazonaws.com/attachment/{fileName}`
    ```
    mongodb:PRIMARY> db.attachments.find({"_id": ObjectId("59ba4a7b2193dc001d821989")}).pretty()
    {
            "_id" : ObjectId("59ba4a7b2193dc001d821989"),
            "fileFormat" : "image/png",
            "fileName" : "33bc391b60dc9ea586db35ccb114d561{reducted}.png",
            "originalName" : "{reducted}.png",
            "filePath" : "attachment/59ae6637434223001e607981/537cb505609ea62e12867ff3797798ab.png",
            "creator" : ObjectId("59ae6637434223001e60797f"),
            "page" : ObjectId("59ae6637434223001e607981"),
            "createdAt" : ISODate("2017-09-14T09:23:07.204Z"),
            "fileSize" : 14638,
            "__v" : 0,
            "temporaryUrlCached" : "https://company-crowi-files.s3.ap-northeast-1.amazonaws.com/attachment/33bc391b60dc9ea586db35ccb114d561{reducted}.png?{reducted}",
            "temporaryUrlExpiredAt" : ISODate("2024-04-03T14:25:59.745Z"),
            "attachmentType" : "WIKI_PAGE"
    }
    ```

What is the expected result? (期待される動作)
-------------------------------------------

- v3.3以前でアップロードしたattachmentが正しく表示される
  - 正しいobject keyでS3の署名付きURLが発行される
  - MongoDB上の `temporaryUrlCached` が `https://{bucket-name}.s3.{region-name}.amazonaws.com/attachment/{filePath}`

Note
----

- GROWI 4.2.20では正常に動作しているように見えるが、事象が発生するようになったバージョンは未調査
  - 手元の環境で、4.5.xや5.1.xがすぐには上手くビルドできず…
- `getFilePathOnStorage` にconsole.logを仕込んだ限りでは、`if (attachment.filePath != null)`がfalseになっている
  - https://github.com/weseek/growi/blob/v6.3.2/apps/app/src/server/service/file-uploader/aws.ts#L81-L92

**Comment by shield-9** [comment]
`attachmentSchema` にfilePathを追加したところ、期待通りの挙動が確認できました。
https://github.com/shield-9/growi/commit/f44dc4a4e93d23107abb6ca92f00898dca63dc10

ドキュメントの記載が漏れているだけで、不具合ではなく、GridFSと同様の仕様変更があったのでしょうか？
https://docs.growi.org/ja/admin-guide/upgrading/63x.html#%E5%BB%83%E6%AD%A2-v3-3-%E4%BB%A5%E5%89%8D%E3%81%A6%E3%82%99%E5%88%A9%E7%94%A8%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%9F-mongodb-gridfs-%E7%94%A8%E3%81%AE%E3%82%A8%E3%83%B3%E3%83%88%E3%82%99%E3%83%9B%E3%82%9A%E3%82%A4%E3%83%B3%E3%83%88%E3%82%92%E5%89%8A%E9%99%A4

**Comment by yuki-takei** [comment]
遠い昔のことで記憶が定かではないですが…
仕様変更によってカバーできていないケースがあったのかもですね

パッチの内容見てから考えたいので出していただけると助かります
