### ISSUE TITLE
[7.0.1]アプリ設定のサイト名、コンフィデンシャルの入力時に変換途中の文字が残る

### ISSUE THREAD

**Issue by kawapoo** [weseek/growi#8706]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.4 LTS|
|GROWI     |7.0.1-RC.0|
|node.js   |20.12.0|
|npm       |10.5.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Microsoft Edge 123.0.2420.81|

How to reproduce? (再現手順)
---------------------------

1. Windows標準IMEで日本語入力状態で、アプリ設定のサイト名/コンフィデンシャル表示に入力する

What happens? (症状)
---------------------

- 入力途中の文字が残る
例えば「あいう」と入力したい場合、「あ」→「ああい」→「ああいあいう」というように、入力途中の文字が残っていく

What is the expected result? (期待される動作)
-------------------------------------------

- 入力途中の文字が残らず、変換までできる

Note
----

-

**Comment by hiromu-ta** [comment]
https://redmine.weseek.co.jp/issues/143954 で修正予定
