### ISSUE TITLE
DRAWIO_URI がサーバールートでない場合、viewer.min.js の URL が正しく生成されず draw.io の図が表示できない

### ISSUE THREAD

**Issue by yasumichi** [weseek/growi#8769]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu-22.04.4-live-server-amd64|
|GROWI     |7.0.2|
|node.js   |20.12.2|
|npm       |10.5.0|
|yarn      |1.22.22|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows|
|browser   | Firefox developer 126.0b5 |

How to reproduce? (再現手順)
---------------------------

- DRAWIO_URI を http://hostname:8080/draw/ にして起動

What happens? (症状)
---------------------

- ページの編集により draw.io の埋め込みエディタは使用可能
- 編集完了後、draw.io の図が表示されない  

What is the expected result? (期待される動作)
-------------------------------------------

- draw.io の図が表示できること  

Note
----

[apps/app/src/components/Script/DrawioViewerScript.tsx](https://github.com/weseek/growi/blob/bcca30bf781fb3658f6c3ab06ca05c7216cddf2e/apps/app/src/components/Script/DrawioViewerScript.tsx#L18) にて

```ts
        src={(new URL('/js/viewer.min.js', rendererConfig.drawioUri)).toString()}
```

のように viewer.min.js の場所を決定していますが、実際に開発者ツールで以下のスクリプトを実行したところ、期待される URL と異なる結果となりました。

```
new URL('/js/viewer.min.js', 'http://hostname:8080/draw/').toString() 
"http://hostname:8080/js/viewer.min.js" 
```

期待されるURL: `http://hostname:8080/draw/js/viewer.min.js`

**Comment by yuki-takei** [comment]
@yasumichi 修正完了しました。次回リリースをお待ちください。
