### ISSUE TITLE
編集画面においてエディタのキーバインドを Vim にした際、入力モードがすぐに終了してしまう。

### ISSUE THREAD

**Issue by yasumichi** [weseek/growi#8814]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 24.04(WSL) |
|GROWI     |7.0.4|
|node.js   |20.13.1|
|npm       |10.5.2|
|yarn      |1.22.19|
|Using Docker|yes
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*
[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 |
|browser   | Firefox Developer Edition 127.0b1 、Google Chrome 124.0.6367.202 |

How to reproduce? (再現手順)
---------------------------

1. 任意のページを編集
1. エディタ設定→キーマップ→Vim
1. ノーマルモードにて`i`などで入力モードに移行

What happens? (症状)
---------------------

1文字入力できる場合もあるが、カーソルがすぐにノーマルモードに戻ってしまう

What is the expected result? (期待される動作)
-------------------------------------------

- Esc キーを押すなど意図的にノーマルモードへ戻る以外は、入力モードが継続されるのが望ましい。 

Note
----

-  [本家のデモ](https://codemirror.net/5/demo/vim.html)では問題なし
- GROWI 7.0.2 でも同様

**Comment by yasumichi** [comment]
v7.0.11 で問題が解消していることを確認しました。

**Comment by yuki-takei** [comment]
ありがとうございます！クローズします
