### ISSUE TITLE
Feature: Support OpenID Connect authentication

### ISSUE THREAD

**Issue by yaamai** [weseek/growi#893]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | ArchLinux |
|GROWI     |3.4.2|
|node.js   |8.15.1|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | ArchLinux |
|browser   | Chromium 73.0.3683 |

How to reproduce? (再現手順)
---------------------------

What happens? (症状)
---------------------

What is the expected result? (期待される動作)
-------------------------------------------
- Authenticate the user with custom OpenID Connect Provider (OP) like keycloak, hydra.
- Support configuration parameter like below.
    - issuer hostname
    - client id
    - client secret
    - attribute name mapped to username
    - attribute name mapped to mail address
    - attribute name mapped to userid (in growi user DB)

Note
----
-

**Comment by yuki-takei** [comment]
@yaamai Thank you for your contribution about #997!
Please wait the next release.
