### ISSUE TITLE
Improvement: コメントのauthorやアバターのツールチップに「表示名」を表示してほしい

### ISSUE THREAD

**Issue by tak-ngs** [weseek/growi#901]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |rancher os|
|GROWI     |3.4.2|
|node.js   | - |
|npm       | - |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |ubuntu 18.04|
|browser   |google chrome 73|

What happens? (症状)
---------------------

- コメント欄やアバターのツールチップにusernameが表示される

What is the expected result? (期待される動作)
-------------------------------------------

- `name` (表示名)が表示される

Note
----

社内にてGrowiをLDAP連携して使っています。
Growiのログインに使用している弊社のLDAPのidは機械的に割り振られた数字であり、これを表示してもユーザの判別が困難であるためです。

 `username`と`name`の併記でも可です。

**Comment by yuki-takei** [comment]
@tak-ngs ご要望ありがとうございます。検討します。

**Comment by yuki-takei** [comment]
@tak-ngs 実装完了しました。次回リリースをお待ちください。
