### ISSUE TITLE
コメントが入力できない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#905]
Environment
------------

### Host
| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 18.04.1 LTS|
|GROWI     |3.4.3|
|node.js   |10.15.3|
|npm       |6.4.1|
|yarn       |1.15.2|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

- Installed plugins:

| package name    | version |
| ------------------ | -------- |
| growi-plugin-lsx | ^2.1.4 |

### Client

| item     | version |
| ---      | --- |
|OS        | macOS 10.14.4|
|browser   | Chrome  72.0.3626.119|

How to reproduce? (再現手順)
---------------------------

1. 任意のページを開く
2. 画面下のAdd Commentボタンを押す

What happens? (症状)
---------------------

- ボタンを押すとAdd Commentボタンが消える
- ページをリロードすると再びAdd Commentボタンが出てくるが結果は同じ

What is the expected result? (期待される動作)
-------------------------------------------

- コメント入力フォームが出てコメントが入力/送信できる

Note
----

- コメント機能は今回初めて使おうとしたので既存のコメントがあった場合どうなっているかはわからないです。
- Mac版のFirefoxやWindows版のChromeでも同様の現象を確認しました。

**Comment by hanapage** [comment]
以前のissueにレイアウトによってコメントできない件があったと思いますので使っているレイアウト情報を追記します。他、カスタムスクリプトなどは使用していません。

- GROWI Enhanced Layout

**Comment by yuki-takei** [comment]
@hanapage ご報告ありがとうございます。手元で再現しました。
修正版リリースまで今しばらくお待ちください。

**Comment by hanapage** [comment]
ご対応ありがとうございました！
