### ISSUE TITLE
コメントが削除できない

### ISSUE THREAD

**Issue by Akira-haruno** [weseek/growi#9054]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |x.y.z|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes/no|
|Using [growi-docker-compose][growi-docker-compose]|yes/no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

※デモ環境で現象が確認できます。
https://demo.growi.org/

### Client

| item     | version |
| ---      | --- |
|OS        |Windows11|
|browser   |GoogleChrome　バージョン: 127.0.6533.122（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. process 1　デモサイトの[Add a comment] ボタンからコメントを追加
1. process 2　コメント右上の×ボタンを押下。
1. process 3　【Delete comment?】のポップアップから【Delete】をボタンを押下すると
　　　　　　　画面が真っ白になり、そのまま進まなくなります。
　　　　　　リロードしてもコメントは残ったままです。
　　　　　　こちらはバグになりますでしょうか？
　　　　　　バグだとしたら、今後のアップデートで修正予定はありますか？
　　　　　　社内導入しようと検討しているため、ご確認いただけますと幸いです。

　　　　　　※なお、社内でテストとしてビルドした際も、同様の事象が再現確認できました。
　　　　　　詳しいバージョン情報は、今は会社にいない為、書くことが出来なく恐縮ですが、
　　　　　　公式で用意されていますデモ環境でも事象が再現されているように見受けられますので、
　　　　　　ご確認下さい。

**Comment by yuki-takei** [comment]
ご報告ありがとうございます。少なくとも最新版の v7.0.18 で再現したことを確認しました。
修正次第リリースしますのでしばらくお待ちください。
