### ISSUE TITLE
Feature: Markdownでautolink記法を有効にしてほしい

### ISSUE THREAD

**Issue by kmyk** [weseek/growi#908]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.2 LTS|
|GROWI     |3.4.2|
|node.js   |6.4.1|
|npm       |1.13.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

備考: XSS(Cross Site Scripting)対策設定として「XSSを抑制する」は `ON` かつ「おすすめ設定」のホワイトリストを利用

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.2 LTS|
|browser   |Google Chrome 73.0.3683.86 (Official Build) (64-bit)|
|browser   |Firefox 66.0.3 (64-bit)|

How to reproduce? (再現手順)
---------------------------

1. 記事の内容を以下のように編集して保存する。
    ```
    <https://example.com/>
    ```

What happens? (症状)
---------------------

- 何も表示されない

What is the expected result? (期待される動作)
-------------------------------------------

- <https://example.com/> というリンク (`<a href="https://example.com/">https://example.com/</a>` に相当する結果) が表示される

Note
----

- エディタ側ではこのautolinkを認識してハイライトしています
- CommonMark における仕様は https://spec.commonmark.org/0.16/#autolinks です
- 新規に編集する場合はなくても問題にはなりませんが、他で書いた文章をGROWIの上に移す場合にはこれがあるとうれしいです

**Comment by yuki-takei** [comment]
@kmyk ご要望いただきありがとうございます。
v3.4.5 で対応予定です。リリースまで今しばらくお待ちください。
