### ISSUE TITLE
[6.3.4]データ移行実行後、一部の記事で500 Internal Server Error.が発生する

### ISSUE THREAD

**Issue by sankyakuT** [weseek/growi#9085]
Environment
------------

### Host(Source)

| item     | version |
| ---      | --- |
|OS        |Ubuntu 24.04|
|GROWI     |6.3.4|
|node.js   |18.17.1|
|npm       |9.6.7|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Host(Destination)

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |6.3.4|
|node.js   |18.20.2|
|npm       |10.5.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 Pro|
|browser   |chrome 128.0.6613.120|
|browser   |edge 128.0.2739.67 |

How to reproduce? (再現手順)
---------------------------

移行元をA環境・移行先をB環境と呼称します。
1. 「データ移行」機能を用いて、A環境からB環境にデータをインポートする。
1. B環境のGrowiに他のPCからアクセスする。
1. B環境で記事を開く。

What happens? (症状)
---------------------

- 一部の記事を開こうとすると500 Internal Server Error.が発生する。

What is the expected result? (期待される動作)
-------------------------------------------

- 記事にアクセスできること。

Note
----

- エラーが発生する記事は全体の半分程度。
- エラーが発生する記事に共通点は見当たらず、50文字程度の文字列のみ記述した記事でも発生する。
- 閲覧権限を設定したページが移行できないことが過去にあり、本件時点では閲覧権限を全て削除済み。
- ![500](https://github.com/user-attachments/assets/b6f9f425-2cc3-482e-9a99-ca32f3c66773)

**Comment by yuki-takei** [comment]
データ移行機能について、申し訳ないのですがかなり長い間インポート機能の方に長らくバグがありました。(エクスポート機能は正常)
最近マージされた https://github.com/weseek/growi/pull/8994 で修正されたので、そちらの機能を使って移行するのであれば環境A/B共に 7.0.17 移行にアップグレードしてからの方がいいと思います。

バージョンをそこまで上げられないのであれば、移行手段として mongorestore/mongodump を使う方法を推奨します。

弊社謹製のバックアップツールもあります。
https://github.com/weseek/awesome-database-backup

**Comment by sankyakuT** [comment]
@yuki-takei さん。初めまして。
お返事ありがとうございます。
また、情報が不足しており申し訳ございません。

インポート機能の方に長らくバグがあり最近修正されたとのこと承知しました。
環境A/B共に 7.0.18にアップグレードしてから再度移行を試してみようと思います。

**Comment by sankyakuT** [comment]
お世話になっております。

環境A/B共に 7.0.18にアップグレードしてから再度移行を試してみました。
結果はうまくいきませんでした。

環境Aで移行を実行したところ、
mongodbの移行がいつまでも終わらず、スピナーがずっと回っている状態になりました。
この状態で環境Bにアクセスすると、環境Aと同じユーザーでログインはできましたが、
PageTreeに「PageTree機能は現在使用できません。」と表示され記事が表示されない状態になりました。

環境Bの設定画面を開いたところ「公開されているページに 古い v4 互換形式のものが存在します。ページツリーや簡単なリネームなどの新機能を利用するには、全てのページを v5 互換形式に変換してください。linkv5 互換形式 へ変換」
と表示されており、v5への変換を試そうとしましたがボタンが見当たらず、こちら試せていません。

この状態で環境B側でサービスを落とすと
環境A側に「GROWI アーカイブファイルの転送に失敗しました。」というメッセージが表示されました。

また本件とは直接関係があるわけではないのですが、
環境Aで全文検索管理を確認するとインデックスの状態が「リビルド中または破損しています」だった為
インデックスのリビルトを試したところ、
こちらも622件中100件まで処理されたとことで処理が進まなくなるという事がありました。

以上の事からバグデータの様なものが存在しており、それが移行の邪魔をしているのではと考えています。
mongodbのログなどを確認してみましたが、私のスキルでは問題を発見することはできませんでした。

今回はツールによる移行は諦め、
手動で記事やファイルを移そうと思います。
