### ISSUE TITLE
同じバージョンにも関わらずエクスポートしたアーカイブをインポートできない

### ISSUE THREAD

**Issue by kota65535** [weseek/growi#9188]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | MacOS Sonoma|
|GROWI     |5.1.11|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |MacOS Sonoma||
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. アーカイブをエクスポート
1. 同じバージョンのGrowiを起動
1. アーカイブをインポート

What happens? (症状)
---------------------

-「現在のGROWIとアップロードしたデータのバージョンが違います」と表示される

What is the expected result? (期待される動作)
-------------------------------------------

- インポートが成功する

**Comment by yuki-takei** [comment]
@kota65535 Issue 作成ありがとうございます。ご迷惑をおかけして申し訳ないです。

当該事象とは別の問題ですが、GROWI v5 リリース以降、インポート機能が長らく正常に機能していないということが2024年の8月くらいに判明しました。エクスポートデータに問題はないが、それをインポートする機能がずっと壊れ続けていた、という状態でした。

以下の PR で修正され、v7.0.17 以降は正常動作するのではないかと思います。
https://github.com/weseek/growi/pull/8994

v5系、v6系に関しては数多くのリリースがありますが、いずれもカレントバージョンではないため上記の問題に関しては修正しないという決定をしています。

そのためご報告いただいたバージョンの v5.1.11 に関して、仮に「現在のGROWIとアップロードしたデータのバージョンが違いますと表示される」問題を解決したとしてもインポート機能自体が先の理由で使い物にならないため、やはりこちらの症状も改修を見送りたいと思います。

## ワークアラウンド
バックアップとリストア、あるいはサーバーリプレースに際しては、MongoDB のデータをそのまま移す mongodump/mongorestore を使うのが最も手堅い方法になります。そちらを試していただきますようお願いいたします。
