### ISSUE TITLE
Growiを複数立てたときのCookieの挙動

### ISSUE THREAD

**Issue by Uta-member** [weseek/growi#9250]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | AmazonLinux2|
|GROWI     |7.0.21|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

How to reproduce? (再現手順)
---------------------------

1. Growiを1つのサーバに複数立てる（公式の手順通りでポート番号3000、3001で作成）
2. 3000番にログインする
3. 3001番でページ遷移する
4. 3000番がログアウトされる

What happens? (症状)
---------------------
Cookieに保存されているconnect.sidのDomainがポートごとに分かれておらず全て共通になっており、他のGrowiでページ遷移などが起こるとCookieの内容が変わってしまいログアウトされてしまう。

What is the expected result? (期待される動作)
-------------------------------------------
ポートごとにCookieを分けて、複数のGrowiで別々の認証状態を維持できるようにしてほしい。
もしくは、こちらの設定ミス等あればご指摘いただきたいです。

**Comment by yuki-takei** [comment]
@Uta-member 環境変数の `SESSION_NAME` を変えるとどうでしょうか？

https://docs.growi.org/ja/admin-guide/admin-cookbook/env-vars.html

**Comment by Uta-member** [comment]
@yuki-takei 
ご回答いただきありがとうございます。
docker-compose.ymlに環境変数を設定して再起動したら正しく動作いたしました。
迅速にご対応いただきありがとうございました。
こちらのIsuueはクローズさせていただきます。
