### ISSUE TITLE
v7.1.0へのアップグレードでlfsエラーが発生します。

### ISSUE THREAD

**Issue by hoverbucks** [weseek/growi#9349]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04 / Ubuntu 24.04|
|GROWI     |7.0.23|
|node.js   |20.18.0|
|npm       |10.9.0|
|yarn      |1.22.22|
|Using Docker| no|
|Using [growi-docker-compose][growi-docker-compose]|no|

How to reproduce? (再現手順)
---------------------------

1. 上記ホストにてアップグレードを実施。
1. pnpmインストールを実施
1. app:buildを行う

    ```bash
sudo npm run app:build
    ```
What happens? (症状)
---------------------

- 以下のエラーが発生
```
@growi/remark-growi-directive:build: 
@growi/app:pre:lfs: Downloading LFS objects:   0% (0/1), 0 B | 0 B/s                                                    @growi/app:pre:lfs: batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
@growi/app:pre:lfs: error: failed to fetch some objects from 'https://github.com/weseek/growi.git/info/lfs'
@growi/app:pre:lfs:  ELIFECYCLE  Command failed with exit code 2.
@growi/app:pre:lfs: ERROR: command finished with error: command (/home/www-data/growi/apps/app) /usr/local/bin/pnpm run pre:lfs exited (2)
@growi/remark-growi-directive:build: 
@growi/remark-growi-directive:build: > @growi/remark-growi-directive@1.0.0 postbuild /home/www-data/growi/packages/remark-growi-directive
@growi/remark-growi-directive:build: > shx cp ./src/mdast-util-growi-directive/index.d.ts ./dist/mdast-util-growi-directive/index.d.ts
@growi/remark-growi-directive:build: 
@growi/remark-growi-directive:build: cp: copyFileSync: could not write to dest file (code=ENOENT):./dist/mdast-util-growi-directive/index.d.ts
@growi/remark-growi-directive:build:  ELIFECYCLE  Command failed with exit code 1.
```

What is the expected result? (期待される動作)
-------------------------------------------

- app:buildに成功する

Note
----

- v7.1.0への機能追加により、LFSの容量がオーバーしたかと存じます。

**Comment by yuki-takei** [comment]
なるほど、ユーザーが増える＆バージョンアップするほど効いてくるんですね、うっかりしてました。
とりあえず課金したので git lfs pull できるはずです。ご確認ください。

LFS 管理しているフォントファイルは高々数百Kbyteですし頻繁に更新するものでもないので次バージョンから LFS 管理をやめる方向でいこうと思います。
