### ISSUE TITLE
半角コロンの右側の半角英字が表示されない

### ISSUE THREAD

**Issue by kzkz** [weseek/growi#9381]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |7.1.0|
|node.js   |20.18.0|
|npm       |10.8.2|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11|
|browser   |Microsoft Edge 130.0.2849.68, Google Chrome 130.0.6723.117|

How to reproduce? (再現手順)
---------------------------

1. 記事を新規作成または編集
1. a:b を入力する

What happens? (症状)
---------------------

- a と表示される

![msedge_YtmLvjL2HT](https://github.com/user-attachments/assets/890ffbac-6aa7-41ce-9731-2661679ab5a5)

What is the expected result? (期待される動作)
-------------------------------------------

- a:b と表示されること

Note
----

- `a\:b`と入力すると a:b と期待値通り表示される
- GROWI v7.1.0 のDEMO環境 https://demo.growi.org/ でも再現した
- GROWI v5.0.4 の環境では問題なし

絵文字の開始と誤認されているのかもしれません。

**Comment by yuki-takei** [comment]
@kzkz Issue 作成ありがとうございます。

この事象は v7.1.0 で [remarkjs/remark-directive](https://github.com/remarkjs/remark-directive) が有効化されたためです。
一応仕様通りではあるのですが、利用者からするとバグのように見えるのは否めないのでちょっとこの先どうするかは考えようと思います。

**Comment by yuki-takei** [comment]
v7.1.1 で修正されます。リリースまでしばらくお待ちください。
