### ISSUE TITLE
Bug: Qiita:Team can't import.

### ISSUE THREAD

**Issue by akashima** [weseek/growi#941]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Amazon Linux AMI release 2018.03  |
|GROWI     | v3.4.5 |
|node.js   | v8.15.1 |
|npm       | 6.9.0 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | mac OS Sierra 10.12.6 |
|browser   | Firefox 66.05 and Safari バージョン12.1 (12607.1.40.1.5) |

How to reproduce? (再現手順)
---------------------------

1. Qiita:Teamからread_qiita_teamのapiコードを取得する
1. growiのインポートページにアクセスし、Qiita:Teamのチーム名を指定する。
1. 1.で取得したread_qiita_teamのapiコードをセットする
1. 更新ボタンを押す
1. インポーを実行する

What happens? (症状)
---------------------

- 2017年11月30日分までのドキュメントは取り込まれるがそれ以前のデータが取り込まれない。
- エラーメッセージには以下の文言が出力されている

```
0|start-server  | [2019-05-13T07:01:46.256Z] ERROR: growi/28514 on growi:
0|start-server  |   Unhandled Rejection: Promise: Promise {
0|start-server  |     <rejected> Error: Cannot create new page to existed path
0|start-server  |       at Function.pageSchema.statics.create (/var/www/html/growi/src/server/models/page.js:1001:13)
0|start-server  |       at <anonymous>
0|start-server  |       at process._tickDomainCallback (internal/process/next_tick.js:229:7) } Reason: Error: Cannot create new page to existed path
0|start-server  |       at Function.pageSchema.statics.create (/var/www/html/growi/src/server/models/page.js:1001:13)
0|start-server  |       at <anonymous>
0|start-server  |       at process._tickDomainCallback (internal/process/next_tick.js:229:7)
0|start-server  |
0|start-server  | [2019-05-13T07:01:46.279Z] ERROR: growi/28514 on growi:
0|start-server  |   Unhandled Rejection: Promise: Promise {
0|start-server  |     <rejected> Error: Cannot create new page to existed path
0|start-server  |       at Function.pageSchema.statics.create (/var/www/html/growi/src/server/models/page.js:1001:13)
0|start-server  |       at <anonymous>
0|start-server  |       at process._tickDomainCallback (internal/process/next_tick.js:229:7) } Reason: Error: Cannot create new page to existed path
0|start-server  |       at Function.pageSchema.statics.create (/var/www/html/growi/src/server/models/page.js:1001:13)
0|start-server  |       at <anonymous>
0|start-server  |       at process._tickDomainCallback (internal/process/next_tick.js:229:7)
0|start-server  |
0|start-server  | (node:28514) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
0|start-server  | (node:28514) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
0|start-server  | [2019-05-13T07:01:46.471Z]  INFO: express/28514 on growi: ::ffff:172.30.2.248 <-- POST /_api/admin/import/qiita HTTP/1.1 200 81 https://growi.yumemi.jp/admin/importer Safari 12.1 Mac OS X 10.12.6 2312.321672 ms (req_id=9d71f5d4-a937-43d3-9840-5a7bc0ae4677)

```

ブラウザには以下のようなエラーメッセージが出力される

![error](https://user-images.githubusercontent.com/3690724/57601879-a8dc4f00-7598-11e9-89f2-77e1cc62207f.png)

What is the expected result? (期待される動作)
-------------------------------------------

-  2017年10月以前のデータも正常に取り込まれること

Note
----

- 
-

**Comment by yuki-takei** [comment]
@akashima ご報告ありがとうございます。

ぱっと見ですが、症状のエラーメッセージとインポートがストップした際のアラート

> TypeError: Cannot read property 'pages' of undefined

は別物っぽいですね。ちょっと現時点ではどちらが原因でインポートされないのか、或いはまた別の問題なのかは現時点ではわかりません。

追加で以下の設定を施し、サーバー側ログを貼っていただくことは可能でしょうか？

## ロガー設定
参考: https://docs.growi.org/dev/tips/logger.html

- `config/logger/config.prod.js` で設定
    ```
    'growi:*': 'debug',
    ```
- 環境変数で設定
    ```
    DEBUG=growi:*
    ```

よろしくお願いいたします。
```

**Comment by akashima** [comment]
お世話になります。

ログデータですが、提供しようと考えておりましたが、社内の情報に関わってくるものがありますので、ログの提供は行えないように感じました。
その中での確認となり恐縮ですが、Qiitaからデータを取得する際の件数制限などありますでしょうか？

気になった点として、取り込み件数を確認したところ grep Successfully | wc -l で98件で止まっており、件数が100件までで止まってる…？ということが引っかかった点となります
何度かやり直しましたが、結果は98件と同じで変わりませんでした。

エラー自体はいただいたdebug方法で確認いたしましたが、出力されていないようです。
Issue最初のエラーは2回目に実行した際に出力されているようです。

**Comment by yuki-takei** [comment]
@akashima 
> Qiitaからデータを取得する際の件数制限などありますでしょうか？
件数制限は GROWI 側では設けておりません。

インポート機能に関して、98, 99件目あたりのデータに起因するバグがあるのではないかという疑いがありますが、ログ or Qiita 上のデータがないことにはこちらでも再現を確認できないため、こちら一旦 close させていただいてもよろしいでしょうか？

**Comment by yuki-takei** [comment]
close します
