### ISSUE TITLE
[7.1.2] Bug: 検索機能が使えない

### ISSUE THREAD

**Issue by komanezumi** [weseek/growi#9429]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | ubuntu |
|GROWI     |7.1.2|
|node.js   |20.18.0|
|npm       |10.8.2|
|Using Docker|yes|
|Using growi-docker-compose|no|

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 11 Pro 23H2|
|browser   | Google Chrome 131.0.6778.69 |

How to reproduce? (再現手順)
---------------------------

1. 検索にキーワードを入力して検索する

What happens? (症状)
---------------------

- 検索結果が 0 pages と表示される
![growi_search](https://github.com/user-attachments/assets/e1f02bbe-47bf-4538-937d-a9d56f539c8e)

What is the expected result? (期待される動作)
-------------------------------------------

- 検索結果が表示されること

Note
----

- バージョンを7.0.23に戻すと検索機能が使えるようになったが、7.0.23に戻した場合も、検索結果が2000件を超えると失敗する。

**Comment by yuki-takei** [comment]
@komanezumi ちょっと情報が少ないので以下確認お願いします。

1. [v7.1.x へのアップグレードガイド](https://docs.growi.org/ja/admin-guide/upgrading/71x.html) を確認してください
2. 管理画面の全文検索管理からインデックスのリビルドを試してください
    - その際にサーバーログに何か出ていないか確認してください
3. 検索実行時にサーバーログに何か出ていないか確認してください

2と3の情報をいただければトラブルシュートのお手伝いができるかもしれません。
