### ISSUE TITLE
v3.3.10-RC でクライアントの閲覧不可

### ISSUE THREAD

**Issue by yuki-510** [weseek/growi#943]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.6.1810|
|GROWI     |3.3.10-RC|
|node.js   |v8.11.2|
|npm       |5.6.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7/10|
|browser   |GoogleChorme 74|

How to reproduce? (再現手順)
---------------------------
ブラウザからアクセスし、Wikiを閲覧もしくは管理画面にて操作をする。

What happens? (症状)
---------------------
閲覧している画面のViewに「目次」のみが表示され他は何も表示されない。
作成したメモ一覧は表示が有り、リンクをクリックしてページジャンプは可能だが
リンク先でも同様に何も表示されない。
管理タブをクリックし、管理画面は閲覧できるが例えばユーザー管理のプルダウン
メニューは「▼」のみの表示になっており、クリックしても何も動作しない。
chromeのデベロッパツール表示のコンソールでは503コードのエラーが
多数表示されている

つい先日までは正常に閲覧やメモ作成が可能でしたが、現在上記症状
となっております。
上記症状につきまして、作成したWikiを正常に参照および管理ツールでの
操作を行うためにはどのような対処が必要がご教示いただけないでしょうか？

Note
・Growiがインストールされている仮想サーバの再起動後に事象が発生
・正常に動作していたクライアントでもchromeのキャッシュをクリアすると
　上記症状となります
・複数クライアントにて試しましたが、正常に閲覧可能なユーザ、上記症状のユーザ、
　IEでは正常に閲覧可能なユーザ、IEでも上記症状のユーザが混在しております。

**Comment by yuki-takei** [comment]
@yuki-510 

GROWI は現在 v3.4.5 が最新ですので、アップグレードしてみてください。

どうしても 3.4 系に上げたくない場合はこちらでも再現確認を行いますので、Git のどのコミットをご利用か、ハッシュを教えていただければと思います。

**Comment by yuki-510** [comment]
@yuki-takei 
コメントありがとうございます。本日v3.4.5にアップグレードしましたが、事象は変わりませんでした。
※バージョンアップ前に閲覧できていたクライアントも同じ事象になりました。

**Comment by yuki-takei** [comment]
> chromeのデベロッパツール表示のコンソールでは503コードのエラーが
多数表示されている

こちらの内容をいただくことはできますか？
それから、ご利用中の環境の `yarn.lock` をなにかしらの手段で共有いただけると助かります。

**Comment by yuki-510** [comment]
@yuki-takei 
上記承知しました。メールでの送付でよろしいでしょうか？

**Comment by yuki-510** [comment]
@yuki-takei 
上記承知しました。添付します。
chromeのエラーにつきましては一部のみ添付します。
他も必要でしたらお手数ですがご連絡ください。
[chrome.log](https://github.com/weseek/growi/files/3197411/chrome.log)

[yarn.lock.log](https://github.com/weseek/growi/files/3197400/yarn.lock.log)

**Comment by yuki-takei** [comment]
@yuki-510 情報添付ありがとうございます。

chrome.log を見るに、CDN へのアクセスが軒並み503なので、Chrome を起動中のPCのネットワーク環境問題か、あるいはちょっと考えにくいですが「たまたまその時間帯に cdn.jsdelivr.net が落ちていた」…といったあたりかなと思います。

ブラウザがアクセスしようとして見つからないと出ているこれらのリソースには、ブラウザで直接URLを指定した場合はアクセスできているのでしょうか？

**Comment by yuki-takei** [comment]
@yuki-510 その後いかがでしょうか。
一旦こちら close しますが、バグであるような挙動をした場合は再度ご報告いただければ reopen します。よろしくお願いいたします。
