### ISSUE TITLE
Bug: grantがnullのページデータ表示時に空のアラート(青い枠)が表示されてしまう

### ISSUE THREAD

**Issue by yamaken1343** [weseek/growi#944]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|GROWI     |3.4.2 |
|node.js   |10.15.2|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04|
|browser   |Vivaldi 2.4.1488.38|

How to reproduce? (再現手順)
---------------------------

1. UpdatePage API を用いて grant を指定せずにページを更新する

What happens? (症状)
---------------------

- grantがnullの状態でページが更新される
- 以下のような青枠が表示される
![Screenshot from 2019-05-14 15-41-09](https://user-images.githubusercontent.com/38549987/57676513-a09b1700-765f-11e9-9f3c-8ec79df8218f.png)

What is the expected result? (期待される動作)
-------------------------------------------
下記のいずれかが自然かと思います.
- grant未指定の場合はページが更新できない(エラーを発生させる)
- grant未指定の場合は自動的に全体公開のgrantが振られる
- grantがnullであることの旨が表示される

Note
----

- grantを正しいものに変更すると青枠は消える

**Comment by yuki-takei** [comment]
@yamaken1343 ご報告ありがとうございます。再現確認しました。
対策を講じて近々リリースします。
