### ISSUE TITLE
Feature: SAML RoleとGrowiの権限の連携

### ISSUE THREAD

**Issue by mizozobu** [weseek/growi#961]
# TODO
- Growiの管理画面でロールごと（keycloakではRole Nameを使う）に出来ること（or 出来ないことを）制限出来るようにする
    - 例
        - `growi_user`でないとログイン出来ない
        - `growi_admin`でないと管理画面に行けない
        - など

- `passport-saml`をversion`1.1.0`にアップグレードする(`getSamlResponseXml`を使うため)
- `passport-saml`の`getSamlResponseXml`で得られるXMLをparseしてロールを抽出
- 抽出したロールと管理画面で設定した制限を照らし合わせて以下を実装
  -  ログインの制限
  - 管理者画面へのアクセスの制限

**Comment by yuki-takei** [comment]
ログインの制限については v3.7.0 で実装されました。

管理者画面へのアクセス制限については他の authentication mechanism でも実装されていないため、当面スコープ外とします。

上記により、この Issue はクローズします。
