### ISSUE TITLE
全文検索「Build Now」がエラーになる

### ISSUE THREAD

**Issue by mzch** [weseek/growi#963]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Debian GNU/Linux 10 (Buster)|
|GROWI     |3.4.7-RC|
|node.js   |10.15.3|
|npm       |6.4.1|
|Elasticsearch|7.1.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5 (Mojave)|
|browser   |Google Chrome 74.0.3729.157|

How to reproduce? (再現手順)
---------------------------
全文検索管理画面の「Build Now」をクリック

What happens? (症状)
---------------------
下記画像の通り、全文検索インデックスの作成に失敗します。
https://d.pr/i/hShn3a

```
curl -XPUT http://localhost:9200/growi
```
とすると正常にインデックスが作成されるので、Growi の問題ではないかと考えました。

What is the expected result? (期待される動作)
-------------------------------------------
正常終了

Note
----

**Comment by akashima** [comment]
直近環境構築したので、コメントを返しますが、恐らくhttp指定なので80ポートになるのではと思います。

以下はぼくが設定した際のドメインをローカルホストに変えただけではありますが、httpsが利用できる環境であったためポートも443にしたことでgrowiが疎通しました。

```
  ELASTICSEARCH_URI: 'https://localhost:443/growi',
```

**Comment by mzch** [comment]
いえ、同じ URI で、curl では正常に応答があるのですが…ElasticSearch 6 で構築したインスタンスは、ちゃんと動作しているので、そこが原因なのかな、と。

**Comment by mzch** [comment]
訂正: elasticsearch を 6.8 にしても同じエラーが発生します...動いていたと思っていたインスタンスでもエラーになってしまってました…

環境変数
```
NODE_ENV=production
PORT=3000
REDIS_URI=redis://127.0.0.1:6379
MONGO_URI=mongodb://growi:[password]@localhost:27017/growi
ELASTICSEARCH_URI=http://localhost:9200/growi
PASSWORD_SEED=/dev/random
FILE_UPLOAD=local
```

他には特に設定していません。

**Comment by yuki-takei** [comment]
@mzch こちら、クリーンインストールした v3.4.7-RC(6ca351f8) で再現しないので、一旦バグ扱いではなく question とさせていただきます。

## テストした構成

- GROWI on Heroku
![image](https://user-images.githubusercontent.com/1638767/58197614-97691480-7d07-11e9-9c36-a3d3405129b5.png)
- 備考
    - Elasticsearch 6.5.4
    - Redis なし(関係はなさそうだが)

## とりあえず気になる箇所

Elasticsearch の7系は、開発チームでは動作を確認していません。  
6.8 でも同様のエラーとのことですが、一番動作実績が多いと思われる growi-docker-compose を利用した環境では 6.6.1 を利用しています。

https://github.com/weseek/growi-docker-compose/blob/98a66bf682dcc1ede1f52e07a6d9791a5569354a/elasticsearch/Dockerfile#L1

正常運用することが目的である場合は、まずは以下2点の実施をおすすめします。

1. ESのバージョンを 6.6.1 まで落とすこと
2. GROWI 本体を RC バージョンではなくリリース済みバージョンにすること


## RCを使いたい、ES6.8以上や7.xを使いたい場合

RCのバグが見つかること、及び新しいミドルウェアでの動作実績が手に入ことのは我々開発チームとしても歓迎いたしますので、もし引き続きチャレンジされる場合は以下の実施と情報提供をお願いしたいです。

1. 問題の切り分け
    - ESの新しいバージョンを利用したい場合は、GROWI 本体を RC バージョンではなくリリース済みバージョンにする
    - 逆に RC 版を利用したい場合は、ESを 6.6.1 まで落とす
1. MongoDB 内のデータはフラッシュし、GROWI 本体をクリーンインストールされた状態にする
1. Build Index 時のログの提供
    - GROWI サーバー側ログに何かエラーは出ていないでしょうか？出ている場合はファイルとして添付いただけると助かります

**Comment by mzch** [comment]
3.4.6 を導入し直し、elasticsearch も 6.8 を再インストールして、mongodb、redis の初期化を試してみたところ、成功しました。ありがとうございます。
