### ISSUE TITLE
Edits written in Growi can not be transferred to codimd.

### ISSUE THREAD

**Issue by akashima** [weseek/growi#966]
Environment
------------

#### Growi

| item     | version |
| ---      | --- |
| OS        | Amazon Linux AMI release 2018.03  |
|GROWI     | 3.4.5 |
|node.js   | v8.15.1 |
|npm       | 6.9.0 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

#### codimd

| item     | version |
| ---      | --- |
| OS        | Amazon Linux AMI release 2018.03  |
|codimd     | 1.3.1 |
|node.js   | v8.16.0 |
|npm       | 6.9.0 |
|Using Docker| no |
|Using [growi-docker-compose][growi-docker-compose]| no |

Growiとcodimdは別々のEC2インスタンスでの構築になります。

### Client

| item     | version |
| ---      | --- |
|OS        | mac os High Sierra 10.12.6（16G2016） |
|browser   | Firefox 66.0.5 |

How to reproduce? (再現手順)
---------------------------

1. 「作成」よりページの作成を行い、一旦保存した上で作成ボタンで保存してしまう
2. hackmdの編集ボタンを押す
3. Start to Edit with HackMDを押す
4. codimdのTOP画面は開くものの、編集画面に移動はしていない。
    ```bash
   
What happens? (症状)
---------------------

- 作成したページに対し、hackmdでの編集が行えない
- データがhackmdに対して引き継がれていない

#### Growi側ログ

```
0|start-server  | [2019-05-22T08:22:29.054Z] DEBUG: growi:lib:swigFunctions/4188 on growi: initializing swigFunctions
0|start-server  | [2019-05-22T08:22:29.055Z] DEBUG: growi:lib:middlewares/4188 on growi: req.skipCsrfVerify undefined
0|start-server  | [2019-05-22T08:22:29.055Z] DEBUG: growi:lib:middlewares/4188 on growi: csrf successfully verified
0|start-server  | [2019-05-22T08:22:29.096Z]  INFO: express/4188 on growi: ::ffff:172.30.2.248 <-- POST /_api/hackmd.integrate HTTP/1.1 200 108 https://growi.***.***/user/Admin/%E3%83%A1%E3%83%A2/2019/05/22/test Firefox 66.0 Mac OS X 10.12.0 41.102487 ms (req_id=2cc1b213-f6d5-45e6-9780-23fb85dffbd5)
0|start-server  | [2019-05-22T08:22:30.726Z] DEBUG: growi:lib:swigFunctions/4188 on growi: initializing swigFunctions
0|start-server  | [2019-05-22T08:22:30.731Z]  INFO: express/4188 on growi: ::ffff:172.30.2.248 <-- GET /login HTTP/1.1 200 12427 - Other 0.0 Other 0.0.0 4.018755 ms (req_id=e8110e1b-8e96-44fb-8570-1993fec412c2)
```

#### CodiMD側ログ

```
0|app  | 2019-05-22T08:22:29.077Z info:         Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'IXeJ_15IVSd4JsrEm-K79dc9MTRah2-X';
0|app  | 2019-05-22T08:22:29.081Z info:         Executing (default): INSERT INTO "Sessions" ("sid","expires","data","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;
0|app  | 2019-05-22T08:22:29.083Z info:         172.30.7.70 - - [22/May/2019:08:22:29 +0000] "GET / HTTP/1.1" 200 18213 "-" "axios/0.18.0"
0|app  | 2019-05-22T08:22:29.182Z info:         Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'YvzjZbKCPI6kujnGk2h2SWF3KruKSz83';
0|app  | 2019-05-22T08:22:29.186Z info:         Executing (default): UPDATE "Sessions" SET "expires"=$1,"updatedAt"=$2 WHERE "sid" = $3
0|app  | 2019-05-22T08:22:29.188Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /?both HTTP/1.1" 200 - "https://growi.***.***/user/Admin/%E3%83%A1%E3%83%A2/2019/05/22/test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.260Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /build/font.css HTTP/1.1" 200 182 "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.266Z info:         Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'YvzjZbKCPI6kujnGk2h2SWF3KruKSz83';
0|app  | 2019-05-22T08:22:29.267Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /build/cover.css HTTP/1.1" 200 - "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.271Z info:         Executing (default): UPDATE "Sessions" SET "expires"=$1,"updatedAt"=$2 WHERE "sid" = $3
0|app  | 2019-05-22T08:22:29.274Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /config HTTP/1.1" 200 266 "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.277Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /build/cover.7c979c87f7ca9aff1074.js HTTP/1.1" 200 - "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.289Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /screenshot.png HTTP/1.1" 200 238635 "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
0|app  | 2019-05-22T08:22:29.580Z info:         Executing (default): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'YvzjZbKCPI6kujnGk2h2SWF3KruKSz83';
0|app  | 2019-05-22T08:22:29.583Z info:         Executing (default): UPDATE "Sessions" SET "expires"=$1,"updatedAt"=$2 WHERE "sid" = $3
0|app  | 2019-05-22T08:22:29.585Z info:         172.30.3.89 - - [22/May/2019:08:22:29 +0000] "GET /me HTTP/1.1" 200 22 "https://md.***.***/?both" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:66.0) Gecko/20100101 Firefox/66.0"
```

What is the expected result? (期待される動作)
-------------------------------------------

- Growiで作成したページをcodimd側で引き続き編集できる状態にする


Note
----

- 以下に関連しそうなGrowiとCodiMDの連携情報を記載します。設定が漏れているのかもしれず、ということを考えていますが、漏れているとした場合に何が漏れているかはドキュメントから読み取ることができませんでした。

#### growiのconfig

```
module.exports = {
  NODE_ENV: 'production',
  // FORMAT_NODE_LOG: false,
  PORT: 80,
  MONGO_URI: 'mongodb://localhost:27017/growi',
  ELASTICSEARCH_URI: 'https://vpc-growi-***-***.ap-northeast-1.es.amazonaws.com:443/growi',
  REDIS_URI: 'redis://growi-***-001.***.0001.apne1.cache.amazonaws.com:6379',
  // PASSWORD_SEED: '`openssl rand -base64 128 | head -1`',
  FILE_UPLOAD: 'aws',
  HACKMD_URI: 'https://md.****.***',
  PLANTUML_URI: 'https://plantuml.***.***',
  APP_SITE_URL: 'https://growi.***.***'
};
```

#### codimdのconfig


```
    "production": {
        "debug": true,
        "domain": "md.***.***",
        "port": "80",
        "imageUploadType": "s3",
        "protocolUseSSL": true,
        "allowAnonymous": false,
        "email": false,
        "sessionSecret": "hackmd",
        "allowEmailRegister": false,
        "defaultPermission": "editable",
        "GROWI_URI": "https://growi.***.****",
        "hsts": {
            "enable": false,
            "maxAgeSeconds": "31536000",
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": false,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": true,
            "addGoogleAnalytics": true
        },
        "db": {
            "username": "hackmd",
            "password": "********",
            "database": "hackmd",
            "host": "hackmd.**********.ap-northeast-1.rds.amazonaws.com",
            "port": "5432",
            "dialect": "postgres"
        },
```

![growi](https://user-images.githubusercontent.com/3690724/58161791-e5582b00-7cbb-11e9-8714-a790703cd5ca.gif)

**Comment by yuki-takei** [comment]
@akashima 
まずは「GROWI サーバーからも `HACKMD_URI` で CodiMD にアクセスできる」ことを確認してください。
その URL ではアクセスできないような構成である場合は、 `HACKMD_URI_FOR_SERVER` の指定を検討してください。

両方共問題ない場合、ブラウザ側の開発者コンソールに何かエラーがでていないか確認してください。出ている場合はここに貼っていただけるとトラブルシュートの助けになります。

**Comment by akashima** [comment]
@yuki-takei 
GROWIサーバからはHACKMD_URIで繋がっていますので、curl https://md.xxxx.xxxx でレスポンスは返ってきております。
HACKMD_URIとHACKMD_URI_FOR_SERVERにはどのような違いが含まれていますか？

HACKMD_URIでレスポンスは返ってきておりますが、一応HACKMD_URI_FOR_SERVERにも同様の設定もしくはEC2インスタンスのプライベートIPで可能か試しましたが、結果は変わらず、CodiMDが開きはするものの、想定している編集画面には移らず、トップページに移動してしまっております。

念のためGROWI agentが正常に動作しているかを確認しましたが、開発コンソール上やソースからどう確認するか？がわからなかったためご教示のほどお願いいたします。

**Comment by yuki-takei** [comment]
> HACKMD_URIとHACKMD_URI_FOR_SERVERにはどのような違いが含まれていますか？

`HACKMD_URI` は、クライアントPC(ブラウザ)からアクセス可能な CodiMD のURL
`HACKMD_URI_FOR_SERVER` は GROWI サーバーからアクセス可能な CodiMD のURL

を指定する必要があります。

> 念のためGROWI agentが正常に動作しているかを確認しましたが、開発コンソール上やソースからどう確認するか？がわからなかったためご教示のほどお願いいたします。

こちらをご覧ください
https://developer.mozilla.org/ja/docs/Tools

こういったトラブルシュート全般、Slack の方がレスポンスが良いと思うので、できればそちらに参加いただけると助かります。(僕以外からも回答返ってきたりするので)

**Comment by yuki-takei** [comment]
@akashima Slack の方で進展伺いましたがお返事がありませんでしたのでこちら一度 close します。クライアント(ブラウザ)のコンソールから何か手がかりが得られましたらメンションいただければ reopen します。
