### ISSUE TITLE
Bug: Still XSS filter breaks PlantUML arrows

### ISSUE THREAD

**Issue by rsp9u** [weseek/growi#981]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |arch-linux|
|GROWI     |3.4.6|
|node.js   |10.15.3|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows7|
|browser   |Chrome 74.0.3729.169|

How to reproduce? (再現手順)
---------------------------

same as #709

What happens? (症状)
---------------------

- One diagram was rendered

What is the expected result? (期待される動作)
-------------------------------------------

- Two diagrams are rendered

Note
----

### Solution proposal

XSS filter library strips the **attributes not in white list** like below;
```
# cat index.js
xss = require("xss")
var opts = {whiteList: {"-": []}}
var html = xss('<- foo; bar ->', opts);
console.log(html);
# node index.js
<->
```

In the mentioned code, `foo;`, `bar`, `-` are erased since they'er interpreted as attributes.
So, the arrows should be passed by `onTag` handler.

#### PlantUML
- `<--` (doted arrow)
- `<[#red]-` (colored arrow)
- `<|-` (outlined triangle arrow)
- `<..` (doted arrow in use case diagram)
- `<<` (stereo type)

Note: the number of `.` and `-` may be greater than two.

#### Blockdiag
- `<--` (seqdiag)
- `<<-` (seqdiag)
- `>-<` `-<` (blockdiag: any token comes behind this. **it's impossible to support this**)

The regexp which matches these would be `/^[[<.|-].*$/`.

### Solution to the root of the problem

I think that XSS filter should be applied the content excluded "plantuml" and "blockdiag" block.

It seems that only "markdown-it" do HTML parsing,
so I think XSS filter should be implemented as markdown-it plugin instead of preprocessor.

**Comment by rsp9u** [comment]
@yuki-takei Aren't you going to fix this issue for the time being?
If you're not, I'll disable XSS filter until fixed since I'm using internally.

**Comment by yuki-takei** [comment]
@rsp9u Thank you for your report, and I'm sorry for my late response.

As you said, this problem might not be fixed completely unless we replace the current XSS filter implementation with something other solution.

At the moment, I think that the solution you described at "Tags should be passed through the filter" section is too specialized about PlantUML and blockdiag, so I would like to let this to be pending.

But we GROWI team recognized this problem is the thing that should be fixed in the near future.

**Comment by rsp9u** [comment]
@yuki-takei Thank you for your reply!

I almost understood your plan.
Temporarily, I'll disable the filter as a workaround.

Thank you again for your time.

**Comment by yuki-takei** [comment]
Relate to: #1597
