### ISSUE TITLE
Syntax highlighting issue /w Antarctic Theme

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#998]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.4.8-RC (f2c137d)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 74.0.3729.169|

How to reproduce? (再現手順)
---------------------------

1. Set theme to "antarctic"
1. Set syntax highlighting theme to "[Dark] Monokai" (or other dark theme).

What happens? (症状)
---------------------

- Too hard to read highlighted codes. Background and text colors are very approximate.
![カスタマイズ   GroupWiki Dev](https://user-images.githubusercontent.com/3660715/58854323-e768b380-86d7-11e9-98e9-17398407ef66.png)

What is the expected result? (期待される動作)
-------------------------------------------

- The background should be darker.

**Comment by itizawa** [comment]
Thank you for using the Theme and reporting.

We'll consider it, and get back to you soon.

**Comment by yuki-takei** [comment]
fixed by #1066
